### PR TITLE
Use params IMDBID, TVDBID, TVMAZEID and TMDBID with json response

### PR DESCRIPTION
**Pull request by swannie-eire**
#### Description
As discussed here https://github.com/Jackett/Jackett/issues/15009 the params for json response only works with a few params.

Implemented so IMDBID, TVDBID, TVMAZEID and TMDBID params are supported with the API json response

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

IMDBID -tested with valid, invalid id
TVDBID - tested with valid, invalid id
TMDBID - tested with valid, invalid id
TVMAZEID - uanble to test as the only site i know that uses tvmaze is BIThdtv but its not a supported param for the site. ```http://localhost:9117/api/v2.0/indexers/bithdtv/results/torznab/api?apikey=<API_KEY>&t=caps```

I will add the other params that is supported by torznab once i know know this will be merged. 

Note if the site does not support the search param that the latest torrents are returned but that is the same behavior as torznab. I will put in a test that search only happens with supported params when i have time.

### CODE REVIEW

**Comment by garfield69** [comment]
It should be noted that this is an internal command path originally intended to be used between the GUI and the Jackett server.
Its not an officially documented API because it is subject to change to suit Jackett GUI/Server interface requirements.
However, since it is open, user may choose to use it, however, making it a dependant of other apps is not recommended.
This is not to say that this PR is not welcome, the idea has merit.
However, for apps that want to use the Jackett services, the official API is the torznab one, which has specifications that are published, and which the *arr apps and Jackett are bound to. Currently only the XML response is supported by Jackett.
While the torznab specifications do allow for a JSON response, option it has not been implemented by Jackett because demand is low and C# volunteers are few, in demand, and apparently not interested in implemented it, thus far.
I thought there was an open enhancement ticket covering implementing torznab o=JSON but I cant seem to find it right now.

**Comment by swannie-eire** [comment]
Thank you for the response.

Will I delete/close the PR if it's not going to be merged?

**Comment by garfield69** [comment]
The team will discuss if we should implement and either merge or close the ticket at some point.

**Comment by ilike2burnthing** [comment]
> I thought there was an open enhancement ticket covering implementing torznab o=JSON but I cant seem to find it right now.

https://github.com/Jackett/Jackett/issues/921 - reopen?

**Comment by garfield69** [comment]
Ah that's the one I was thinking of.
Perhaps its better if we open a fresh one specifically dedicated to torznab o=json implementation so its clear what's intended.

**Comment by garfield69** [comment]
we will merge, because it will be a step forward to supporting GUI id searches other than the current imdb ttnnnnnnnn search.

**Comment by swannie-eire** [comment]
Thank you

**Comment by garfield69** [comment]
v0.21.1635

**Comment by garfield69** [comment]
Oops

**Pull request merged**
