### PR TITLE
torrentmafya: added new public Turkish indexer resolves #9181

### LINKED ISSUE #9181: [REQ]torrentmafya.org
Turkish movie share torrent site.
Link: https://www.torrentmafya.org/
Search engine and magnets running.
Site is have big database.

### PR DESCRIPTION
**Pull request by ertugrulk**
Added torrentmafya.org indexer  as requested by  issue #9181

### CODE REVIEW

**Review by garfield69 — CHANGES_REQUESTED** [review]
on the Jackett dashboard, searching with the torrentmafya indexer, once results are presented, the user should be able to click on the title of a torrent and be routed to the details page on the web site.
take a look at the changes I made to your darmowetorrenty PR regarding the Comments and Guid

also, searching for `raised wolves` does not return anything, but on the web site it works.
are you looking for exact matches? is there a mask that works for searches such as separating search words with a plus or percent symbol or something?

**Comment by ertugrulk** [comment]
@garfield69 yeah, seems like the API that I found expects wildcard instead of spaces even in the website, fixed that. Since there are multiple torrents per details page I have left Guid as is: link of a torrent instead of link of details page. Let me know if that needs to change..

**Review by garfield69 — APPROVED** [review]
LGTM
tested via dashboard

now just pending code style compliance review from @ngosang

**Review by ngosang — APPROVED** [review]

**Comment by ngosang** [comment]
Thank you!

**Pull request merged**
