### PR TITLE
torrent9: remove *.li domain

### PR DESCRIPTION
**Pull request by ilike2burnthing**
Relates to https://github.com/Jackett/Jackett/commit/e2defbcb839006d7daa9a46e542140804e559398

https://torrent9.to/search_torrent/bad-boys-for-life.html,trie-date-d
and
https://torrent9.to/search_torrent/bad%20boys%20for%20life%3Ftrie-date-d
return the same results (same for .gg and .me)

The only issues are with
https://torrent9.to/search_torrent/bad-boys-for-life,trie-date-d
and
https://torrent9.to/search_torrent/bad%20boys%20for%20life%2Ctrie-date-d
which include `,trie-date-d` in the search term (same for .gg and .me)

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
Last commit just switches the order as .to is a lot faster.

**Comment by garfield69** [comment]
OK.
But you do realise that for users that have already got a config for this indexer, the last change will not make any difference to them, they will continue to use oxtorrent since that was the first sitelink when they added the indexer.
They would only switch to .to if the created a new config or manually selected that domain from the alternate links in the config while editing.

**Comment by ilike2burnthing** [comment]
Yea, neither is outright objectionable, I'm essentially just listing them by preference. Will be of benefit to anyone adding it new, but that's about it. Other than changing them to legacy links for a week or few, and then re-adding them, there's not much more that can be done.

**Review by garfield69 — CHANGES_REQUESTED** [review]
No.
your indexer is generating 
https://torrent9.to/search_torrent/bad%20boys%20for%20life%3Ftrie-date-d,trie-leechs-d
use this link on a browser and see how when you switch the sorts by clicking on taille, seed or leech they do not turn black? the address shows what is going on.
only https://torrent9.to/search_torrent/bad-boys-for-life,trie-date-d is the correct parameters.

However, all this is academic. 
when looking for bad boys for life using the indexer only
https://torrent9.to/search_torrent/bad-boys-for-life.html
gets results
using any of the sorts causes all the hits that are partial matches to be shown first and unless you can find a search mask that forces the site to include all the words then this change is not going to improve the indexer for anyone.

**Comment by ilike2burnthing** [comment]
The results are the same in both links, even if in browser they don't function the same, but I take your point.

I've changed things to adhere as closely as possible to the original URL format, kept the sorting options, but added a new default sort option `best` (no sorting). Gives users the choice if they want it, but it won't affect anyone who doesn't go into the config options.

**Review by garfield69 — APPROVED** [review]
Good job.

**Pull request merged**
