### PR TITLE
Feature/refactor indexer management

### PR DESCRIPTION
**Pull request by chibidev**
I'm a little bit scared to open this pull request, as the diff is... well, brace yourselves, it is GIGANTIC. I'm sorry to make it so big, it really started small, but then it was grossing over and over... Jumping from one class to another...
In my defence the average time in which PRs get approved wouldn't fit for a continuous refactoring, as PRs can take days to be merged and I'd rather not wait when I'm in the flow.
Anyhow, this is unbearable, and probably not so wise to hand in such a big PR, so in the future I'll try to come up with some idea to hand it in sooner, with less change.
Once again, in my defence, a couple classes are so big that whatever you're changing it's definitely gonna be big. And this PR is basically about that. Breaking them up. Smaller classes will be probably easier to refactor, review, and essentially use. And that will eventually lead to me writing unit tests (well, once AutoMapper and Autofac gets thrown out).

All in all, please take your time reviewing this. I touched a lot of areas where I think I grasped the concept and why things work the way they do, but I'd not bet my neck on that. Please let me know if anything needs to be changed, or how I could improve even more. I'll try to look it over and over again, to see whether I find something, but I need more eyes than just mine :)

### CODE REVIEW

**Comment by chibidev** [comment]
Now that I see the actual stats, I'm a little bit disappointed in myself, that the ratio of added and removed code is over 1.0.

**Comment by kaso17** [comment]
thank you for cleaning up :)

**Comment by kaso17** [comment]
In my case it caused jackett startup to fail due to an autofac exception (due to the missing default autofac constructor for CardigannIndexer).
fb59e84def2d50ccf3eaee4becf07eabd3eb8c01 should properly fix it.

Can you have a look at the test cases (causing appveyor to fail)?

**Comment by chibidev** [comment]
@kaso17 I was just about to do that when you pushed it already :)

**Pull request merged**
