### PR TITLE
(Add) Blutopia (BLU)

### PR DESCRIPTION
**Pull request by HDVinnie**

### CODE REVIEW

**Comment by buthed010203** [comment]
Should remove this as well https://github.com/Jackett/Jackett/blob/ca802f998e7151e91111fd220e906ce566c56186/src/Jackett.Updater/Program.cs#L317

**Comment by garfield69** [comment]
OR you could have just asked me to revert my removal commit ;-)
Anyway, glad its back!

**Comment by HDVinnie** [comment]
> OR you could have just asked me to revert my removal commit ;-)
> Anyway, glad its back!

true that

**Comment by garfield69** [comment]
v0.22.1009

**Pull request merged**
