### PR TITLE
Add query url separator option for Cardigann indexer

### PR DESCRIPTION
**Pull request by cadatoiva**
Related #8054

### CODE REVIEW

**Comment by garfield69** [comment]
so theodyssey indexer i'm building ha a download block that looks like this
```yaml
  download:
    # details href: http://theodyssey.cc/index.php?topic=301.msg357#msg357
    before:
      # thanks href: http://theodyssey.cc/index.php?action=thank;msg=357;member=19;topic=301;refresh=1
      path: index.php
      method: get
      inputs:
        action: thanks
        topic: "{{ re_replace .DownloadUri.Query.topic \".msg\" \";msg=\"}}"
         member: "{{ .TBP.member }}"
        refresh: 1
     selector: a[href^="magnet:?xt="]
    attribute: href
```
how does the `separator` fit into this?

**Comment by cadatoiva** [comment]
It would go like this:
```  download:
    # details href: http://theodyssey.cc/index.php?topic=301.msg357#msg357
    before:
      # thanks href: http://theodyssey.cc/index.php?action=thank;msg=357;member=19;topic=301;refresh=1
      path: index.php
      method: get
      queryseparator: ;
      inputs:
        action: thanks
        topic: "{{ re_replace .DownloadUri.Query.topic \".msg\" \";msg=\"}}"
        member: "{{ .TBP.member }}"
        refresh: 1
    selector: a[href^="magnet:?xt="]
    attribute: href
```

**Comment by cadatoiva** [comment]
@garfield69 does that format work for you, or would you like a change?

**Comment by garfield69** [comment]
are you asking: (1) does `queryseparator: ;` conform to the standards of the download block statement structure,
or are you asking: (2) have you tested this and does it help you move a step closer to completing theodyssey  as a working yaml indexer?

(1) I cannot think of a better name for the statement, and given it will not see a lot of use, Im not fussed what is is called. 
(Note to self: I must remember to add it to the wiki as soon as its merged or I'll forget it even exists.)

(2) so I cheated and hard coded the input parms so that a valid thanks link would be generated
```yaml
  download:
    # details href: http://theodyssey.cc/index.php?topic=351.msg407#msg407
    before:
      # thanks href="http://theodyssey.cc/index.php?action=thank;msg=407;member=1;topic=351;refresh=1"
      path: index.php
      method: get
      queryseparator: ";"
      inputs:
        _action: thanks
        msg: 407
#        member: "{{ .TBP.member }}"
        member: 1
#        topic: "{{ .DownloadUri.Query.topic }}"
        topic: 351
        refresh: 1
    selector: a[href^="magnet:?xt="]
    attribute: href
```
unfortunately the thank link that jackett sent was
`http://theodyssey.cc/index.php?action=thanks&msg=407&member=1&topic=351&refresh=1`
it should have look like
`http://theodyssey.cc/index.php?action=thanks;msg=407;member=1;topic=351;refresh=1`

I tried `queryseparator: ;` and `queryseparator: ";"`
but I don't think this is working as you intended :-(

**Comment by cadatoiva** [comment]
Bit of both. I'll try to see why it's not working.

**Comment by cadatoiva** [comment]
@garfield69 think I found it, had to look at the parser settings. The correct term is `query-separator: ;`

**Comment by garfield69** [comment]
> think I found it, had to look at the parser settings. The correct term is `query-separator: ;`

no sorry, that is not it. Tested query-separator and the result was unchanged.
surely the keyword must match what you defined in the IndexerDefinition
```
public String QuerySeparator { get; set; } = "&";
``` 
case is ignored by Cardiagann so `queryseparator: ;` would seem correct

what is clear is that request.QuerySeparator remains set to "&" so the `queryseparator: ;` statement is not getting processed into request.QuerySeparator for some reason.

**Comment by cadatoiva** [comment]
Ok, after extensive testing, there is very clearly some kind of case sensitive something going on in the converter from YAML to code. I don't know what the system is specifically, but if I change any existing entry mappings to be PascalCase, it similarly breaks them in the definition loading. And removing the capitals in the middle like the others fixes the problems we've been having with `queryseparator` not working. I've tested this with a mock YAML and the value changes as expected.

**Comment by cadatoiva** [comment]
One more thing of note. While testing I managed to turn off error suppression on the YAML parsing temporarily. There are several yaml files that are malformed. To see which ones and in which ways, remove this line: https://github.com/Jackett/Jackett/blob/0fc36236cd3ffe95947060f7ab04a94d512baaf6/src/Jackett.Common/Services/IndexerManagerService.cs#L96

then either put a breakpoint here, or watch the log file for the message described in this line: https://github.com/Jackett/Jackett/blob/0fc36236cd3ffe95947060f7ab04a94d512baaf6/src/Jackett.Common/Services/IndexerManagerService.cs#L115

As example, one of the errors was that https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/4thd.yml is missing the `desc:` tag in all of the category mappings, and the error suggests that this means the descriptions are blank when they shouldn't be.

**Comment by garfield69** [comment]
Desc is supposdd to be optional on the cat mappings. The code is supposed to (and I think does) load the desc with the string equivalent of the torznab cat it is set toi, if one is not supplied.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/wiki/Definition-format#caps

**Comment by cadatoiva** [comment]
Yes, desc is optional, but putting a description string without tagging it as a desc is not, which is what happened in that file. Other files have different errors too, like containing entire sections that don't exist in our format.

Our current system will accept any file that contains legal YAML, regardless of if it's legal cardigann YAML.

**Comment by garfield69** [comment]
Fantastic!!
turning this on has provided the clue I needed to understand why **categorymappings** has not been working as documented in the wiki  #5544 
the documentation was wrong, and _categorymappings_  in the docs should have been **categories** !!!
\o/

**Comment by cadatoiva** [comment]
Nice. For any other issues like that, note that this file has the entire cardigann YAML hierarchy of names/types in it. First letter is made lowercase, but the rest is case sensitive: https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Models/IndexerDefinition.cs

**Comment by garfield69** [comment]
regarding IgnoreUnmatchedProperties in the IndexerManagerService
that was turned on in #1549 Feature/remove autofac from indexer manager

I am inclined to remove this to enable trapping again, as I cannot think why we should be ignoring the kind of things that I am now finding in the yaml which cause (from the point of view of the yaml writer) unexplained behaviour, or even worse, behaviour that goes against the intention of the writer.

**Comment by cadatoiva** [comment]
That's fine by me. Just know that as the current code stands, that means that any malformed YAML indexers will log an error and will be completely excluded from Jackett at runtime.

**Comment by garfield69** [comment]
yes, i'm going through the hits right now and correcting them, so that when I disable that ignore no existing yaml will get rejected ;-)

**Comment by cadatoiva** [comment]
Whenever I figure out how, we should probably also add an integration test that checks for this error specifically in future commits/PRs.

**Comment by ngosang** [comment]
> I am inclined to remove this to enable trapping again, as I cannot think why we should be ignoring the kind of things that I am now finding in the yaml which cause (from the point of view of the yaml writer) unexplained behaviour, or even worse, behaviour that goes against the intention of the writer.

Agree, we have to enable the validator always.

> Whenever I figure out how, we should probably also add an integration test that checks for this error specifically in future commits/PRs.

Yes, in this case is important. There are 2 ways:
* Doing a real integration test running a Jackett exec and wait for the logs (or the exit code if it fails).
* Doing a unit test with part of the code that Jackett uses to read the .ymls and parsing. We can try to load all of them and fail if there are any error. This will be unit testing for the cardigan parser only instead of the whole app.

The 2nd is more easier to do and I think is enough for now.

**Comment by cadatoiva** [comment]
They are probably both equally difficult, because the first can be done by reading the Console.Write() output that the logger puts out instead of grabbing and reading logs. Meanwhile, the code used to load the cardigann files spans a couple of classes, and would likely involve inheritance to create mock classes that ignore how tightly integrated the system is.

**Comment by ngosang** [comment]
Nah, that was easy => #8165

**Pull request merged**
