### PR TITLE
Re-run dotnet format and enable style enforcement.

### PR DESCRIPTION
**Pull request by cadatoiva**
This PR runs `dotnet format` on the solution and also adds a Pipelines job that fails if running a solution wide `dotnet format` would produce changes in any future PR. Honestly, I have no idea if the .yml is correct, so @junglebus will likely need to correct that, hence the WIP.

### CODE REVIEW

**Comment by junglebus** [comment]
@cadatoiva 
This was the best I get, bit obtuse, but it works
When I target everything I hit these errors https://dev.azure.com/jackett/7ce5b700-cf77-43c4-99d0-5a94780a195d/_apis/build/builds/455/logs/26
I'm not specifying the workspace, the tool is determining it. Command run was `dotnet-format --dry-run --check --verbosity diagnostic`

Updated the `dependsOn` in the pipeline as well. It's not strictly true, but I made it that way as we get a maximum of 10 VM's to use at once and that was the fastest pipeline completion time I could see

```
2020-04-06T11:04:06.4443818Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/4844d447-8d95-43c7-8ad4-35948014d0f9.sh
2020-04-06T11:04:06.9697508Z   Formatting code files in workspace '/home/vsts/work/1/s/src/Jackett.sln'.
2020-04-06T11:04:06.9698420Z   Loading workspace.
2020-04-06T11:04:09.7398231Z   Msbuild failed when processing the file '/home/vsts/work/1/s/src/Jackett.Tray/Jackett.Tray.csproj' with message: The imported project "/opt/hostedtoolcache/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.WinFX.props" was not found. Confirm that the expression in the Import declaration "Microsoft.WinFX.props" is correct, and that the file exists on disk.  /opt/hostedtoolcache/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.props
2020-04-06T11:04:09.7401961Z   Msbuild failed when processing the file '/home/vsts/work/1/s/src/Jackett.Updater/Jackett.Updater.csproj' with message: /opt/hostedtoolcache/dotnet/sdk/3.1.201/Microsoft.Common.CurrentVersion.targets: (1177, 5): The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
2020-04-06T11:04:09.7407483Z   Msbuild failed when processing the file '/home/vsts/work/1/s/src/Jackett.Updater/Jackett.Updater.csproj' with message: /opt/hostedtoolcache/dotnet/sdk/3.1.201/Microsoft.Common.CurrentVersion.targets: (1177, 5): The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
2020-04-06T11:04:09.7408894Z   Found project reference without a matching metadata reference: /home/vsts/work/1/s/src/Jackett.Common/Jackett.Common.csproj
2020-04-06T11:04:09.7410812Z   Msbuild failed when processing the file '/home/vsts/work/1/s/src/Jackett.Test/Jackett.Test.csproj' with message: /opt/hostedtoolcache/dotnet/sdk/3.1.201/Microsoft.Common.CurrentVersion.targets: (1177, 5): The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
2020-04-06T11:04:09.7413423Z   Msbuild failed when processing the file '/home/vsts/work/1/s/src/Jackett.Test/Jackett.Test.csproj' with message: /opt/hostedtoolcache/dotnet/sdk/3.1.201/Microsoft.Common.CurrentVersion.targets: (1177, 5): The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
2020-04-06T11:04:09.7416175Z   Msbuild failed when processing the file '/home/vsts/work/1/s/src/Jackett.Server/Jackett.Server.csproj' with message: /opt/hostedtoolcache/dotnet/sdk/3.1.201/Microsoft.Common.CurrentVersion.targets: (1177, 5): The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
2020-04-06T11:04:09.7418973Z   Msbuild failed when processing the file '/home/vsts/work/1/s/src/Jackett.Server/Jackett.Server.csproj' with message: /opt/hostedtoolcache/dotnet/sdk/3.1.201/Microsoft.Common.CurrentVersion.targets: (1177, 5): The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
2020-04-06T11:04:09.7420504Z   Found project reference without a matching metadata reference: /home/vsts/work/1/s/src/Jackett.Common/Jackett.Common.csproj
2020-04-06T11:04:09.7421126Z   Found project reference without a matching metadata reference: /home/vsts/work/1/s/src/Jackett.Common/Jackett.Common.csproj
2020-04-06T11:04:09.7421762Z   Found project reference without a matching metadata reference: /home/vsts/work/1/s/src/Jackett.Server/Jackett.Server.csproj
2020-04-06T11:04:09.7432296Z   Complete in 2771ms.
2020-04-06T11:04:09.7432548Z   Determining formattable files.
2020-04-06T11:04:11.7268663Z   Complete in 1986ms.
2020-04-06T11:04:11.7269085Z   Running formatters.
2020-04-06T11:04:13.7117423Z   Complete in 1985ms.
2020-04-06T11:04:13.7132727Z   Formatted 0 of 304 files.
2020-04-06T11:04:13.7133403Z   Format complete in 6744ms.
2020-04-06T11:04:13.7385234Z 
```

**Comment by ngosang** [comment]
I agree with the changes `dotnet format` did in the code.
Will this check fail if the code is not formatted properly?

**Comment by cadatoiva** [comment]
The `--dry-run --check` means that it won't make changes to the code, but will return an error if running `dotnet format` would have made changes to the code, so builds will fail if they violate the options supported by `dotnet format`. It's not all formatting, but it is practically all the whitespace formatting options, as detailed in this link: https://github.com/dotnet/format/blob/master/docs/Supported-.editorconfig-options.md

**Comment by ngosang** [comment]
ok, approved.

**Pull request merged**
