### PR TITLE
keepfriends: add doubanid search

### PR DESCRIPTION
**Pull request by ilike2burnthing**
@BusiBeaver @yuaner66 @gaofashao we want to add searching by Douban ID, but this needs tested as none of the maintainers have an account.

Please download this test build from [here](https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/6490/artifacts?artifactName=drop&api-version=7.0&%24format=zip), extract the version for your system, and install over your current install (if you're using Docker, you'll need to test this natively instead, e.g. on a Windows computer, and add KeepFriends).

To test that searching by Douban ID is working, use the links below, changing the address if needed, and replace `YOURAPIKEY` with your Jackett API key.

TV search for The Mandalorian:
http://127.0.0.1:9117/api/v2.0/indexers/keepfriends/results/torznab/api?apikey=YOURAPIKEY&t=tvsearch&cat=&doubanid=30344167

Movie search for Lightyear:
http://127.0.0.1:9117/api/v2.0/indexers/keepfriends/results/torznab/api?apikey=YOURAPIKEY&t=movie&cat=&doubanid=35284168

Searching within Jackett's UI will NOT work.

Check that the results are the same as those in your browser on KeepFriends by clicking the links below:
[The Mandalorian](https://pt.keepfrds.com/torrents.php?search=30344167&incldead=0&spstate=0&search_area=5&search_mode=0&sort=date&type=desc)
[Lightyear](https://pt.keepfrds.com/torrents.php?search=35284168&incldead=0&spstate=0&search_area=5&search_mode=0&sort=date&type=desc)
Results may differ slightly if you've set the freeleech, sort, and order Jackett settings.

If there are no results even on the website, please pick a different TV show or movie from https://movie.douban.com/ - for example The Mandalorian ID is `30344167`, this can be found at the end of its URL - https://movie.douban.com/subject/30344167/

[edit] entirely likely that the build will have expired by the time any of you get around to testing this, so if that is the case just let us know and we will re-build asap.

### CODE REVIEW

**Comment by garfield69** [comment]
@RoloSoze  can you help with testing this change for keepfriends?

**Comment by RoloSoze** [comment]
> @RoloSoze can you help with testing this change for keepfriends?

Sadly I'm not a member there anymore. It has been disabled due to inactivity.

**Comment by ilike2burnthing** [comment]
@BusiBeaver @yuaner66 @gaofashao

Please see above. This should only take about 5 minutes.

**Comment by yuaner66** [comment]
Use douban ID can't find any results
TV search for The Mandalorian:

Movie search for Lightyear:

Search The Mandalorian douban id in keepfirds:

Search  Lightyear douban id in keepfirds:

Search The Mandalorian in keepfirds:

Search  Lightyear in keepfirds:

We can use this link to search results:
[30344167](https://pt.keepfrds.com/torrents.php?incldead=0&spstate=0&inclbookmarked=0&option-torrents=0&search=30344167&search_area=1&search_mode=0)

**Comment by ilike2burnthing** [comment]
Many thanks. Will switch to description search instead.

**Pull request merged**
