### PR TITLE
Add Cardigann configuration for 720pier indexer.

### PR DESCRIPTION
**Pull request by xilic615**
Fixes https://github.com/Jackett/Jackett/issues/9524

### CODE REVIEW

**Comment by ngosang** [comment]
@garfield69 I think I fixed the 720pier issues in #9523 
If the .yml can show the same info the c# does I think the .yml is preferable because it's easy to maintain.

**Comment by garfield69** [comment]
replaced by #9131

**Comment by garfield69** [comment]
https://720pier.ru/ returns ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/632

**Pull request closed without merging**
