### PR TITLE
update girotorrent

### PR DESCRIPTION
**Pull request by Jorman**
possibility to go up to 10 pages during search/sync

### CODE REVIEW

**Comment by kaso17** [comment]
Why did you move the inputs to the paths?
With this change the categories are ignored for empty searches

**Comment by Jorman** [comment]
Mmm, I did an empty search with category selection and was ok, maybe I miss some
ricerca
But actually if I look to the code I see what you mean, do you think is better to add
`&category={{range .Categories}}{{.}};{{end}}`
to the empty searches?

**Comment by kaso17** [comment]
the categories are filtered on the jackett side again, you only see 8 results in your example.
I would suggest you use the common parameters as they have been used before your changes and just add the pages input to each path (all paths will use the common inputs and just override the pages input)

**Comment by Jorman** [comment]
The only way that came into my mind is to make ten times this search
`- path: "{{if .Keywords}}index.php?&category={{range .Categories}}{{.}};{{end}}&search={{ .Keywords}}&page=torrents&active=0&order=3&by=2&pages=1{{else}}/index.php?&category={{range .Categories}}{{.}};{{end}}&page=torrents&active=0&search=&&options=0&order=3&by=2&pages=1{{end}}"`

Do you mean to add an extra input
`pages: 1 // this make only page one`
But for different pages
How can I do this?

In that way the code remain more compact and elegant, but I don't know how to handle that

**Comment by kaso17** [comment]
Something like this:
```
  search:
    paths:
      - path: /index.php
        inputs:
          pages: 1
      - path: /index.php
        inputs:
          pages: 2
      - path: /index.php
        inputs:
          pages: 3
      ...
    inputs:
      search: "{{ .Keywords }}"
      category: "{{range .Categories}}{{.}};{{end}}"
      page: "torrents"
      active: 0
      order: 3
      by: 2

```

**Comment by Jorman** [comment]
Ok, I'll try and I'll update the code

Il giorno mar 15 gen 2019, 15:37 kaso17 <notifications@github.com> ha
scritto:

**Pull request merged**
