### PR TITLE
Update winget.yml

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
Thanks

**Comment by ilike2burnthing** [comment]
[v0.20.1208](https://github.com/Jackett/Jackett/releases/tag/v0.20.1208)

**Comment by ilike2burnthing** [comment]
Last two release updates have failed with:

```text
Run # Setup working environment
svn: E170000: URL 'https://github.com/vedantmgoyal2009/vedantmgoyal2009/trunk/winget-pkgs-automation/wingetdev' doesn't exist
warning: LF will be replaced by CRLF in Tools/YamlCreate.ps1.
The file will have its original line endings in your working directory
Run # Update manifests and publish
Resolve-Path: D:\a\_temp\d01f88e2-4874-439a-a6b9-5ea75dd31384.ps1:3
Line |
   3 |  … WinGetDev = (Resolve-Path -Path ..\..\wingetdev\wingetdev.exe).Path # …
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'D:\a\Jackett\Jackett\wingetdev\wingetdev.exe' because it does not exist.
```

**Comment by vedantmgoyal2009** [comment]
It is now fixed in commit https://github.com/vedantmgoyal2009/winget-releaser/commit/d273ef1dc9a9979d817f1fccf51a111c26d68e9f. Thanks for telling 🙏🏻

**Comment by vedantmgoyal2009** [comment]
@ilike2burnthing @garfield69 Please update the fork manually since there are some workflow changes on the upstream.

**Comment by ilike2burnthing** [comment]
Done.

**Comment by ilike2burnthing** [comment]
@vedantmgoyal2009 errors with the actions today:

```text
Exception: D:\a\_temp\01c0b942-045c-45cd-ab53-38ffa9726ed1.ps1:33
Line |
  33 |              throw $_.Exception.Message
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Conversion from JSON failed with error: Unexpected character encountered while parsing value: S. Path
     | '', line 0, position 0.

Error: Process completed with exit code 1.
```

Is it currently undergoing work?

**Comment by vedantmgoyal2009** [comment]
This is weird. I haven't made any changes in the action yet 🤷🏻

**Comment by ilike2burnthing** [comment]
We had the same error a few days ago, but we just updated the fork, reran the job, and it worked. Tried that, same error.

Does the error make sense to you?

**Comment by vedantmgoyal2009** [comment]
> Does the error make sense to you?

Nope. BTW, I'm re-writing the action in JavaScript and hope that will work better. It will come most probably by this weekend.

Really sorry for the inconvenience caused 🙏🏻

**Comment by vedantmgoyal2009** [comment]
The issue should be fixed now. Sorry for the inconvenience caused🙏🏻

**Comment by ilike2burnthing** [comment]
Working, thanks.

**Comment by ilike2burnthing** [comment]
@vedantmgoyal2009 new as of today, getting `Check Spelling` job errors:
https://github.com/Jackett/winget-pkgs/actions/runs/3279166307
https://github.com/Jackett/winget-pkgs/actions/runs/3279222156

**Pull request merged**
