### PR TITLE
Added Beyond-HD Torrents API indexer

### LINKED ISSUE #10898: [REQ] Beyond-HD new API
Beyond-HD has released a proper API for searching torrents.
Using this seems more robust and practical than todays yaml config file.

Documentation is on their forums: https://beyond-hd.me/forums/topic/torrents-api-overview-beyondhd.3721

### PR DESCRIPTION
**Pull request by PNWebster**
Added C# based indexer to resolve #10898

### CODE REVIEW

**Comment by RoloSoze** [comment]
I'm getting the following error message: `Value cannot be null. (Parameter 'source')`

Enhanced log:
2021-04-05 14:44:07.7634 Info Request starting HTTP/1.1 POST http://127.0.0.1:9117/api/v2.0/indexers/beyond-hd-api/config application/json 169 
2021-04-05 14:44:07.7634 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/beyond-hd-api/config 
2021-04-05 14:44:07.7634 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/beyond-hd-api/config 
2021-04-05 14:44:07.7634 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/beyond-hd-api/config 
2021-04-05 14:44:07.7634 Debug POST requests are not supported 
2021-04-05 14:44:07.7634 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2021-04-05 14:44:07.7634 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/beyond-hd-api/config' 
2021-04-05 14:44:07.7634 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/beyond-hd-api/config' 
2021-04-05 14:44:07.7634 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole)' 
2021-04-05 14:44:07.7634 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole)' 
2021-04-05 14:44:07.7734 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (JackettConsole). 
2021-04-05 14:44:07.7734 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2021-04-05 14:44:07.7734 Debug Execution plan of resource filters (in the following order): None 
2021-04-05 14:44:07.7734 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2021-04-05 14:44:07.7734 Debug Execution plan of exception filters (in the following order): None 
2021-04-05 14:44:07.7734 Debug Execution plan of result filters (in the following order): None 
2021-04-05 14:44:07.7734 Info Authorization was successful. 
2021-04-05 14:44:07.7734 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole) 
2021-04-05 14:44:07.7734 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole) 
2021-04-05 14:44:07.7734 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2021-04-05 14:44:07.7734 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
2021-04-05 14:44:07.7734 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'. 
2021-04-05 14:44:07.7734 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'. 
2021-04-05 14:44:07.7734 Debug Connection id "0HM7OCAKPTU3C", Request id "0HM7OCAKPTU3C:0000000E": started reading request body. 
2021-04-05 14:44:07.7734 Debug Connection id "0HM7OCAKPTU3C", Request id "0HM7OCAKPTU3C:0000000E": done reading request body. 
2021-04-05 14:44:07.7911 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2021-04-05 14:44:07.7911 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2021-04-05 14:44:07.7911 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2021-04-05 14:44:07.7911 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2021-04-05 14:44:07.7911 Debug CACHE CleanIndexerCache / Indexer: beyond-hd-api 
2021-04-05 14:44:07.7911 Debug CACHE PruneCacheByTtl / Pruned queries: 0 
2021-04-05 14:44:07.7911 Debug CACHE Status / Total cached results: 0 
2021-04-05 14:44:07.8125 Debug WebClient(HttpWebClient2).GetResultAsync(Method: POST Url: https://beyond-hd.me/api/torrents/xxxxxxxxxxx PostData: {action=search, rsskey=yyyyyyyyyyyyyyy, search=} RawBody: ) 
2021-04-05 14:44:08.6082 Debug __cfduid=df45bed93c6d0adf0c9cf1bdd33a719e51617648250; expires=Wed, 05-May-21 18:44:10 GMT; path=/; domain=.beyond-hd.me; HttpOnly; SameSite=Lax 
2021-04-05 14:44:08.6090 Debug XSRF-TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa; expires=Mon, 05-Apr-2021 20:44:10 GMT; Max-Age=7200; path=/; secure 
2021-04-05 14:44:08.6090 Debug beyondhd_session=dddddddddddddddddddddddd; expires=Mon, 05-Apr-2021 20:44:10 GMT; Max-Age=7200; path=/; secure; httponly 
2021-04-05 14:44:08.6090 Debug WebClient(HttpWebClient2): Returning OK => 102 bytes
{"status_code":0,"status_message":"Invalid API key: You must be granted a valid key.","success":false} 
2021-04-05 14:44:08.6090 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) in 842.4744ms 
2021-04-05 14:44:08.6090 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole)' 
2021-04-05 14:44:08.6090 Error Jackett.Common.ExceptionWithConfigData: Value cannot be null. (Parameter 'source')
   at Jackett.Common.Indexers.BeyondHDAPI.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\BeyondHDAPI.cs:line 78
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61 Jackett.Common.ExceptionWithConfigData: Value cannot be null. (Parameter 'source')
   at Jackett.Common.Indexers.BeyondHDAPI.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\BeyondHDAPI.cs:line 78
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
2021-04-05 14:44:08.6381 Debug The response will be compressed with 'gzip'. 
2021-04-05 14:44:08.6381 Debug Connection id "0HM7OCAKPTU3C" completed keep alive response. 
2021-04-05 14:44:08.6381 Info Request finished HTTP/1.1 POST http://127.0.0.1:9117/api/v2.0/indexers/beyond-hd-api/config application/json 169 - 500 - application/json 877.0668ms

**Comment by PNWebster** [comment]
@RoloSoze 

I am able to reproduce the error when I put invalid apikey/rsskey.
Response from BHD API (from your logs) is:

{"status_code":0,"status_message":"**Invalid API key: You must be granted a valid key**.","success":false}

Can you ensure api and rsskey are valid?

**Comment by ilike2burnthing** [comment]
@RoloSoze ping

**Comment by ilike2burnthing** [comment]
@PNWebster can you retest to confirm it's working for you and we can move forward?

**Comment by PNWebster** [comment]
@ilike2burnthing sure, I have retested with a cleanly fetched repo and it's still good for me.

I have tested it using Sonarr and Radarr on my machine, by adding Jackett as a Torznab indexer.
In Radarr I searched for The Dark Knight, got a few results, downloaded one, and its correct torrent with correct passkey.
In Sonarr I searched for Friends, Season 10, got a few results, downloaded one, and its correct torrent with correct passkey. 

On BHD, in the "My Security" page, the RSS key is listed before the API key, so perhaps @RoloSoze input them in incorrect order.

**Comment by ilike2burnthing** [comment]
Thanks.

@JigSawFr can you give the code a quick look over just to see if everything looks ok generally?

**Review by JigSawFr — APPROVED** [review]

**Comment by ItsME6969** [comment]
@PNWebster is it possible to access the video info (Dolby Vision / HDR) from the API. There are lots of Hybrid releases that are DoVi and HDR fallback but one cannot know because it doesn't appear on the release titles. If so what I was thinking is that it could be added as an option and placed at the end of the Titles. As of right now there's no way of knowing whether a title has HDR fallback without actually browsing the tracker.
abcd - Copy

**Comment by PNWebster** [comment]
@ItsME6969 Unfortunately the BHD Torrents API currently does not return that information.

The API does support filters for "features", which are described as

> DV, HDR10, HDR10P, Commentary

But this features filter must be included in the search query. For me there is no obvious way to add support to Jackett.

**Comment by ItsME6969** [comment]
Oh ok, no worries appreciate you taking the time to look into this @PNWebster. Cheers.

**Comment by ItsME6969** [comment]
@PNWebster the API was updated to return that info if maybe you can have a second look.

**Comment by PNWebster** [comment]
@ItsME6969 Thanks for the heads up, I've created a new pull request #13398

**Comment by ItsME6969** [comment]
@PNWebster Amazing!!! Thanks alot. This update will for sure be useful to alot of folks.

**Pull request merged**
