### PR TITLE
lemonhd: add doubanid search

### PR DESCRIPTION
**Pull request by ilike2burnthing**
@Uzibird @horseytr @hoong7 @tuningman9790 @finikium @skygunner @tjxme we want to add searching by Douban ID, but this needs tested as none of the maintainers have an account.

Please download this test build from [here](https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/6188/artifacts?artifactName=drop&api-version=7.0&%24format=zip), extract the version for your system, and install over your current install (if you're using Docker, you'll need to test this natively instead, e.g. on a Windows computer, and add LemonHD).

To test that searching by Douban ID is working, use the links below, changing the address if needed, and replace `YOURAPIKEY` with your Jackett API key.

TV search for The Mandalorian:
http://127.0.0.1:9117/api/v2.0/indexers/lemonhd/results/torznab/api?apikey=YOURAPIKEY&t=tvsearch&cat=&doubanid=30344167

Movie search for Lightyear:
http://127.0.0.1:9117/api/v2.0/indexers/lemonhd/results/torznab/api?apikey=YOURAPIKEY&t=movie&cat=&doubanid=35284168

Searching within Jackett's UI will NOT work.

Check that the results are the same as those in your browser on LemonHD by clicking the links below:
[The Mandalorian](https://lemonhd.org/torrents.php?search=30344167&search_area=douban&suggest=0&column=date&sort=desc)
[Lightyear](https://lemonhd.org/torrents.php?search=35284168&search_area=douban&suggest=0&column=date&sort=desc)
Results may differ slightly if you've set the freeleech, sort, and order Jackett settings.

If there are no results even on the website, please pick a different TV show or movie from https://movie.douban.com/ - for example The Mandalorian ID is `30344167`, this can be found at the end of its URL - https://movie.douban.com/subject/30344167/

### CODE REVIEW

**Comment by tjxme** [comment]
Sry I’m using docker composer. What should I do to install this??? 

Regards,

J.T

**Comment by ilike2burnthing** [comment]
As I said, if you're using Docker, you'll need to test this natively instead, e.g. on a Windows computer, and add LemonHD.

If that's impossible, there is a workaround, but I'd rather not have to resort to it.

**Comment by tjxme** [comment]
Ok. I guess I should not bother getting chrome docker then. I will do a new install for windows and test it right?

**Comment by ilike2burnthing** [comment]
A new install on Windows would be the best option, yes. Thanks.

**Comment by tjxme** [comment]
TESTED to found 7 releases for Madalorian

<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://127.0.0.1:9117/" rel="self" type="application/rss+xml" />
    <title>LemonHD</title>
    <description>LemonHD is a CHINESE Private Torrent Tracker for HD MOVIES / TV</description>
    <link>https://lemonhd.org/</link>
    <language>en-US</language>
    <category>search</category>
    <item>
      <title>The Mandalorian S01 2160p HDR DSNP WEB-DL H.265 DDP5.1 Atmos-OurTV</title>
      <guid>https://lemonhd.org/download.php?https=1&amp;id=307943</guid>
      <jackettindexer id="lemonhd">LemonHD</jackettindexer>
      <type>private</type>
      <comments>https://lemonhd.org/details_tv.php?id=307943</comments>
      <pubDate>Mon, 06 Jun 2022 21:33:06 -0400</pubDate>
      <size>37903085568</size>
      <grabs>120</grabs>
      <description>The Mandalorian S01 2160p HDR DSNP WEB-DL H.265 DDP5.1 Atmos-OurTV</description>
      <link>http://127.0.0.1:9117/dl/lemonhd/?jackett_apikey=9hea5dc8yt6kzvo5k8z0aopwl2cm5455&amp;path=Q2ZESjhJZ0hDMlFxV2ZKR2xLb1RzMW1Ca3Vnd3lMSV9vcXFzTVJ4aWpuOTJKNmRiQTRfQ1A2SS1XcVpoX3JBeDRlc2tSeGV1MlNlbjF0Rnd3bW4tRzNEVG1jQ0UxbFJoY3p5WGo2NWJMMjZGRmVrUERPMUkxVUFxeEQ2SUJMV05qNW40UXpJNDZtQV9RSWVEX2pKdUVZTDdDcTZqQnpmRlJUU2NWVjVlMUVaWG1OYnFDUm9hYngxSmVCTi1xWHR0bFlZekZR&amp;file=The+Mandalorian+S01+2160p+HDR+DSNP+WEB-DL+H.265+DDP5.1+Atmos-OurTV</link>
      <category>5000</category>
      <category>103583</category>
      <enclosure url="http://127.0.0.1:9117/dl/lemonhd/?jackett_apikey=9hea5dc8yt6kzvo5k8z0aopwl2cm5455&amp;path=Q2ZESjhJZ0hDMlFxV2ZKR2xLb1RzMW1Ca3Vnd3lMSV9vcXFzTVJ4aWpuOTJKNmRiQTRfQ1A2SS1XcVpoX3JBeDRlc2tSeGV1MlNlbjF0Rnd3bW4tRzNEVG1jQ0UxbFJoY3p5WGo2NWJMMjZGRmVrUERPMUkxVUFxeEQ2SUJMV05qNW40UXpJNDZtQV9RSWVEX2pKdUVZTDdDcTZqQnpmRlJUU2NWVjVlMUVaWG1OYnFDUm9hYngxSmVCTi1xWHR0bFlZekZR&amp;file=The+Mandalorian+S01+2160p+HDR+DSNP+WEB-DL+H.265+DDP5.1+Atmos-OurTV" length="37903085568" type="application/x-bittorrent" />
      <torznab:attr name="category" value="5000" />
      <torznab:attr name="category" value="103583" />
      <torznab:attr name="imdb" value="8111088" />
      <torznab:attr name="imdbid" value="tt8111088" />
      <torznab:attr name="genre" value="" />
      <torznab:attr name="seeders" value="17" />
      <torznab:attr name="peers" value="17" />
      <torznab:attr name="downloadvolumefactor" value="1" />
      <torznab:attr name="uploadvolumefactor" value="1" />
    </item>
    <item>
      <title>The Mandalorian S01 2160p DSNP WEB-DL DDP5.1 Atmos DV HEVC-MZABI</title>
      <guid>https://lemonhd.org/download.php?https=1&amp;id=284091</guid>
      <jackettindexer id="lemonhd">LemonHD</jackettindexer>
      <type>private</type>
      <comments>https://lemonhd.org/details_tv.php?id=284091</comments>
      <pubDate>Sun, 30 Jan 2022 02:08:48 -0500</pubDate>
      <size>37935300608</size>
      <grabs>174</grabs>
      <description>The Mandalorian S01 2160p DSNP WEB-DL DDP5.1 Atmos DV HEVC-MZABI</description>
      <link>http://127.0.0.1:9117/dl/lemonhd/?jackett_apikey=9hea5dc8yt6kzvo5k8z0aopwl2cm5455&amp;path=Q2ZESjhJZ0hDMlFxV2ZKR2xLb1RzMW1Ca3VqR3F5OTBBRjB2bXR0cEVUbDBZMHZVLXNfOUk4a0ZpLVJKMkdJT3A5blhLSVd6RjVvREtNc2VEUE5YRlZKVmFscWw4bjg3SnU3WHEycTFKNUljRWpjQjZrc3V2dUlsUi1uTmxiVVctdVIxTUs3S1lYYnlxVXVEZFJGWWJWdTcta3BnRl9PZ2F4Q0pFWGFoczI1ME9lZzVMVG5oWVJ1VHRVUUtSbEo4R0w0NkR3&amp;file=The+Mandalorian+S01+2160p+DSNP+WEB-DL+DDP5.1+Atmos+DV+HEVC-MZABI</link>
      <category>5000</category>
      <category>103583</category>
      <enclosure url="http://127.0.0.1:9117/dl/lemonhd/?jackett_apikey=9hea5dc8yt6kzvo5k8z0aopwl2cm5455&amp;path=Q2ZESjhJZ0hDMlFxV2ZKR2xLb1RzMW1Ca3VqR3F5OTBBRjB2bXR0cEVUbDBZMHZVLXNfOUk4a0ZpLVJKMkdJT3A5blhLSVd6RjVvREtNc2VEUE5YRlZKVmFscWw4bjg3SnU3WHEycTFKNUljRWpjQjZrc3V2dUlsUi1uTmxiVVctdVIxTUs3S1lYYnlxVXVEZFJGWWJWdTcta3BnRl9PZ2F4Q0pFWGFoczI1ME9lZzVMVG5oWVJ1VHRVUUtSbEo4R0w0NkR3&amp;file=The+Mandalorian+S01+2160p+DSNP+WEB-DL+DDP5.1+Atmos+DV+HEVC-MZABI" length="37935300608" type="application/x-bittorrent" />
      <torznab:attr name="category" value="5000" />
      <torznab:attr name="category" value="103583" />
      <torznab:attr name="imdb" value="8111088" />
      <torznab:attr name="imdbid" value="tt8111088" />
      <torznab:attr name="genre" value="" />
      <torznab:attr name="seeders" value="11" />
      <torznab:attr name="peers" value="11" />
      <torznab:attr name="downloadvolumefactor" value="1" />
      <torznab:attr name="uploadvolumefactor" value="1" />
    </item>
    <item>
      <title>The Mandalorian S01 2019 Disney+ WEB-DL 1080p H.264 DDP-AREY</title>
      <guid>https://lemonhd.org/download.php?https=1&amp;id=251418</guid>
      <jackettindexer id="lemonhd">LemonHD</jackettindexer>
      <type>private</type>
      <comments>https://lemonhd.org/details_tv.php?id=251418</comments>
      <pubDate>Mon, 06 Sep 2021 01:03:57 -0400</pubDate>
      <size>19026704384</size>
      <grabs>133</grabs>
      <description>The Mandalorian S01 2019 Disney+ WEB-DL 1080p H.264 DDP-AREY</description>
      <link>http://127.0.0.1:9117/dl/lemonhd/?jackett_apikey=9hea5dc8yt6kzvo5k8z0aopwl2cm5455&amp;path=Q2ZESjhJZ0hDMlFxV2ZKR2xLb1RzMW1Ca3VnVndkcVBqbUlUS2wybFQ5alRGMlJFTlRvQkdpenJQc2J5OXpRclhhRUhkSXFPU1V3YjJ2OFA1djNZVUtHdlBmQk5pVC1LWXZMU1BFdGlKZkxJRzJ1cEM0cFVLNGxuZzN0SkZZQ2k2TjdsSWhOSkYtVzYwQy04N2lCVGlHa2hlbm9ycXJUQzUwTUZBRWRGY2dUaXhDZTBKZV95T2Q2OWVyTmphbGNOT3FDWEZR&amp;file=The+Mandalorian+S01+2019+Disney%2B+WEB-DL+1080p+H.264+DDP-AREY</link>
      <category>5000</category>
      <category>103583</category>
      <enclosure url="http://127.0.0.1:9117/dl/lemonhd/?jackett_apikey=9hea5dc8yt6kzvo5k8z0aopwl2cm5455&amp;path=Q2ZESjhJZ0hDMlFxV2ZKR2xLb1RzMW1Ca3VnVndkcVBqbUlUS2wybFQ5alRGMlJFTlRvQkdpenJQc2J5OXpRclhhRUhkSXFPU1V3YjJ2OFA1djNZVUtHdlBmQk5pVC1LWXZMU1BFdGlKZkxJRzJ1cEM0cFVLNGxuZzN0SkZZQ2k2TjdsSWhOSkYtVzYwQy04N2lCVGlHa2hlbm9ycXJUQzUwTUZBRWRGY2dUaXhDZTBKZV95T2Q2OWVyTmphbGNOT3FDWEZR&amp;file=The+Mandalorian+S01+2019+Disney%2B+WEB-DL+1080p+H.264+DDP-AREY" length="19026704384" type="application/x-bittorrent" />
      <torznab:attr name="category" value="5000" />
      <torznab:attr name="category" value="103583" />
      <torznab:attr name="imdb" value="8111088" />
      <torznab:attr name="imdbid" value="tt8111088" />
      <torznab:attr name="genre" value="" />
      <torznab:attr name="seeders" value="13" />
      <torznab:attr name="peers" value="13" />
      <torznab:attr name="downloadvolumefactor" value="1" />
      <torznab:attr name="uploadvolumefactor" value="1" />
    </item>
    <item>
      <title>The Mandalorian S01 2160p WEB-DL DDP5.1 x265-TEPES</title>
      <guid>https://lemonhd.org/download.php?https=1&amp;id=184546</guid>
      <jackettindexer id="lemonhd">LemonHD</jackettindexer>
      <type>private</type>
      <comments>https://lemonhd.org/details_tv.php?id=184546</comments>
      <pubDate>Tue, 24 Nov 2020 23:30:29 -0500</pubDate>
      <size>46042050560</size>
      <grabs>109</grabs>
      <description>The Mandalorian S01 2160p WEB-DL DDP5.1 x265-TEPES</description>
      <link>http://127.0.0.1:9117/dl/lemonhd/?jackett_apikey=9hea5dc8yt6kzvo5k8z0aopwl2cm5455&amp;path=Q2ZESjhJZ0hDMlFxV2ZKR2xLb1RzMW1Ca3VpLWpjTm5MZ2JOWi01bXUxaGtKRk8zVWl5VTdiTmhRRUw3eUMwdTRmWVNobnladGZBUEhiRHJ3RmRIbWJJcUJsd3FPN2UyTVpfbnp4eG9BTDgxSThaU2MtbEZ2dXhSQ3ZKX1JzXy1KcDFvcnYxZ0t5MzZNRlIzNmozQ2Z4Q1ZfU0Nnbm90b3BBQS1GRHNYcUxlSVBQeHg4WEFwWlpmbDEwbC1fNU05ZHNrelpB&amp;file=The+Mandalorian+S01+2160p+WEB-DL+DDP5.1+x265-TEPES</link>
      <category>5000</category>
      <category>103583</category>
      <enclosure url="http://127.0.0.1:9117/dl/lemonhd/?jackett_apikey=9hea5dc8yt6kzvo5k8z0aopwl2cm5455&amp;path=Q2ZESjhJZ0hDMlFxV2ZKR2xLb1RzMW1Ca3VpLWpjTm5MZ2JOWi01bXUxaGtKRk8zVWl5VTdiTmhRRUw3eUMwdTRmWVNobnladGZBUEhiRHJ3RmRIbWJJcUJsd3FPN2UyTVpfbnp4eG9BTDgxSThaU2MtbEZ2dXhSQ3ZKX1JzXy1KcDFvcnYxZ0t5MzZNRlIzNmozQ2Z4Q1ZfU0Nnbm90b3BBQS1GRHNYcUxlSVBQeHg4WEFwWlpmbDEwbC1fNU05ZHNrelpB&amp;file=The+Mandalorian+S01+2160p+WEB-DL+DDP5.1+x265-TEPES" length="46042050560" type="application/x-bittorrent" />
      <torznab:attr name="category" value="5000" />
      <torznab:attr name="category" value="103583" />
      <torznab:attr name="imdb" value="8111088" />
      <torznab:attr name="imdbid" value="tt8111088" />
      <torznab:attr name="genre" value="" />
      <torznab:attr name="seeders" value="6" />
      <torznab:attr name="peers" value="6" />
      <torznab:attr name="downloadvolumefactor" value="1" />
      <torznab:attr name="uploadvolumefactor" value="1" />
    </item>
    <item>
      <title>The Mandalorian S01 INTERNAL HDR 2160p WEB H265-SKGTV</title>
      <guid>https://lemonhd.org/download.php?https=1&amp;id=27729</guid>
      <jackettindexer id="lemonhd">LemonHD</jackettindexer>
      <type>private</type>
      <comments>https://lemonhd.org/details_tv.php?id=27729</comments>
      <pubDate>Tue, 12 May 2020 20:07:16 -0400</pubDate>
      <size>38107099136</size>
      <grabs>101</grabs>
      <description>The Mandalorian S01 INTERNAL HDR 2160p WEB H265-SKGTV</description>
      <link>http://127.0.0.1:9117/dl/lemonhd/?jackett_apikey=9hea5dc8yt6kzvo5k8z0aopwl2cm5455&amp;path=Q2ZESjhJZ0hDMlFxV2ZKR2xLb1RzMW1Ca3VpRHFmV1h2VFgtTjBMUDcySmExSDYtcVExUUpSaEdnZlBHMzBCTWpvX2lnWEplVlFsSkpQQWtueEstWW0yUE1LNGRyR05ySnFVdTJkdmFZWVpJNDl4Vm5odTFtNHNtd2ZuNXc1RFM4a2pwMzhYUVkzUGVqcF9DUGFxczB1UTN5aXN6bDBSb0JWZUIwVGw1aHVEOERvbUgwUGhiYXc0ejZUVWpqNV9KYm50Uk9B&amp;file=The+Mandalorian+S01+INTERNAL+HDR+2160p+WEB+H265-SKGTV</link>
      <category>5000</category>
      <category>103583</category>
      <enclosure url="http://127.0.0.1:9117/dl/lemonhd/?jackett_apikey=9hea5dc8yt6kzvo5k8z0aopwl2cm5455&amp;path=Q2ZESjhJZ0hDMlFxV2ZKR2xLb1RzMW1Ca3VpRHFmV1h2VFgtTjBMUDcySmExSDYtcVExUUpSaEdnZlBHMzBCTWpvX2lnWEplVlFsSkpQQWtueEstWW0yUE1LNGRyR05ySnFVdTJkdmFZWVpJNDl4Vm5odTFtNHNtd2ZuNXc1RFM4a2pwMzhYUVkzUGVqcF9DUGFxczB1UTN5aXN6bDBSb0JWZUIwVGw1aHVEOERvbUgwUGhiYXc0ejZUVWpqNV9KYm50Uk9B&amp;file=The+Mandalorian+S01+INTERNAL+HDR+2160p+WEB+H265-SKGTV" length="38107099136" type="application/x-bittorrent" />
      <torznab:attr name="category" value="5000" />
      <torznab:attr name="category" value="103583" />
      <torznab:attr name="imdb" value="8111088" />
      <torznab:attr name="imdbid" value="tt8111088" />
      <torznab:attr name="genre" value="" />
      <torznab:attr name="seeders" value="14" />
      <torznab:attr name="peers" value="14" />
      <torznab:attr name="downloadvolumefactor" value="1" />
      <torznab:attr name="uploadvolumefactor" value="1" />
    </item>
    <item>
      <title>The Mandalorian 2019 S01 1080p WEBRiP x264 DTS-HD MA-CREATiVE24</title>
      <guid>https://lemonhd.org/download.php?https=1&amp;id=13122</guid>
      <jackettindexer id="lemonhd">LemonHD</jackettindexer>
      <type>private</type>
      <comments>https://lemonhd.org/details_tv.php?id=13122</comments>
      <pubDate>Sat, 22 Feb 2020 23:46:57 -0500</pubDate>
      <size>44775034880</size>
      <grabs>77</grabs>
      <description>The Mandalorian 2019 S01 1080p WEBRiP x264 DTS-HD MA-CREATiVE24</description>
      <link>http://127.0.0.1:9117/dl/lemonhd/?jackett_apikey=9hea5dc8yt6kzvo5k8z0aopwl2cm5455&amp;path=Q2ZESjhJZ0hDMlFxV2ZKR2xLb1RzMW1Ca3VqSEhQaDIzT2dkTzlocENRV2hEb1owN1pza2ZyYzZoekViTkRnMWpZQS1KWW1OemtVTG9KSDY1bnpiVkVnX2JtajV2V3AwaFVUaFJTaVdRdGhBYkNtTVR5YWdnazR0Zjd3RUlHcDVlc2lHcXZHb3p1US13NHR0bExNUkJmMnlhQ2RaVXBXQVJVaGdQa1JuUldDVDJna2ViZDFhVElVY3UwRGpJTUI4ZWJybm93&amp;file=The+Mandalorian+2019+S01+1080p+WEBRiP+x264+DTS-HD+MA-CREATiVE24</link>
      <category>5000</category>
      <category>103583</category>
      <enclosure url="http://127.0.0.1:9117/dl/lemonhd/?jackett_apikey=9hea5dc8yt6kzvo5k8z0aopwl2cm5455&amp;path=Q2ZESjhJZ0hDMlFxV2ZKR2xLb1RzMW1Ca3VqSEhQaDIzT2dkTzlocENRV2hEb1owN1pza2ZyYzZoekViTkRnMWpZQS1KWW1OemtVTG9KSDY1bnpiVkVnX2JtajV2V3AwaFVUaFJTaVdRdGhBYkNtTVR5YWdnazR0Zjd3RUlHcDVlc2lHcXZHb3p1US13NHR0bExNUkJmMnlhQ2RaVXBXQVJVaGdQa1JuUldDVDJna2ViZDFhVElVY3UwRGpJTUI4ZWJybm93&amp;file=The+Mandalorian+2019+S01+1080p+WEBRiP+x264+DTS-HD+MA-CREATiVE24" length="44775034880" type="application/x-bittorrent" />
      <torznab:attr name="category" value="5000" />
      <torznab:attr name="category" value="103583" />
      <torznab:attr name="imdb" value="8111088" />
      <torznab:attr name="imdbid" value="tt8111088" />
      <torznab:attr name="genre" value="" />
      <torznab:attr name="seeders" value="2" />
      <torznab:attr name="peers" value="2" />
      <torznab:attr name="downloadvolumefactor" value="1" />
      <torznab:attr name="uploadvolumefactor" value="1" />
    </item>
    <item>
      <title>The Mandalorian 2019 S01 2160p WEB H265</title>
      <guid>https://lemonhd.org/download.php?https=1&amp;id=10422</guid>
      <jackettindexer id="lemonhd">LemonHD</jackettindexer>
      <type>private</type>
      <comments>https://lemonhd.org/details_tv.php?id=10422</comments>
      <pubDate>Mon, 30 Dec 2019 18:41:42 -0500</pubDate>
      <size>33586644992</size>
      <grabs>135</grabs>
      <description>The Mandalorian 2019 S01 2160p WEB H265</description>
      <link>http://127.0.0.1:9117/dl/lemonhd/?jackett_apikey=9hea5dc8yt6kzvo5k8z0aopwl2cm5455&amp;path=Q2ZESjhJZ0hDMlFxV2ZKR2xLb1RzMW1Ca3VpWlpUTTlrNGlNcG56SDF4cXFYSlhmRlBzR1gyb1ZVYjBPd3VmaTU0Z3lFdFJqWDQweWlVc1JlVnVISFpyY3U3ZFRYaDNScVppR1RLWDd3UnZpbFJNVVlNdjU3VVl2Nmo5NWFjTUROMElWcVVuRlJUcmdBU0FadUY5eldpcnVhblZjcjB2TVdEM2xaU0ZlanRFeWVBRHFkd2hvN1hDWWJEX3ViYk4tRk85Zkdn&amp;file=The+Mandalorian+2019+S01+2160p+WEB+H265</link>
      <category>5000</category>
      <category>103583</category>
      <enclosure url="http://127.0.0.1:9117/dl/lemonhd/?jackett_apikey=9hea5dc8yt6kzvo5k8z0aopwl2cm5455&amp;path=Q2ZESjhJZ0hDMlFxV2ZKR2xLb1RzMW1Ca3VpWlpUTTlrNGlNcG56SDF4cXFYSlhmRlBzR1gyb1ZVYjBPd3VmaTU0Z3lFdFJqWDQweWlVc1JlVnVISFpyY3U3ZFRYaDNScVppR1RLWDd3UnZpbFJNVVlNdjU3VVl2Nmo5NWFjTUROMElWcVVuRlJUcmdBU0FadUY5eldpcnVhblZjcjB2TVdEM2xaU0ZlanRFeWVBRHFkd2hvN1hDWWJEX3ViYk4tRk85Zkdn&amp;file=The+Mandalorian+2019+S01+2160p+WEB+H265" length="33586644992" type="application/x-bittorrent" />
      <torznab:attr name="category" value="5000" />
      <torznab:attr name="category" value="103583" />
      <torznab:attr name="imdb" value="8111088" />
      <torznab:attr name="imdbid" value="tt8111088" />
      <torznab:attr name="genre" value="" />
      <torznab:attr name="seeders" value="4" />
      <torznab:attr name="peers" value="4" />
      <torznab:attr name="downloadvolumefactor" value="1" />
      <torznab:attr name="uploadvolumefactor" value="1" />
    </item>
  </channel>
</rss>

**Comment by tjxme** [comment]
the lightyear returns one result.

**Comment by ilike2burnthing** [comment]
Great, thanks very much!

**Pull request merged**
