### PR TITLE
Feature/package reference restore

### PR DESCRIPTION
**Pull request by NathanNZ**
Pull request for Issue #2024

### CODE REVIEW

**Comment by NathanNZ** [comment]
Looks like Appveyor is set to use Visual Studio 2015 even though it's referenced in the YAML file to use Visual Studio 2015.

On my own instance of appveyor set to use Visual Studio 2017 it works up until the build of the test project, where it ends up failing. Not sure why this is the case as it works from the command line locally. Will investigate this tomorrow.

**Comment by NathanNZ** [comment]
So I have managed to get it working on my own instance of appveyor after setting the environment to Visual Studio 2017. Still doesn't quite work as mono isn't installed on the 2017 Build Agent and the newer csproj files are not supported by xbuild.

This might not be an issue if we move from xbuild to msbuild as per #2026 .

**Comment by flightlevel** [comment]
Awesome work!  
I exposed appveyor.yml now and updated the build script to remove xbuild in favour of MSBuild as per https://github.com/Jackett/Jackett/pull/2031
Would you be able to remove appveyor.yml (i've caused a merge conflict) changes from your PR and update to latest and I'll get this merged in

**Comment by NathanNZ** [comment]
Hurrah!

**Pull request merged**
