### PR TITLE
Fix TV search for MoreThanTV

### PR DESCRIPTION
**Pull request by majorearnest**
The logic to check if the query is for TV is not working correctly because the query can contain sub categories.
This will fix it.

### CODE REVIEW

**Comment by flightlevel** [comment]
Thanks @majorearnest

**Comment by armani316** [comment]
Great! MTV had a minor issue where Jackett couldn't return some results! I tested the ones I had encountered in the past, and it works perfectly fine now! Thanks, @majorearnest!

**Comment by armani316** [comment]
Great! MTV had a minor issue where Jackett couldn't return some results! I tested the ones I had encountered in the past, and it works perfectly fine now! Thanks, @majorearnest!

However, there is still a small issue, and I guess this has to do with the way MTV groups and names TV seasons, so I'm not sure if it can be solved in Jackett.

For example, search MTV on Jackett for:
24 S07 - [1 result]
24 Season 7 - [3 results] which do not include the one found previously

Can something be done about this, @majorearnest?

**Comment by majorearnest** [comment]
@armani316 Unfortunately not. That would require making two requests to MTV for every search with I'd imagine would be undesirable.
Since most seasons are grouped in the second format, I figured this was the better compromise.

**Comment by armani316** [comment]
@majorearnest Thanks for responding. Yeah I guess MTV's method of grouping seasons isn't exactly ideal. I guess we'll just have to search twice using both keywords to make sure all results are returned in Jackett. Thanks again!

**Pull request merged**
