### PR TITLE
torrentleech: add 2fa support

### LINKED ISSUE #13772: [TorrentLeech] upcoming 2FA
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
All
```

### Description

TLDR, add a `alt2FAToken` setting to pass with the username/password fields for TL

TL is implementing 2FA options for its users. This will of course break being able to send the user/pass and login to search. Until they add a proper search API they are going to implement a new field `alt2FAToken` that will be an MD5 hash to bypass the 2FA login. So basically users will get this 2FA token from TL and add it to Jackett so it can bypass enabled 2FA user logins.

The staff is already testing the 2FA and plans are to roll it out to users in the next couple days. 

### Logged Error Messages

```text
None yet
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by mynameisbogdan**
* Fixes #13772

### CODE REVIEW

**Review by ilike2burnthing — APPROVED** [review]
I won't be testing this, as it would mean using my personal authenticator with TL, but it looks good to me.

**Comment by garfield69** [comment]
So who has tested this then, because I don't see otpkey as a key on the login page, so ??

**Comment by garfield69** [comment]
Thank you.

**Comment by garfield69** [comment]
if the proper 2fa works then lets keep it. The bypass code was an early fix which we did not install in time because C# ;-b

**Pull request merged**
