### PR TITLE
abnormal: fix no results error

### PR DESCRIPTION
**Pull request by JigSawFr**

### CODE REVIEW

**Comment by JigSawFr** [comment]
@ilike2burnthing @garfield69 thanks guys for whitespace, if you can tell me how you remove/replace these, I will be glad to understand it ! :)

**Comment by ilike2burnthing** [comment]
If you look at the `Code Style Compliance Linting Dotnet` check - https://github.com/Jackett/Jackett/pull/11932/checks?check_run_id=2857383520 - the log shows:
```
/home/vsts/work/1/s/src/Jackett.Common/Indexers/Abnormal.cs(295,27): error WHITESPACE: Fix whitespace formatting. Insert '\s'. [/home/vsts/work/1/s/src]
```
So line 295, position 27, add 1 space.

In other cases it may be `\n\s\s\s\s\s\s` which would be `1 new line and 6 spaces`.

**Comment by JigSawFr** [comment]
@ilike2burnthing thank you !

**Comment by ilike2burnthing** [comment]
Our check uses:
`dotnet-format --check --verbosity diagnostic --folder ./src`

To fix whitespaces yourself, use:
`dotnet-format --fix-whitespace --verbosity diagnostic --folder ./src`

**Pull request merged**
