### PR TITLE
core: refactor book-search

### PR DESCRIPTION
**Pull request by ngosang**

### CODE REVIEW

**Comment by ngosang** [comment]
@garfield69 
* I renamed book param `title` to `booktitle` but I'm not sure if we are following newznab or torznab specs. Could we check what parameters LazyLibrarian or similar software uses? => https://torznab.github.io/spec-1.3-draft/torznab/Specification-v1.3.html#predefined-attributes
* This PR enables book-search in a lot of indexers. In the previous code there was a validation that only enabled book-search in bibliotik indexer. => https://github.com/Jackett/Jackett/pull/9897/files#diff-76185f0a79a2c5123ec2731d21a9318e3d857edda80e5b02dbbd9e812fbcc00bL116
* Should we add more book params?
* Some indexers like shareisland have imdbid parameter in `search` mode. Is that correct? => https://github.com/Jackett/Jackett/blob/6da1b5beae65d7f1f8c43a905b2078f782d87fca/src/Jackett.Common/Definitions/shareisland.yml#L26

**Comment by garfield69** [comment]
>I renamed book param title to booktitle but I'm not sure if we are following newznab or torznab specs. Could we check what parameters LazyLibrarian or similar software uses? 

I'm confused about this. It was my understanding that the book-search parms are q, author and title.
where did you read that the book-search parm should be booktitle?

I've not used lazylibrarian as there is no windows version, just mac and linux. It's a python based tool with bugger all useful docs, I am not inclined to spend time researching.
The only book app I have used is Readarr, and I tested this with 0.16.1817 (from this PR) but it looks like the torznab query this app uses is t=search, so I don't know if this meant it did not like the t=book-search parms and is defaulting to t=search or if the app just always used the standard t=search mode.
I know of no other book-search torznab apps...anyone aware of any for windows that I can test?

>We should update the documentation => https://torznab.github.io/spec-1.3-draft/torznab/Specification-v1.3.html#predefined-attributes

do you mean you want me to update our wiki and readme to also point to this draft torznab 1.3 document?

>Should we add more book params?

IMO not for now. only author and title are expected to be used. we can always add more parms if requested.

>Some indexers like shareisland have imdbid parameter in search mode. Is that correct?

no it is not. it was a mistaken assumption that if a yml indexer supported imdbid search, then users of the dashboard would need support via the search: [q, imdbid]
but I just tested this with blutopia in 0.16.1817 with just search: [q] in the indexer, and then used the dashboard to search for a imdbid and it was returned.
I have submitted a commit correcting this mistake.

**Comment by garfield69** [comment]
OK. I have an update regarding the book-search.
I took your source in this PR and altered it so that the book-search parms were q,title,author 
then I tested it against my Readarr app and this time I got results from the apps search!!
the app first did a t=caps and was presented by my jackett with
```xml
<?xml version="1.0" encoding="UTF-8"?>
<caps>
  <server title="Jackett" />
  <searching>
    <search available="yes" supportedParams="q" />
    <tv-search available="no" supportedParams="q" />
    <movie-search available="no" supportedParams="q" />
    <music-search available="no" supportedParams="q" />
    <audio-search available="no" supportedParams="q" />
    <book-search available="yes" supportedParams="q,title,author" />
  </searching>
  <categories>
    <category id="100058" name="Biografie" />
    <category id="100066" name="Bladmuziek" />
    <category id="100011" name="Crime" />
    <category id="100013" name="Detective" />
    <category id="100004" name="Diverse" />
    <category id="100056" name="Engels" />
    <category id="100015" name="Erothiek" />
    <category id="100051" name="Fantasy" />
    <category id="100061" name="Geschiedenis" />
    <category id="100017" name="Hobby" />
    <category id="100007" name="Jeugd" />
    <category id="100052" name="Kerst" />
    <category id="100050" name="Kookboeken" />
    <category id="100064" name="Literatuur" />
    <category id="100009" name="Luisterboeken" />
    <category id="100057" name="Maatschappij" />
    <category id="100019" name="Medisch" />
    <category id="100065" name="Non-Fiction" />
    <category id="100008" name="Oorlog" />
    <category id="100002" name="Roman" />
    <category id="100060" name="Sci-Fi" />
    <category id="100021" name="Sport" />
    <category id="100010" name="Stripboeken" />
    <category id="100003" name="Thriller" />
    <category id="100016" name="Tijdschriften" />
    <category id="100053" name="Waargebeurd" />
    <category id="8010" name="Books/Ebook" />
  </categories>
</caps>
```
and then when I searched for a book and the app posted the following torznab request to my jackett
```
http://127.0.0.1:9117/api/v2.0/indexers/ebookparadijs/results/torznab/api?t=book&cat=8010&extended=1&apikey=myapikey&offset=0&limit=100&author=Jim%20Butcher&title=Battle%20Ground
```

so based on this one app behaviour I would say that you should change booktitle to title

**Comment by ilike2burnthing** [comment]
Re: booktitle - https://github.com/Jackett/Jackett/pull/9719 (see Additional Note and References)

**Comment by garfield69** [comment]
>Re: booktitle - #9719 (see Additional Note and References)

These references have been,  IMO. miss-read by ngosang.
The use of booktitle applies to the torznab results that get sent back to the app.
The torznab query that began the t=book search remains title.
Thats is what bears out in my test. I query with title and return results with booktitle.

**Comment by ilike2burnthing** [comment]
Is seeyabye's implementation of booktitle also wrong then?

Seems this may be the correct reference then - https://newznab.readthedocs.io/en/latest/misc/api/#book-search

**Comment by garfield69** [comment]
from the same document that was used to pull up the references for the results
https://newznab.readthedocs.io/en/latest/misc/api/#predefined-attributes
scrolling up to the book-search definitions
https://newznab.readthedocs.io/en/latest/misc/api/#book-search

**Comment by garfield69** [comment]
To my mind, what is not up for debate is whether the t=book should have a parm called booktitle.
The answer is **no**.
All the docs I have read state **t=book,&q=,&author=,&title=**

What is up for debate is whether the results for the _newsnab attributes_ should have the book title as _title_ (as shown in the content example just below the definition at https://newznab.readthedocs.io/en/latest/misc/api/#book-search)
`     <newznab:attr name="title"    value="Weather and Folk Lore of Peterborough and District" />`
or as _booktitle_ (as shown in the predefined attributes reference https://newznab.readthedocs.io/en/latest/misc/api/#predefined-attributes)
`booktitle | Book | Book title | “Weather and Folk Lore of Peterborough and District”`
implying 
`     <newznab:attr name="booktitle"    value="Weather and Folk Lore of Peterborough and District" />`

I do not see why we could not have both attributes provided in the results, after all the docs states
`Therefore a client application should not rely on any particular attributes being in the returned data but should take this list as an optional extra information.`

**Comment by ngosang** [comment]
> I'm confused about this. It was my understanding that the book-search parms are q, author and title.
where did you read that the book-search parm should be booktitle?

I read it here => https://torznab.github.io/spec-1.3-draft/torznab/Specification-v1.3.html#predefined-attributes
But I was wrong, valid params are: q, author and title I changed this PR.

> I've not used lazylibrarian as there is no windows version, just mac and linux. It's a python based tool with bugger all useful docs, I am not inclined to spend time researching.

I did some tests and they are not using book-search. Just regular search => http://10.0.2.15:9117/api/v2.0/indexers/ebooks-shares/results/torznab/api?t=search&apikey=redacted&q=Agatha+Christie&extended=1

> do you mean you want me to update our wiki and readme to also point to this draft torznab 1.3 document?

Only if we change the param `title => booktitle` but it's not required anymore.

> What is up for debate is whether the results for the newsnab attributes should have the book title as title

I'm not 100% sure but since Readarr has this spec in the source code I think booktitle is fine. Do you notice something weird in Readarr or it's working fine?
https://github.com/Readarr/Readarr/blob/7359c2a9fa274cbc1653236fc781ec9574ce810c/schemas/torznab.xsd

After reverting the `booktitle` rename I think this is ready to merge.

**Pull request merged**
