### PR TITLE
Digital Hive Provider

### PR DESCRIPTION
**Pull request by ipsq**
@JigSawFr Here you go

**Note** – I have not yet tested this implementation so I'm hoping the developers can create a beta-distribution from this feature branch and have people with access to a Windows machine and a Digital Hive account test this and give feedback.

### CODE REVIEW

**Comment by ipsq** [comment]
@JigSawFr Could you try to compile this? I'm not really sure I used C# Async abilities right... I come from a Java and Golang background.

**Comment by ipsq** [comment]
I'm closing this pull request because Digital Hive has Cloudflare DDOS protection which disables the captcha ID scraping.

**Comment by JigSawFr** [comment]
@ipsq you can request cookies / passkey or something else. Or bypass CF

**Comment by ipsq** [comment]
How? It's a JavaScript challenge.

**Comment by JigSawFr** [comment]
You can't get captcha ID to let user resolve it on Jackett, is that you mean ?

**Comment by ipsq** [comment]
I forgot to mention that the whole site is in fact CloudFlare protected.

**Pull request closed without merging**
