### PR TITLE
DanishBits: add Passkey info to hopefully prevent #1892 #1873 #1850

### PR DESCRIPTION
**Pull request by garfield69**

### CODE REVIEW

**Comment by garfield69** [comment]
Oops. I can't figure out what the problem is, sorry about that.

**Comment by garfield69** [comment]
Still missing something, because the instructions are not showing up on the jackett dashboard...

**Comment by garfield69** [comment]
\\o/ I've been able to test this change as far as the jackett dashboard, to confirm that the danishbits config shows the passkey info text as intended, but since I don't have an invite to the site, I've not actually tested that it works all the way.      
so  I would recommend a through review, it's my first c# attempt and I had plenty of missteps along the way.

**Comment by kaso17** [comment]
It's working fine, thank you.

**Pull request merged**
