### PR TITLE
core: improve windows tray launcher code. #10068

### PR DESCRIPTION
**Pull request by garfield69**
@Illegal-Services submitted this post in #10068 to improve the script

### CODE REVIEW

**Comment by garfield69** [comment]
does not work, looping with `JackettUpdater is still running` even though that task is not active.

**Comment by garfield69** [comment]
reopen to try some amendments

**Review by garfield69 — COMMENTED** [review]
not working.
while the updater is active
image
the script just exits
image

**Comment by garfield69** [comment]
no wait, might have been an invalid test condition. need to test again.

**Comment by Illegal-Services** [comment]
Also I don't understand the last line, with the start command, maybe there is a reason but, when I look at this:
Code_2021-09-18_02-16
Then i'm only thinking the last line is what you guys are trying to `start`. I can't be sure because I don't know why you guys added that old code, but yeah, I'm just saying...

**Comment by garfield69** [comment]
I'm too tired to test further, I think I'm making setup mistakes.
I'm going to wait for a 2nd opinion from ilike2burnthing

**Comment by Illegal-Services** [comment]
Sure, but hey if the old version was working, for such a small improvement you can just leave it, I just tough things would be simplier. Honneslty it's not a big deal.

**Comment by Illegal-Services** [comment]
Have a good night, I'm tired too^^

**Review by ilike2burnthing — COMMENTED** [review]
https://github.com/Jackett/Jackett/pull/12320#pullrequestreview-757918338 - I got the same results

As for the last line of the script, we're launching JackettTray with the 'jackett has updated to v0.1.2.3' notification as it doesn't get relaunched after the update.

**Pull request closed without merging**
