### PR TITLE
Freeleech setting for Torrentleech

### PR DESCRIPTION
**Pull request by StellaTerra**
Solution for https://github.com/Jackett/Jackett/issues/9456 (for Torrentleech only)

Let me know if you think this should be a bespoke config rather than a general-use one, but it seems like a lot of trackers need this, so it seemed a reasonable expansion.

### CODE REVIEW

**Comment by ngosang** [comment]
@StellaTerra thank you! I prefer to not create a configuration class for this use case. There are other indexers in C# which supports "only freeleech" but many of them are not using user/pass.
Clod by #10298

**Comment by StellaTerra** [comment]
@ngosang hey, thanks for the feedback?  Would you like me to rewrite it some other way and resubmit?  I'd really like this feature, is there anything I can do to make it acceptable?

**Comment by StellaTerra** [comment]
@ngosang As I offered in the PR, it'd be trivial to make it bespoke.  Alternately, if it's possible I could look into converting it into a cardigan.

**Comment by ngosang** [comment]
It was implemented by me in #10298
It's already merged, will be releases in the next release in few hours.

**Pull request closed without merging**
