### PR TITLE
Add support for book-search

### PR DESCRIPTION
**Pull request by ta264**
1. Adds backend support for the book-search newznab function.

1. Adds book-search support for bibliotek

1. Some more minor fixes for bibliotek - clean up login and extra attributes

### CODE REVIEW

**Comment by garfield69** [comment]
@ta264  Thank you very much!
We will need some time to review and test the changes.

**Comment by ta264** [comment]
You're welcome. I'm in the Readarr/Radarr/Lidarr discord if you want to chat about anything.

**Comment by garfield69** [comment]
Hmm. difficult to test as I am not aware of any windows book-search torznab apps we can plug a jackett indexer into... readarr source has no releases... are you aware of any such apps?

**Comment by ta264** [comment]
You can grab the windows installer for readarr from [here](https://artprodcus3.artifacts.visualstudio.com/Af2b01d57-4f38-4d91-acc9-412d59f0a070/34393bab-b896-4651-a109-cddb27254e55/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL1JlYWRhcnIvcHJvamVjdElkLzM0MzkzYmFiLWI4OTYtNDY1MS1hMTA5LWNkZGIyNzI1NGU1NS9idWlsZElkLzIwOS9hcnRpZmFjdE5hbWUvV2luZG93c0luc3RhbGxlcg2/content?format=file&subPath=%2FReadarr.develop.0.1.0.148.windows-core-x64-installer.exe) and it should work with book-search.  Let me know if you need any assistance testing.

**Comment by garfield69** [comment]
unable to add indexer on readarr https://github.com/Readarr/Readarr/issues/355

**Comment by garfield69** [comment]
@ngosang  I take it you don't have any free time to do reviews ATM, so shall I just go ahead and merge?

**Comment by garfield69** [comment]
Jackett 0.16.1012

**Pull request merged**
