### PR TITLE
Added new tracker Partis.si

### PR DESCRIPTION
**Pull request by klemk86**
Added new private Slovenian tracker Partis.si

### CODE REVIEW

**Comment by garfield69** [comment]
Fantastic! 
Thank you.

**Comment by garfield69** [comment]
jacket 0.12.1146

**Comment by jaka87** [comment]
I get an error while trying to use it..

```
Jackett.Common.ExceptionWithConfigData`
  at Jackett.Common.Indexers.Partis+<>c__DisplayClass8_0.<ApplyConfiguration>b__0 () [0x0001f] in C:\projects\jackett\src\Jackett.Common\Indexers\Partis.cs:106 
  at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK (System.String cookies, System.Boolean isLoggedin, System.Func`1[TResult] onError) [0x00034] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:267 
  at Jackett.Common.Indexers.Partis.ApplyConfiguration (Newtonsoft.Json.Linq.JToken configJson) [0x00165] in C:\projects\jackett\src\Jackett.Common\Indexers\Partis.cs:102 
  at Jackett.Server.Controllers.IndexerApiController.UpdateConfig (Jackett.Common.Models.DTO.ConfigItem[] config) [0x0012d] in C:\projects\jackett\src\Jackett.Server\Controllers\IndexerApiController.cs:108 
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0 
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0 
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0 
  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x00042] in C:\projects\jackett\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:29 
```

**Comment by garfield69** [comment]
@jaka87  unfortunately the stack dump you provided is not much use.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by jaka87** [comment]
Thx for pointing that out. I pasted full debug...
https://pastebin.com/5DennQpg

**Comment by garfield69** [comment]
@jaka87  it looks like after the login you are being redirected to http://www.partis.si/prva instead of the torrent search page.
so I suggest to login to partsi via your browser and check you have not outstanding alerts, notices or mail to read, that would prevent you seeing the torrent search page. Then logout and try jackett again.
@klemk86  I presume you have tested this indexer and it works for you?

**Comment by klemk86** [comment]
Yes, it is working for me.

Redirect to www.partis.si/prva is normal behavior after login for this tracker.
Looks like login goes through but it fails while checking cookies.
Will test a bit more and see if I can replicate the issue.

**Comment by jaka87** [comment]
I have tried both on my ARM device and my laptop, both running linux and i got the same issue. 
Im not sure why /user/login is used since it appears /prijava seems to be the official address for login. For example if I open /user/login in browser and enter my credentials I then get redirected to /prijava. Cookies are created but i have manually  enter the correct url to to see the torrents. But if I open /prijava end enter my credentials then I get inside the tracker immediately. I don't know if if helps, I m just pointing it out...

Could you please paste sample .json config file so i can try manually add the tracker.

**Comment by garfield69** [comment]
a sample config .json file will not help you to manually add the indexer, since the password is encrypted and you cannot provide is without using the app.

**Comment by klemk86** [comment]
Because login form on /prijava has a submit path to /user/login. And form on /user/login has a submit path /prijava. That is why if you manually try to login on /user/login it just redirects to /prijava. And if /prijava is used as login it always redirects back to /prijava, it never actually logins. A POST method is used on /user/login to login on partis.si.

**Comment by jaka87** [comment]
I have tried on freshly installed jackett on my brother's WIN7 and got the same error.

**Comment by klemk86** [comment]
[Jacket.Common.zip](https://github.com/Jackett/Jackett/files/3964763/Jacket.Common.zip)

@jaka87 Try this please and report if it is working. Shutdown Jackett and replace both files in Jackett install directory (make backup first). Then restart and report.

**Comment by jaka87** [comment]
i get error while running jackett 

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Jackett.Common, Version=0.12.1198.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Jackett.Common, Version=0.12.1198.0, Culture=neutral, PublicKeyToken=null'

```

**Comment by klemk86** [comment]
https://github.com/klemk86/Jackett/releases/download/0.12.5/Jackett.Installer.Windows.exe

Try this. For testing purposes only.

**Comment by jaka87** [comment]
It seems to be working !

**Pull request merged**
