### PR TITLE
Wolfmax4k: fix download torrents with password

### PR DESCRIPTION
**Pull request by highfredo**
#### Description

Wolfmax4k: fix download torrents with password
For example: https://wolfmax4k.com/descargar/serie-en-hd/constelacion/temporada-1/capitulo-01/

### CODE REVIEW

**Review by ilike2burnthing — COMMENTED** [review]
Looks good.

I've only found a few other examples of this, and while the passworded link is first for all of them, would it be better to exclude `class="buttonPassword"` rather than just selecting the last one?

**Comment by garfield69** [comment]
Titles whose download require a password should be excluded from the results

**Comment by ilike2burnthing** [comment]
All the examples I found had both a passworded download and normal download, so it should be fine.

**Comment by garfield69** [comment]
I don't understand what is on offer in these detail pages.
Are you saying that the second download is an in-the-clear download of the title .torrent?

So what's the first link with the buttonpassword class do, is an alternate .torrent download link for the same title, that once downloaded required a password to unpack, or something else?
Strange goings on IMO. %-/

**Comment by highfredo** [comment]
> Looks good.
> 
> I've only found a few other examples of this, and while the passworded link is first for all of them, would it be better to exclude `class="buttonPassword"` rather than just selecting the last one?

sure, i will do it

> I don't understand what is on offer in these detail pages. Are you saying that the second download is an in-the-clear download of the title .torrent?
> 
> So what's the first link with the buttonpassword class do, is an alternate .torrent download link for the same title, that once downloaded required a password to unpack, or something else? Strange goings on IMO. %-/

The torrent "per se" does not have a password, but one of the files to download is a rar with a password

**Comment by ilike2burnthing** [comment]
Thanks!

**Comment by garfield69** [comment]
v0.21.2140

**Pull request merged**
