### PR TITLE
[Feature] add proxy type 'Disabled' to disable proxy. Resolves #8138

### LINKED ISSUE #8138: [enhancement] change disabling proxy to - Proxy type: None (disabled)
Rather than removing the proxy URL to disable it (which is then a minor annoyance to retype each time you want to re-enable, more so if only certain ones work), is it possible to add `None (disabled)` to `Proxy type` as a simple off switch?

Thanks!

### PR DESCRIPTION
**Pull request by ilike2burnthing**
_Disclaimer: this is a complete stab in the dark by someone (me) who doesn't know C#, or indeed any coding language. ~So by all means tell me this is a mess and won't work.~ There isn't much added, so hopefully it won't waste anyone's time._
_~EDIT: well that didn't work. Am I doing something stupid, or was it never going to work?~_

An attempt to resolve #8138 by adding a 'disabled' option to the proxy type list which will disable the proxy. It addresses the minor annoyance of having to retype/paste the URL when you want to re-enable it. Basically an off switch.

I have no way of compiling this myself, so it's posted untested.

### CODE REVIEW

**Comment by garfield69** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/equality-operators

**Comment by ilike2burnthing** [comment]
Thank you!

**Comment by ilike2burnthing** [comment]
Tested in Windows Sandbox, and it works! Thank you again @garfield69 never going to forget the phrase 'equality operators' 😋 

'Disabled' disables it, having a URL entered doesn't override that, nor does changing the URL, and changing back to HTTP re-enables fine. Left on HTTP and removing the URL still disables the proxy as well.

Any other testing needed, the formatting or stylising changed, or text elsewhere edited?

**Comment by ngosang** [comment]
Wait for me few days before merge.

**Pull request closed without merging**
