### PR TITLE
Add Speed-Share indexer

### PR DESCRIPTION
**Pull request by Guizzoni**
As per request #1699

### CODE REVIEW

**Comment by GiowGiow** [comment]
I'm trying to user Speed Share indexer on Jackett Version 0.8.361.0, but on the logs i get the message 
When                                   Level    Message
Nov 09, 2017 12:53:17 PM | Error | {0}

**Comment by Guizzoni** [comment]
@GiowGiow 
It's working fine for me in 0.8.361.0

**Comment by GiowGiow** [comment]
I did a test searching for "Walking Dead" to the Speed Share indexer and then I read through the advanced logs, these were my results
It does the search:
IWebClient.GetString(Url:http://speed-share.org/buscar_tor.php?search=Walking%20Dead&incldead=1)

Then there is a big XML with Walking Dead torrents, the first line is:
IWebClient: Returning OK => <table id='torrentsPortal' width="100%" border="0" cellpadding="0" cellspacing="0" align="center" style="min-width: 765px">

Then the next message is:
Manual search for "Walking Dead" on speed-share with 0 results.

I don't know why but maybe it is parsing the xml wrong to me?

**Comment by Guizzoni** [comment]
I don't know what's happening in your end, everything is ok here.
I suggest you to redownload Jackett, add Speed-Share again and try redoing the search.
image

**Comment by kaso17** [comment]
@GiowGiow please provide the full log (including the XML/HTML part).

**Comment by GiowGiow** [comment]
@kaso17 Here https://pastebin.com/Q8epHa1r

**Comment by Guizzoni** [comment]
@GiowGiow

Go to http://speed-share.org/account.php?action=edit_settings&do=edit and
set "Modelo da Home:" to "Sistema Lista de Torrents"

**Comment by GiowGiow** [comment]
It worked @Guizzoni, thank you

**Pull request merged**
