### PR TITLE
Update BHD to UNIT3D

### LINKED ISSUE #5218: [beyondhd] New website with different login mechanism
It seems like BeyondHD updated to UNIT3D and removed the option for an URL login. 

I'm willing to help with this problem if needed.

### PR DESCRIPTION
**Pull request by zotanw**
Resolves #5218 
Wasn't able to test freeleech filters, but everything else works.

### CODE REVIEW

**Comment by ZEEN0j** [comment]
Do I as a user have to change anything to get it working again after the fix is implemented?

**Comment by zotanw** [comment]
@ZEEN0j yes, as far as I gathered they now use reCaptcha, which means you need to add the cookie string instead of login url, which doesn't exist on UNIT3D

**Comment by b101marc** [comment]
Hey all, checking to see if any update. Not working for me.

**Comment by garfield69** [comment]
Thanks.

**Comment by evlsmurf** [comment]
will we need to update our installed version to get this fix or just redo the tracker setting in jackett

**Comment by garfield69** [comment]
you will need to upgrade to jackett pre-release v0.11.307
but you might as well hold off, the site is going though a few teething problems, I'm seeing internal server errors when browsing torrents at the moment.

**Comment by evlsmurf** [comment]
ok thanks

**Pull request merged**
