### PR TITLE
cardigann: add trakt support

### PR DESCRIPTION
**Pull request by ilike2burnthing**
Related to, but kept separate from, https://github.com/Jackett/Jackett/pull/13384

### CODE REVIEW

**Comment by garfield69** [comment]
can you crosscheck cardigann with the query.variables builder section
https://github.com/Jackett/Jackett/blob/57c4105dc839ee083f5c02ddad9f507783a25ef5/src/Jackett.Common/Indexers/CardigannIndexer.cs#L1284
and add/correct any missing vars, and bring the wiki https://github.com/Jackett/Jackett/wiki/Definition-format#variables-available-during-search-queries up to date please? thanks.

**Comment by garfield69** [comment]
OH, there may be nothing to do. The query vars are input from the torznabcapabilities.cs and all your work recently deals with output.

**Comment by garfield69** [comment]
v0.20.1357

**Comment by ilike2burnthing** [comment]
I can implement Trakt queries, and look into TVMaze for both input and output.

And yea, I'll update the wiki.

**Comment by ilike2burnthing** [comment]
Oh, do we want to add Douban queries?

**Comment by garfield69** [comment]
Hm, tricky. While some Chinese sites support searching with a douban ( audiences, pterclub ), I don't think there are any torznab apps that make torznab queries using the doubanid, yet.
So we may be making available support that may never actually get any use. 
But I guess it cost nothing to add it, apart from your time ;-D so I leave it up to you.

**Comment by ilike2burnthing** [comment]
Any chance you know why genre queries are disabled?

https://github.com/Jackett/Jackett/blob/ebd1fdba71cdbc6f8d1cafe6db7102d972db4aef/src/Jackett.Common/Indexers/CardigannIndexer.cs#L1309

It was added in https://github.com/Jackett/Jackett/commit/1603516666136f35de6969d6358243a6d9a0f1a7 without comment.

**Comment by garfield69** [comment]
>Any chance you know why genre queries are disabled?

Might be related to #1896.  Looks like https://github.com/Jackett/Jackett/issues/1896#issuecomment-337652672 is the start of the genre thread. Qstick was involved.

**Pull request merged**
