### PR TITLE
Nyaa.se: Added tracker definition 

### PR DESCRIPTION
**Pull request by bonny1992**
With fallback for non-present leechers and seeders

Time isn't in list, but it's in details page.

### CODE REVIEW

**Comment by nikogaug** [comment]
I see that Nyaa.se is available since 0.7.1167.0 version. I have this version installed but I didnt' find the Nyaa.se tracker. Do you know why ?

**Comment by kaso17** [comment]
Was missing from the project file, fixed with 8ef705dc2fec61df46d87b3a165c9352938431f4.
If you don't want to wait for the next release just download the yml file manually.

**Comment by nikogaug** [comment]
Great thanks kaso17. I will wait for the next release. Great thanks again for your software !

**Comment by bonny1992** [comment]
@kaso17 
I may have missed the csproj update with the other definitions I made... xD

**Comment by kaso17** [comment]
I believe you only submitted this one via a own pull request (the other one came via paste bin). For the paste bin's I've added them.

**Comment by bonny1992** [comment]
@kaso17 
This one and the PassioneTorrent one I believe.

**Comment by kaso17** [comment]
PassioneTorrent was added by me, f2bcc654f1347bb09b01b17edf0289daf9294346

**Comment by bonny1992** [comment]
Oh right, sorry then!

**Pull request merged**
