### PR TITLE
newpct: fixed 404 torrent download url. resolves: #11841

### PR DESCRIPTION
**Pull request by javierjp93**
Fix for #11841

The download url page does not include js function with download link:
https://maxitorrent.com/descargar/serie/fbi/temporada-3/capitulo-11/hdtv/
The torrent download url has to be extracted from https://maxitorrent.com/descargar/torrent/serie/fbi/temporada-3/capitulo-11/hdtv/

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
maxitorrent was removed from NewPCT in https://github.com/Jackett/Jackett/commit/114e4d86a23ee1655ee088affa9962c8cceaef4c ([v0.18.171](https://github.com/Jackett/Jackett/commit/114e4d86a23ee1655ee088affa9962c8cceaef4c)).

This breaks downloads for all the other site links of NewPCT.

It would either have to try both, or maxi would need to be a separate indexer.

**Review by garfield69 — CHANGES_REQUESTED** [review]
or you could add the maxi domain back, and only perform the replace if the domain contains maxi.
not pretty but functional.

**Comment by javierjp93** [comment]
With the last commit, only url from maxitorrent.com wil be rewritted

**Review by garfield69 — APPROVED** [review]
LGTM but untested because I don't have an active account on newpct
@ilike2burnthing  could you test this please. Thanks.

**Review by ilike2burnthing — APPROVED** [review]
> or you could add the maxi domain back, and only perform the replace if the domain contains maxi.

The magic of C#, it didn't occur to me that that was a possibility.

Yep, this works well, and no account needed, NewPCT is public.

**Comment by garfield69** [comment]
>and no account needed, NewPCT is public.

Oh Duh!

**Pull request merged**
