### PR TITLE
Fixes "Manicomio Share" search

### PR DESCRIPTION
**Pull request by Guizzoni**
This fixes content search in general

*Since the tracker returns no results when searching with a year on the query, i've also added a workaroud to fix CouchPotato and Radarr search*

### CODE REVIEW

**Comment by Guizzoni** [comment]
Sorry about the multiple commits

**Comment by JigSawFr** [comment]
@kaso17 can you come on your Discord chat ? (link on readme)

**Comment by tnascif** [comment]
The year issue is still messed up
untitled

**Comment by Guizzoni** [comment]
Yes, unfortunately since the Tracker does not provide the date in a straightforward way (without having to click the + button), there's no way to fix this, as far as i know.

**Comment by tnascif** [comment]
Do you happend to know if BJ-share is facing the same problem? @Guizzoni

**Comment by Guizzoni** [comment]
@tnascif yes, unfortunately we have the same issue with BJ-Share. 
Only B2S-Share is showing the date properly

**Comment by FabioCastilho** [comment]
O jackeet nao esta retornando nenhum resultado usando o manicomio poderia a verificar ?
image

**Comment by Guizzoni** [comment]
@FabioCastilho 
Please write in English... Everything is working fine for me.

image

**Comment by ppucci** [comment]
Hey @Guizzoni nice to see you making it work with Manicomio. Could you help me fix mine? I'm using mainly with Radarr but it will not download anything saying it could not find the name on the release name.

**Comment by FabioCastilho** [comment]
Mine stopped working both asylum and bj share

O meu parou de funcionar tanto o manicômio quanto o bj share

**Comment by Guizzoni** [comment]
I don't use Radarr, so i don't know what might be happening with you.

The indexer is working properly on both CouchPotato and Sonarr.

**Comment by FabioCastilho** [comment]
Radarr works in the same sonarr method if it is not working in radarr it should not be working in sonarr

O radarr funciona no mesmo método do sonarr se  não está funcionando no radarr não deve estar funcionando no sonarr.

**Comment by Guizzoni** [comment]
I can guarantee you, it is working on Sonarr.

image

**Comment by ppucci** [comment]
My problem is specific with Anime... 

[img]https://i.imgur.com/xe28uI7.png[/img]

**Comment by ppucci** [comment]
@FabioCastilho the worse part is that Radarr actually has "name flexibility" configs that if I am not mistaken @Guizzoni himself added to the project.

Sonarr


Radarr

**Comment by ppucci** [comment]
By the way @Guizzoni I got it working on Radarr, thank you for your work.

**Comment by Guizzoni** [comment]
Those options are related to the Radarr side of things, the year workaround
I added in the Jacket definition has nothing to do with it.

Great! You got it working by using the same options?

Em 31 de out de 2017 17:52, "ppucci" <notifications@github.com> escreveu:

**Comment by ppucci** [comment]
@Guizzoni yes, now it seems to be working fine for Radarr. For Sonarr, however, it seems to still have issues with the name, note sure if the reason is the Manicomio uses both the title in Portuguese and original. Will keep checking if it works for other regular series as well...

**Comment by tnascif** [comment]
@ppucci
I think you meant that Sonarr is working fine and Radarr is having problems with the titles being in Portuguese and English. At least that is how mine is righ now!

**Pull request merged**
