### PR TITLE
Wrong image path causes torrent parsing to fail.

### PR DESCRIPTION
**Pull request by Moulde**
One torrent having a wrong image caused the parsing of the torrents to fail, and error would only show up if the search contained that specific torrent......

Changed parsing to skip torrent if errors occur, and changed to use tryCreate when creating Uri's from strings.

### CODE REVIEW

**Comment by kaso17** [comment]
can you share which torrent is causing the problem?

**Comment by Moulde** [comment]
Hi kaso17

Oh yeah, sure.

Studie.5.S01E03.DANiSH.720p.WEB-DL.H.264.AAC2.0-TWA

https://hounddawgs.org/torrents.php?id=99103

**Comment by Moulde** [comment]
Html:

Studie.5.S01E03.DANiSH.720p.WEB-DL.H.264.AAC2.0-TWA

**Comment by Moulde** [comment]
...

img style="max-width: 100%;" src="Studie.5.S01E03.DANiSH.720p.WEB-DL.H.264.AAC2.0-TWA" alt="Studie.5.S01E03.DANiSH.720p.WEB-DL.H.264.AAC2.0-TWA" onclick="lightbox.init(this,220);"

**Comment by kaso17** [comment]
added e309d96c51518b557390539286841de6e1e861fd in order to handle it better (the release still get's added, only without bannerUrl.
Thank you for investigating!

**Comment by kaso17** [comment]
Just noticed your solution is way better than mine (Thought you just put a big try around the row parsing).
merged, thank you!

**Comment by Moulde** [comment]
I added the try catch around the whole block as a precaution for other things that might fail in the future.
The Uri.TryCreate will not throw an exception, just return false before creating the Uri.

But i just noticed that I, for the bannerUri, use the Uri.TryCreate, and then create the Uri from the string afterwards, instead of using the out parameter: bannerUri from the TryCreate method.

**Comment by kaso17** [comment]
fixed via eb00665df11e7e32b09fb7cd6a0e1fe4dbf46d73

**Comment by Moulde** [comment]
Hi Kaso17, how does the release procedure work for Jackett? 
Like when will the current pre-release turn into a release? And does this trigger say, the linuxserver.io images to be updated as well?

Thanks in advance.
Sorry if this is the wrong place, but i didn't feel like this question qualified for creating a new issue.

/Malte

**Comment by kaso17** [comment]
I'll push a new stable release within the next 3 hours. It should also trigger a linuxserver.io build.

**Comment by Moulde** [comment]
Nice! :) Have a nice weekend.

**Pull request merged**
