### PR TITLE
32p: create second .yml for cookies login with 2fa

### PR DESCRIPTION
**Pull request by janot**
I'm still being kicked out after some hours with 2fa even with lockip disabled. No such problem with cookies login.
I browsed through repo and looks like creating additional .yml is the way in such cases? Until this is implemented https://github.com/Jackett/Jackett/issues/7780

### CODE REVIEW

**Comment by janot** [comment]
Not a new indexer

**Comment by garfield69** [comment]
before I merge this, take a second look at the regular 32pages indexer.
the login page on the site has the following
```html
<input type="checkbox" id="keeplogged" name="keeplogged" value="1"/>
<label for="keeplogged">Remember me</label>
```
but the indexer sets the following
https://github.com/Jackett/Jackett/blob/ac3f274d075a55fd9d4f1d5100bbfbe31252aa26/src/Jackett.Common/Definitions/32pages.yml#L69

**Comment by janot** [comment]
@garfield69 omg, sorry. I'll check, how it behaves with this one

**Comment by janot** [comment]
Works as expected now

**Pull request closed without merging**
