### PR TITLE
assorted: correct MST and MR

### PR DESCRIPTION
**Pull request by ilike2burnthing**
See commits for comments.

Only ones that gave me pause:
**GigaTorrents** - it has a global MR but none for individual seeds, so do we leave this out?
**HDZone** - in a quick browse through their recent torrents, I haven't seen an H&R logo, but should we account for a download having one and include the 14 day MST?

### CODE REVIEW

**Comment by garfield69** [comment]
>GigaTorrents - it has a global MR but none for individual seeds, so do we leave this out?

add the global MR

>HDZone - in a quick browse through their recent torrents, I haven't seen an H&R logo, but should we account for a download having one and include the 14 day MST?

Ideally we would only apply the 14 day MST when the logo is associated with that torrent.
So the MST would turn into a case block similar to the DVF with the h&r: 14day and default 0.
Question is, do the docs show what the h&r logo looks like?

**Comment by ilike2burnthing** [comment]
No, just plain text. I'll have a look at some older torrents to see if I can find anything.

HDDisk has just come back online, so I'll take a look at it too

**Comment by ilike2burnthing** [comment]
Couldn't find anything, but it may have been another bad Google translation. A few other translation services give, "The H&R-marked seed..." or "Seeds marked H&R..."

What do you think? Remove MST and just leave the MR?

**Comment by garfield69** [comment]
I've taken a look at their theme.css to see if I could find any classes to do with hit and run but not found anything.
so yes, I would comment out the mst with a note that this is not implemented as we could not find the h&r tag.

**Comment by ilike2burnthing** [comment]
That's everything then, ta!

**Review by garfield69 — CHANGES_REQUESTED** [review]
>uniongang: users below 0.2 should raise the rating in the next two weeks to at least 0.30

I would set the MR as 0.3

**Review by garfield69 — APPROVED** [review]

**Pull request merged**
