### PR TITLE
Remove CsQuery and use AngleSharp instead. Closes #7292

### LINKED ISSUE #7292: Remove CsQuery and use AngleSharp instead
Currently we have two libraries to parse HTML: CsQuery and AngleSharp
There are several reasons to remove CsQuery:
* CsQuery is not maintained anymore => https://github.com/jamietre/CsQuery#not-actively-maintained
* AngleSharp performance is better => https://anglesharp.github.io/docs/Performance.html
* We have notice CsQuery requires more memory than AngleSharp in Jackett. => https://github.com/Jackett/Jackett/pull/7094#issuecomment-589938887 https://github.com/Jackett/Jackett/pull/7094#issuecomment-589948133
* There is no point in using two libraries for the same thing

We have 39 indexers using CsQuery. Use this task list to track the progress.
- [x] Abnormal
- [x] Abstract/AvistazTracker
- [x] AnimeTorrents
- [x] BakaBT
- [x] BB
- [x] BitCityReloaded
- [x] BitHdtv
- [x] DigitalHive
- [x] FileList
- [x] FunFile
- [x] Fuzer
- [x] GimmePeers
- [x] HDOlimpo
- [x] HDSpace
- [x] HDTorrents
- [x] Hebits
- [x] ImmortalSeed
- [x] IPTorrents
- [x] LostFilm
- [x] MoreThanTV
- [x] myAmity
- [x] NCore
- [x] NewRealWorld
- [x] Norbits
- [x] Nordicbits
- [x] Partis
- [x] PirateTheNet
- [x] Pretome
- [x] RevolutionTT
- [x] SceneTime
- [x] Shazbat
- [x] SpeedCD
- [x] TorrentBytes
- [x] TorrentDay
- [x] TorrentHeaven
- [x] TorrentLeech
- [x] TorrentSyndikat
- [x] TVstore
- [x] XSpeeds

@Jackett/maintainers What do you think? Could you help with the changes?

@junglebus Thank you for noticing

### PR DESCRIPTION
**Pull request by ngosang**
This is the last PR. It will pass checks after other PRs are merged.
@cadatoiva I can't find the option to remove unused dependencies in Rider. I think this is ok but take a look.

### CODE REVIEW

**Comment by cadatoiva** [comment]
All the others have been merged. The analysis says we've removed all references, and I've tested this successfully. Before we merge this PR though, we need to add the library's folders/files to the oldFiles array so the updater can remove them from all installations.

**Comment by ngosang** [comment]
Ready

**Comment by junglebus** [comment]
Are you sure about removing "System.Xml.XPath.XmlDocument.dll"  ?
Builds without CsQuery still include this dll

**Comment by cadatoiva** [comment]
The only place in code I can find that comes close to using Xml/Xpath/XmlDocument that would potentially require this .dll is in the unit tests. Removing this from production during an automated update should be just fine
 https://github.com/Jackett/Jackett/blob/a3f30a2dd96099581254bb1fea775119ee465fc2/src/Jackett.Test/Util/ParseUtilTests.cs#L38

**Comment by ngosang** [comment]
@junglebus Cout you check it again? There are several files with similar names.

I used a external tool (Meld) to compare directories of 2 releases (v0.13.405 vs v0.13.228) and those 3 files are not included in the Jackett.Binaries.LinuxAMDx64.tar.gz build at least.
image
image

**Comment by junglebus** [comment]
You are right, my bad, very similar file name

**Pull request merged**
