### PR TITLE
core: rename banner field to poster #10092

### PR DESCRIPTION
**Pull request by ngosang**

### CODE REVIEW

**Comment by ngosang** [comment]
@garfield69 update the doc

**Comment by garfield69** [comment]
Ahh. we may need to still support bannerurl as a torznab predefined attribute for results.
While https://newznab.readthedocs.io/en/latest/misc/api/#predefined-attributes has poster, the Sonarr specs still expect ballerurl https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer#torznab-results

**Comment by ngosang** [comment]
I didn't change the toznab result in this PR.
I added `coverurl` field yesterday in #10122 but I can rename it to `bannerurl` in another PR if you want to.

**Comment by garfield69** [comment]
No, you are right. 
coverurl is the correct attribute to return, I found in the the specs https://newznab.readthedocs.io/en/latest/misc/api/#predefined-attributes

it has poster (` poster | ALL | NNTP Poster`)but that is not the same thing.
coverurl (`coverurl | TV, Movies, Music, Book | URL to cover image`) is listed further down the page.

So as long as the xml returned for torznab results continues to return coverurl then we are no breaking anyone's app.
Internally in Jackett, via c# indexer and yaml , we use poster. and that's fine by me.

**Comment by ngosang** [comment]
Merge after review and doc updated. I have more PRs in progress.

**Review by garfield69 — APPROVED** [review]
Excellent.
Tested with ShareUniversity (yaml with posters) and AniDUB (C# with posters), using the dashboard and a torznab query.
LGTM.
Wiki for cardigann updated.

**Pull request merged**
