### PR TITLE
Merge master into web client feature branch.

### PR DESCRIPTION
**Pull request by cadatoiva**
This brings a much needed update to the feature branch before moving forward with the project.

### CODE REVIEW

**Comment by cadatoiva** [comment]
Huh, I don't see why it has conflicts, this is literally a merge commit.

**Comment by cadatoiva** [comment]
@ngosang or @garfield69, either of you have an understanding of git+github that can help make this mergeable?

**Comment by cadatoiva** [comment]
Found the problem. GitHub has case sensitive branches. VS does not. The base branch I was basing from was not the one I was merging to, it was and older fragment due to this fact. Ready for review.

**Comment by ngosang** [comment]
@cadatoiva please don't merge this blasphemy. I'll do a clean rebase in the afternoon.

**Comment by ngosang** [comment]
@cadatoiva branch rebased. This PR is not necessary, just remove your local branch and pull again.
https://github.com/Jackett/Jackett/tree/Feature/web-client

**Comment by cadatoiva** [comment]
Yeah, I was just trying to make it play nice with Github so I didn't make an update without some kind of feedback or check. I did a clean rebase in my local branches with #8921 so you didn't need to do the work again.

**Pull request closed without merging**
