### PR TITLE
[New Tracker] SportsVideoOrg

### PR DESCRIPTION
**Pull request by mysterio21**
Added support for this website which lists multiple sports categories and is a free public tracker.
Had to implement some scraping and handle the paging
**URL**: https://www.sport-video.org.ua/index.html

### CODE REVIEW

**Comment by janot** [comment]
You're using different name everywhere:
SportVideoOrg in readme
name: "SportsVideoOrg"
description: "Sports Video

at site's mainpage it's SPORT-VIDEO
at guestbook page it's SPORT-VIDEO.ORG.UA

**Comment by cadatoiva** [comment]
This PR raises a lot of questions as to how and why this is implemented the way it is. If I understand it correctly this code is downloading every single page/torrent entry from the site into the cache and then searching within the cache for any torrent titles that contain the full query string in order. I haven't gone to look at the source site, so I don't know if this is the only way to search, but this seems inefficient, and dare say crude.

It's really hard to read this code, so I can't even be sure of that. There's code where the LINQ call chain is `Select().ToArray().Where()` and calling `ToArray()` inside function parameters that accept `IEnumerable` so this code is spending a lot of time looping through results and allocating memory that it doesn't need to.

**Comment by mysterio21** [comment]
> You're using different name everywhere:
> SportVideoOrg in readme
> name: "SportsVideoOrg"
> description: "Sports Video
> 
> at site's mainpage it's SPORT-VIDEO
> at guestbook page it's SPORT-VIDEO.ORG.UA

I will clean up the naming, it was confusing when viewing the website

**Comment by cadatoiva** [comment]
I've added a commit that cleans up a lot of the base code to be more efficient and readable. Please test the changes and make any improvements as necessary.

**Comment by mysterio21** [comment]
> This PR raises a lot of questions as to how and why this is implemented the way it is. If I understand it correctly this code is downloading every single page/torrent entry from the site into the cache and then searching within the cache for any torrent titles that contain the full query string in order. I haven't gone to look at the source site, so I don't know if this is the only way to search, but this seems inefficient, and dare say crude.
> 
> It's really hard to read this code, so I can't even be sure of that. There's code where the LINQ call chain is `Select().ToArray().Where()` and calling `ToArray()` inside function parameters that accept `IEnumerable` so this code is spending a lot of time looping through results and allocating memory that it doesn't need to.

The website has no way to query the torrents and requires html parsing of different categories & those category/pages have paging. Agree its very crude, only way I could think about handling this source.

**Comment by garfield69** [comment]
IMO, if the site does not have a search engine then it is not suitable for use with Jackett.

**Comment by cadatoiva** [comment]
I agree with @garfield69. Many of our users are on NAS hardware that isn't designed to cache an entire website's search results in order to use that site correctly. Out of the other caching indexers, I didn't see any that implement this same site style either.

I appreciate your effort, but we're going to have to decline adding this indexer unless/until there is a site side searching mechanism.

**Pull request closed without merging**
