### PR TITLE
sharespacedb: remove definition

### PR DESCRIPTION
**Pull request by janot**
tracker shut down http://torrentinvites.org/f31/sharespacedb-ssdb-news-site-has-shut-down-562888/

### CODE REVIEW

**Comment by cadatoiva** [comment]
Thanks!

**Comment by garfield69** [comment]
@cadatoiva  when a yml indexer is removed we should also update https://github.com/Jackett/Jackett/blob/master/src/Jackett.Updater/Program.cs
so that the yml gets deleted from the users local definitions folder.

**Comment by cadatoiva** [comment]
Right, I missed that one. Sorry

**Comment by garfield69** [comment]
Jackett 0.16.164

**Pull request merged**
