### PR TITLE
Use Artist instead of keyword

### PR DESCRIPTION
**Pull request by Akuma737**
use artist instead of keyword if artist is supplied to make it somewhat compatible with lidarr(by default supplies artist and album with empty keyword)

### CODE REVIEW

**Comment by kaso17** [comment]
Thank you, merged.

the modes/music-search parameters aren't correct in this definition. Only the ones supported by the definition should be included (now q and artist, the other ones should be removed). You can try to remove all except of q or the complete line. Then lidar should use the normal (keywords only) search.

**Comment by Akuma737** [comment]
Thank you

I will change it accordingly and try to add some other features

Is it possible to use multiple conditions in an if statement or to use nested it's?

**Comment by Akuma737** [comment]
Do multiple conditions in an if statement work
Like {{if. Keywords && .Query.Artist}}

**Comment by kaso17** [comment]
No

**Comment by Akuma737** [comment]
If I wanted to fix some of the code for the templating system do you know in which file I should search for?

**Comment by kaso17** [comment]
You can find the relevant code here:
https://github.com/Jackett/Jackett/blob/e05783a25ac272c59e4f62321d0f4eccd37d36f2/src/Jackett.Common/Indexers/CardigannIndexer.cs#L222

Using nested regexes might improve the situation a little. See https://retkomma.wordpress.com/2007/10/30/nested-regular-expressions-explained/
Implementing a proper grammar would be even better.
Adding a full blown interpreter language like JavaScript (using e.g. Jint) is also an option.

**Comment by Akuma737** [comment]
Adding a full blown interpreter sounds tempting but wouldn't that imply some kind of transition from the current torrent definitions to completely new ones? (which I imagine could confuse a lot of people if not done properly)

**Comment by kaso17** [comment]
It shouldn't be a problem to make it coexist with the current definition/templating system (just like the cardigann definitions coexist with the native indexers).
A most basic implementation could add e.g. a javascript command element to the current templating system. E.g. ```{{ javascript if (X) { return "X"; } else if (Y) { return "Y"; } else { return "Z"; } }}```

A new definition option to change between the current golang templating and a new javascript templating engine might be an alternative too.

Adding a complete java script based indexer format probably would be the most work intensive solution.

**Comment by Akuma737** [comment]
Thanks for the help I'll do it in two steps 
first I'll try "fixing" the current templating system so either you can use ifs with multiple conditions or nested ifs (I think I prefer multiple conditions)
And then I'll try to setup a new Java script based indexer when I have the time for it

**Comment by kaso17** [comment]
ok, sounds great.
Ok, when you decide which JS interpreter you want to use please consider that the HTML/CSS selector engine jackett currently mostly uses (anglesharp) has some integration with the jint javascript implementation to. We don't use it yet but in case we ever do (actually anglesharp with JS integration might be a good starting point) I would like to avoid having dependencies on two different JS interpreters.
Of course if there's a good reason to use another JS interpreter instead that shouldn't be a problem at the end.

**Pull request merged**
