### PR TITLE
Add cpasbien tracker

### PR DESCRIPTION
**Pull request by ploufs**

### CODE REVIEW

**Comment by kaso17** [comment]
merged

Thank you, next time please don't commit the changes to the project file but update the README.

**Comment by prophetmaster** [comment]
problem with date in search, if you add date no result same in the cpasbien.co website how to remove date in search query ?

**Comment by garfield69** [comment]
i give up. which is the official cpasbien domain now?
last one I had was https://www.cpasbien.vg/  but that is returning ERR_NAME_NOT_RESOLVED
f'ing site changes domains more often than i do socks ;-)

**Comment by garfield69** [comment]
https://www.cpasbien.lol/

**Comment by garfield69** [comment]
https://www.cpasbien.lol/ is now redirecting to https://www.gktorrent.biz/
as are a lot of the old domains in the legacylinks section of the cpasbien indexer.
anyone know if the site has a official new domain?
or has it been permanently taken over the the gktorrent crowd?

**Pull request merged**
