### PR TITLE
[ilCorsaroNero]

### PR DESCRIPTION
**Pull request by bonny1992**
Switched from the advanced search to the normal one (the admin has replied to me and he's checking what's wrong, until that, normal search). 
Also, I don't know if some golang templating functions are available, so I commented what I added.
And I added the new categorymappings

[First time doing a pull request, sorry if I did something wrong]

### CODE REVIEW

**Comment by bonny1992** [comment]
I feel like I forgot something here :\

**Comment by kaso17** [comment]
no, the golang template engine used in jackett only contains a very limited feature set (regex based matching). I was to lazy to implement it as a proper grammar based engine). and/or are not supported. Even nesting probably doesn't work. I'll try it later.

**Comment by kaso17** [comment]
`The nested version (`{{ if .Query.Keywords }}{{ if .Config.advanced-search }}adv/{{ .Query.Keywords }}.html{{else}}argh.php?search={{ .Query.Keywords }}{{end}}{{else}}/recenti{{end}}`) doesn't work (as expected). It should be possible to make nesting work using advanced regex features.
But I'm not motivated to to that at this time.

I'll hope that the admin finds the problem with the advanced search making this unnecessary. If that doesn't happen please remind me to implement a better templating engine.

**Comment by bonny1992** [comment]
I don't think it's needed, it was a flair of mine adding the switch normal/advanced search. 
The normal one works just fine and it's updated at the edge.

**Pull request merged**
