### PR TITLE
Socks proxy support

### PR DESCRIPTION
**Pull request by sv01a**
#1083

### CODE REVIEW

**Comment by sv01a** [comment]
Dotnet Core project with installed SocksWebProxy package build without any problems. Also anytime we can easily convert https://github.com/postworthy/SocksWebProxy/ to NETStandard.

Big question is will it work on non Windows platforms.

**Comment by NathanNZ** [comment]
I've put up a pull request (linked above) to see if we can get .NET Standard support. Licence is GPL so I hope somebody still maintains this project as it's a bit trickier than MIT to fork it off if they don't. (I'm not a lawyer, so I might be wrong, but MIT seems much more permissive in that regard)

**Comment by NathanNZ** [comment]
I've also cherry picked my changes into a fork of this library that Sonarr uses. Will see how we go! 👍

**Comment by sv01a** [comment]
I was try to use lloydsparkes/SocksWebProxy, but this fork seems too old and don't work as expected.

**Comment by NathanNZ** [comment]
Looks like both forks are more or less up to date with each other, but I've pull requested both so either will do :)

**Comment by flightlevel** [comment]
Thanks @sv01a 
Nice work!

**Pull request merged**
