### PR TITLE
Create channelx.yml

### PR DESCRIPTION
**Pull request by Sc4nd4l**
add channelX site. Need some help making it fully function again though.

### CODE REVIEW

**Comment by garfield69** [comment]
>add channelX site. Need some help making it fully function again though.

what appears to be the issue?
The most likely cause is a mismatch of the unit3d version...
If you send an invite to garfieldsixtynine @ gmail.com I can help out.

**Comment by Sc4nd4l** [comment]
Done! It did work, now its returning «no search results”

**Comment by garfield69** [comment]
the site's registration page did not show success or failure in registering... no emails either.
if I try to use my creds I just get the login page again. I may be pending validation....
can you check if you have to validate my registration?

**Comment by Sc4nd4l** [comment]
Yea! Active now

**Comment by garfield69** [comment]
hmm. i think the login page is broken on this site, i'm seeing this in the chrome console log
```

**Comment by garfield69** [comment]
hmm. i think the login page is broken on this site.
i enter my creds and i get an empty login page back.

On the the chrome console log I see this error, it may be relevant
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://www.google.com/recaptcha/api.js https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/api2/ https://www.gstatic.com/recaptcha/api2/v1550471573786/recaptcha__en.js https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.1/moment-with-locales.min.js https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.min.js https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.15.35/js/bootstrap-datetimepicker.min.js 'nonce-b549699a43e74bbb855b048a18800af2'". Either the 'unsafe-inline' keyword, a hash ('sha256-VS1xKGQ/eY1xOar131wmqZLSuebzf2lMk4VFLnNNSYw='), or a nonce ('nonce-...') is required to enable inline execution.
```

I'm on chrome Version 73.0.3683.86 (Official Build) (64-bit)
I'll try another browser and see if that makes a difference.

**Comment by Sc4nd4l** [comment]
Sure. Working fine here with both Safari and Chrome

**Comment by garfield69** [comment]
nah, i've tried win10 versions of opera, edge, chrome and tor and all of them will not let me login to channelx.online :-(
what version of chrome are you using and on what platform?

**Comment by garfield69** [comment]
well i've got 9 other unit3d sites and i can login to them all fine from my win10 chrome73
I've also tried channelx with my ubuntu18 chrome73 and mojave chrome72 and they fail too.
so its looking to me like that error I posted earlier is interfering either with my registration, or with my subsequent login.
I'll try again over the next few days and see if it resolves.
BTW, does your login look like this?
image
or do you see a recaptha challenge as well?

**Comment by Sc4nd4l** [comment]
I'm using 72.0.3626.121(64-bit). I've sent you an email with new credentials.

**Comment by garfield69** [comment]
login successful with you credentials you provided. thank you. 
I'll start looking into the "no search results" issue now. ;-)

**Comment by garfield69** [comment]
regarding the registration problem, I raised a query with the unit3d support and they responded 
https://github.com/HDInnovations/UNIT3D/issues/650

**Comment by garfield69** [comment]
Try out Jackett pre-release 0.11.106

**Comment by garfield69** [comment]
been getting ERR_CONNECTION_TIMED_OUT for a couple days now.... has the site got a new domain or is it just having some server / gateway issues?

**Comment by Sc4nd4l** [comment]
Hi! 
Site had some downtime last days, but are back up now.

**Comment by garfield69** [comment]
nice one. I see you have upgraded to unit3d 1.9.2 so I'll update channelx indexer to handle the improvements (login error detection and what not :-)

**Comment by garfield69** [comment]
Oh, and in case you haven't noticed, you may want to update your login page title with your site name which appears to be set to the default unit3d
image

**Comment by Sc4nd4l** [comment]
Awesome!

**Comment by garfield69** [comment]
https://channelx.online/ returning ERR_CONNECTION_TIMED_OUT
it likely the site is down while they upgrade to unit3d 2.* , similar to what happened back in march.

**Comment by HDVinnie** [comment]
Still shows `<div class="Jackett" style="display:none;">Powered By UNIT3D Community Edition v1.9.4</div>`. Site is back up it seems now. I know owner said he does plan to update to `UNIT3D Community Edition v2.2.2` soon.

**Comment by garfield69** [comment]
thanks for the update.

**Pull request merged**
