### PR TITLE
Add Back-ups and SkTorrent trackers

### PR DESCRIPTION
**Pull request by halali**

### CODE REVIEW

**Comment by halali** [comment]
If you have some more trackers to make let me know...

**Comment by garfield69** [comment]
@halali  https://github.com/Jackett/Jackett/projects/1 :grinning:

**Comment by adamwinn** [comment]
@halali It would be best to leave off the full url in places like below and others in case the domain changes later on
```
a[href*="https://back-ups.me/details.php?id="]
```
I believe you can just do
```
a[href*="/details.php?id="]
```

**Comment by halali** [comment]
You are right.

**Comment by kaso17** [comment]
Thank you

**Comment by kaso17** [comment]
made some minor changes via 0bb231eecace89154a56341413e3f19b0c48a6f6

**Pull request merged**
