### PR TITLE
feat(indexers): added gay-torrents.net

### PR DESCRIPTION
**Pull request by thebluepotato**
🏳️‍🌈
I’m on a roll here! Like #1689, this is a tracker with mostly porn, but also many gay-themed movies, tv-shows, documentaries (that are otherwise hard to find). This is technically a private tracker, but there’s no requirement of ratio. I’ve set it as `semi-private` because there’s no invite needed but you have to log in.
Cheers!

### CODE REVIEW

**Comment by PoshSparks** [comment]
great work!   two observations...

* I noticed I'm only seeing freeleech items when searching against this indexer (I've confirmed my login credentials).
* though I can add the indexer successfully, the test fails... resulting output from jacket's log.txt file: 

```
2017-08-19 09:41:44.0183 Error Exception in test_indexer System.Exception: Found no results while trying to browse this tracker
  at Jackett.Services.IndexerManagerService+<TestIndexer>c__async0.MoveNext () [0x000ef] in <3c02d63f4dc54c69812f99444f189d7e>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <204f770036d441bb8dfd3daba3550e83>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <204f770036d441bb8dfd3daba3550e83>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <204f770036d441bb8dfd3daba3550e83>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <204f770036d441bb8dfd3daba3550e83>:0
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0
  at Jackett.Controllers.AdminController+<Test>c__async5.MoveNext () [0x0012b] in <3c02d63f4dc54c69812f99444f189d7e>:0
2017-08-19 09:42:14.4202 Info Found 0 releases from Gay-Torrents.net
2017-08-19 09:42:14.4202 Error Exception in test_indexer System.Exception: Found no results while trying to browse this tracker
  at Jackett.Services.IndexerManagerService+<TestIndexer>c__async0.MoveNext () [0x000ef] in <3c02d63f4dc54c69812f99444f189d7e>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <204f770036d441bb8dfd3daba3550e83>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <204f770036d441bb8dfd3daba3550e83>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <204f770036d441bb8dfd3daba3550e83>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <204f770036d441bb8dfd3daba3550e83>:0
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0

```

**Comment by thebluepotato** [comment]
Testing and freeleech detection fixed.

**Comment by PoshSparks** [comment]
working much better...  seeing non-freeleech in results... 

Not even sure if this issue can be fixed... but I did observe that the search results in jackett appear to be mirroring only the 1st page of results from the site... 

for example... I search for the movie "Daddy"... this is themed/nonporn movie...  in Jackett, I get the typical list of Porn categories for the word "Daddy"... no additional pages available (in jackett)... However, if I limit the search to catagory "Movies" I now get no results.. 

on the website, if you do a **generic** search for "Daddy" the first page of results mimic the results from Jackett listed as noted above... However, in this case, additional pages are available... and if you go a few pages into the results (page 6) , you can find the movie "Daddy (2015) as expected" under category "Comedy" (another copy under "Drama")... 

this makes me think that jackett is only pulling the first page of results, and filtering the categories from that list only... thoughts?

**Comment by thebluepotato** [comment]
@PoshSparks yup, this is a recognized issue with Jackett: #975. I'm guessing we'll soon see improvements in that field though.

**Comment by PoshSparks** [comment]
well, beyond that issue, all seems to be working so far! :)  thanks so much for your help!

**Pull request merged**
