### PR TITLE
webui: add negative filtering in search results. resolves #7660

### LINKED ISSUE #7660: [req] Manual search - add second Search box which removes results with entered text
_I had originally posted this as an edit to #6791 but I realise now it's completely different to what I had originally suggested._

Change the Dashboard Search box (not 'Query', but rather the secondary 'Search' which filters the results) to two boxes, with Search becoming Refine and the new box being Remove (or something to that effect).

Example taken from OP:
When searching for a show called Huge, not surprisingly you get a lot of porn, and filtering by '2010' just gives you a lot of 2010 porn instead. Being able to tell Jackett to remove results containing 'XXX', or anything else, would be a great help.

### PR DESCRIPTION
**Pull request by ngosang**
Tested
image

### CODE REVIEW

**Comment by ngosang** [comment]
Sure I did, but it doesn't work as you expect.
We are using a search function provided by DataTables that doesn't work well with special characters like "-" or "+". These characters are removed from the search text in some situations and I can't fix that.

Good cases:
* 1080p => contains 1080p
* +1080p => contains 1080p
* -1080p => not contains 1080p

In this cases we have the same behavior as Jackett has now (it's not as you expect)
* ++1080p => contains +1080p
* +-1080p => contains -1080p
* -+1080p => not contains +1080p

**Comment by ilike2burnthing** [comment]
Ah, just tested it and see what you mean. Oddly just using `-` (and presumably `+`) works fine as a filter for results that contain `-` (e.g. web-dl), but if you type anything after that without a space then it fails. Similarly in your build `--` removes web-dl and others, but trying to use `--dl` doesn't work.

Everything looks good though, thanks for this work!

**Comment by ilike2burnthing** [comment]
It's separate from this PR, but do we want searches to be applied to only the Name column, rather than all of them, given that we can already filter by Tracker and Category?

**Comment by garfield69** [comment]
>It's separate from this PR, but do we want searches to be applied to only the Name column, rather than all of them, given that we can already filter by Tracker and Category?

nah. 
In most cases a user might start a query and forget to refine it by tracker or category.
With the search filtering in this PR applying to results already fetched from the web sites, it saves the user from having to initiate a new query with tracker/category filters enabled to refine a query a second time.
So the way the PR works now saves time and resources by avoiding having to go fetch again.

**Comment by ilike2burnthing** [comment]
I was thinking the footer filters already covered that eventuality. But I suppose with this PR they could exclude an unhelpful category or tracker, rather than only being able to include with the footer filters.

**Pull request merged**
