### PR TITLE
remove expired cert

### PR DESCRIPTION
**Pull request by tomaskazragis**
fails search on the site

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
Test, keyword search, and download are all working fine here. Is there some specific scenario which fails?

**Comment by tomaskazragis** [comment]
It might be that I get failure because of FlareSolverr...
 Jackett.Common.IndexerException: Exception (uniondht): Ssl
error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED

  at /SRC/mono-6.8.0.105/external/boringssl/ssl/handshake_client.c:1132
---> System.Net.Http.HttpRequestException: The SSL connection could
not be established, see inner exception. --->
System.Security.Authentication.AuthenticationException: Authentication
failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl
error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /SRC/mono-6.8.0.105/external/boringssl/ssl/handshake_client.c:1132
  at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00048] in
<0c3b3cba6a384e83868468e2cb9eddf2>:0
  at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake
(Mono.Net.Security.AsyncOperationStatus status, System.Boolean
renegotiate) [0x000da] in <0c3b3cba6a384e83868468e2cb9eddf2>:0
  at (wrapper remoting-invoke-with-check)
Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)
  at Mono.Net.Security.AsyncHandshakeRequest.Run
(Mono.Net.Security.AsyncOperationStatus status) [0x00006] in
<0c3b3cba6a384e83868468e2cb9eddf2>:0
  at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation
(System.Threading.CancellationToken cancellationToken) [0x000fc] in
<0c3b3cba6a384e83868468e2cb9eddf2>:0
   --- End of inner exception stack trace ---
  at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication
(System.Boolean runSynchronously,
Mono.Net.Security.MonoSslAuthenticationOptions options,
System.Threading.CancellationToken cancellationToken) [0x00262] in
<0c3b3cba6a384e83868468e2cb9eddf2>:0
  at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore
(System.IO.Stream stream,
System.Net.Security.SslClientAuthenticationOptions sslOptions,
System.Threading.CancellationToken cancellationToken) [0x000c3] in
<3ea6f766f8264d0ebd22eb3930c429fe>:0
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore
(System.IO.Stream stream,
System.Net.Security.SslClientAuthenticationOptions sslOptions,
System.Threading.CancellationToken cancellationToken) [0x00102] in
<3ea6f766f8264d0ebd22eb3930c429fe>:0
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync
(System.Net.Http.HttpRequestMessage request,
System.Threading.CancellationToken cancellationToken) [0x00322] in
<3ea6f766f8264d0ebd22eb3930c429fe>:0
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync
(System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2]
in <3ea6f766f8264d0ebd22eb3930c429fe>:0
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync
(System.Net.Http.HttpRequestMessage request, System.Boolean
doRequestAuth, System.Threading.CancellationToken cancellationToken)
[0x00089] in <3ea6f766f8264d0ebd22eb3930c429fe>:0
  at System.Net.Http.DecompressionHandler.SendAsync
(System.Net.Http.HttpRequestMessage request,
System.Threading.CancellationToken cancellationToken) [0x000ca] in
<3ea6f766f8264d0ebd22eb3930c429fe>:0
  at FlareSolverrSharp.ClearanceHandler.SendAsync
(System.Net.Http.HttpRequestMessage request,
System.Threading.CancellationToken cancellationToken) [0x00099] in
<fbd88ea441c7406e935b66a246fef262>:0
  at System.Net.Http.HttpClient.FinishSendAsyncBuffered
(System.Threading.Tasks.Task`1[TResult] sendTask,
System.Net.Http.HttpRequestMessage request,
System.Threading.CancellationTokenSource cts, System.Boolean
disposeCts) [0x0017e] in <3ea6f766f8264d0ebd22eb3930c429fe>:0
  at Jackett.Common.Utils.Clients.HttpWebClient.Run
(Jackett.Common.Utils.Clients.WebRequest webRequest) [0x00487] in
<5bf14e545b754b49bb1aa8ba13ed9c70>:0
  at Jackett.Common.Utils.Clients.WebClient.GetResultAsync
(Jackett.Common.Utils.Clients.WebRequest request) [0x001b0] in
<5bf14e545b754b49bb1aa8ba13ed9c70>:0
  at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync
(System.String url, System.String cookieOverride,
Jackett.Common.Utils.Clients.RequestType method, System.String
referer, System.Collections.Generic.IEnumerable`1[T] data,
System.Collections.Generic.Dictionary`2[TKey,TValue] headers,
System.String rawbody, System.Nullable`1[T] emulateBrowser) [0x00101]
in <5bf14e545b754b49bb1aa8ba13ed9c70>:0
  at Jackett.Common.Indexers.CardigannIndexer.PerformQuery
(Jackett.Common.Models.TorznabQuery query) [0x00810] in
<5bf14e545b754b49bb1aa8ba13ed9c70>:0
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery
(Jackett.Common.Models.TorznabQuery query, System.Boolean
isMetaIndexer) [0x000cb] in <5bf14e545b754b49bb1aa8ba13ed9c70>:0
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery
(Jackett.Common.Models.TorznabQuery query, System.Boolean
isMetaIndexer) [0x00123] in <5bf14e545b754b49bb1aa8ba13ed9c70>:0
  at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery
(Jackett.Common.Models.TorznabQuery query, System.Boolean
isMetaIndexer) [0x00071] in <5bf14e545b754b49bb1aa8ba13ed9c70>:0
  at Jackett.Server.Controllers.ResultsController.Results
(Jackett.Common.Models.DTO.ApiSearch requestt) [0x0027c] in
<faa622824ca04b0585cebdbc35925145>:0


2021-03-07, sk, 15:18 ilike2burnthing <notifications@github.com> rašė:

**Comment by ilike2burnthing** [comment]
Either your certificates need updated, or your mono needs upgraded or downgraded.

Any chance you're running Jackett on a Synology NAS?

**Comment by tomaskazragis** [comment]
Nope I'm running it on QNAP NAS.

2021-03-07, sk, 16:27 ilike2burnthing <notifications@github.com> rašė:

**Comment by ilike2burnthing** [comment]
This won't be exactly the same then, but should be similar enough - https://github.com/Jackett/Jackett/wiki/Synology-installation

**Pull request closed without merging**
