### PR TITLE
teamhd: expand cookie guide with steps about changing user-agent

### PR DESCRIPTION
**Pull request by janot**
After seeing these user-agent issues with teamhd https://github.com/Jackett/Jackett/issues/6029, https://github.com/Jackett/Jackett/issues/6070#issuecomment-537340253, https://github.com/Jackett/Jackett/issues/6661, https://github.com/Jackett/Jackett/issues/6970, https://github.com/Jackett/Jackett/issues/7819 I wanted to do something about it until it is not user configurable https://github.com/Jackett/Jackett/issues/7786

I've tried to condense and simplify expanded guide but it still turned out twice as big and harder to understand
 
What do you think?

### CODE REVIEW

**Comment by cadatoiva** [comment]
It might be better to put the instructions in a wiki on the page, so we can link to it in this and other trackers where needed and have a single place to update. What you have looks good otherwise

**Comment by janot** [comment]
Will this do for starters? 
https://github.com/janot/Jackett/wiki/Finding-cookies-with-Jackett's-user-agent

**Comment by RoloSoze** [comment]
> 
> 
> Will this do for starters?
> https://github.com/janot/Jackett/wiki/Finding-cookies-with-Jackett's-user-agent

@janot In step #6, I'm can't find "More tools" under the three horizontal dots in Firefox. It's not an option.

**Comment by janot** [comment]
@RoloSoze This is only for Google Chrome as stated in the beginning (just made it bold).
Instructions for Firefox can be added later right into main repo's wiki if this pull request will be accepted.

**Comment by RoloSoze** [comment]
> 
> 
> @RoloSoze This is written for Google Chrome as stated in the beginning (just made it bold).
> Instructions for Firefox can be added later right into main repo's wiki if this pull request will be accepted.

I missed the part about this being Chrome-specific. It works fine now, Thank you!

**Comment by garfield69** [comment]
with #8431 in the pipeline, is it still worth merging this 8391?

**Comment by janot** [comment]
@garfield69 nope! teamhd login works with these changes

**Pull request closed without merging**
