### PR TITLE
core: disable SupportsImdbTVSearch in all trackers due to #8107

### LINKED ISSUE #8102: IPTorrents is returning more results than specified to Sonarr
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linux/UnRAID

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Unsure

**.Net Version**: N/A

**Jackett Version**: 0.14.476.0

**Last Working Jackett Version**: Unsure, updated docker today to latest.

**Are you using a proxy or VPN?** [yes/no] No

### Description

My setup was working fine up until a day or so ago. I have Jackett setup with site IPTorrents, with Sonarr utilizting Jackett for indexing.

When I do an interactive search in Sonarr for a single episode, Jackett returns up to 100 results instead of matching the single episode. In the below example screenshot and log, an interactive search was run for "Deadliest Catch Season 15 Episode 21". However, a lot of older episodes and even a Season 16 episode was included in the results. This is happening for all shows contained in Sonarr, not just this particular one.

When checking Sonarr's trace log, it shows that it is requesting the specific season and episode number "S15E21" in the GET URL, but Jackett is returning those results anyway.

Some other searching I have done has suggested there was a previous bug in an old version that allowed Jackett to search by IMDB ID but would not properly return results. It was indicated that the issue was fixed, but this seems to be the exact same issue.

### Logged Error Messages

No error messages that I can see.

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

https://i.imgur.com/jSnVsiQ.png

[log.txt](https://github.com/Jackett/Jackett/files/4453779/log.txt)

### PR DESCRIPTION
**Pull request by ngosang**
See #8107

Resolves #8102

### CODE REVIEW

**Comment by ngosang** [comment]
@garfield69 I disabled only in c# indexers. Could you take a look and see if Cardigann are working with Sonarr? I guess they don't.

**Comment by garfield69** [comment]
I tested both Sonarr2 and Sonnar3beta with beyond-hd, a unit3d yaml indexer.
unit3d has very good imdbid support, able to lookup imdbid for movies and tv with additional keywords filtering, for example, you can do the following:
https://beyond-hd.me/torrents?search=S01E01&doSearch=Search&uploader=&imdb=tt10234362&tmdb=&categories[]=2&min_year=0&max_year=0&sorting=created_at&direction=desc&qty=100

Both Sonarr2 and 3b sent the following (same) query to Jackett
http://127.0.0.1:9117/api/v2.0/indexers/beyond-hd/results/torznab/api?t=tvsearch&cat=5000&extended=1&apikey=**redacted**&offset=0&limit=100&q=Avenue%205&season=1&ep=1
note, no imdbid was used

And Jackett generated
https://beyond-hd.me/torrents?categories[]=2&search=Avenue+5+S01E01&description=&uploader=&imdb=&tmdb=&sorting=created_at&direction=desc&qty=100

Resulting in just 2 torrents returned, same as the web site.

Cardigann does not have real support for tv imdbid lookup despite beyond-hd's indexer having 
```yaml
    modes:
      search: [q, imdbid]
      tv-search: [q, season, ep, imdbid]
``` 
which is what I suspected you expected when you said
>Could you take a look and see if Cardigann are working with Sonarr? I guess they don't.

So I do not believe we need to do anything to Cardigann with regards to #8107 
but once 8107 is resolved Cardigann will need amending if we really want it to support tv-imdbid.
;-)

**Comment by ngosang** [comment]
@garfield69 great. Copy you message to #8107 for the future.

**Comment by kevindd992002** [comment]
How about for TorrentDay? I can search "imbdid SxxExx" in the TorrentDay's site itself but when I do the same in Jackett's UI it doesn't work. So that can't be an indexer problem, right?

**Comment by cadatoiva** [comment]
The TorrentDay code is setup so that it only sends imdbid when it's an imdbid search. If you want to help us by submitting a PR to add the query.GetEpisodeString() to the imdb version we can turn that back on.

**Comment by kevindd992002** [comment]
I see what you're saying. I would submit a PR if I'm a coder but I'm not. I only know Powershell which is not useful here, sorry.

**Comment by cadatoiva** [comment]
I mean, powershell is fully .net-clr compatible, so if you've done any GUI powershell programming with WinForms, you probably could ;)

**Comment by kevindd992002** [comment]
I have not, unfortunately. I only know the basics (like loops).

**Comment by kevindd992002** [comment]
Would you guys be willing to turn back the TorrentDay IMDB ID search and fix the search bug for me?

**Comment by garfield69** [comment]
direct your question to #8107 please. thanks.

**Pull request merged**
