### PR TITLE
Todotorrents: new Spanish indexer

### PR DESCRIPTION
**Pull request by Lyuu17**
Caps: TV, Movies, Music

Based on MejorTorrent's .cs

### CODE REVIEW

**Comment by garfield69** [comment]
Thank you.

**Comment by garfield69** [comment]
v0.20.314

**Comment by killo3967** [comment]
When will be this indexer avaible?

**Comment by garfield69** [comment]
@killo3967  use the dontorrent indexer. you can select https://todotorrents.net/ as a site link if you want, its the same site.

**Pull request merged**
