### PR TITLE
Add code style guide and update documentation to reflect changes

### PR DESCRIPTION
**Pull request by cadatoiva**
This pull request creates a .editorconfig file to enforce a consistent code style solution wide as well as updating the documentation to reflect this change for code contributors. There are updates to the Issue template and added details for contributors filing bug reports on the issues tab.

I've also cleaned up the README a bit while I was working on this. I found that GitHub supports turn down menus in Markdown files and used that to collapse supported trackers in order to make the whole file easier to read.

Please review the proposed code style to approve or modify before merging this request. Once the code style is finalized, I'll run `dotnet format` and submit the Pull Request that formats the existing solution code appropriately.

### CODE REVIEW

**Comment by junglebus** [comment]
Editorconfig LGTM, nice work. Must admit I'm not a huge fan of var everywhere for readability, but happy to give it a go
Will leave it to @garfield69 and @ngosang to comment on the readme files

**Comment by cadatoiva** [comment]
Yeah, there's some things I'd prefer were different too, but I left this largely with the default settings generated by VS, including leaving spaces instead of tabs.

I know that no one is going to be 100% happy with any given Code Style, so the thought is that this is better than having no standard style at all. I can live with the things that I would prefer be different.

**Comment by ngosang** [comment]
I agree with Editorconfig. In other PR we should run `dotnet format` and after that, in other PR, change the GitHub checks to validate the format in new PRs.
About the markdown changes, I didn't read. IMHO those changes shout be in other PR.
Some notes about the doc:
* README.md is too long. We should move the install and build sections to the wiki or separate markdown files. I prefer markdown files in the repository because you can read offline and it's versioned together with the code.
* The screenshot is ugly. We have to make a better one with less configured trackers. Also a screenshot with search results (Ubuntu or something legit)

**Comment by cadatoiva** [comment]
In the README, I did 3 things:

1. Added "see our contributing guide" and remove Contributing stubs.
2. Made it so that supported trackers are hidden behind turn-down menus (click to reveal)
3. Ran spell check largely so I could fix my own typos

I didn't think making a whole Pull Request to change `###` titles to `<details> ... </details>` seemed very prudent. And while I'm spell checking, might as well fix the whole document at once. I can undo those if you really want and move them to new PR, with your other proposed cleanup suggestions too.

**Comment by ngosang** [comment]
Wait for @garfield69 before doing any changes. He has the last opinion.

**Comment by cadatoiva** [comment]
@garfield69 This is just waiting on your approval or recommendations for the changes in README.md and ISSUE_TEMPLATE.md

Unless you know someone else who should review the style guide before we commit to it?

**Comment by cadatoiva** [comment]
It's all good, just wasn't sure if it slipped under the radar is all.

**Pull request merged**
