### PR TITLE
WiHD Provider

### PR DESCRIPTION
**Pull request by JigSawFr**
### Implementation of WiHD as a Jackett Provider,

> WiHD is a French High Private Tracker

Working as well, ready for using in a production environment.

> Features

- [x] Search on Tracker (Categories supported for querying, all categories mapped)
- [x] Max Page Crawling (default to 4)
- [x] Browser Simulation (Injecting additionals headers to request, configurable)
- [x] Latency Simulation (Between a range of two milliseconds numbers, configurable)
- [x] Calculate date from "Ago date"
- [x] Advanced Configuration with messages displayed
- [x] Settings checked and validated before saving.
- [x] Dev mod for developers (output to logfile in prod, console in dev)

> Informations on release:

- [x] Title
- [x] Guid
- [x] Link
- [x] MinimumSeedTime
- [x] MinimumRatio
- [x] Category
- [x] Date
- [x] Size
- [x] Description
- [x] Seeders
- [x] Peers
- [x] Comments
- [x] Uploader

### CODE REVIEW

**Comment by JigSawFr** [comment]
New PR, rebased on mainstream.

**Comment by raspdealer** [comment]
you have an invit for me to test it?
thx

**Comment by JigSawFr** [comment]
@raspdealer sorry i'have not at this time, it's hard to obtain an invit from this tracker.
But i can redirect you somewhere to make a request if you want

**Comment by raspdealer** [comment]
username at gmail thx

**Comment by JigSawFr** [comment]
@raspdealer just sent.

**Comment by itdaboyz** [comment]
Hello @JigSawFr ,
As you may have noticed, FnT will close in 7 days. It's sad for your hard work in integrating it in Jackett. It was working really well !
Now I don't have any french tracker working with Jackett/Sonaar and I see that you may have a way to request a invitation on WiHD.
I know it's not the point at all of this topic, but if you could send me the way to request an invitation at myusername @ gmail, it would save my day !

**Comment by raspdealer** [comment]
Please don't delete it for now :)
May be it will come back !

**Comment by JigSawFr** [comment]
@itdaboyz sorry i can't provide you an invitation, it's an **high** private tracker. So meaning it's hard to join and invites are very rare.

**Comment by itdaboyz** [comment]
@JigSawFr You were talking about a way to request an invite. Could you redirect me to this place? I know it will be hard to get one... Thanks !

**Comment by JigSawFr** [comment]
@itdaboyz It's a detourned way, and it's only for french. And anyone must wait a minimum of five months before first invite generation on this tracker.

**Comment by itdaboyz** [comment]
@JigSawFr Well I'm french if that's matter ! I understand that it's easier for a developper that will do great things related to the tracker than it is to a standard user. Thanks for the info about the delay.

**Comment by JigSawFr** [comment]
@itdaboyz sent :)

**Comment by itdaboyz** [comment]
I'm sorry @JigSawFr but I got nothing. Should I wait more or could it be that you sent it to another adress ? Mine is itdaboyz at gmail dot com.
Thanks again and I apologyze for the spam in this thread...

**Comment by JigSawFr** [comment]
@itdaboyz resend to right email

**Comment by smiro0** [comment]
someone have invite that i can have please ?

it is the only french site that i don't have.

Please :D

**Comment by raspdealer** [comment]
never received it @JigSawFr

**Comment by JigSawFr** [comment]
I can't give invitations for this website sorry :v:

**Pull request merged**
