### PR TITLE
Update winget-releaser to use main branch

### PR DESCRIPTION
**Pull request by vedantmgoyal9**

### CODE REVIEW

**Comment by garfield69** [comment]
well that did not work;
```
Run curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
++ mktemp -d
+ cd /tmp/tmp.92FDFylDLa
+ base_url=https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-
++ uname -s
+ os=Linux
+ '[' Linux == Darwin ']'
+ '[' Linux == Linux ']'
++ uname -m
+ machine=x86_64
+ target=x86_64-unknown-linux-musl
+ '[' x86_64 == armv7 ']'
+ url=https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
+ curl -L --proto =https --tlsv1.2 -sSf https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
+ tar -xvzf -
cargo-binstall
+ ./cargo-binstall -y --force cargo-binstall
 INFO resolve: Resolving package: 'cargo-binstall'
 INFO resolve: Verified signature for package 'cargo-binstall': gh=cargo-bins/cargo-binstall git=768[14](https://github.com/Jackett/Jackett/actions/runs/9657167931/job/26635930850#step:2:17)e4e8feaede87d8d112a4fad519d8eeaf81d ts=2024-06-23T[15](https://github.com/Jackett/Jackett/actions/runs/9657167931/job/26635930850#step:2:18):01:20.609Z run=9634346903
 WARN The package cargo-binstall v1.7.3 (x86_64-unknown-linux-gnu) has been downloaded from github.com
 INFO This will install the following binaries:
 INFO   - cargo-binstall (cargo-binstall -> /home/runner/.cargo/bin/cargo-binstall)
 INFO Installing binaries...
 INFO Done in 2.278368799s
+ CARGO_HOME=/home/runner/.cargo
+ [[ :/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: == *\:\/\h\o\m\e\/\r\u\n\n\e\r\/\.\c\a\r\g\o\/\b\i\n\:* ]]
Run # check if at least one version of the package is already present in winget-pkgs repository
Invoke-WebRequest: /home/runner/work/_temp/22df0e98-f6f6-41fa-b7fa-e846[16](https://github.com/Jackett/Jackett/actions/runs/9657167931/job/26635930850#step:2:19)c959c4.ps1:4
Line |
   4 |  Invoke-WebRequest -Uri "https://github.com/microsoft/winget-pkgs/tree …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Response status code does not indicate success: 404 (Not Found).
Error: Process completed with exit code 1.
```

**Comment by vedantmgoyal9** [comment]
Made a dumb error: https://github.com/vedantmgoyal9/winget-releaser/commit/3659f24b3c6cafe2c0eb0f926d849a4888d2958b. It should be working now.

**Comment by garfield69** [comment]
still running after 3minutes, log so far:
```
Run curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
++ mktemp -d
+ cd /tmp/tmp.JTKHkyvRkg
+ base_url=https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-
++ uname -s
+ os=Linux
+ '[' Linux == Darwin ']'
+ '[' Linux == Linux ']'
++ uname -m
+ machine=x86_64
+ target=x86_64-unknown-linux-musl
+ '[' x86_64 == armv7 ']'
+ url=https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
+ curl -L --proto =https --tlsv1.2 -sSf https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
+ tar -xvzf -
cargo-binstall
+ ./cargo-binstall -y --force cargo-binstall
 INFO resolve: Resolving package: 'cargo-binstall'
 INFO has_release_artifact{release=GhRelease { repo: GhRepo { owner: "cargo-bins", repo: "cargo-binstall" }, tag: "v1.7.3" } artifact_name="cargo-binstall-x86_64-unknown-linux-gnu.tar.bz2"}:do_send_request{request=Request { method: GET, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.github.com")), port: None, path: "/repos/cargo-bins/cargo-binstall/releases/tags/v1.7.3", query: None, fragment: None }, headers: {"accept": "application/vnd.github+json", "x-github-api-version": "[20](https://github.com/Jackett/Jackett/actions/runs/9657167931/job/26638013113#step:2:23)22-11-28"} } url=https://api.github.com/repos/cargo-bins/cargo-binstall/releases/tags/v1.7.3}: Received status code 403 Forbidden, will wait for 120s and retry
 INFO has_release_artifact{release=GhRelease { repo: GhRepo { owner: "cargo-bins", repo: "cargo-binstall" }, tag: "v1.7.3" } artifact_name="cargo-binstall-x86_64-unknown-linux-gnu.tar.bz2"}:do_send_request{request=Request { method: GET, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.github.com")), port: None, path: "/repos/cargo-bins/cargo-binstall/releases/tags/v1.7.3", query: None, fragment: None }, headers: {"accept": "application/vnd.github+json", "x-github-api-version": "20[22](https://github.com/Jackett/Jackett/actions/runs/9657167931/job/26638013113#step:2:25)-11-28"} } url=https://api.github.com/repos/cargo-bins/cargo-binstall/releases/tags/v1.7.3}: Received status code 403 Forbidden, will wait for 120s and retry
```

**Comment by vedantmgoyal9** [comment]
It's a problem in an upstream project—https://github.com/cargo-bins/cargo-binstall. I will ask them if there's any fix for it or to avoid this situation of retrying again and again after 120s altogether.

**Comment by garfield69** [comment]
While we wait for that cargo-whatever to be fixed, shall I revert this PR so get the old winget working again, or is this not an option?

**Comment by vedantmgoyal9** [comment]
Made some changes, and it is working now. The cargo thing is also fixed.

**Comment by vedantmgoyal9** [comment]
Made some changes, and it is working now. The cargo thing is also fixed.

Tested with a draft PR - https://github.com/microsoft/winget-pkgs/pull/160242

**Comment by vedantmgoyal9** [comment]
Oh no! I did put a condition, but I don't know why github actions simply ignored it 😭 

https://github.com/vedantmgoyal9/winget-releaser/blob/bb2969bb16d093d00be87bf3527ccd37cee25d32/action.yml#L89

**Comment by vedantmgoyal9** [comment]
Apologies for so many PRs being created through your account because of my action. I'm not sure why it happened, it didn't during my test runs - https://github.com/vedantmgoyal9/test/actions

**Comment by ilike2burnthing** [comment]
```yml
    - if: ${{ inputs.max-versions-to-keep > '0' }}
```

**Comment by vedantmgoyal9** [comment]
I think this is better - https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-data-type

**Comment by vedantmgoyal9** [comment]
And it works!!! 🎉 It will run as smoothly as before. Sorry again for the PR spam thing 🙏🏻

**Comment by ilike2burnthing** [comment]
Thanks, that's all working well for us too. The 0.22.217 run didn't publish, as your PR was already open, but the 0.22.209 did.

**Comment by ilike2burnthing** [comment]
Error on today's and yesterday's runs:

```text
Error: 
   0: Jackett.Jackett does not exist in microsoft/winget-pkgs
   1: Something went wrong while executing your query.
      This may be the result of a timeout, or it could be a GitHub bug.
      Please include `50AC:1325B4:4E639:918B3:669144AC` when reporting this issue.
   2: Failed to retrieve directory content of manifests/j/Jackett/Jackett
```

Seems to be the same as https://github.com/russellbanks/Komac/issues/446 and https://github.com/russellbanks/Komac/issues/447. Bit weird that they're from back in February though, and ours only started yesterday.

**Comment by ilike2burnthing** [comment]
And now it works 🤷

**Pull request merged**
