### PR TITLE
Bump to dotnet 8.0

### PR DESCRIPTION
**Pull request by mynameisbogdan**
#### Description
Draft to test the builder with NET 8.0

8.0 needs a file migration for OSX to move `~/.config/Jackett` to `~/Library/Application Support/Jackett`.

#### Issues Fixed or Closed by this PR

* Fixes #13876 
* Fixes #13879

### CODE REVIEW

**Comment by txtsd** [comment]
Thanks for doing this. I went at it a few weeks ago but I wasn't able to grok the automapper stuff.

**Comment by ilike2burnthing** [comment]
Can we bump `PublishCodeCoverageResults` to v2 here? Or is that better looked at separately (as I'm not sure it's even working)?

**Review by ilike2burnthing — COMMENTED** [review]
Still testing at the moment (Windows), but thus far all semi-private indexers are working fine; thrown in a mix of FlareSolverr and proxy usage as well. No slow down or high resource usage, even when running Test All.

**Review by ilike2burnthing — APPROVED** [review]

**Comment by garfield69** [comment]
Excellent work, thank you @mynameisbogdan 
does anyone think we need to give the linuxserver.io docker team a heads up that the next release will be on net8?

**Pull request merged**
