### PR TITLE
3 littles changes

### PR DESCRIPTION
**Pull request by aureliensauv**
removed label experimental in ConfigurationDataEliteTracker.cs file.
removed hdforever.yml (tracker deleted) and up readme.

### CODE REVIEW

**Comment by garfield69** [comment]
Thank you.

**Comment by aureliens13** [comment]
@garfield69 Could you revert my change about hdforever ?
Tracker is still alive !
Sorry for that.

**Comment by garfield69** [comment]
okely dokely.
but afterwards you are going to have to submit a PR for the change to elitetracker you included here as it is going to get reversed as well.
let that be a lesson for you, in future submit PRs for each indexer separately ;-)

**Comment by aureliens13** [comment]
Yes, I know !
I'm going to study why I deleted the hdforever definition because I think I missed something.

Thanks !

**Pull request merged**
