### PR TITLE
ci/cd: update azure pipelines to include yamllint. resolves #8575

### LINKED ISSUE #8575: core: validate yaml definitions (yamllint)
I'm using this tool to validate all the yaml definitions. => https://github.com/adrienverge/yamllint

Install in Linux `sudo python3 -m pip install yamllint`

Custom rules (.yamllint)
```yaml
---
extends: default

rules:
  comments: disable
  line-length: disable
  key-duplicates: disable
  truthy: disable
```

run validations `yamllint -c .../.yamllint .../Jackett/src/Jackett.Common/Definitions/`

Report:
[yamllint.log](https://github.com/Jackett/Jackett/files/4604814/yamllint.log)

@garfield69 I can automate this in Azure Pipelines if you want.

### PR DESCRIPTION
**Pull request by ngosang**
Merge after all errors in #8575 are resolved

### CODE REVIEW

**Comment by garfield69** [comment]
i'll work through the report but the following is legit and needs an exception.
changing to args: "src=\\\'(.+?)\\\'" does not work.
2020-05-12T20:02:35.6973749Z ./src/Jackett.Common/Definitions/ttsweb.yml
2020-05-12T20:02:35.6975433Z   148:27    error    syntax error: found unknown escape character "'" (syntax)
https://github.com/Jackett/Jackett/blob/fd7a47e45d64996c04ebeab789e07a83acfaed49/src/Jackett.Common/Definitions/ttsweb.yml#L142-L150

**Comment by ngosang** [comment]
I think he is right, even Github is telling you in red that it's bad.
Could you test `"src=\\\\'(.+?)\\\\'"` ?

**Comment by garfield69** [comment]
it works. Cool. I'll update the yaml.

**Comment by garfield69** [comment]
is this treating warnings as errors?

**Comment by ngosang** [comment]
yes. i can relax that if you want but I think it's good as is.
btw, i don't know what text editor are you using but "modern" ones like sublime text / vim will help you to sort of some issues in yamls

**Comment by garfield69** [comment]
the ones that are left are ones that have code that has been commented in the first column because its temporary or as a reminder of what the code was to prevent reapplying it (eg unit3d login test).

can we allow comments starting in column 1 to be ignored?

**Comment by ngosang** [comment]
@garfield69 errors in comments will be printed as warning and the build will pass. iIt will fail only on errors. I enabled more kind of errors in comments too. Not need to be fixed now. We will fix eventually.

**Comment by cadatoiva** [comment]
JK, I found it.

**Pull request merged**
