### PR TITLE
bitcityreloaded: update indexer

### PR DESCRIPTION
**Pull request by ilike2burnthing**
I had tried to convert this to yaml, but dates would fail for most but not all results, for no reason I could see:

> Error while parsing DateTime "15.04.2021 16:08:21 +01:00", using layout "02.01.2006 15:04:05 -07:00" (dd.MM.yyyy HH:mm:ss zzz): String '15.04.2021 16:08:21 +01:00' was not recognized as a valid DateTime.

Size and leechers would also seemingly randomly not work for individual results, and a selector which should have worked for leechers just wouldn't. No idea what was going on, but the C# indexer was fine.

In case anyone wants to give it a shot:

<details>
<summary>bitcityreloaded.yml</summary>

```yml
---
id: bitcityreloaded
name: Bit-City Reloaded
description: "Bit-City Reloaded is a GERMAN Private Torrent Tracker for MOVIES / TV / GENERAL"
language: de-DE
type: private
encoding: ISO-8859-1
links:
  - https://bc-reloaded.net/

caps:
  categorymappings:
    - {id: 1, cat: Other, desc: "Anderes"}
    - {id: 34, cat: PC, desc: "Appz/Linux"}
    - {id: 35, cat: PC/Mac, desc: "Appz/Mac"}
    - {id: 36, cat: PC, desc: "Appz/Other"}
    - {id: 20, cat: PC/0day, desc: "Appz/Win"}
    - {id: 4, cat: Books/EBook, desc: "EBooks"}
    - {id: 10, cat: PC/Games, desc: "Games/PC"}
    - {id: 15, cat: PC/Mobile-Android, desc: "Handy & PDA"}
    - {id: 16, cat: Audio/Audiobook, desc: "Hörspiel/Hörbuch"}
    - {id: 30, cat: Movies/Foreign, desc: "International"}
    - {id: 43, cat: Movies/3D, desc: "Movie/3D"}
    - {id: 6, cat: Movies/HD, desc: "Movie/HD 1080p"}
    - {id: 7, cat: Movies/HD, desc: "Movie/HD 720p"}
    - {id: 17, cat: Movies/Other, desc: "Movie/MegaPack"}
    - {id: 9, cat: Movies/SD, desc: "Movie/SD"}
    - {id: 26, cat: XXX, desc: "Movie/XXX"}
    - {id: 41, cat: XXX/Other, desc: "Movie/XXX/Other"}
    - {id: 42, cat: XXX/Pack, desc: "Movie/XXX/Pack"}
    - {id: 45, cat: Movies/UHD, desc: "Movies/4K"}
    - {id: 33, cat: Movies/BluRay, desc: "Movies/BluRay"}
    - {id: 19, cat: Audio/Video, desc: "Musik Videos"}
    - {id: 18, cat: Audio, desc: "Musik/MP3/Flac"}
    - {id: 13, cat: Console/WiiU, desc: "Nintendo"}
    - {id: 12, cat: Console/PS4, desc: "Playstation"}
    - {id: 22, cat: TV/HD, desc: "Serie/HD"}
    - {id: 38, cat: TV, desc: "Serie/Pack"}
    - {id: 23, cat: TV/SD, desc: "Serie/SD"}
    - {id: 25, cat: TV/Sport, desc: "Sport"}

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    music-search: [q]
    book-search: [q]

settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password
  - name: freeleech
    type: checkbox
    label: Filter freeleech only
    default: false
  - name: sort
    type: select
    label: Sort requested from site
    default: added
    options:
      added: created
      seeds: seeders
      size: size
      name: title
  - name: type
    type: select
    label: Order requested from site
    default: desc
    options:
      desc: desc
      asc: asc
  - name: info_tpp
    type: info
    label: Results Per Page
    default: For best results, change the <b>Anzahl der Torrents beim Durchsuchen</b> setting to <b>100</b> on your account profile.

login:
  path: login/
  method: form
  form: form[action="/login/index.php"]
  inputs:
    username: "{{ .Config.username }}"
    password: "{{ .Config.password }}"
  error:
    - selector: div[id="login_error"]
  test:
    path: index.php
    selector: a[href="logout.php"]

search:
  paths:
    # https://bc-reloaded.net/uebersicht.php?c7=1&c17=1&showsearch=1&search=2021+720p&blah=0&incldead=1&orderby=added&sort=desc
    - path: uebersicht.php
  inputs:
    $raw: "{{ range .Categories }}c{{.}}=1&{{end}}"
    showsearch: 1
    search: "{{ .Keywords }}"
    # 0 name, 1 descr, 2 both
    blah: 0
    # 0 active, 1 incldead, 2 onlydead
    incldead: 1
    orderby: "{{ .Config.sort }}"
    sort: "{{ .Config.type }}"
    # site does not support imdbid searching or display imdb links in results.

  rows:
    selector: "table.tableinborder tbody tr:has(a[href^=\"download.php\"]){{ if .Config.freeleech }}:has(img[src$=\"torrent_ou.gif\"]){{ else }}{{ end }}"

  fields:
    category:
      selector: a[href^="uebersicht.php?cat="]
      attribute: href
      filters:
        - name: querystring
          args: cat
    title:
      selector: a[href^="details.php?id="]
    details:
      selector: a[href^="details.php?id="]
      attribute: href
    download:
      selector: a[href^="download.php"]
      attribute: href
    date:
      selector: tr:nth-child(2) td:nth-child(5)
      filters:
        - name: append
          args: " +01:00" # CET
        - name: dateparse
          args: "02.01.2006 15:04:05 -07:00"
    size:
      selector: tr:nth-child(2) td:nth-child(1) b:nth-child(1)
#      filters:
#        - name: regexp
#          args: "(.+?) in"
    files:
      selector: tr:nth-child(2) td:nth-child(1) b:nth-child(2)
    grabs:
      selector: tr:nth-child(2) td:nth-child(3) b:nth-child(1)
    seeders:
      selector: tr:nth-child(2) td:nth-child(2) b:nth-child(1)
#      filters:
#        - name: regexp
#          args: "(\\d+) Seeder"
    leechers:
      selector: tr:nth-child(2) td:nth-child(2) # b:nth-child(2)
      filters:
        - name: regexp
          args: "(\\d+) Leecher"
    downloadvolumefactor:
      case:
        img[src$="torrent_ou.gif"]: 0
        "*": 1
    uploadvolumefactor:
      case:
        img[src$="torrent_2u.gif"]: 0
        "*": 1
    minimumratio:
      text: 0.7
    minimumseedtime:
      # 2 days (as seconds = 2 x 24 x 60 x 60)
      text: 172800
# engine n/a
```
</details>

### CODE REVIEW

**Comment by garfield69** [comment]
I you want I can take a look at the yml, if you provide creds in the usual place or email them direct.
But don't let that stop you merging the C#, I can always do a separate release for the conversion if I crack the mystery.

**Comment by ilike2burnthing** [comment]
Registration is still be open - https://bc-reloaded.net/registry.php

**Comment by ilike2burnthing** [comment]
Well this build seems to be working, but there's no rush, got a whole day before the next release.

If you figure it out, close this, otherwise feel free to merge it, cuz I need sleep ;P

The above yaml causes the result `Die.​Ibiza.​Affaere.​S01E03.​GERMAN.​HDTVRip.​x264-​TMSF` to have a size of 103 B and have 103 seeders (103 appears nowhere and `S01E01` and `S01E04` are unaffected, so it's not somehow stripping the season and episode numbers).

Commenting out the `b` of the size selector and uncommenting the filter gives a size of 0 B. Doing the same for seeders fixes the issue for it. Doing the opposite for leechers returns no leechers.

There were other examples, like `Abbott.​und.​Costello.​treffen.​Frankenstein.​1948.​German.​AC3D.​DL.​1080p.​BluRay.​x264-​Jako` which only had an issue with size, so it was kinda all over the place and I eventually gave up.

**Comment by garfield69** [comment]
replaced by dc1961b

**Pull request closed without merging**
