### PR TITLE
awesomehd: remove the year from the search

### PR DESCRIPTION
**Pull request by ngosang**
Part of #7829

### CODE REVIEW

**Comment by RoloSoze** [comment]
@ngosang Thank you. Did you take this point into consideration? https://github.com/Jackett/Jackett/issues/7424#issuecomment-618209007 This is for something like `1917 2019`

**Comment by ngosang** [comment]
Of course

**Comment by RoloSoze** [comment]
@ngosang Thank you!

@garfield69 Might be useful in case you decide to modify the code for https://github.com/Jackett/Jackett/issues/7424#issuecomment-618213360

**Comment by cadatoiva** [comment]
Regex checks for a space before the year, and also includes [year] or (year) options. You can see the explained Regex in https://regexper.com/#%20%5B%5C%28%5C%5B%5D%3F%2819%7C20%29%5Cd%7B2%7D%5B%5C%29%5C%5D%5D%3F%24

This does mean that years in the title that aren't the first year will also get removed. But that's about as good as something like this can get.

**Comment by ngosang** [comment]
Thanks for that tool. :wink:

**Comment by cadatoiva** [comment]
The one I like better when testing is https://myregextester.com/ because it has the option to specifically use .Net syntax, because C#/.Net isn't ECMA compliant as a default. It also can tweak your Regex and convert it to pastable C# code.

**Comment by RoloSoze** [comment]
> it also checks that this year term is the last term in the search,

Yup, `1917 2019` works fine.



> so it breaks under two conditions, if the release year isn't the last search term

Should be extremely rare since the majority of users who choose to enter the release year enter it at the very end of the search keywords. 





> or if there is no release year and the last word in the title is a matching year. 

Like with `Blade Runner 2049` which is fine because `2049` will be removed and `Blade Runner` will remain.

**Pull request merged**
