### PR TITLE
add acg.rip

### PR DESCRIPTION
**Pull request by whtsky**

### CODE REVIEW

**Comment by garfield69** [comment]
Fantastic!
thank you.

**Comment by garfield69** [comment]
acgrip returning ERR_CONNECTION_TIMED_OUT
is the site gone, changed domain or just broken?

**Comment by garfield69** [comment]
working again.

**Comment by garfield69** [comment]
https://acg.rip/ returning ERR_CONNECTION_REFUSED
just me, or is the site broken, gone or moved to a new domain?

**Comment by whtsky** [comment]
It works for me ( in Mainland China )

**Comment by garfield69** [comment]
Thank you for the info.

**Comment by garfield69** [comment]
working again for me too now. :-)

**Comment by garfield69** [comment]
https://acg.rip/ is doing it again. returning ERR_CONNECTION_REFUSED for me.
expect its a temporary issue like last time.

**Comment by whtsky** [comment]
Works for me in Mainland China right now, guess it's a temporary issue

**Comment by garfield69** [comment]
yes, very temporary. working for me too now ;-)

**Pull request merged**
