### PR TITLE
Remove yggtorrent support

### PR DESCRIPTION
**Pull request by HLFH**
Hi,

YggTorrent is no longer supported because of Cloudflare protections.
The [current issue](https://github.com/Jackett/Jackett/issues/8840#issuecomment-639062081) should be closed and classified as `won't fix`.

Before Jackett is able to bypass Cloudflare protections thanks to some new contributors, it is best to remove the `yggtorrent` files as it is no longer supported.

In the mean time, I recommend everyone to use their own scraper for yggtorrent or - more easily - to migrate to an alternative such as the torrent tracker that [has recently been implemented into Jackett](https://github.com/Jackett/Jackett/commit/9f4cb17284e201b7765115bc0b56c5fcf8272fa9): [ONLYscene](https://www.onlyscene.org/.).

### CODE REVIEW

**Comment by ngosang** [comment]
You need to do some changes in the updater code too.
Anyway this issue is affecting more sites, Jackett developers have to make a global decision about Cloudflare.

**Comment by HLFH** [comment]
Not sure what you mean by the required changes in the updater code.

On a different project, the Cloudflare bypass issue has never been fixed.
wallabag is an alternative to the Pocket read-it-later service: https://github.com/wallabag/wallabag/issues/1399 ; and five years laters, neither the core team nor the contributors fixed.

Happily, more developers have worked in the last years to tackle this issue, so I guess Jackett will be able to fix it thanks to its community.

**Comment by Ekhozie** [comment]
I don't think this PR is still required as cloudflare has been removed from yggtorrent (see #8840) and everything is now working well.

**Comment by HLFH** [comment]
@Ekhozie Yes,

> I don't think this PR is still required as cloudflare has been removed from yggtorrent (see #8840) and everything is now working well.

I understand it and it works. I'll close this PR as soon as the discussion is over, that the https://github.com/Jackett/Jackett/issues/8840 issue is closed, and that a global issue concerning the bypass of CloudFlare Security Protections is submitted.

**Comment by cadatoiva** [comment]
One thing we could do to remain relatively lightweight and still solve the JS challenges relatively easily is to have a node.js component to the system and run that as the challenge solver: https://stackoverflow.com/questions/15136952/can-a-c-sharp-application-communicate-with-node-js-code

Since it's already a JS engine, it should be able to run the code from the site to parse, and then pass along the finished result.

Other option is to look for progress on the javascript interpreter front.

**Comment by ngosang** [comment]
@guish I have been working in a NodeJS server based on this code https://github.com/Jackett/Jackett/issues/8840#issuecomment-640046242 but it's generic, it works with all sites and challenges. And a C# handler/interceptor that is able to send the requests to the NodeJS server and get the cookies. Implements this https://github.com/Jackett/Jackett/issues/8840#issuecomment-640100213

All is implemented and working but it's no reliable because Cloudflare is able to detect Selenium and Puppeteer and It shows the hCaptcha instead of the JS challenge. https://github.com/berstend/puppeteer-extra/issues/208 https://github.com/berstend/puppeteer-extra/issues

I can share all the code but I think this is going to be the cat and mouse game again...

**Comment by AdityaAnand1** [comment]
> I can share all the code but I think this is going to be the cat and mouse game again...

Please do, we gotta start somewhere 😁

**Comment by ngosang** [comment]
This is the server source code => https://github.com/ngosang/FlareSolverr
I will publish the C# interceptor source code soon.

@Guisch **@ All** Any help to improve the code or to bypass Cloudflare detection will be appreciated.

**Comment by ngosang** [comment]
For those interested in the Cloudflare problem that affects other trackers see #9029

**Pull request closed without merging**
