### PR TITLE
core: add cli parameters in jackett_launcher.sh

### PR DESCRIPTION
**Pull request by ngosang**

### CODE REVIEW

**Comment by ngosang** [comment]
@MichaIng maybe this is interesting to you!
https://github.com/linuxserver/docker-jackett/pull/102

**Comment by ngosang** [comment]
@garfield69 I published a pre-release for doing some tests. You can publish the next release as usual.

**Comment by MichaIng** [comment]
Many thanks for the info. Since we create an own systemd unit with known user and directory, we integrated the loop right into it:
```
ExecStart=/bin/dash -c '/opt/jackett/jackett --NoRestart; while pgrep -u jackett JackettUpdater > /dev/null; do sleep 1; done'
```
However great idea and reasonable to pass CLI args. Though one minor question: Does the binary have issues with doubled arguments? Since `--NoRestart` is passed within the launcher, it could now be accidentally passed two times, when one does not having a look into the script.

Good to know that we are not the only ones who suffer the issue of bug reports/support requests sent to upstream developers instead of sending them to the distro/package/container maintainers first to rule out issues with the integration or outdated version in the first place 🤔. Your case is a good example of good communication and finding the best solution together, instead of collecting frustration about the amount of bug reports that are not an upstream issue or solved there already.

**Comment by ngosang** [comment]
> Though one minor question: Does the binary have issues with doubled arguments?

Nice catch. It doesn't work but the error message is clear.
```
$ ./jackett_launcher.sh -c httpclient --NoRestart
Jackett v0.16.546.0

ERROR(S):
  Option 'NoRestart' is defined multiple times.
```
We can do some text replacement with `sed` but I think it's not worth it.

> Good to know that we are not the only ones who suffer the issue of bug reports/support requests sent to upstream developers instead of sending them to the distro/package/container maintainers first to rule out issues with the integration or outdated version in the first place

It would be best if you use our version, but I understand that you have your own version for performance / resources reasons. I get it and it's fine, but it comes at a cost to you.

We have to be very careful with the changes in the updater because we have very different users with Linux, FreeBSD, * nix, NAS ... The current script works for all of them.

**Comment by MichaIng** [comment]
> We can do some text replacement with `sed` but I think it's not worth it.

Jep I had the same idea, however someone who creates a systemd unit will most likely recognise this, so I agree to keep it simple and put some trust into maintainers and admins 😉.

> It would be best if you use our version, but I understand that you have your own version for performance / resources reasons. I get it and it's fine, but it comes at a cost to you.

Generally I agree, in this case I was involved in the script creation and the reason/related issues that were the reason to create it. I'll keep an eye on any changes to adapt in case necessary.

**Pull request merged**
