### PR TITLE
core: force garbage collector to limit memory usage

### PR DESCRIPTION
**Pull request by ngosang**

### CODE REVIEW

**Comment by junglebus** [comment]
I don't think this will work as you expect. If you google  GC.Collect(), the consensus is that you really shouldn't being doing it. I wouldn't be surprised if this delays the results being returned and makes a negligible difference to memory usage. Remember GC runs regularly so you are just calling it slightly before it will run automatically anyway

Either way, think this should be a feature toggle and not on by default at least initially. It's really easy to add feature toggle since we load appsettings.json from the config folder already https://github.com/Jackett/Jackett/blob/master/src/Jackett.Server/Program.cs#L109 A couple of users use this to listen on a specific IP address e.g https://github.com/Jackett/Jackett/search?q=appsettings.json&type=Issues

And then in the controller it's easy to grab this value e.g.
https://stackoverflow.com/a/55801199

**Comment by ngosang** [comment]
> I don't think this will work as you expect. If you google GC.Collect(), the consensus is that you really shouldn't being doing it.

@junglebus I know it's a bad idea. I don't want to merge this PR, just testing. Maybe you can help me.

My goal is to reduce max memory usage in Jackett to a finite amount, eg 200 MB, so it doesn't affect other processes. NOTE: I have 50 trackers enabled. I know that is more than the average user but reducing memory usage is a good thing in general. In my server, Jackett's memory looks like this after 5 days.
image
My first thought was "there isn't a memory leak because the fist day the memory was flat".

The second thing was the cache of results. The memory increases after every search and some time later, the memory decreases a bit (because the cache TTL is 1 hour). I opened this PR #7069 but I tested it for a week and it's not working as I expected. The cache uses memory but few MB.

The remaining thing is the GC and I pretty sure the problem is there, but I don't have a profiler to test it deeply. My guess is the GC detects there are a lot of free RAM in the system, and it doesn't need to collect the garbage. In Java, the solution is to configure the max heap size (-Xmx) and the GC will be more or less aggressive to free memory when it's close to the limit. That guarantees that you never surpass a threshold. I tried this:
* Environment variable COMPlus_GCHeapHardLimit . If I set this value low the process crash with OutOfMemory, if the number is enough to start the program, the memory usage is high as before. I'm in Linux, I don't know if I doing the test right, I don't have a profiler. => https://docs.microsoft.com/en-us/dotnet/api/system.gcmemoryinfo.totalavailablememorybytes?view=netcore-3.0
* Using Workstation GC. I didn't notice anything... => https://blog.discountasp.net/reducing-net-core-memory-usage/
* Calling the GC manually (this PR). The effect is noticeable, the memory increases but more slowly. But... that is a ugly hack and doesn't limit the max memory.

For me the best solution will be to fix the max heap size (like in Java) but I don't know how to. **Could you help me?** If you want to profile the memory configure 30 public trackers and perform an empty search in the Jackett UI.

**Comment by cadatoiva** [comment]
I'll profile this in ReSharper which has a better memory profiler. I'll just have to port in my config from my production machine, which uses 33 public torrents.

The biggest source of memory leaks in a C# program is leaving objects subscribed to events. Not sure if this is the problem here, but if an object adds one of its functions to an event listener, and is later deleted by going out of scope, the event listener holds the object in scope which prevents the GC from recognizing it as dead and in need of cleanup.

**Comment by junglebus** [comment]
My thoughts are this could be a MS issue.
Never seen anyone complain about memory usage that runs Windows. Maybe it's that low powered devices are generally Linux, but it would be interesting to know how much memory @garfield69 Window's instance uses since he has a lot of trackers

If this only occurs on Linux and not Windows, unlikely we can do anything in Jackett except keep up with .NET Core updates. Wonder if would be worth trying with say Docker where you can limit the containers memory???

Not saying its exactly this issue https://github.com/dotnet/runtime/issues/13301 but shows there can differences in different OSes

**Comment by cadatoiva** [comment]
running dotnet-core version on Windows 10 with ReSharper DotMemory profiler, I get the following stats:

After Jackett is started fresh, all loading complete, memory stable:
- Total: 97.2MB
- Unmanaged: 74.48 MB
- Heap Gen1: 433 KB
- Heap Gen2: 17.51 MB
- Large Object Heap: 1.04 MB

While search is running, peak memory usage:
- Total 191.24MB
- Unmanaged: 96.15
- Heap Gen1: 1.07 MB
- Heap Gen2: 63.03 MB
- Large Object Heap: 27.4 MB

After Search results are returned and memory stabalized:
- Total 164.95MB
- Unmanaged: 96.32MB
- Heap Gen1: 638.5KB
- Heap Gen2: 40.44MB
- Large Object Heap: 26.4MB

image

**Comment by cadatoiva** [comment]
Running the DotTrace application profiler in ReSharper shows that a significant amount (>10%) of time and memory allocation is involved in parsing the DateTime values from returned results. So that's probably where we want to focus our efforts.

**Comment by garfield69** [comment]
on my win10 jackett FullFrameworkWindows variant using the HttpWebClient 
afer performing a test-all on 251 indexers
the jackettservice used about 25MB, the jackettconsole 262MB, and the jacketttray 36MB

**Comment by ngosang** [comment]
I'm testing Environment variable `COMPlus_GCHeapHardLimit` again and it's working but I have to set a high value (300 MB+) to avoid OutOfMemory crash. This could be a solution for me but this value is hard to configure for the average user.

@cadatoiva I have been thinking in 2 things. 
1. The memory usage when it is idle is high.

Why Jackett takes too long to release the memory after the search? What is it saving in G2 and LO heaps? I had Jackett running for 3 days, in the top graph you can see the CPU usage (can be translated to queries to Jackett), in the bottom the memory usage. As you can see the memory always goes up (it releases a bit several hours after but it's weird...)
Note: Linux + .Net Core 3.1 + HttpWebClient2NetCore + COMPlus_GCHeapHardLimit (if I remove the env var COMPlus_GCHeapHardLimit the memory goes higher).
Could you repeat the profiling with a longer tests, doing more queries?
image

2. Concurrency

When we call the aggregate indexer (all) we are making all requests in parallel, no matter if they are 5 or 200. I don't know much about c#, but I think that is what Tasks do => https://github.com/Jackett/Jackett/blob/98541ac6f86509a3a2fef126a249b9cf29264b92/src/Jackett.Server/Controllers/ResultsController.cs#L226
If we want to limit the maximum memory (at least in low end devices) we have to use a Thread Pool with a limited number of workers (eg 10). The request will take longer if you have many indexers but the memory will be bounded.

**Comment by cadatoiva** [comment]
When I get a chance, I'll run it through a more rigorous profiling to see what I can dig up. [This link](https://www.jetbrains.com/help/dotmemory-unit/Introduction.html) is in the ReSharper menu in Visual Studio as a getting started in finding memory problems. I haven't read it yet, but it might be a starting point for your own investigation as well.

**Comment by cadatoiva** [comment]
To your second point about Concurrency, the CLR already has a default manager for the number of Tasks running. It usually starts at # of cores, and goes up or down based on how long each task takes to run. Tasks and concurrency + thread safety was a huge aspect of a project I worked on at one point.

Unless we're already manually tweaking the Task settings somewhere else in code, then the Task library already works behind the scenes to optimize tasks on CPU and Mem usage.

**Comment by ngosang** [comment]
> To your second point about Concurrency, the CLR already has a default manager for the number of Tasks running. It usually starts at # of cores, and goes up or down based on how long each task takes to run. Tasks and concurrency + thread safety was a huge aspect of a project I worked on at one point.

Sorry for the late response. In my installation the number of threads seems too high... I tested in 2 Linux systems (desktop with 4 cores and server with 4 cores) and I get `32767 workerThreads, 1000 completionPortThreads` in both
```
02-22 00:06:51 Info Starting Jackett v0.13.135.0 
02-22 00:06:53 Info Environment version: 3.1.1 (/home/kizar/Jackett/) 
02-22 00:06:53 Info OS version: Unix 5.4.13.1 (64bit OS) (64bit process) 
02-22 00:06:53 Info Jackett variant: CoreLinuxAmdx64 
02-22 00:06:53 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
02-22 00:06:53 Info App config/log directory: /home/kizar/.config/Jackett 
02-22 00:06:53 Info issue: Arch Linux \r (\l) 
02-22 00:06:53 Info Using HTTP Client: HttpWebClient2NetCore 
```

With Mono I get more reasonable values
```
02-21 21:59:20 Info Starting Jackett v0.13.160.0 
02-21 21:59:21 Info Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5) 
02-21 21:59:21 Info OS version: Unix 5.4.13.1 (64bit OS) (64bit process) 
02-21 21:59:21 Info Jackett variant: Mono 
02-21 21:59:21 Info ThreadPool MaxThreads: 400 workerThreads, 200 completionPortThreads 
02-21 21:59:21 Info App config/log directory: /home/xxx/.config/Jackett 
02-21 21:59:21 Info issue: Arch Linux \r (\l) 
02-21 21:59:21 Info mono version: 6.4.0 (makepkg/fe64a4765e6 Sat 16 Nov 2019 04:59:42 PM UTC) 
02-21 21:59:21 Info Using HTTP Client: HttpWebClient
```

**Comment by junglebus** [comment]
I just tried changing a random indexer (AvistazTracker.cs) from using CsQuery to Anglesharp. Wanted to see how much work would be involved as it seems silly having two libraries that do the same thing and CsQuery isn't maintained. Noticed a pretty significant reduction in memory usage:
Test tracker with old code (CsQuery) -> Memory jumped by 27MB
Test tracker with updated code (Anglesharp) -> Memory jumped by 17MB
Can someone try changing another tracker and see if they get similar results to make sure my testing method isn't flawed

**Comment by ngosang** [comment]
@junglebus that's an awesome find. I can confirm your results with IPTorrents.

Tracker IPTorrents, Start memory 54.24MB
| Search | CsQuery | Anglesharp |
|--------|---------|------------|
| harry  | 80.35 MB | 73.73 MB    |
| /empty/  | 84.16 MB | 74.56 MB    |

There is a speed improvement also => https://anglesharp.github.io/docs/Performance.html

I think we should remove CsQuery but there are 39 indexers using it. I can open an issue to keep the tracking, but I will need help to do the changes and testing.

**Comment by ngosang** [comment]
I'm testing the latest release without CsQuery and the results look good. In my installation with 50 trackers (4 of them were using CsQuery) the max memory is around 60 MB less, but it's soon to say.
If the results are right I will close this PR.

**Comment by cadatoiva** [comment]
After I get #7342 updated and pulled, my next refactor will help even more with the memory issue. Our `PerformQuery` functions return `IEnumerable<ReleaseInfo>` but almost all of them store that in a `List<ReleaseInfo` and return them all at once. Instead, we should be using `yield return` for lazy evaluation, returning individual results only as needed. This removes the temporary `List<>` allocation from memory, and allows the `PerformQuery` functions to pause/sleep between results. It also means that in cases when we aren't using the results (like testing during config or pressing test button) and just calling `Any()` to verify >0 results returned become enormously faster.

**Comment by ngosang** [comment]
I'm closing this. This problem can be solved gradually in other PRs.

**Pull request closed without merging**
