### PR TITLE
FNT Provider ~ Download HOTFIX & SSL

### PR DESCRIPTION
**Pull request by JigSawFr**
### Improvement of FNT Jackett's Provider,

> FNT is a French Private Tracker

Working as well, ready for using in a production environment.

> Changes

- [x] SSL enabled.

> Fixes

- [x] Unable to handle torrent downloading.

> Requested from:

* Issue https://github.com/Jackett/Jackett/issues/155

> This provider is part of the French Private Tracker's ROADMAP:

* Available at https://github.com/Jackett/Jackett/issues/145

*Updated with love,*
**Enjoy this provider for Jackett,**
JigSaw

### CODE REVIEW

**Comment by Bybou** [comment]
Tested and approved with love ;-)

**Comment by itdaboyz** [comment]
Working like a charm but tracker will close in 7 days. Sigh.

**Comment by Bybou** [comment]
Yes i heard that. So sad...

**Comment by raspdealer** [comment]
:(

**Comment by JigSawFr** [comment]
I will submit a delete PR in 7 days, sorry guys.

**Pull request merged**
