### PR TITLE
Update mononokebt.yml

### PR DESCRIPTION
**Pull request by xfouloux**
fix double tests

### CODE REVIEW

**Comment by xfouloux** [comment]
it seems to not work all the time.... it works on my pc, but not on my seedbox.... :/

**Comment by ilike2burnthing** [comment]
The path and error should also be removed.

The cookie is probably IP dependent.

**Comment by xfouloux** [comment]
I think there is something wrong with how jackett handle cookie somehow, using the form login it should work :/

**Comment by ilike2burnthing** [comment]
We'll publish this fix for now. If you're able to track down the issue then we can resolve it later.

**Comment by ilike2burnthing** [comment]
[v0.17.538](https://github.com/Jackett/Jackett/releases/tag/v0.17.538)

**Pull request merged**
