### PR TITLE
Feature/new api

### PR DESCRIPTION
**Pull request by chibidev**

### CODE REVIEW

**Comment by chibidev** [comment]
Sad. I didn't manage to delete more lines than I added :(

**Comment by flightlevel** [comment]
Awesome work @chibidev killing it

Your dev skils are way beyond mine, so can't provide much of a 'review' sorry

Did try running v1611 and am getting a 404 on the /Admin/Dashboard
Got to run now, but can have a closer look tomorrow if needed

```
07-23 12:10:20 Info Starting web server at http://*:9117/
07-23 12:10:20 Debug Web server started
07-23 12:10:24 Info redirecting to /Admin/Dashboard
07-23 12:10:24 Debug DefaultHttpControllerTypeResolver GetControllerTypes
System.Web.Http.Controllers: DefaultHttpControllerTypeResolver GetControllerTypes
07-23 12:10:24 Debug DefaultHttpControllerTypeResolver GetControllerTypes
System.Web.Http.Controllers: DefaultHttpControllerTypeResolver GetControllerTypes
07-23 12:10:24 Info   http://localhost:9117/Admin/Dashboard
System.Web.Http.Request:   http://localhost:9117/Admin/Dashboard
07-23 12:10:24 Info WebAPIRequestLogger SendAsync
System.Web.Http.MessageHandlers: WebAPIRequestLogger SendAsync

07-23 12:10:24 Debug GET: http://localhost:9117/Admin/Dashboard
07-23 12:10:24 Debug Body:
07-23 12:10:24 Info DefaultContentNegotiator Negotiate Type='HttpError', formatters=[JsonMediaTypeFormatterTracer, XmlMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer]
System.Net.Http.Formatting: DefaultContentNegotiator Negotiate Type='HttpError', formatters=[JsonMediaTypeFormatterTracer, XmlMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer]
07-23 12:10:25 Info XmlMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'XmlMediaTypeFormatter' for type='HttpError', mediaType='application/xml; charset=utf-8'
System.Net.Http.Formatting: XmlMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'XmlMediaTypeFormatter' for type='HttpError', mediaType='application/xml; charset=utf-8'
07-23 12:10:25 Info XmlMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'XmlMediaTypeFormatter' formatter
System.Net.Http.Formatting: XmlMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'XmlMediaTypeFormatter' formatter
07-23 12:10:25 Info DefaultContentNegotiator Negotiate Selected formatter='XmlMediaTypeFormatter', content-type='application/xml; charset=utf-8'
System.Net.Http.Formatting: DefaultContentNegotiator Negotiate Selected formatter='XmlMediaTypeFormatter', content-type='application/xml; charset=utf-8'
07-23 12:10:25 Info XmlMediaTypeFormatter WriteToStreamAsync Value='System.Web.Http.HttpError', type='HttpError', content-type='application/xml; charset=utf-8'
System.Net.Http.Formatting: XmlMediaTypeFormatter WriteToStreamAsync Value='System.Web.Http.HttpError', type='HttpError', content-type='application/xml; charset=utf-8'
07-23 12:10:25 Info XmlMediaTypeFormatter WriteToStreamAsync
System.Net.Http.Formatting: XmlMediaTypeFormatter WriteToStreamAsync
<Error><Message>No HTTP resource was found that matches the request URI 'http://localhost:9117/Admin/Dashboard'.</Message><MessageDetail>No route data was found for this request.</MessageDetail></Error>
07-23 12:10:25 Debug Response: <Error><Message>No HTTP resource was found that matches the request URI 'http://localhost:9117/Admin/Dashboard'.</Message><MessageDetail>No route data was found for this request.</MessageDetail></Error>
07-23 12:10:25 Info WebAPIRequestLogger SendAsync
System.Web.Http.MessageHandlers: WebAPIRequestLogger SendAsync
07-23 12:10:25 Info   Content-type='application/xml; charset=utf-8', content-length=202
System.Web.Http.Request:   Content-type='application/xml; charset=utf-8', content-length=202
```

**Comment by chibidev** [comment]
@flightlevel lol, thanks, man. I am requesting a review not just about the code itself, but you and @kaso17 have been maintaining Jackett for a longer time. This is a complete revamp of the web API, so I might break something that is not in code and you guys might have knowledge about. And I'm still fairly new to C# and ASP.NET.

Another thing I'd like your opinion about is whether this helps porting to .NET Core as it was my primary intention. I'd like to see Jackett taken out of ASP.NET and ditching mono in favor of Core.

I might have left intact the default redirect that takes you to the dashboard. I can take a look later today, however if you can jump in I appreciate that.

**Comment by chibidev** [comment]
Oh and one more thing. I added a button to be able to add public trackers with their default configuration. It wasn't requested, it seemed like a quick and easy win, but I want to hear your opinion about it. I am willing to take it out if necessary, it just made my life easier testing the API.

**Comment by flightlevel** [comment]
Killing it @chibidev !
Definitely think this will help with porting to .NET core
Would like to get Kaso to look it over before merging in

**Comment by chibidev** [comment]
@flightlevel thanks, man.

Yeah, I also would like @kaso17 to review this. It's a big monster so it won't be easy (sorry), however I consider this a good base for further improvements.

**Comment by flightlevel** [comment]
@kaso17 @chibidev 
Are we ready for a pre-release? Latest master seems to go alright for me, but I don't have a massive amount of indexers

**Comment by kaso17** [comment]
Will push a few more fixes, then push a pre-release in a few hours.

**Comment by chibidev** [comment]
@flightlevel most of my configured trackers are public ones, and I haven't encountered any issue with those during development.
One thing that I've been meaning to look into is the Cache headers of the js SDK. Upon development, Chrome often loaded it's cached version of common.js instead of what the server provided. If that's happening with others as well, they might have issues with Jackett after releasing this.

**Comment by kaso17** [comment]
Expect some issues caused by caching issues. It's common after such updates. Unfortunately I can't reproduce any caching issues. I never had any issues.

**Comment by flightlevel** [comment]
@chibidev @kaso17 Awesome work guys!
Just one little thing I noticed, the 'Apply server settings' button isn't working
Do we need to include jsonObject in the params at 1093 in custom.js

**Comment by chibidev** [comment]
@flightlevel darn, nice catch. Yep, it's missing from there, nice catch.

**Comment by flightlevel** [comment]
@chibidev done 0103c48c97780bb7c1182129fe5cd0494ca6fe24

**Pull request merged**
