### PR TITLE
Fix postman root path

### PR DESCRIPTION
**Pull request by arthurmelton**
#### Description
Postman was having some issues before because the request it would end up creating was 
`http://tracker2.postman.i2p/?view=Main&search=&category=-1&orderby=1&lastactive=-1&lang=-1`, this caused postman to hang. This fixes it so that it creates a request like 
`http://tracker2.postman.i2p/index.php?view=Main&search=&category=-1&orderby=1&lastactive=-1&lang=-1`, and that makes it work as expected.

### CODE REVIEW

**Comment by garfield69** [comment]
Thank you.

**Comment by arthurmelton** [comment]
I don't know if this is exactly the right place to ask, but I was wondering if this pr / d9562d57dea30dd25e59e722c80e68ed79c2c66e has to be added to Prowlarr, or if the update will just propagate?

**Comment by ilike2burnthing** [comment]
They merge our definitions with theirs periodically, could be a few hours to a few days.

**Comment by garfield69** [comment]
v0.22.260

**Pull request merged**
