### PR TITLE
[BUGFIX] Fix incomplete titles being returned by Partis indexer

### PR DESCRIPTION
**Pull request by RugeljGG**
Search results on Partis return shortened titles (40 chars), which makes it unusable with apps like Radarr / Sonarr which rely on title text for determining the type and quality. This is fixed by looking at sub-pages of individual releases, which contain full titles.

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
Thanks for your contribution, but unfortunately this change makes 40 additional requests to the site (or whatever number of results you get), which is a quick way to get your account flagged for bot activity (as well as taking ~40 times longer to get results).

What some other trackers do is have the full title in the mouse over tooltip, or even just hidden in the HTML. You may need to contact the site maintainers/admins to see if they're willing to add that to the results page.

**Comment by RugeljGG** [comment]
I agree, it's a nasty workaround. Unfortunately there's no sign of full titles anywhere in the HTML, so I don't see any other way.

I was thinking about making it an optional parameter (i.e. you would choose in tracker settings if you want this enabled or not), would that be preferable?

**Comment by ilike2burnthing** [comment]
It's not something I'd want to include, even as an option, even if said option had a warning, as it will get users banned, especially if they're making 41 requests every 30mins (or 15mins if they change/disable the cache and are using Sonarr).

I'll message the site maintainers to see if they'll add the full title somewhere.

**Comment by RugeljGG** [comment]
Ok, thank you for looking into it. If you get any information, I'd love if you'd let me know.

**Comment by ilike2burnthing** [comment]
Will do, I'll just leave this open for now as a reminder.

**Comment by ilike2burnthing** [comment]
Partis has since been removed from Jackett as it's been down for nearly 3 months due to the OVH fire.

They never got back to me, but if they do come back and are re-added to Jackett, I'll try reaching out again.

**Comment by FileGo** [comment]
Partis seems to be back online, is there any chance to support it again?

**Comment by garfield69** [comment]
@FileGo  The new site's engine is different from the old one and the old indexer cannot even reference the login page.
Since none of the current team have an account on this site:
If you want Partis added to Jackett the please raise a request [here](https://github.com/Jackett/Jackett/issues/new?assignees=&labels=&template=indexer-request.yml&title=%5Breq%5D%3A+) and provide instructions on how to register or provide an invite if that is the only way to join.
Thanks.

**Comment by garfield69** [comment]
@FileGo  never mind, see #1596

**Pull request closed without merging**
