### PR TITLE
morethantv: add imdb search and others category

### PR DESCRIPTION
**Pull request by ngosang**
* Add IMDB search
* Add Others category

Part of #4859

### CODE REVIEW

**Comment by ngosang** [comment]
@RoloSoze ping

**Comment by RoloSoze** [comment]
#6783 Related :)

**Comment by ngosang** [comment]
> does the site provide imdb in some of the results?

Nop

**Comment by RoloSoze** [comment]
@garfield69 I mentioned this to @ngosang already but thought I'd mention it to you as well just to keep it on record: 

The IMDb ID search support in MTV only works if you search using the ID in the Torrent description search box (on the website). It's not 100% reliable since it only works if the uploader chooses to insert the IMDb link in the description.

However, in Jackett, I think the option of searching the 'Torrent description' should only be enabled when the query is done using IMDb ID. Enabling it for all searches would likely return a ton of irrelevant results.

Also, the IMDb link, if & when it's available, only shows up in the body of the description but not next to the torrent's name, so I'm not sure if the link can be shown in Jackett.

**Comment by ngosang** [comment]
It's implemented as you say.

**Pull request merged**
