### PR TITLE
manage Microsoft logs by NLog

### PR DESCRIPTION
**Pull request by aureliensauv**
Microsoft logs are now correctly log by NLog.
By default, these are deactivated for service log.
You can set tracing enabled option or Enhanced logging to true for log again.

### CODE REVIEW

**Comment by flightlevel** [comment]
@aureliensauv 
I like your idea
Have you tested it?
I suspect it will remove Microsoft.* logs when viewed via the 'Logs' button on the Jackett dashboard, but Microsoft.* logs will still be present on the console(systemd) and in log text file?
Is that your intention?
I think ideally it should remove Microsoft.* logs from all the logging targets if the level is Info or less (i.e warning and above still retained)

**Comment by aureliensauv** [comment]
Thanks.
Yes, my first intention it was only cleaned logs via 'logs' button.
But i'm agree with you, ideally all targets logs needs the same operation.
Currently the solution works nicely on my fork.

**Comment by aureliensauv** [comment]
I will try to found something for  extend this solution to all targets.

**Comment by aureliensauv** [comment]
All microsoft logs are cleared by default in all targets (only under warn level).
Working perfectly after merge!

**Comment by kaso17** [comment]
looking fine to me, merging and releasing a pre-release

**Pull request merged**
