### PR TITLE
Feature/autofac tidyup

### PR DESCRIPTION
**Pull request by NathanNZ**
# Autofac Tidyup

Just pushing in some of the changes I've been working on mainly regarding autofac.

This doesn't include the removing of reflection for the indexers (as that's a big change and probably should be done just by itself) 

## Misc Changes
- Bumping versions, now running the latest stable version of Autofac.  
- Removed the Owin WebAPI Autofac package as we were not actually using the extension methods it supplies and it doesn't seem to be maintained anymore.
- Doing best practice in the form of immutable DI containers as rebuilding containers is being culled from the next version of autofac. This might break some things if we have depended on lazy evaluation or late loading of modules into our container, but I've looked through the code and have not seen anything that really uses this and things still seem to work fine across the board - so I'm putting it down to possibly legacy reasons that this was implemented this way.

## Module Changes
We have two new modules!

- **JackettModule**
The module that does the dependency injection for most of the services. This also registers the interfaces that other modules might implement in the Jacket.Common project.

- **WebApi2Module**
The module that implements the WebAPI2 functionality for .NET Framework code. It registers specific implementations and functionality required only for .NET Framework

In the future we'll probably have another one for .NET Core and possibly one for testing or specific operating systems. Have not thought further than .NET Core at this stage 👍 

## Other changes
I've gone and moved content and resources into the big shared project. Will be useful in the future to share assets and interfaces between .NET Framework and .NET Core, small and steady changes seem to be the way to go - will look at cleaning up the front end in future ✨

### CODE REVIEW

**Comment by NathanNZ** [comment]
Also apologies for the commits where I wrote "Autoface" or "Jacket". Case of the fingers typing faster than I can think 😃

**Comment by kaso17** [comment]
This cause some run time null pointer exceptions for me due to Engine.Logger calls before Engine.container was initialized.
Fixed via 06c47ec10a671af37fc0156806f86cc9ed08ec86 and 4cd01433b742f40e9d208e4e7547ebe3d10f9a1a

**Comment by kaso17** [comment]
updater also needs autofac: b040187c3f7842ecb3d3592035f7a17cf6c6df7c

**Comment by wesleycombs** [comment]
Thanks for the fix. I am attempting run Jackett on Windows Server 2012 and kept running into the Jackett Tray crash. Will a new installer be posted soon? I apologize if that is a dumb question - it's my first time following an issue on GitHub.

**Comment by kaso17** [comment]
@wesleycombs you can try the v0.8.393 pre-release

**Comment by wesleycombs** [comment]
@kaso17 thank you. I can confirm the problem is fixed in v0.8.396

**Comment by NathanNZ** [comment]
Hmmm sorry about that @kaso17 , did some dry runs before I pushed the code so not sure how I missed those null exceptions 😕 

Will see if I can get some integration tests working sometime to remove the human element of those kind of basic sanity tests.

**Pull request merged**
