### PR TITLE
Better reverse proxy support

### PR DESCRIPTION
**Pull request by tehjojo**
This fixes support for putting Jackett behind a reverse proxy. 

Tested fully with my setup of Jackett living behind a HTTPS proxy via "my-example-site.com/jackett/".

Redirects and download links work correctly with newly added "Base Path Override" configuration option. For my example site, it would be "jackett".

### CODE REVIEW

**Comment by JigSawFr** [comment]
Great :+1:

**Comment by raspdealer** [comment]
Thanks!!

**Comment by PartTimeLegend** [comment]
ACK

**Comment by Azerelat** [comment]
I fixed several issues, check it still works for you.

**Pull request merged**
