### PR TITLE
[enhancement] [webui] Add status update to document.title during and after search in webui

### PR DESCRIPTION
**Pull request by vonvenera**
#### Description
Add status update to document.title during and after search in webui

#### Screenshot (if UI related)
image

### CODE REVIEW

**Comment by garfield69** [comment]
I personally do not see the point of this.
All the information you need is on the dashboard search page, while the search is on progress and after the search is completed. I've never looked up at the browser tab label and thought "that needs a status right there", when the page below is providing all the info you need of the progress and results.
@mynameisbogdan  opinion?

**Comment by vonvenera** [comment]
useful if you have multiple tabs with autoreaload searches open

**Review by garfield69 — CHANGES_REQUESTED** [review]
Please also update index.html.
Near the bottom you will find the script link for custom.js, please change the stamp so that it forces browser cache to load afresh

**Review by garfield69 — APPROVED** [review]

**Comment by garfield69** [comment]
tested on firefox, edge, opera, vivaldy and chrome.
LGTM

**Comment by garfield69** [comment]
v0.21.1832

**Pull request merged**
