### PR TITLE
Fixed rutracker title formatting for TV series without metadata

### PR DESCRIPTION
**Pull request by serge1peshcoff**
When the TV series torrent doesn't have a metadata in the title, it doesn't match the regexp schema, so I've fixed this by making the $5 group optional.

I don't know how to test it properly as I don't have windows, but I've checked it this way:

```
sh-3.2$ cat ~/Documents/test.cs
using System.Text.RegularExpressions;


var regex = new Regex(".+\\/\\s([^а-яА-я\\/]+)\\s\\/.+Сезон\\s*[:]*\\s+(\\d+).+(?:Серии|Эпизод)+\\s*[:]*\\s+(\\d+-*\\d*).+,\\s+(.+)\\][\\s]?(.*)");
var format = "$1 - S$2E$3 - rus $4 $5";

var oldRegex = new Regex(".+\\/\\s([^а-яА-я\\/]+)\\s\\/.+Сезон\\s*[:]*\\s+(\\d+).+(?:Серии|Эпизод)+\\s*[:]*\\s+(\\d+-*\\d*).+,\\s+(.+)\\]\\s(.+)");


Console.WriteLine("Old regex:");
regex.Replace("Чёрное зеркало / Black Mirror / Сезон: 5 / Серии: 1-3 (3) (Оуэн Харрис, Карл Тиббеттс, Отто Баферст) [2019, Великобритания, фантастика, триллер, драма, WEBRip 1080p] DVO (Кубик в Кубе) + Original + Sub (Rus, Eng)", format);
regex.Replace("Эпидемия / To the Lake / Сезон: 1 / Серии: 1-8 из 8 (Павел Костомаров) [2019, драма, фантастика, триллер, WEBRip 720p]", format);

Console.WriteLine("New regex:");
oldRegex.Replace("Чёрное зеркало / Black Mirror / Сезон: 5 / Серии: 1-3 (3) (Оуэн Харрис, Карл Тиббеттс, Отто Баферст) [2019, Великобритания, фантастика, триллер, драма, WEBRip 1080p] DVO (Кубик в Кубе) + Original + Sub (Rus, Eng)", format);
oldRegex.Replace("Эпидемия / To the Lake / Сезон: 1 / Серии: 1-8 из 8 (Павел Костомаров) [2019, драма, фантастика, триллер, WEBRip 720p]", format);

sh-3.2$ csharp ~/Documents/test.cs
Old regex:
"Black Mirror - S5E1-3 - rus WEBRip 1080p DVO (Кубик в Кубе) + Original + Sub (Rus, Eng)"
"To the Lake - S1E1-8 - rus WEBRip 720p "
New regex:
"Black Mirror - S5E1-3 - rus WEBRip 1080p DVO (Кубик в Кубе) + Original + Sub (Rus, Eng)"
"Эпидемия / To the Lake / Сезон: 1 / Серии: 1-8 из 8 (Павел Костомаров) [2019, драма, фантастика, триллер, WEBRip 720p]"
```

### CODE REVIEW

**Review by garfield69 — APPROVED** [review]
tested, LGTM

**Comment by garfield69** [comment]
Thanks.

**Comment by serge1peshcoff** [comment]
@garfield69 which version this commit would be included in?

**Comment by garfield69** [comment]
The one published 3 hours ago, 0.16.2124 ;-)

**Comment by serge1peshcoff** [comment]
lovely, thanks!

**Pull request merged**
