### PR TITLE
Update speed-share.yml

### PR DESCRIPTION
**Pull request by Guizzoni**
Added missing categories, release date, release type. 
Fixed some errors, and removed some useless strings.

 _**Unfortunately the indexer shows non scene resolutions like "848x480; 1920 x 960" and i wasn't able to translate that to "480p; 720p" because there are so many different resolutions. If someone could help me with that, i'd be glad.**_

### CODE REVIEW

**Comment by kaso17** [comment]
I suggest you ask if someone can help with a resolution list in the issue.

**Comment by kaso17** [comment]
Or maybe just strip the first (horizontal resolution) part and add a "p" using a regex
848x480 => 480p
1920 x 960 => 960p
...

**Comment by Guizzoni** [comment]
@kaso17 
If i do that then we would have odd resolutions like 536p... Would Sonarr even detect that?

**Comment by kaso17** [comment]
Looking at https://github.com/Sonarr/Sonarr/blob/58d158a5dcb125ae591ae40a63565514425bd144/src/NzbDrone.Core/Parser/QualityParser.cs#L43 it doesn't
You probably need more (re_)replace filters.

**Pull request merged**
