### PR TITLE
4K quality Fix for Rutracker serials Title

### PR DESCRIPTION
**Pull request by denozord**
Fix 4k quality in the naming of TV series for Sonarr parsing

### CODE REVIEW

**Comment by garfield69** [comment]
can you please provide a search example that would make use of this so I can do a PR review? thanks.

**Comment by ilike2burnthing** [comment]
If you search that new category you should find plenty of examples like:
`Stranger Things /​ : 3 /​ : 1-​8 8 [2019, HEVC, HDR, WEB-​DL, 2160p, 4K]`
or in UHD music videos (UHD музыкальное видео):
`[MV, PV] LOONA – 4K ( 18 ) [2017-​2021, KPop, UHDTV, UHD 2160p, 4K]`

**Comment by garfield69** [comment]
well, since you are here, you might as well review and merge ;-)

**Review by ilike2burnthing — COMMENTED** [review]
@denozord it seems the TV UHD category missing was the only thing preventing the regex title fixes. With that now added and your fix removed, the earlier example is now:
`Stranger Things -​ S3E1-​8 -​ rus 4K Dub + Original + Sub (Rus, Eng)`

Unless you know of any other examples causing an issue we can just merge the missing category.

**Comment by denozord** [comment]
Sonarr
This is how it looks on the distribution, which is not in the UHDTV category.
I suggest leaving 2 changes: both mine and yours :)
It's just that 4K Sonarr doesn't define it as 2160p

**Comment by denozord** [comment]
изображение
Correct parsing looks like this

**Comment by garfield69** [comment]
v0.18.786

**Pull request merged**
