### PR TITLE
Cinematik date parse

### PR DESCRIPTION
**Pull request by adamwinn**

### CODE REVIEW

**Comment by flightlevel** [comment]
@adamwinn Did this get fixed with https://github.com/Jackett/Jackett/commit/daf2ea202c433958a18564b6afe0e14a59e0db28 or was this meant to be an extra fix?

**Comment by adamwinn** [comment]
Ya I'm not sure what happened here.  These are my first github contributions; I'm used to working on projects at work where I have rights to merge to master.  

I did a 
```
git pull upstream master
```
and it wanted me to merge the changes I picked up from the parent repo.  Do you know what the proper workflow is?

**Comment by flightlevel** [comment]
Kaso is the guru on this stuff...
But what I usually do , pull the latest master into my fork, create a branch from the master eg bugfix, commit my changes to bugfix branch, then on the github webpage it will offer to create a pull request for you into upstream master from your bugfix branch, stops all the commits building up in the PR

**Comment by flightlevel** [comment]
and you should have merge rights now, did you get the invite?

**Comment by adamwinn** [comment]
@flightlevel ya, that's exactly what I do too.  Except later on, then my fork says I'm "X number of commits behind" so then I run "git pull upstream master" and after it pulls in the changes from Jackett master, it wants me to push them again.  I don't know why.  Oh, maybe I didn't have the master branch checked out when I ran "git pull upstream master".  I'll keep an eye on it next time I do a fix.

Yes, i got the invite but I couldn't commit to master tho.  And I do like doing PR's instead too.

**Comment by kaso17** [comment]
You probably have to rebase your local master + new branch first.
See:
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Pull request closed without merging**
