### PR TITLE
issue template: change to github issue form

### PR DESCRIPTION
**Pull request by ilike2burnthing**
Apologies for the commit mess, had to use the master branch for it to take effect on my fork. Removed the bots for now, they were just using default settings, and we'd need to retire jackettbot as well

### CODE REVIEW

**Comment by garfield69** [comment]
>and we'd need to retire jackettbot as well

do you mean https://github.com/Jackett/Issue-Bot or has that been obsolete for a long while now and something else is managing the issues?

**Comment by garfield69** [comment]
v0.18.755

**Comment by ilike2burnthing** [comment]
I think it and https://github.com/organizations/Jackett/settings/apps/jackettbot/ are separate beasts, with Issue-Bot just being a long abandoned first attempt.

**Comment by garfield69** [comment]
so you think I can delete that issuebot repo altogether to prevent confusion?
what about the *.md files at https://github.com/Jackett/Jackett/tree/master/.github, can they go too?

**Comment by ilike2burnthing** [comment]
I'd doublecheck with @ngosang first.

**Pull request merged**
