### PR TITLE
Fix siambit unlimitz and bitded category and description

### PR DESCRIPTION
**Pull request by showkubii**

### CODE REVIEW

**Review by ilike2burnthing — COMMENTED** [review]
Looks fine, but I'll let @garfield69 check as they have accounts for those trackers.

A question though, why the change from `Movies` to `TV`?

**Comment by showkubii** [comment]
> Looks fine, but I'll let @garfield69 check as they have accounts for those trackers.
> 
> A question though, why the change from `Movies` to `TV`?

I'm Thai and it's the right category.

**Comment by ilike2burnthing** [comment]
Is there an issue with the translations then? I would have assumed `Movie Packs` would be movies.

**Comment by showkubii** [comment]
> Is there an issue with the translations then? I would have assumed `Movie Packs` would be movies.

มันคือทีวี

It is TV.

**Review by garfield69 — APPROVED** [review]

**Comment by garfield69** [comment]
Thank you.

**Comment by garfield69** [comment]
v0.20.2459

**Pull request merged**
