### PR TITLE
danishbytes: migrated to cs

### PR DESCRIPTION
**Pull request by seeyabye**
Migrated from yaml to c# and using API as the search endpoints.

The API is a little clunky as I inspected the code for UNIT3D. It doesn't support sorting, which means results from filtering can be very old and dated. It also has a limitation of returning 15 results whereas, without filters, it could return 25. 

Resolves https://github.com/Jackett/Jackett/issues/11857

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
@piratkongen are the sorting and limit issues resolvable on your end?

**Comment by seeyabye** [comment]
Should be resolved in https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/1803. I have not tested this myself though.

Danishbytes probably just needs to update to the latest version.

**Comment by piratkongen** [comment]
Sorting by latest has now been introduced, and the limit has been increased to 100.

**Comment by seeyabye** [comment]
I've updated the code to support v2 filters.

**Comment by ilike2burnthing** [comment]
Thanks, this works well

**Pull request merged**
