### PR TITLE
Fix thepiratebay.xml for General Hospital

### PR DESCRIPTION
**Pull request by JimboMonkey1234**
The only uploader on TPB for General Hospital puts a space between season and episode. This change adjusts the query term for this, so "S01E02" becomes "S01E02 | (S01 E02)", searching both formats in case someone starts uploading with the standard format.

### CODE REVIEW

**Comment by flightlevel** [comment]
Not a massive fan of this one, fine to put in your personal install, but how far do we go with individual shows, any thoughts others?

**Comment by kaso17** [comment]
We've similar hacks for specific shows in some other tracker definitions. I'm ok with it.
@JimboMonkey1234 can you please add a comment (e.g. your PR description) into the definition file itself?

**Comment by JimboMonkey1234** [comment]
@kaso17 added comment

**Comment by JimboMonkey1234** [comment]
Also, @flightlevel for future reference, is there an easy way to include this in my personal install? That's what I did for about a little while, but Jackett's auto-updating kept undoing it.

**Comment by flightlevel** [comment]
Thanks @JimboMonkey1234 
When you start Jackett it will show directories other than your install directory where it will look for definitions
eg. last line
```
08-12 16:15:56 Info App config/log directory: C:\ProgramData\Jackett
08-12 16:15:56 Info Starting Jackett 0.0.0.0
08-12 16:15:56 Info Environment version: 4.0.30319.42000 (C:\Windows\Microsoft.NET\Framework\v4.0.30319\)
08-12 16:15:56 Info OS version: Microsoft Windows NT 6.2.9200.0 (64bit OS)
08-12 16:15:56 Info ThreadPool MaxThreads: 2047 workerThreads, 1000 completionPortThreads
08-12 16:15:56 Info Using HTTP Client: HttpWebClient
08-12 16:15:57 Info Loading Cardigann definitions from: C:\Users\..............................
```

**Comment by JimboMonkey1234** [comment]
Thanks (for the hint and for merging)! I'll try messing around with adding definition files.

**Pull request merged**
