### PR TITLE
Add certificate hash for tasmanit.es

### PR DESCRIPTION
**Pull request by gotson**
Tasmanit.es certificate expired on 24 Jan 2022

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
I'm not getting an invalid cert, rather I'm seeing:
Screenshot 2022-02-15 143526

**Comment by ilike2burnthing** [comment]
Thanks

**Comment by garfield69** [comment]
v0.20.573

**Comment by gotson** [comment]
works like a charm, thanks!

**Pull request merged**
