### PR TITLE
Fixes #1606 

### LINKED ISSUE #1606: TorrentPotato doesn't find torrents
Jackett version:  0.7.1622.0
Installed with Docker 
https://hub.docker.com/r/linuxserver/jackett/
-------------------------------

All queries from TorrentPotato return with empty data:
```
07-30 20:59:19 Info Found 0 torrentpotato releases from Torrent9 for: Risen 2016
07-30 20:59:20 Info Found 0 torrentpotato releases from YGGtorrent for: Risen 2016
07-30 20:59:21 Info Found 0 torrentpotato releases from The Pirate Bay for: Risen 2016
07-30 20:59:22 Info Found 0 torrentpotato releases from Sky torrents for: Risen 2016
```
With no error in CP logs and a good looking query:
```https://xxx.xx/potato/thepiratebay?imdbid=tt3231054&search=Risen+2016&user=&passkey=xxx```

Whereas Manual searchs and Torznab in Radarr work fined
```
07-30 21:04:35 Info Found 30 releases from The Pirate Bay for: risen 2016
07-30 21:04:36 Info Found 30 releases from The Pirate Bay for: risen 2016
07-30 21:04:42 Info Found 29 releases from The Pirate Bay for: resurrection 2016
07-30 21:04:43 Info Found 0 releases from The Pirate Bay for: clavius 2016
```

I tried to update Jackett as it says in this issue [1573](https://github.com/Jackett/Jackett/issues/1573), but it solves nothing :/

Here my ServerConfig.json :
```
{
  "Port": 9117,
  "AllowExternal": true,
  "APIKey": "xxx",
  "AdminPassword": "",
  "InstanceId": "qsdekcklr6xa2faaxtaftccqtxojsv118p0koh3hze8y67s94g4estn9djpqm16i",
  "BlackholeDir": "",
  "UpdateDisabled": true,
  "UpdatePrerelease": true,
  "BasePathOverride": "",
  "OmdbApiKey": ""
}
```

### PR DESCRIPTION
**Pull request by NitriKx**
Since we check if the indexer can handle the query with the `CanHandleQuery` method, the TorrentPotato requests that specifies the `imdbid` are not executed if the indexer does not support ImdbId search (`caps.SupportsImdbSearch == false`).

I've also fixed the movie requests which only have the `imdbid` parameter and a valid OMDB Api Key.

Related issue: #1606

### CODE REVIEW

**Comment by kaso17** [comment]
Can you fix the conflict please?
Otherwise it looks fine and we should release it as test release and see if it causes trouble somewhere else.

**Comment by NitriKx** [comment]
Oops I missed that the PotatoController has been removed, I'm doing the merge

**Comment by NitriKx** [comment]
Conflit fixed

**Comment by chibidev** [comment]
@NitriKx PotatoController was recently removed, functionality has been moved to another controller. The PR right now contains an unused PotatoController, modification to that should be re-introduced in ResultsController.

**Comment by kaso17** [comment]
yes, the old PotatoController was removed.
You probably have to make your change in here: https://github.com/Jackett/Jackett/blob/master/src/Jackett/Models/DTO/TorrentPotatoRequest.cs

**Comment by NitriKx** [comment]
Ok thanks, I've updated the PR.

**Comment by NitriKx** [comment]
Done

**Comment by flightlevel** [comment]
Thank you @NitriKx

**Pull request merged**
