### PR TITLE
Add PTP as a new Indexer

### PR DESCRIPTION
**Pull request by Codehhh**
Tested and working! If any changes need to be made let me know

### CODE REVIEW

**Comment by flightlevel** [comment]
@Codehhh Thanks, great commit. Now included in latest release

**Comment by theotherp** [comment]
Wouldn't it be better to use the ReleaseName as title? As it is now you get a list of different releases, all with the movie title as title. That's not very helpful or informative.

**Comment by Codehhh** [comment]
Good catch! I changed it on my fork. Let me know how it works.

**Comment by theotherp** [comment]
Would like to test it but have no build environment. Could you please create a release and a new PR for the change?

**Pull request merged**
