### PR TITLE
AnimeBytes Add option to add a release based on filename

### PR DESCRIPTION
**Pull request by timothy-adam**
https://github.com/Jackett/Jackett/issues/13631#issuecomment-1270836655

### CODE REVIEW

**Review by ilike2burnthing — APPROVED** [review]
Assuming you've tested this, then it looks fine.

**Comment by ilike2burnthing** [comment]
@garfield69 any point tagging people to test?

**Comment by garfield69** [comment]
what about the existing code that generates a row from the group section that has single torrents... surely if AddFileNameTitles  is enabled, then those users are going to get duplicate torrents, one from the group name code, and another under the filename code?

**Comment by timothy-adam** [comment]
> what about the existing code that generates a row from the group section that has single torrents... surely if AddFileNameTitles is enabled, then those users are going to get duplicate torrents, one from the group name code, and another under the filename code?

I don't know? Isn't that the whole point of all those extra options, to add duplicate, but differently named releases?

This works, and I'm not noticing any double duplicates of the  AddFileNameTitles  releases.

brave_2022-10-06_21-15-44

**Comment by garfield69** [comment]
ok, well we shall see if we get any feedback once published. Thanks.

**Pull request merged**
