### PR TITLE
Travis CI - The Beginning 

### PR DESCRIPTION
**Pull request by PartTimeLegend**
Any decent sized project should have CI, so I've created a basic .travis.yml for this project.

Currently the build fails, I don't have a Windows machine to try it out with though.

### CODE REVIEW

**Comment by JigSawFr** [comment]
Total agree with you, need to be implemented !

**Comment by flightlevel** [comment]
What's the advantage of using Travis compared to our current AppVeyor setup?
Currently every pull request or merge goes through the entire build process (even creating the installer) exactly the same as a release. If you look for the red crosses under closed PRs you can see the ones it caught.
For details on where a PR is failing you can click details for more info
eg.Details 
eg. Details of your PR https://ci.appveyor.com/project/camjac251/jackett/build/0.7.123
It was failing Travis on just one filename due to the casing, wasn't causing a problem as the build occurs on Windows. Fixed now

**Comment by JigSawFr** [comment]
@flightlevel Yes Appveyor is great, but it was missing in last PR for unknown reason.... (Just reactivated ?). I know that Travis CI can do code analysis to force respect of somes rules or good practices, not available now with Appveyor, or misconfigured ?

**Comment by PartTimeLegend** [comment]
AppVeyor does not show on the pull request, whilst Travis has hooks directly into GitHub.

Also whilst Travis CI doesn't have brilliant C# integration, it is improving and it already identified a problem with the system that AV had not spotted. This might seem like a small issue, but for those compiling against mono it is a show stopper.

Two build and test systems, help find more issues and provide a better UX.

**Comment by JigSawFr** [comment]
@PartTimeLegend Appveyor work same as Travis on github, but it was deactivated i think, with my first PR, i could see AppVeyor, and on latest PR, it was reactivated (or shown to public)

**Comment by PartTimeLegend** [comment]
This is therefore either a discussion of apples and oranges or belt and braces.

I think as Travis CI identified a bug, and implementing it is simple it would be worth having the two run in parallel. Measure twice, and cut once I was always taught in woodwork.

**Comment by PartTimeLegend** [comment]
Also for clarification on how far Travis has come with CI for .NET Projects we used to do silly things like this.

`language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console

script:
  - xbuild BitcoinExchangeAutoHacker/BitcoinExchangeAutoHacker.sln`

**Comment by flightlevel** [comment]
Not sure why the integration between AppVeyor & Github wasn't working for those three days? It was still firing the build process but just not showing up on github. Looks good now, will keep an eye on it.
For now I think its best sticking with one CI, can revisit at a later date if C# improves on Travis

**Pull request closed without merging**
