### PR TITLE
Added option to normalize release name [Ygg]

### PR DESCRIPTION
**Pull request by Khogniak**
Hello,

Many peoples are experiencing problems with french release names in which the date is not always right behing the movie titles.
So I added an option (disabled by default), to normalize names :

**[Option disabled]**

**[Option enabled]**

### CODE REVIEW

**Comment by kaso17** [comment]
Did you try making the regex case insensitive instead of calling tolower?

**Comment by Khogniak** [comment]
I wanted to, but can not find how to make it incensitive.

Tried :
``
["/^(?:(.+?)((?:[\\.\\-\\s_\\[]+(?:imax|(?:dvd|bd|tv)(?:rip|scr)|bluray(?:\\-?rip)?|720\\s*p?|1080\\s*p?|vof?|vost(?:fr)?|multi|vf(?:f|q)?[1-3]?[1-3]?|(?:true)?french|eng?)[\\.\\-\\s_\\]]*)*)([\\(\\[]?(?:20|1[7-9])\\d{2}[\\)\\]]?)(.*)$|(.*))$/i", "$1 $3 $2 $4 $5"]
``
But it doesn't worked and wiki is incomplete. I already had to check in the code to find the trim & tolower functions :)

**Comment by kaso17** [comment]
Try adding `(?i)` to the beginning.

**Comment by Khogniak** [comment]
You learnt me something

Ty

**Comment by kaso17** [comment]
thank you

**Pull request merged**
