### PR TITLE
[ToTheGlory] Implement Gamez&Warez search

### PR DESCRIPTION
**Pull request by zenof**
Close: #8885

### CODE REVIEW

**Comment by garfield69** [comment]
@RoloSoze  please test. in particular, since you don't currently have access to c=G, try a keywordless search with a cat set to one or more of [1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070, 1080, 1090, 1100, 1110, 1120, 1130, 1140, 1150, 1160, 1170, 1180, 4000, 4010, 4020, 4030, 4040, 4050, 4060, 4070, 7000, 7010, 7020, 7030, 7040, 7050, 7060] to see what happens.
also test regular searches from the c=M set.

**Comment by RoloSoze** [comment]
@garfield69 I will as soon as I'm able to resolve #8903

**Comment by RoloSoze** [comment]
@garfield69 The error was fixed via b570b1d in 0.16.643. It might be best if you merge this PR and let me test it with the next release because I can't test it on an older version.

**Comment by garfield69** [comment]
@RoloSoze  I've brought this PR up to date with master so the new artefacts contain the 8903 fix.
Download the latest artefact from this PR and you should be able to test this PR indexer. Thanks.

**Comment by RoloSoze** [comment]
@garfield69 Searching the normal categories works as expected. Searching any of the class-restricted categories you mentioned returns 0 results, as expected. 

On TTG's website, if an unqualified user tries to browse the class-restricted categories via https://totheglory.im/browse.php?c=G, a message is displayed in Mandarin that translates to: 

`The user level is not enough, you cannot browse this page!`

**Comment by garfield69** [comment]
did you check the jackett log after a keyworldless search or a search for c=M torrents, are there any errors generated ?

**Comment by RoloSoze** [comment]
> 
> 
> did you check the jackett log after a keyworldless search or a search for c=M torrents, are there any errors generated ?

I did. None that I've noticed.

**Comment by garfield69** [comment]
Thank you.

**Pull request merged**
