### PR TITLE
iptorrents: added pagination

### PR DESCRIPTION
**Pull request by seeyabye**
Resolves https://github.com/Jackett/Jackett/issues/11532

Pagination is missing which only resulted in 50 results returned at the maximum. This PR includes pagination support for IPTorrents.

### CODE REVIEW

**Comment by seeyabye** [comment]
Thanks for the feedback and my apologies for not testing carefully.

I've included a limit when no keyword searches are given, which should just load the first page.
I'm still unsure why this pagination was not coded in the first place, perhaps it could have been missed out.

**Comment by garfield69** [comment]
The optimal method is for Jackett to make ONE request to the site, and for the site to return up to 100 torrents. Note 100 is a goal not a requirement. 
We usually avoid making multiple requests at one time to a site, and usually cap the request to no more that 5 to avoid spamming.
this site has an site account setting option to return a max of 100 torrents in one request so it appears to me that pagination is not required.
What am I missing?

**Comment by seeyabye** [comment]
I think if we do not include pagination, we are unable to obtain more than 100 torrents. I'm not certain if there's a hard limit that the number of torrents Jackett will return, but so far I'm aware of it.

Issue https://github.com/Jackett/Jackett/issues/11532 demonstrates the issue when pagination is absent. In the worst case, the user only obtains 50 (out of 607) results. If IPTorrent's account setting is set to return a max of 100 (out of 607) torrents in one request, we are still missing out 507 torrents.

I just checked if I could set IPTorrents to return more than 100 torrents per page, but it appears to be the maximum limit.

**Comment by ilike2burnthing** [comment]
The same issue occurs if you search for something common like `720p`.

As far as I'm aware (correct me if I'm wrong), Sonarr et al only use the first 100 results anyway.

**Comment by seeyabye** [comment]
There are some indexers in Jackett that have implemented pagination (https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/Abnormal.cs https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/DivxTotal.cs).

Anyway, I'll leave the merging decision to you.

**Comment by garfield69** [comment]
pagination is used on divxtotal because the site only returns 15 torrents per page, so we make 3 requests to try and get at least 45. Likely something similar is done with abnormal for a similar reason.
The goal is not to return 607 torrents, this first 100 is plenty enough.

**Comment by element4l** [comment]
I am a little confused at the purpose of jackett if it's not going to return all the results from my searches. You have set an arbitrary limit of 100, when there are clearly reasons to return more than 100 results.

**Comment by ilike2burnthing** [comment]
> Jackett works as a proxy server: it translates queries from apps (Sonarr, Radarr, SickRage, CouchPotato, Mylar, Lidarr, DuckieTV, qBittorrent, Nefarious etc.) into tracker-site-specific http queries, parses the html response, then sends results back to the requesting software. This allows for getting recent uploads (like RSS) and performing searches. Jackett is a single repository of maintained indexer scraping & translation logic - removing the burden from other apps.

https://github.com/Jackett/Jackett#jackett

Jackett has never been a full replacement for searching a tracker on its own site. As shown above, depending on the tracker and what you search you could end up with hundreds or thousands of results across many pages, each of which has to be fetched separately. That could mean you end up with 10, 50, 100, or more requests to a site in quick succession, an easy way to get your IP marked for bot activity, or account suspended (or for smaller sites, quickly cripple them when suddenly thousands of people are making dozens of requests every 15mins).

For many indexers we allow users to configure whether they want to request the most/least recent, most/least seeded, or largest/smallest results from the tracker for any particular search term, and for private trackers whether to look for freeleech torrents only or not; so 100 results suited to your needs is likely going to be more than enough. In the few cases where it isn't (e.g. you want every individual episode of a 20 season program), then yes you will have to go to the site directly for that, though best of luck finding even 100 that are still alive.

**Pull request closed without merging**
