### PR TITLE
ArcheTorrent - Better search

### PR DESCRIPTION
**Pull request by elliotvr**

### CODE REVIEW

**Comment by garfield69** [comment]
when I set up a definition that added plus to the keywords, kaso17  recently suggested the following:
```yaml
    keywordsfilters:
      - name: replace
        args: ["-", " "] # remove special search character (negative search)
      - name: replace
        args: ["+", " "] # remove special search character (positive search)
      - name: re_replace
        args: ["(\\w+)", " +$1"] # prepend + to each word
``
I think you should do the same.

**Comment by kaso17** [comment]
@elliotvr thank you.
I assume you want to prepend a "+" to all keywords?
With your solution this won't happen to the first keyword.
The code from garfield's comment might be more suitable if it's also required for the first keyword.

**Comment by elliotvr** [comment]
Done !

**Comment by kaso17** [comment]
thank you

**Comment by elliotvr** [comment]
@kaso17 this doesn't seem to work, i got : 

```11-15 16:35:22 Debug IWebClient.GetString(Url:https://archetorrent.com/torrents-search.php?search=Harry+Potter&incldead=1)```

Or i should have got : 
```11-15 16:35:22 Debug IWebClient.GetString(Url:https://archetorrent.com/torrents-search.php?search=%2BHarry+%2BPotter&incldead=1)```

**Comment by kaso17** [comment]
You've to change
`search: "{{ .Query.Keywords }}"`
to
`search: "{{ .Keywords }}"`

.Query.Keywords is always the original query string.

**Pull request merged**
