### PR TITLE
Update shareisland

### PR DESCRIPTION
**Pull request by Jorman**
Update download selector

### CODE REVIEW

**Comment by Jorman** [comment]
There's another problem, but I don't know if this one is connected to this mod
When I send the torrent to blackhole I got error from transmission
`watchdir Failed to add (corrupted?) torrent file:`
The html file is downloaded and if I try to download the torrent from jackett I got error 404
Can be related to this problem?

**Comment by garfield69** [comment]
Cheers.

**Comment by Jorman** [comment]
Thanks @garfield69 

But check the comment before.

Seems that now the selector is changed, and this one works, this open a new page for the "real" download link, in this case is
https://shareisland.org/download.php?id=8bd......
How can I fix this?

**Comment by garfield69** [comment]
you'll need to include a download block. take a look at https://github.com/Jackett/Jackett/wiki/Definition-format#download for details and draw on examples: simple iloveclassics.yml, complex girotorrent.yml

**Pull request merged**
