### PR TITLE
ui: search tracker name and tracker url. resolves #10870

### LINKED ISSUE #10870: Search trackers both in names and URLs
I search tracker by its URL and nothing found:
https://i.imgur.com/1u85GFG.png

I search tracker by its name and it is found:
https://i.imgur.com/Wqq52Wb.png

I would be better to show results for URLs and names.

### PR DESCRIPTION
**Pull request by ngosang**

### CODE REVIEW

**Comment by ngosang** [comment]
@ilike2burnthing test and merge

**Comment by ilike2burnthing** [comment]
Search function is working well in both configured indexer list:

and add indexer list:

but it's had a knock on effect on the layout:



Not sure if that's a result of the change to colspan from 2 to 3, or something else.

**Comment by ngosang** [comment]
What is your web browser?

**Comment by ilike2burnthing** [comment]
Edge, was just trying it out in Windows Sandbox. Will check now in other browsers.

**Comment by ngosang** [comment]
I commited a fix but it's not tested.

**Comment by ilike2burnthing** [comment]
Tried with Chrome, Edge, and Firefox, new build still has the same issue.

**Comment by ngosang** [comment]
@ilike2burnthing try again

**Comment by ilike2burnthing** [comment]
Yep, that's working great, thanks!

**Pull request merged**
