### PR TITLE
core: remove legacy configuration files

### PR DESCRIPTION
**Pull request by ngosang**
#10392 #10415

### CODE REVIEW

**Comment by ngosang** [comment]
@ilike2burnthing Sorry for your effort. Test this PR, you will see some traces at the start up:
`Removing old configuration file: ....`

**Comment by ngosang** [comment]
The PR can be merged with your approval. I'm going to bed, I'm already 9 minutes late.

**Comment by ilike2burnthing** [comment]
No worries lol
I'll test this out now and merge after.
Night!

**Comment by ngosang** [comment]
It's good to have tests :smile: Should be fixed now.
OMG 28 minutes late.

**Comment by ilike2burnthing** [comment]
Go sleep! 😋

**Review by ilike2burnthing — APPROVED** [review]
Working for .yml and native indexers

**Comment by ilike2burnthing** [comment]
Just to make you aware of a related issue - https://github.com/Jackett/Jackett/issues/10381#issuecomment-739453054

No rush, as we've survived this long without it being a significant issue, and I doubt it will be anywhere near as simple a fix.

**Pull request merged**
