### PR TITLE
Fixing macOS agent installs

### PR DESCRIPTION
**Pull request by thebluepotato**
Updates some legacy launchctl commands and adds a very short delay before installer checks whether agent was successfully launched

### CODE REVIEW

**Comment by garfield69** [comment]
@ilike2burnthing  I cant test this any longer since my Oracle VirtualBox stopped allowing my MacOSx BigSur beta image from starting up (I think oracle and apple signed an agreement to allow only licenced installs) :-(
@thebluepotato on which macs has this been tested on?

**Comment by garfield69** [comment]
and will these changes work on 10.15 macs (the current minimum supported macosx)?

**Comment by thebluepotato** [comment]
This was tested on Ventura (13.0) but these subcommands have existed since Yosemite (10.10). Therefore, this should work for older OSes as well.

**Comment by garfield69** [comment]
Great. Thanks.

**Comment by garfield69** [comment]
v0.20.2080

**Pull request merged**
