### PR TITLE
Fix Infinite redirect with disabled cookies

### LINKED ISSUE #15134: Infinite redirect with disabled cookies
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett v0.21.1981+43de7aa9e059578f70e7bf381f26dbd4817afd2d
Environment version: 6.0.26
OS version: Unix 6.7.8.1 (64bit OS) (64bit process)
Jackett variant: CoreLinuxAmdx64
```

### Description

When cookies are disabled that will cause infinite redirect.

I was just trying
```
$ curl -Lv http://127.0.0.1:9117/jackett
```

and that caused infinite redirect loop between:
1. `Location: /jackett/UI/Dashboard`
2. `Location: http://127.0.0.1:9117/jackett/UI/Login?ReturnUrl=%2Fjackett%2FUI%2FDashboard`
3. goto 1.

If I do
```
$ curl -Lv  --cookie-jar /tmp/cookies http://127.0.0.1:9117/jackett
```

That works fine but I think it's not good to have such recursion possible.

There are multiple ways so solve this but maybe easiest way would be adding `&from=login` to `ReturnUrl` so then `Dashboard` could check if it's present and if we don't have any cookies then show error page asking to enable cookies.

Also by the way I noticed that some characters like `%0A` causes 500 error with stack trace.

```
$ curl -v 'http://127.0.0.1:9117/jackett/UI/Login?ReturnUrl=%2F%0A'
*   Trying 127.0.0.1:9117...
* Connected to 127.0.0.1 (127.0.0.1) port 9117
> GET /jackett/UI/Login?ReturnUrl=%2F%0A HTTP/1.1
> Host: 127.0.0.1:9117
> User-Agent: curl/8.6.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Date: Sat, 09 Mar 2024 22:07:31 GMT
< Server: Kestrel
< Cache-Control: no-cache,no-store
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Pragma: no-cache
< Set-Cookie: Jackett=CfD...OXU8; expires=Sat, 23 Mar 2024 22:07:31 GMT; path=/jackett; samesite=lax; httponly
< Transfer-Encoding: chunked
<
{
  "result": "error",
  "error": "Invalid non-ASCII or control character in header: 0x000A",
  "stacktrace": "   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(Char ch)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(String headerName, StringValues headerValues, Func`2 encodingSelector)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Location(StringValues value)\n   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationEvents.<>c.<.ctor>b__45_8(RedirectContext`1 context)\n   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.ApplyHeaders(Boolean shouldRedirectToReturnUrl, AuthenticationProperties properties)\n   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleSignInAsync(ClaimsPrincipal user, AuthenticationProperties properties)\n   at Microsoft.AspNetCore.Authentication.AuthenticationService.SignInAsync(HttpContext context, String scheme, ClaimsPrincipal principal, AuthenticationProperties properties)\n   at Jackett.Server.Controllers.WebUIController.MakeUserAuthenticated() in ./Jackett.Server/Controllers/UIController.cs:line 102\n   at Jackett.Server.Controllers.WebUIController.Login() in ./Jackett.Server/Controllers/UIController.cs:line 49\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)\n   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61"
}
```

### Logged Error Messages

```text
* Maximum (50) redirects followed
curl: (47) Maximum (50) redirects followed
```
```


### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Fippsy**
#### Description
Fixed infinite redirect by checking if Cookies work :
1. Adding TestCookie
2. Redirecting to TestCookie route
3. If Cookie present redirect back to login with cookiesChecked set to 1
4. Otherwise return 400 Bad Request

Some Refactoring : 
1. Remove Logger from UIController -> not used
2. Remove ServerConfig -> Replaced with  ISecurityService
3. Renaming variables according to naming convention -> private variables begin with _ and are camelCase
4. Remove magic strings -> Replaced with nameof

#### Screenshot (if UI related)
N/A
#### Issues Fixed or Closed by this PR

* Fixes #15134

### CODE REVIEW

**Comment by garfield69** [comment]
looks like the test suite needs to be update to cater for the changes this PR makes to the dashboard login, but I'm not the man for this job. @mynameisbogdan  when you have time can you take a look? thanks.

**Comment by Fippsy** [comment]
I think the tests are working fine, but there is a problem with the change. I made a PR without running the integration test because I couldn't get them to run properly on my machine and I didn't think it would have an impact.

I finally got them running and will take an other look at the problem tomorrow :-)

**Comment by garfield69** [comment]
For what its worth, I copied your source changes and integrated them into my win10 VS2022 and compiled and ran Jackett.
I tested it with both admin password enabled and disabled in combo with setting my chrome browser to block cookies or allowing cookies and it appears to work for me as intended. :-)

**Review by garfield69 — APPROVED** [review]
Tested on windows 10 and an ubuntu22 image on my win10  VirtualBox
with cookies disabled and enabled on a chrome browser
LGTM and your final solve is much simpler too ;-)
Thank you.

**Pull request merged**
