### PR TITLE
Add HDCity.li

### PR DESCRIPTION
**Pull request by segator**
I wanted to help to the community adding to jackett this amazing torrent tracker.

HDCity is a spanish tracker that have dual audio (VO/Spanish) so i added some regex that can be modified from the config page of jackett to modify this regex.

I tried the compatibility of the tracker with Sonarr and works almost perfect

### CODE REVIEW

**Comment by kaso17** [comment]
Can you please clean up the conflicts and unnecessary changes?

**Comment by segator** [comment]
Hi, what do you mean with unnecessary changes?

**Comment by kaso17** [comment]
See the "files changed" tab: https://github.com/Jackett/Jackett/pull/845/files
There are plenty of unrelated whitespace changes.

**Comment by flightlevel** [comment]
@segator 
Thanks for your PR, it would be great to have HDCity in Jackett, but there are a few issues with this PR. When you are ready please create a new PR noting the following points
-Please don't add a new package for HTMLAgilityPack, use the already included Anglesharp, its much better, maintained and frequently updated
-Please don't modify the console app, include your options in the trackers file
-Don't include unnecessary files, 'you've modified' 32 files, but really only 4 or 5 files are changes

**Comment by kicker83** [comment]
Hi, why doesn't appear HDCity in latest Jackett release? How could I install it?.

Thanks

**Comment by RoloSoze** [comment]
@kicker83 I believe HDCity's support was never added in Jackett. @segator didn't implement @flightlevel's changes, and so this Pull Request wasn't approved.

**Comment by kicker83** [comment]
Oh! what a pity, it would be awesome to have support of a spanish tracker. Thanks so much for the info @RoloSoze

**Comment by RoloSoze** [comment]
@kicker83 If you have an invite, maybe one of the developers is willing to add it.

**Comment by kaso17** [comment]
yes, this PR would need some cleanup in order to accept it.

**Comment by kicker83** [comment]
The problem is that the invitations are close right now. If they open registrations, I will send you one invite. Thanks!

**Comment by segator** [comment]
Hi guys, before create a new PR a wanted to fix some things and clean up the code but I didn't have time yet.  but my branch works perfectly I am using every day with sonarr, compile my branch meanwhile I don't have time to clean up the code.

**Comment by kicker83** [comment]
Hi Isaac! Nice to read you :P. It would be awesome to have hdcity with sonarr! please make it happen guys!

Thanks!

**Comment by segator** [comment]
I compiled the code for you, you can download it here, and start using it --> https://drive.google.com/open?id=0B01AY2-d4-28cjFLNDBXMTNXTFk

I don't know where I will have time to fix the PR

**Comment by kicker83** [comment]
Isaac, you are the man!! 

Thanks so much

**Comment by kicker83** [comment]
Hi Isaac, I installed your version and is working perfect! Thanks so much

**Comment by kicker83** [comment]
Hi Isaac, the indexer is still working for you? For example Legion in hdcity is legion 1x05 but jacket is search s01e05, and is not finding anything.

**Comment by segator** [comment]
Yes, it's working
remember to setup correctly the parameters
If you are using Sonarr you should check
TV Show English format

and set this Regular expression on the field TV Show Filters
(dual|triaudio|multi)|((es|spa|cast?)( *)[ /|-]( *)(eng?|v( *)(\.?)( *)o)(
*))|((eng?|v( *)(\.?)( *)o)( *)[ /|-]( *)(es|spa|cast?))

Rigards,

2017-03-15 15:10 GMT+01:00 kicker83 <notifications@github.com>:

**Comment by kicker83** [comment]
Of course is working! but I didnt check Tv show english format... sorry v_v

Thanksss

**Comment by romancin** [comment]
Hello segator, thank you for this awesome development!!

Searching is not working from sonarr, I can see this in the Jackett Console:

04-14 14:13:59 Info Starting web server at http://*:9117/
https://hdcity.li/index.php?page=torrents&category=0&active=1&options=0&search=Quantico+S02E01
https://hdcity.li/index.php?page=torrents&category=0&active=1&options=0&search=Quantico+2x01+
04-14 14:14:38 Info Found 0 releases from hdcity for: Quantico S02E01

If you copy and paste the second link in the web browser, it founds the episode correctly:
image

Manual search from Jackett works correctly:
image

I am using the precompiled version you posted on 12 March. 
Am I doing something wrong?
Thank you really much.

**Comment by segator** [comment]
Hi, did you see something wrong in the binding of the categories ID? If you know exactly what is wrong you could do a Pull Request to fix it. (Check HDcity.cs file) 
 About language I know.. I tried to talk with HDCity admins and they don't like the idea of have an automated Downloader. My idea is they shall change torrent title to use standard format  as every english tracker does. It's very dificult to parse HDcity "name convention" I have multiple regular expressions in the code but lot of cases couldn't be fixed without their colaboration.
I started also to try to implement IMDB API to get the translations on the fly but as I said they didn't use a standard format so is dificult to know in the torrent title where start/end movie/tvshow name.

**Comment by romancin** [comment]
Your jackett was right, i was not selecting correct categories in sonarr. For the moment I have TV Show automation resolved using your jackett sonarr and ombi, let's hope someday downloading films is possible too. Maybe if sonarr supports another language in the future this would be easier to work.

**Pull request closed without merging**
