### PR TITLE
[Bug fix] Removed admin rights requirement to start service on Windows when Jackett Updates

### LINKED ISSUE #6435: [Windows] Starting Jackett service after update when running as Virtual Service Account
After learning about best practices for application services in a Windows environment, I realized that running services as `LocalSystemAccount` is akin to running the service as `root` on Linux. I wanted to create a more secure environment, so I modified to Jackett service to run as a Virtual Service account, i.e. `NT Service\Jackett`

Jackett works fine as such, but when it updates, it fails to start the service back up. The update itself is successful. I looked into the event logs, and noticed the below error when Jackett failed to start back up. The IDs correspond to `Immersive Shell`. Is this something that could be fixed at Jackett's end, or is it essential to run the service as an Admin/LSA?

```
The machine-default permission settings do not grant Local Activation permission 
for the COM Server application with CLSID {RedactedID} 
and 
APPID {RedactedID} 
to the user NT SERVICE\Jackett SID (RedactedID)
```

Jackett Version 0.12.1038.0

### PR DESCRIPTION
**Pull request by ultnrg**
Closes #6435

### CODE REVIEW

**Comment by ngosang** [comment]
@ultnrg I think this PR won't fix all the issues related to admin user. If you search `IsUserAdministrator` in the source code you will see there are several cases when the user has to be admin to change the listening ports.
¿Could you take a look at the rest of the code and do some tests? I'm a Linux user and testing this will require a lot of effort for me.

**Comment by ultnrg** [comment]
> @ultnrg I think this PR won't fix all the issues related to admin user. If you search `IsUserAdministrator` in the source code you will see there are several cases when the user has to be admin to change the listening ports.
> ¿Could you take a look at the rest of the code and do some tests? I'm a Linux user and testing this will require a lot of effort for me.

You're right, this PR will not fix all issues requirements for admin. This issue that was raised was specific to when Jackett updates, as the service does not even attempt to start back up due to the user not being admin (which is annoying because every time it updates Jackett does not come back and needs to be manually started).

Jackett won't allow a non admin user to change the url/listening ports until a code update is done there. That one is a bit trickier because the user needs rights to be able to run netsh, so jackett either needs to check for these rights _or_ do another try / catch, although that may not work depending on what netsh sends back as an error (I haven't tested this)

**Comment by ultnrg** [comment]
Hi, is there any reason why this PR can't be merged?

**Comment by garfield69** [comment]
I was waiting for one of the c# devs that I assigned to this PR to review.
But it seems they are all still AWOL ATM. :-(
Since I'm not a c# dev I normally don't review and merge c# code changes.
But it has been a month so I suppose I will have to get on with it. I'll set aside some time later today.

**Review by garfield69 — APPROVED** [review]

**Pull request merged**
