### PR TITLE
[Feature] Filter Meta Indexer by tag and by language

### PR DESCRIPTION
**Pull request by alecsg77**
Resolving #8884

Solution:
Allows to group the list of configured Indexes based on properties or custom tags

Implementation:

1. Extends MetaIndexer with FilterIndexer to apply filter criteria on top of all the Indexers
2. Add Tags property to all the Indexers
3. Add meta indexer prefix "tag:" for referencing all the Indexes that have the specific tag configured
    IE: tag:t1 -> all the Indexes that have t1 in the tag list
4. Add meta indexer prefix "lang:" for referencing all the Indexes that support the specific language
   IE: lang:en-us -> all the Indexes of English (United States) language
   IE: lang:en -> all the Indexes of English language (en-au, en-bz, en-ca, en-ie, en-jm, en-nz, en-za, en-tt, en-gb, en-us, en-*)
5. Display tags in the configured Indexers list

Open points:

1. How to allow users to use tags in manual search from UI
2. Improve the tags editing experiance
3. Are tags case sensitive?
4. Review FilterIndexer cache policy. Potential infinite memory consumption. IE: Using a limited FIFO

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
Thanks for this contribution.

Just tested it out there: added an indexer, opened its configuration panel, typed in a tag, clicked Okay, and no tag was added. Opening the config panel shows there is no tag, and there is none in the indexer's .json file.

If I edit the .json file to add a tag and then restart, it's present in the configured indexers list, and also in the config panel. Trying to delete the tag from the config panel doesn't work, so I'm assuming no changes are being saved for it.

A short description will probably be needed as to what tags are. A (very) rough example, "Group indexers together by using Tags for quick preset searches. Multiple Tags can be added by separating them with a space."

As for your points:
1. a) making the tags in the configured indexers list clickable, which would open the manual search with those indexers selected (and they could then select or deselect indexers if they want), 
b) or in the manual search panel having a third dropdown menu for tags (not sure how that would work with the tracker menu though, maybe just similarly to option a),
c) or integrate tags into the tracker menu at the top, so when clicked the relevant trackers are selected,
d) or integrate tags into the tracker menu beside the indexers' names, so that they can be filtered by it,
e) both a and b or c or d
2. a) would the name Groups be easier to understand than Tags?
b) allow existing tag names to autofill/be suggested after the first character
3. probably not

**Comment by alecsg77** [comment]
New increment.

1. Fix tags persistence: missed implementation on client-side
2. Tags renamed into groups.
3. Group selector in the manual search
4. Group clickable and open the manual search with group pre-selected

**Comment by ilike2burnthing** [comment]
Looks good.

Just a quick check before I test:
1. `TagsConfigurationItem` in ConfigurationData.cs isn't meant to be `GroupsConfigurationItem`?
2. `return CreateFilterIndexer(GroupFilterPrefix + tag, x => x.Groups.Contains(tag));` in IndexerManagerService.cs isn't meant to be `return CreateFilterIndexer(GroupFilterPrefix + group, x => x.Groups.Contains(group));`?

Was just looking for any possibly missed 'tag' references, no idea if they actually need to be changed.

**Comment by alecsg77** [comment]
1. I kept TagsConfigurationItem cause this class defines the behavior of a configuration item and it is not strictly related to the group configuration (groups are configured as ...).
Does HashsetConfigurationItem sound better to you?
On the client side, the editor will be a tag-like editor.
As soon as I found better names, I will change them.
But I don't want to call it GroupsConfigurationItem cause someone can use it also in another context to configure a unique set of values separated by space or another character.
2. Right, it's a typo.

**Comment by ilike2burnthing** [comment]
That sounds fine, `TagsConfigurationItem` can be left as is, or if you find something more fitting then by all means.

**Comment by ilike2burnthing** [comment]
Works well. Selecting a Group filters the Tracker list to just those indexers in that group, and you can then search using all of them by default, or choose individual ones. I like it.

Was using radio buttons for Groups, rather than checkboxes, just a choice, or was there a reason behind that? I could see a case where a user may want to select more than one group to search by. If that's possible, it should probably be 'all indexers in Group A and all indexers in Group B', instead of 'only indexers in both Group A and Group B'.

Thanks again for the contribution, this has been a long sought after feature.

**Comment by ilike2burnthing** [comment]
Wondering if Public, Semi-Private, and Private should be considered as existing Groups as well, then make those clickable in the configured indexers list in the same way.

**Comment by alecsg77** [comment]
> Was using radio buttons for Groups, rather than checkboxes, just a choice, or was there a reason behind that? I could see a case where a user may want to select more than one group to search by. If that's possible, it should probably be 'all indexers in Group A and all indexers in Group B', instead of 'only indexers in both Group A and Group B'.

It's a design choice to simplify the logic, also in the backend.
To partially cover your use case, you can create two additional groups (`A union B`) and (`A intersected B`)
An indexer can below to multiple groups.
It's a manual operation

Otherwise, we have to reserve some characters to automate those operations.
IE:
`|` for union
`&` for intersection
Those characters are not allowed in a group name, so we can define that:
`group:GroupA|GroupB` is the id of MetaIndexer that search in all the indexer in GroupA or GroupB
`group:GroupA&GroupB` is the id of MetaIndexer that search in all the indexer in GroupA and GroupB
If a user assign to a Indexer a group named `GroupA&GroupB` or `GroupA|GroupB`
We consider the special characters as separators, so we consider it as equal to assign `GroupA` and `GroupB` to the indexer.

In order to be able to extend the functionality in this direction,
my question here is: what are the valid characters in a group name?
there is a policy/restriction/allowed set of characters on an indexer id?
Can we apply the same for the group name?

**Comment by alecsg77** [comment]
I found those Issues, potential related to this PR

#8884
#7170
#4787
#2185

I want to ask the people involved if they want to contribute to the design.

Better later than never 😊

**Comment by alecsg77** [comment]
On the UI side, I added dynamic tabs to filter by group the list of the configured indexers.
For the time been, I can not do more than that.
All the other ideas around the filter by other criteria require a better UX design.
I'm going to extend and complete the capabilities of the FilterMetaIndexer on the server-side,
to allows at least at the API level to perform complex operations.

Waiting for suggestions and reviews.

Cheers

**Comment by ilike2burnthing** [comment]
How it works at the moment is great, particularly as, like you said, users can create groups which fulfil that need, e.g. have a group `Anime` which includes indexers also in groups `TV`, `Public`, and `Films`, but then create another group `Anime_TV` (or conversely have `Anime_TV`, `Anime_Public` and `Anime_Films`, and then also have `Anime` which includes all of those indexers).

If you're up for doing the extra work, by all means, the characters `|` and `&` seem like good options. @garfield69 are you aware of any restrictions for the characters used in indexer IDs (e.g. alphanumeric and hypens only)? Any reason why that with `.`, `,`, `_` and `+` added would cause any issues for group names? This would be the format used:
```
http://127.0.0.1:9117/api/v2.0/indexers/group:GroupName/results/torznab/?apikey=12345...
```

Issues https://github.com/Jackett/Jackett/issues/8884, https://github.com/Jackett/Jackett/issues/7170 and https://github.com/Jackett/Jackett/issues/2185 seem to be covered by this PR already.

If we could make Public, Semi-Private, and Private all considered as existing groups at some point in the future then https://github.com/Jackett/Jackett/issues/4787 would be covered as well, rather than users having to duplicate these labels with groups.

This PR may also be a way of implementing https://github.com/Jackett/Jackett/issues/661 in a round about fashion by the user having `Enabled` and `Disabled` groups and, given your implementation of the tabbed interface for the configured indexers list, it will even work for the `Test All` function. It's not quite the one click button option asked for (and definitely not the automated function asked for in https://github.com/Jackett/Jackett/issues/3292), but it would seem to work well.

For the sake of tidiness, once this is merged the branch [feature/indexer-grouping](https://github.com/Jackett/Jackett/tree/feature/indexer-grouping) can be removed (introduced in https://github.com/Jackett/Jackett/pull/1659).

In terms of which of those requestors might be able to contribute, it's probably just @binhex, as @RoloSoze has been absent for a while, @ngosang is taking a step back and popping in when possible, and the rest just seem to be normal users wanting the feature. So @binhex if you're around and have any suggestions, have at it.

**Comment by ilike2burnthing** [comment]
@garfield69 on a separate point, would this be a good marker for v0.18?

**Comment by garfield69** [comment]
>are you aware of any restrictions for the characters used in indexer IDs (e.g. alphanumeric and hypens only)? Any reason why that with ., ,, _ and + added would cause any issues for group names?

The only restriction I can think of is the one that uses only US-ASCII characters because those chars do not need to be URL-encoded in the torznab URI that apps send to Jackett.
Any other restrictions on which char to use would be down to simply how the Jackett C# core code handles breaking down the parameters of the URI for processing incoming requests, something I've no knowledge about as its buried in the C# code someplace which I don't get involved with.

>on a separate point, would this be a good marker for v0.18

yes.

**Comment by alecsg77** [comment]
A new step on the API side.
There are three base filters:

- `group:xxx` check if groups property contains the group xxx
- `type:yyy` check if the type is yyy
- `lang:zzz` check if the language is starting with zzz

and three base operators:

- `xxx+yyy` xxx AND yyy
- `xxx,yyy` xxx OR yyy
- `!xxx` NOT xxx

It is possible now to perform operation like
`/api/v2.0/indexers/group:group1,type:public+lang:it/results/torznab/`
Get all configured Indexer that are in the group1 or (public and Italian language).

I wrote unit tests to cover the filter function builder as much as possible

Missing points
- More base filter has to be created on the other properties
- Validation of the group name to avoid conflicts with special characters
- Improve parser to allows even more complex expression and new operators (using some third party library)
- Improve the filter function composition using LINQ Expression and compile the final result to improve the filter performance.

**Comment by ilike2burnthing** [comment]
Pipelines seems to be tripping up over
```
new FilterFuncBuilderComponentStub("bool", args => bool.Parse(args) ? _ => true : _ => false)
```
in FilterFuncCompositeBuilderTests.cs with the error:
```
##[error]src/Jackett.Test/Common/Utils/FilterFuncBuilders/FilterFuncCompositeBuilderTests.cs(91,68): Error CS8370: Feature 'target-typed conditional expression' is not available in C# 7.3. Please use language version 9.0 or greater.
/home/vsts/work/1/s/src/Jackett.Test/Common/Utils/FilterFuncBuilders/FilterFuncCompositeBuilderTests.cs(91,68): error CS8370: Feature 'target-typed conditional expression' is not available in C# 7.3. Please use language version 9.0 or greater. [/home/vsts/work/1/s/src/Jackett.Test/Jackett.Test.csproj]
```
see also lines 102, 113, and 124.

**Comment by alecsg77** [comment]
Ok. There is to way to fix it: convert it to C# 7.2 syntax or enable C# 9.
There is a technical reason that the project uses dotnet 5 but not C# 9?

**Comment by alecsg77** [comment]
Increment on UI side:
- Extended the functionality of groups to the more generic filters
- Two kinds of filters: `type:` and `group:`.
 By default, there are three predefined filters on type: `type:public`, `type:private`, `type:semi-private`
 The `group:` filters are created based on the groups defined by the user.
- Smart filter creation
 One filter is created only if it's relevant: it excludes some indexers and shows at least one indexer.
 For example: if all the configured indexers are `public`, no filters based on type are created. If none of the configured indexers is `private`, the `type:private` filter is not created.
- Smart filter display
 The manual search dialog follow the filter selection
 The filter selection is visible only if there is at least one filter

From my point of view, we have all the minimum features to cover this functionality.
Additional tests and small improvements on the existing feature have to be complete before merging in master.

**Comment by garfield69** [comment]
remember to bump the **changed** date to force browser cache to load updated JS
https://github.com/Jackett/Jackett/blob/3317eafbc18c23f69478742d86209e4003ebd825/src/Jackett.Common/Content/index.html#L724

**Comment by alecsg77** [comment]
I also have to squash all the commits, right?

**Comment by ilike2burnthing** [comment]
When merged all commits are squashed, so there's no need for you to do so.

I'll test this in the next hour when I get some free time.

**Comment by ilike2burnthing** [comment]
The shift to dotnet 5.0 at the end of last year (https://github.com/Jackett/Jackett/pull/10346) was started by a contributor, and that bumped us from v0.16 to v0.17.

Nothing similar has been suggested for C# 9, but I'm not a C# dev do I don't know if this was for a particular reason, or just prioritising time and effort, given that everything was working ok without it.

As for testing this build, group labels are no longer clickable (due to the change of L324 in src/Jackett.Common/Content/index.html), and while the test function works, all searches result in `Request to Jackett server failed` with the logs showing `Request for unknown indexer: 0`.

**Comment by alecsg77** [comment]
😫 A last-minute typo. Fixed

About the group label clickable: I removed it cause I thought it was too strange that the group was clickable and the type not.
I see now applying the filter to the list as a more intuitive behavior for click on a label.

I got some new ideas for the UI UX that are going to cover also this case, but I want to open an additional PR for them.
So, to avoid introducing a thing that I will go to change next, in this PR, I will remove the filter tab feature and keep only the filter selection in the manual search.
I don't want to keep this PR open forever, trying to reach the perfect solution in one shot.

**Comment by ilike2burnthing** [comment]
Yea, that makes sense, rather than having some clickable and some not.

Separate PRs sounds like a good idea.

Tested a few variations of `/api/v2.0/indexers/group:group1,!type:private+lang:it/results/torznab/` and it's working well.

The smart filter creation and smart filter display works as it should too.

**Comment by binhex** [comment]
> In terms of which of those requestors might be able to contribute, it's probably just @binhex, as @RoloSoze has been absent for a while, @ngosang is taking a step back and popping in when possible, and the rest just seem to be normal users wanting the feature. So @binhex if you're around and have any suggestions, have at it.

hi guys, i apologise for the delay in my response, i am most definitely still keen to see some sort of grouping being added to jackett and im really pleased to see progress being made, so thanks for that!. I am not 100% sure what i can do to help out, but let me know if you need me for anything (apart from coding, my javascript and c# skills are next to zero), im happy to test and give you feedback if that helps.

**Comment by alecsg77** [comment]
Hi @binhex
No worry, we mention you (and other people) to give you the opportunity to contribute to the design of the first version of groups in Jackett.
For the javascript and C#, I will take care, no problem.

Here is more about the design. I want to provide something that not covers only my needs, but try to solve as much as possible the few most common use cases.

We are going to release a minimum version, and try to improve it with other changes later to cover more cases.

It will be nice if you can try this draft version of the functionality.
I don't know how you are used to getting a version of Jackett.
Here you can download the binary version for all the platform [Build #0.17.1030](https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/3417/artifacts?artifactName=drop&api-version=6.0&%24format=zip)
**ATTENTION** This is an unstable version. The installation on a machine where there is an official version will override it and breaks it (and sometimes summon Cthulhu). 
So, don't do it if you don't know how to do it 😁

Also, comments and suggestions in this thread are always welcomed.

**Comment by binhex** [comment]
thanks for the link to the dev build, i have downloaded, extracted and run and i can se the new tabbed interface for All, Public, and Semi-Private, that looks good!.

i then decided to see how you create a new group, and it was intuitive for me, so i simply 'configure' the indexer and set the group, so that is also great from my point of view.

what i really wanted the ability to do is to see a link to all three 'Feed' types for the new group, with the idea that this group link would give me an aggregated feed for the indexers **ONLY** in the group. i could then add this aggregated group feed to the downloader to give me a filtered.

a screenshot to confirm what i am seeing at present:-

image

So i really like the changes from a ui standpoint, but the real win for me would be the ability to hit this group via api, of course this is all from my personal wants, so please feel free to ignore :-).

**Comment by alecsg77** [comment]
Good, cause it already works like this 👍 

The whole functionality starts from the API: you can see [here](#issuecomment-833014105) for the syntax.

Some notes
- On the UI side, the filter capabilities are not so powerful as the API, for the time being. (UX idea is missing)
- The tabs will not be in this version. They will be in the next one.
- The group names are space-separated, so, you can assign an indexer to more than one group. Was it also clear?

Can you help me to write down the manual, too? 😁

**Comment by binhex** [comment]
> Good, cause it already works like this 👍
> 
> The whole functionality starts from the API: you can see [here](#issuecomment-833014105) for the syntax.

ooo nice!!!, if only i had looked up a bit eh :-), ok well in that case i am extremely pleased with the change, the syntax looks good for supplying mutlple groups. 

The only comment i would say is that perhaps a lot of people will not realise you can also hit the api via group name, i know you said you are going to write a wiki or some such on the new functionality, and that is all great, but perhaps a more in your face ui addition so people can see the links for the groups via the ui may help for people who don't (or won't) RTFM :-), i will leave that design decision to your good self.

> * The group names are space-separated, so, you can assign an indexer to more than one group. Was it also clear?

No, that wasn't clear to me that you could do that through the ui, ive just tried it and of course it works, a quick thought on this is that you could do something similar to the Blue text that is shown under the 'Site Link', and place it under 'Groups' saying something like 'Multiple Group names can be specified using a space as the separator'.

**Comment by alecsg77** [comment]
Binaries [#0.17.1039](https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/3426/artifacts?artifactName=drop&api-version=6.0&%24format=zip)

- Added [tagify](https://yaireo.github.io/tagify/) as group editor
- Removed the filters tabs
- Group name allowed characters: `A-Z``a-z``0-9``-``.``_``~`
- Documentation: WIP

Do you see anything else missing or to improve?

**Comment by garfield69** [comment]
>Do you see anything else missing or to improve?

one thing that come to mind, is that the group editor should blacklist the words `private`, `public` and `semi-private` as these are default groups that already exist.
Allowing users to add groups by these names could cause the scenario where a `public` indexer gets a group added by the user as `private`, and this could cause confusion later in the filter pulldown. Mind you, the user deserves all the confusion they get if they were silly enough to do this in the first place, but we might as well prevent it if we can?

**Comment by ilike2burnthing** [comment]
Should we also blacklist the word 'all' as well then?

Can these be blacklisted in a way that still allows group names like `public_anime` and `tv.all`?

**Comment by alecsg77** [comment]
I see.
First of all, thanks a lot.
Your contribution helps me to improve a lot the design.

We have a big misunderstanding.

1. There is no default **group** `public`, `private`, or `semi-private`. They are predefined **filters**.
2. A **group** (initially called tag) is a custom label that the user can apply (one or multiple) to an Indexer or more. (nothing more than that)
2. The system creates automatically one **filter** for each **group**.
3. In the manual search, the user chooses a **filter** (not a **group**).
4. The API allows operations on an aggregation of indexers based on a **filter**.
5. On the API, the user can specify a **filter** using a specific syntax
6. A **filter** is a composition of filter criteria like `type = 'private'` or `groups contains 'bar'`

I don't see any reason to blacklist some words as a **group** name.
The group called public is something different by the type public.
There is no collision on the API side, cause the two predefined filters have two different name/syntax: `group:public` and `type:public`
I can show in the filter list  `group:public` and `type:public` to eventually disambiguate.

I am even more convinced that it is more clear the initial name of **tag** instead of **group**, after your observation.

**Comment by ilike2burnthing** [comment]
I understood garfield's comment to be in reference to the Filter menu in manual search, rather than any concern about API conflicts.

If you have a mix of `public`, `private`, and `semi-private` indexers, these will appear in the Filter menu as `public`, `private`, and `semi-private`. If you also have the groups `public`, `private`, and `semi-private`, they too will appear in the Filter menu, but with no way to tell the 3 groups apart from the 3 types.

The filter list ends up looking like this:
Filters

**Comment by alecsg77** [comment]
I hope this will be the final version of the functionality.
This probably solve the misunderstanding and the possibility to have both the filter by public type and by public tag in the filters

image

**Review by ilike2burnthing — APPROVED** [review]

**Comment by ilike2burnthing** [comment]
@alecsg77 are you ok for documentation to be in a second PR (happy to help with that) and we can merge this now?

Thanks again for all your work on this.

**Comment by alecsg77** [comment]
Ok.
I hope it's enough stable.
Feel free to assign or tag me to any issue related to the functionality.
I will try to do my best to solve them as soon as possible.

**Pull request merged**
