### PR TITLE
Core: Add Filters to JSON Parsing

### LINKED ISSUE #12442: [req]: core Cardigann JSON. add the equivalent functions of the CSS :has(), :not(), :contains()
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

n/a

### Describe the solution you'd like

https://github.com/Jackett/Jackett/pull/12424#issuecomment-946587491
https://github.com/Jackett/Jackett/pull/12424#issuecomment-946593839
https://github.com/Jackett/Jackett/pull/12424#issuecomment-946611230
https://github.com/Jackett/Jackett/pull/12424#issuecomment-946614557
https://github.com/Jackett/Jackett/pull/12424#issuecomment-946708416

### Describe alternatives you've considered

_No response_

### PR DESCRIPTION
**Pull request by mikeoscar2006**
Resolves #12442.

- [x] has filter (Row)
- [x] not filter (Row)
- [x] contains filter (Row)
- [x] not contains filter (Row)
- [ ] Field level Filters
- [ ] Nested Filters
- [ ] Cleanup

### CODE REVIEW

**Comment by mikeoscar2006** [comment]
Sorry everyone for such delayed updates in this pull. Got stuck IRL and every time I wanted to continue here, found a few problems in the code. So I've changed my approach completely and as a result, I've added the remaining filters on selector level at least.
As before, I've tried them with the xBit yml indexer and before continuing If possible please give feedback through testing or any other means. Sorry once again and Thanks.

**Comment by garfield69** [comment]
There is no need for apologies, we are all grateful you are able to contribute, however long it may take, to crack these logic puzzles.

> I've added the remaining filters on selector level at least

So for the :contains() used in a row selector, can I confirm that the syntax supported is something like:
```yaml
  rows:
    selector: dht_results:has(MAGNET:contains("urn"))
```
or is it something else?

**Comment by mikeoscar2006** [comment]
Thanks a lot. Happy to contribute always :)

There is no need for the double quotes inside contains filter's brackets. Similarly with the not contains filter.
I used the following for testing (only) if it helps:
```yml
    selector: dht_results:has(MAGNET):not(NAME:contains(2012))
```

**Comment by garfield69** [comment]
so would you expect 
```yaml
    selector: dht_results:has(MAGNET:contains(xt=urn))
```
to work?

**Comment by mikeoscar2006** [comment]
Yes, it should work.

**Comment by mikeoscar2006** [comment]
@garfield69 I forgot to add validation in the contains filter. Should be working after the latest commit.

**Comment by garfield69** [comment]
Cheers.
I'll putz about throughout the day as free time allows, testing with different indexers various permutations and see how it goes. ;-)

**Comment by mikeoscar2006** [comment]
Cool, I'll figure out the field level filters till then :)

**Comment by garfield69** [comment]
Excellent!

I added a gotemplateparse to the rows selector so I could easily test row selector variations by using the dashboard config editor for the xbit indexer.
See https://github.com/Jackett/Jackett/pull/12424#issuecomment-946477522 for the updated xbit test yaml.

I tried out the following
```
dht_results:has(MAGNET)
dht_results:has(MAGNET):not(TORRENT)
dht_results:has(MAGNET):has(NAME)
dht_results:has(MAGNET):not(NAME)
dht_results:has(MAGNET):not(NAME:contains(720p))
dht_results:has(MAGNET):has(NAME:contains(720p))
dht_results:has(MAGNET):not(TORRENT:contains(720p))
dht_results:has(MAGNET:contains(xt=urn))
dht_results:has(MAGNET:contains(xt=urn)):has(NAME:contains(720p))
```
All returned the expected results, except `dht_results:has(MAGNET):not(TORRENT:contains(720p))` which returned no results, and I was expecting, since the TORRENT key does not exist in the set, that  we would get all results with the key MAGNET in the set.
Did I miss-use the :not(:contains()) in this instance, or would you also have expected results?
Admittedly, such a selector is probably not going to be used in real life so it may not worth persuing.

**Comment by mikeoscar2006** [comment]
Well, for not-contains, I've set the condition that the key must exist and the value must not contain the input. That's why it returned 0 results. I can make the changes according to the condition or cases you suggest, no problem in that.

**Comment by garfield69** [comment]
> for not-contains ... I've set the condition that the key must exist and the value must not contain the input.

So do the :contains() handle cases where the key is using the `optional: true` variant?

**Comment by garfield69** [comment]
I think the following should be the process, (I hope I get this right, please test for nonsense):
- before the rows :contains() is processed the presence of the `optional:true` flag for the dependant key should be checked.
- if optional:true is not present, and the key is not found, then that should be a missing key error.
- if optional:true is not present, and the key is found, then :contains should evaluate presence of string. not:contains negates.
- if optional:true is present, and key is not found, then :contains should return false and not:contains returns true.
- if optional:true is present, and key is found, then :contains should evaluate presence of string. :not:contains negates.

**Comment by mikeoscar2006** [comment]
> So do the :contains() handle cases where the key is using the `optional: true` variant?

Doesn't optional:true comes in play only in the field-level selectors? I've only added the filters to the rows selector for now.

**Comment by garfield69** [comment]
Yes. Ignore my last post I've gotten a bit confused. Time to go to bed.

**Comment by mikeoscar2006** [comment]
@garfield69 do you mind restoring the deleted comment? It was a great explanation for field-level filters alongside optional. Will come in handy to cross-check the logic.

**Comment by garfield69** [comment]
>do you mind restoring the deleted comment? It was a great explanation for field-level filters alongside optional. Will come in handy to cross-check the logic.

Cant, there is no undo for deleted comments. 
If you have the comment in your email feel free to post it back, I don't have it since I wrote it direct in the web site.
Sorry.

**Comment by mikeoscar2006** [comment]
No worries, got it from the email. Thanks again for the email idea and the explanation.

**Comment by garfield69** [comment]
@mikeoscar2006  hey you, still alive? Any ETA on completing phase 2?

**Comment by ilike2burnthing** [comment]
replaced by https://github.com/Jackett/Jackett/pull/12922

**Pull request closed without merging**
