### PR TITLE
core: separate categories from movie-search

### PR DESCRIPTION
**Pull request by ngosang**
* Categories and Torznab movie-search are separated
* Movie-search parameters are validated
* Fixed some bugs in Cardigann indexers

### CODE REVIEW

**Comment by ngosang** [comment]
@garfield69 review this PR carefully. Not the C# code, just the functionality of the indexers.
I tried to keep the same behavior in all indexers but there are some changes in Cardigann because the old code was ignoring imdbid tags.
If you have a diff tool compare these files to see the differences before/after this PR:
[before.txt](https://github.com/Jackett/Jackett/files/5388292/before.txt)
[after.txt](https://github.com/Jackett/Jackett/files/5388293/after.txt)
[diff.txt](https://github.com/Jackett/Jackett/files/5388294/diff.txt)

**Comment by garfield69** [comment]
>One question. In case some indexer has movie-search: [imdbid] without the q I should assume only imdb search is allowed or always add q no matter if the user include it or not?

there are currently **no** yml indexers with `movie-search: [imdbid]` defined, and my understanding of the torznab specs is that the parm `q` is the default parm, so I have always defined `movie-search: [q]` as a standard, and added imdbid optionally only  if the web site supports searching with it.

I will hold off reviewing until you say the PR is ready. IMO there is little point testing if the code is likely to change here and there ;-)
besides I've plenty on my plate ATM to be getting on with.

**Comment by garfield69** [comment]
You have added movie-search to some yml indexers whose categories do not have any movies, for instance funkytorrents is a music site with only audio categories.
I believe that search modes should only be added to indexers if there is a category available that makes it worth while searching with that mode. ;-)

**Comment by ngosang** [comment]
@garfield69 I reviewed the changes and I think they are good. In funkytorrents I see the cat `3: Movies # (Movie)`. I'm going to merge to work in other issues. You can do a post-review and do some adjustments if I miss something.

**Comment by ngosang** [comment]
> One question. In case some indexer has movie-search: [imdbid] without the q I should assume only imdb search is allowed or always add q no matter if the user include it or not?

The right thing to do is always add "q", but if you forget, I will add it for you!

**Pull request merged**
