### PR TITLE
core: improve windows tray launcher code. resolves #10094

### LINKED ISSUE #10094: [enhancement] improve the Windows Tray start-up code
currently the Windows system Tray start-up code looks like this
https://github.com/Jackett/Jackett/blob/0ad911f97ae322d7c25674e564725cd85ed8fbef/src/Jackett.Tray/Main.cs#L95-L113

we should be able to improve this to allow for a more dynamic start-up that starts the tray as soon as practical
a suggestion as a starting place is the following script provided by @ilike2burnthing 

```
@echo off
start JackettUpdater.exe
timeout /t 30 > NUL # if we wanted to keep the 30s delay
:_loop
tasklist /FI "IMAGENAME eq JackettUpdater.exe" | findstr = > NUL || goto _cleanup
timeout /t 5 > NUL
goto _loop
:_cleanup
C:\ProgramData\Jackett\JackettTray.exe
```

volunteer needed to implement this, or something similar, that allows the tray to be started without interfering with the updater (see issue #10068)

### PR DESCRIPTION
**Pull request by ngosang**
Updates will be faster on most systems.

### CODE REVIEW

**Comment by ngosang** [comment]
@garfield69 @ilike2burnthing This should fix the issue. It's similar to the Linux solution. The only concern is `timeout /t 1 /nobreak > nul` is not available on Windows XP. I'm using ping command to wait instead. Do some tests.

**Review by ilike2burnthing — APPROVED** [review]
Tested again with `jackettupdater --norestart -p C:\ProgramData\Jackett` being executed from C:\Windows\Temp while jackett_launcher.bat was running in C:\ProgramData\Jackett. Batch file was updated, along with all other files, and JackettTray started with update notification.

Can't test an automatic update obviously, but this looks good.

**Review by garfield69 — APPROVED** [review]
for test, I downloaded and installed this PR 0.16.2096
then clicked check-for-update on dashboard
TrayLog.txt
```
2020-11-07 14:47:18.7977 Info Received signal from tray lock service 
2020-11-07 14:47:18.8022 Info Starting launcher script as Jackett is running as a Windows service: cmd.exe /c "C:\ProgramData\Jackett\jackett_launcher.bat" 
2020-11-07 14:47:18.8883 Info Close of tray application initiated 
2020-11-07 14:47:24.6462 Info Starting Jackett Tray v0.16.2080.0 
2020-11-07 14:47:24.7707 Info Display balloon tip, updated to 0.16.2080.0 
```
updater.txt
```
2020-11-07 14:47:19.0542 Info Jackett Updater v0.16.2080 
2020-11-07 14:47:19.0807 Info Options "--Path" "C:\ProgramData\Jackett" "--Type" "WindowsService" "--Args" " " "--KillPids" "7044" 
2020-11-07 14:47:19.0807 Info Jackett variant: CoreWindows 
2020-11-07 14:47:19.0807 Info Pausing for 3 seconds to give Jackett & tray time to shutdown 
2020-11-07 14:47:22.1543 Info Killing process 7044 
2020-11-07 14:47:22.1543 Info Finding files in: C:\WINDOWS\TEMP\JackettUpdate-v0.16.2080-637403572367089791\Jackett\ 
2020-11-07 14:47:22.1618 Info 943 update files found 
2020-11-07 14:47:22.1618 Info Attempting to copy Accessibility.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.16.2080-637403572367089791\Jackett\Accessibility.dll to destination: C:\ProgramData\Jackett\Accessibility.dll 
2020-11-07 14:47:22.1618 Info Copied Accessibility.dll 
[...]
2020-11-07 14:47:23.0199 Info File copying complete 
2020-11-07 14:47:23.0199 Info Starting Windows service 
```
log.txt
```
2020-11-07 14:47:08.6673 Info Checking for updates... Jackett variant: CoreWindows 
2020-11-07 14:47:09.0288 Info New release found. Current version: v0.16.2092 New version: v0.16.2080 
2020-11-07 14:47:09.0288 Info Downloading release v0.16.2080 It could take a while... 
2020-11-07 14:47:18.7903 Info Starting updater: C:\WINDOWS\TEMP\JackettUpdate-v0.16.2080-637403572367089791\Jackett\JackettUpdater.exe --Path "C:\ProgramData\Jackett" --Type "WindowsService" --Args " " --KillPids "7044" 
2020-11-07 14:47:18.7903 Info Updater started process id: 1600 
2020-11-07 14:47:18.7903 Info Signal sent to lock service 
2020-11-07 14:47:20.8004 Info Exiting Jackett.. 
2020-11-07 14:47:23.4807 Info Starting Jackett v0.16.2080.0 
```
LGTM

**Comment by ilike2burnthing** [comment]
I overlooked an issue for those updating to this version from a previous ones - there is no jackett_launcher.bat in the installation directory for JackettUpdater to run, and so JackettTray doesn't launch after install.

This will only happen once, so I'm not sure it actually needs 'fixed'.

**Comment by ngosang** [comment]
No. It will work because the "old tray" doesn't launch the script.

**Pull request merged**
