### PR TITLE
hdolimpo: adds HD-Olimpo, private Spanish tracker. resolves #5142

### LINKED ISSUE #5142: [REQ] hdolimpo .co [Private / Spanish]
Request to add support for Spanish private tracker https://hdolimpo.co
I don't have invitations, but if you provide an email address I think I can get one.
Thank you!

### PR DESCRIPTION
**Pull request by ngosang**

### CODE REVIEW

**Comment by garfield69** [comment]
urg, I cant test this right now, I'm getting 
image
hopefully its just the server unavailable and not a **you-are-not-a-Spanish-IP** block!

**Comment by ngosang** [comment]
Internal news with Google Translator
> As of today, VPNs are totally prohibited, this means that if we see any user who does not use their IP from their home line it will be automatically banned without option to replicate, **we do not want to see a IP that is not Spanish**, if a user has more than 5 different Spanish ips will be banned, this means that we understand that you use the home, work and wifi ip of the bar in your area, but that of having up to 30 different ips not will never be tolerated.

Maybe @RicardoVelaC or @skttbv can help with testing. If not, I can give access to my seedbox.

**Comment by RicardoVelaC** [comment]
@ngosang you are right since last days you only can access with an Spanish IP
@garfield69 I can try the c# indexer HDOlimpo.cs but I don't know how to compile.
I know how to try *.yml in a easy way but I don't have idea with *.cs

Do you have a quick clue?

**Comment by ngosang** [comment]
Each PR generates artifacts during the appveyor build check.
Linux / Mac => https://ci.appveyor.com/project/Jackett/jackett/builds/29899381/job/y78qw1xy9io6kc11/artifacts
Windows => https://ci.appveyor.com/project/Jackett/jackett/builds/29899381/job/ndr4b9lkct5j3c00/artifacts

**Comment by garfield69** [comment]
@RicardoVelaC  let me know when you've approved the change and I'll merge.

**Comment by ngosang** [comment]
I did some improvements. Latest artifacts => https://ci.appveyor.com/project/Jackett/jackett/builds/29921035
@garfield69 I tested this carefully. You can merge, he can test the release.

**Comment by garfield69** [comment]
Okely Dokely. Thanks.

**Pull request merged**
