### PR TITLE
iptorrents: some fixes and code cleanup

### PR DESCRIPTION
**Pull request by ngosang**
* Add SupportsImdbTVSearch
* Fix 4k category
* Remove files code, not available in the website
* Add description
* Add configuration advice
* Code cleanup

Tested

### CODE REVIEW

**Comment by JayXon** [comment]
But files is available? Could you add it back?
image

**Comment by ngosang** [comment]
It's fixed in the next release.

**Comment by JayXon** [comment]
Thank you!

**Comment by garfield69** [comment]
Jackett 0.16.521

**Pull request merged**
