### PR TITLE
core: add infohash parameter in cardigann definition

### PR DESCRIPTION
**Pull request by ngosang**
#8590 #10087

### CODE REVIEW

**Comment by ngosang** [comment]
@garfield69 we have to add "infohash" parameter to documentation and some notes about auto generated magnets.
Review all cardigann indexers with the words "coppersurfer", "announce" or "tr=".

**Comment by garfield69** [comment]
so to be clear, for the wiki, 
when the infohash block is used, it requires a selector (and any supporting filters if necessary) in order to produce an infohash key, and the cardigann will automatically build a magnet URI, loading the `&dn=` with the `.Result.title` and using default `&tr=` from a hard coded list. 
And this means a magnet block will not be required.
Have I got that right?

**Comment by ngosang** [comment]
Yes but the last part. Magnet block still exists and it's preferable over infohash.
* If some site provides magnet links we should use the magnet link provided using the magnet block. The site can provide more specific trackers for that torrent.The infohash will be auto generated.
* If the magnet is not available but we can get the infohash, use the infohash block. This will auto generate the magnet link as you described.
* You can use both blocks if you want (although I think it is better to use only the magnet in this case). Nothing will be auto generated in this case.

**Comment by ilike2burnthing** [comment]
So first preference is `download:` (and optionally `magnet:`), but if we have to build a magnet URI, as one isn't available in the results page, use `infohash:` (in which case `download:` does not need to be included)?

Does that mean that `magnet-hash:` and `magnet-name:` will no longer be needed once we move all indexers over to `infohash:`?

**Comment by garfield69** [comment]
>Does that mean that magnet-hash: and magnet-name: will no longer be needed once we move all indexers over to infohash:?

those two fields are custom fields that have not corresponding torznab equivalent.
you can in a yaml indexer create any field name you like, to use to put together results data later.
they become available for use as `.Result.whatever-you-calledit` for the official torznab fields like title,size,seeders etc.
see the note in https://github.com/Jackett/Jackett/wiki/Definition-format#variables-available-during-search-queries for details.

**Comment by ilike2burnthing** [comment]
Ah, gotcha

**Comment by garfield69** [comment]
>So first preference is download: (and optionally magnet:), but if we have to build a magnet URI, as one isn't available in the results page, use infohash: (in which case download: does not need to be included)?

- use download for .torrent link
OR
to point to the details page when the .torrent link is not in the results page, in which case the download block defined before the search block gets invoked to process the details page and look for what ever the selector is set to find, .torrent or magnet (only one link is supported).
- use magnet for magnet uri
- use infohash to build a magnet when a magnet uri is not already available.

**Review by garfield69 — APPROVED** [review]

**Review by ilike2burnthing — APPROVED** [review]

**Comment by garfield69** [comment]
Wiki updated.

**Comment by garfield69** [comment]
all yaml with magnet building in the search block have been converted to use infohash

remaining are yaml that create a magnet from the details page using the download block, which is unsupported ATM.

**Comment by ngosang** [comment]
take a look at `emtrek`. the magnet is in the search block, not in download block

**Comment by garfield69** [comment]
Ah. no, emtrek is a different case.
there is a complete magnet uri already there, but it has only the emtrek tracker on it. 
So we add additional trackers to their existing magnet uri.

I suppose we could extract the infohash out of their maget uri and build out own magnet, to effectively drop their private tracker and use our internal tracker list... do you think we should do this?

**Comment by ngosang** [comment]
I saw they are including his own tracker. It's fine as it's.

**Comment by ilike2burnthing** [comment]
Could we append their tracker to those provided by infohash?

**Comment by ngosang** [comment]
No without changing a lot of code. It's a corner case for me.

**Pull request merged**
