### PR TITLE
(Update) blutopia.yml

### PR DESCRIPTION
**Pull request by HDVinnie**
- note this change should also be applied to all other tracker based off latest UNIT3D release.

### CODE REVIEW

**Comment by garfield69** [comment]
would you happen to know if there is any way to identify what sites have upgraded to the latest release of unit3d other than after the fact when the relevant jackett indexer fail their searches?

**Comment by sleekmountaincat** [comment]
fyi, worked for me

**Comment by garfield69** [comment]
what would really be handy would be if the the sites login page had a hidden html comment stating the unit3d version.
then it would be easy to check what a site's unit3d version was at, and update the indexer with any global update you publish if they are up to date.
because until the site upgrades we don't want to preempt updates ahead of time and break existing indexers ;-)

**Comment by HDVinnie** [comment]
@garfield69 I can for sure add in a hidden comment on the login page. I will add it into UNIT3D's next release which will be `v1.9.2`

**Comment by HDVinnie** [comment]
@garfield69 

https://github.com/HDInnovations/UNIT3D/commit/a87a0bc2a0e79d553bd995640c4e5e5743c514ad

[](https://postimg.cc/Jy8bMghW)

**Pull request merged**
