### PR TITLE
magnetdl & torrentquest: remove by quest of site maintainers

### PR DESCRIPTION
**Pull request by ilike2burnthing**
TorrentQuest recently added Cloudflare DDoS protection checks on their TV and Movies pages (our keywordless search paths). Previously, keywordless search results (e.g. 2020) have been blocked as well.

I got in contact with the maintainers for the site (and so also of MagnetDL), and explained the situation. This part of their response makes it pretty clear that we (or technically Sonarr, et al.) are having a negative impact on the sites:
```
The Movies and TV pages of TorrentQuest had 2.4M requests in the past 24 hours with
99.97% non-human traffic, a site that gets < 2,000 visitors per day [...] the server
has been getting hit hard, sometimes a sudden influx of about 10,000+ connections
all at once.
```
Developing a search API for the site, or providing a 'Latest' link for us to use aren't an option for them, so they have requested we remove support for their sites.

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
_**If**_ a Latest 100 RSS feed is added in the future they will let me know

**Comment by swannie-eire** [comment]
Thanks for providing the explanation of why it was removed.

I understand the site maintainers concerns but it does not nessacarily mean that all or even a reasonable percentage of the non-human traffic is coming from jackett as many other indexers and auto downloaders are still going to be accessing the site like sickchill, Couchpotato etc..

MagnetDl is probably the best place to get public torrents so would definitely be grateful to see it again.

I would be curious to know since it was removed if the percentage of non-human traffic notability decreased.

**Comment by ilike2burnthing** [comment]
Each time we changed the URL used for updates, that is the one that got hit, so it seems very likely it was Jackett, or rather those programs using Jackett.

I left it with them that if the issue continued, to get back in touch; they didn't get back in touch other than to say https://github.com/Jackett/Jackett/pull/10347#issuecomment-737788666

**Comment by RileyXX** [comment]
It's been several years with lot's of changes/improvements to automated software perhaps now would be a good time try adding this site back again as an indexer? 

If the developers of MagnetDL can't implement the latest 100 feed to reduce traffic load then that's their problem imo. If it's not possible to add this indexer without the latest 100 feed then I guess we're just SOL. 

Technically someone could index and cache the site and serve the feed from a dedicated server specifically for Jackett but obviously that would cost $$.

**Comment by ilike2burnthing** [comment]
We're not here to knowingly cripple sites and/or their owners' bank accounts. They've asked us to stop supporting the sites, we have, that's not changing unless they contact us.

**Pull request merged**
