### PR TITLE
TorrentSeeds: Convert to csharp

### PR DESCRIPTION
**Pull request by fnk93**
#5973 

Old indexer did not parse single results. This is now possible with this c# solution.

### CODE REVIEW

**Comment by garfield69** [comment]
Jackett 0.13.581

**Comment by whitesnakeftw** [comment]
@fnk93 @garfield69 I still have this problem (#5973) on version 0.16.2233.0. Can you guys still reproduce it as well?

**Comment by fnk93** [comment]
@whitesnakeftw  Unfortunately, my account has been banned from the search there. So I can't really test it.

**Comment by garfield69** [comment]
yes, I see this too.  #5973 re-opened.

**Pull request merged**
