### PR TITLE
add BTDB public tracker. Closes #1564

### LINKED ISSUE #1564: [request] Please add BTDB to list
http://btdb.to/

This is a great fallback torrent site to retrieve hard to find items and all torrents in general. Its open/public - I tried creating a scraper file but failed.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/47272077-request-please-add-btdb-to-list?utm_campaign=plugin&utm_content=tracker%2F25207257&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F25207257&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by garfield69**

### CODE REVIEW

**Comment by garfield69** [comment]
@kaso17  so I recently discovered that Jackett definitions that do not have any categorymappings, or have mappings that are not numeric, will not be compatible with sonarr. They fail the test during the sonarr indexer adding step.    
So, what is the procedure in these cases:     
- do we add at least one dummy category,
  ```
      - {id: 1, cat: Other, desc: "Other"}
  ```
- or add a bunch of standard ones
  ```
      - {id: 1, cat: TV, desc: "TV"}
      - {id: 2, cat: Movies, desc: "Movies"}
      - {id: 3, cat: Audio, desc: "Music"}
      - {id: 4, cat: Books, desc: "Books"}
      - {id: 5, cat: PC/Games, desc: "Games"}
      - {id: 6, cat: PC, desc: "Apps"}
      - {id: 7, cat: XXX, desc: "Porn"}
      - {id: 8, cat: Other, desc: "Other"}
  ```
- or don't add any because they are not intended for use with sonarr
- or some other option?

**Comment by kaso17** [comment]
The numeric vs non numeric IDs should have no impact.
The standard problem with failed sonarr tests is that sonar search only in the categories TV/SD and TV/HD by default, to change that you need to change the categories option (only visible with advanced options enabled). If the tracker e.g. only supports the parent "TV" category it won't find any results with the default settings.

You've some example torznab query URLs made by sonarr during the failed tests?

**Comment by garfield69** [comment]
you are right., I retried my tests in light of what you said and see now that they do indeed work.     
please reject 1881, 1882 and 1884 as they are not required.         

This leaves the question about bdtb. without any categories defined, i cannot load it into sonarr. Should I define a tv and movie cat, like how skytorrents.yml has ?

**Comment by kaso17** [comment]
Yes, if there are no categories defined the corresponding dummy categories TV/Movies need to be defined

**Pull request merged**
