### PR TITLE
Fix https://github.com/Jackett/Jackett/issues/1633

### PR DESCRIPTION
**Pull request by gprime44**

### CODE REVIEW

**Comment by Khogniak** [comment]
YGG indexer is already created and merged see PR : https://github.com/Jackett/Jackett/pull/1536

**Comment by gprime44** [comment]
@Khogniak Yes but it's a fix for this issue #1633

**Comment by Khogniak** [comment]
Ow ok, nice
I worked on it and was just writting a PR while you made yours,
please have a look : https://github.com/Jackett/Jackett/pull/1635

:smiley:

**Comment by gprime44** [comment]
Okay ! perfect ! So i can close this PR

**Comment by kaso17** [comment]
closing this one in favor of #1635. Thank you both for your work!

**Pull request closed without merging**
