### PR TITLE
requestdelay 3.1s resolves #13796

### LINKED ISSUE #13796: [TorrentLeech] Error Parsing Json Response: Status=TooManyRequests
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-12-21 05:09:07.3493 Info Environment version: 6.0.12 (/home/<username>/Jackett/) 
2022-12-21 05:09:07.3557 Info OS version: Unix 5.10.0.20 (64bit OS) (64bit process) 
2022-12-21 05:09:07.3586 Info Jackett variant: CoreLinuxAmdx64 
2022-12-21 05:09:07.3586 Info File /etc/issue: Debian GNU/Linux 11 \n \l 
2022-12-21 05:09:07.3586 Info Running in Docker: No 
2022-12-21 05:09:07.3644 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
2022-12-21 05:09:07.3650 Info App config/log directory: /home/<username>/.config/Jackett 
2022-12-21 05:09:07.3650 Info Using proxy: Disabled 
2022-12-21 05:09:07.3650 Info Using FlareSolverr: http://127.0.0.1:8191 
2022-12-21 05:09:07.3840 Info Using HTTP Client: HttpWebClient2
```

### Description

When doing a Sonarr TV series scan the tracker activates Cloudflare protection and the search fails.

### Logged Error Messages

```text
2022-12-21 05:09:43.9682 Info Torznab search in TorrentLeech for Outlander S01 => Found 100 releases 
2022-12-21 05:09:45.5077 Info Torznab search in TorrentLeech => Found 100 releases 
2022-12-21 05:09:46.7716 Info Torznab search in TorrentLeech for Outlander S01 => Found 100 releases 
2022-12-21 05:09:49.0239 Info Torznab search in TorrentLeech for Outlander S01 => Found 100 releases 
2022-12-21 05:09:49.8017 Error Jackett.Common.IndexerException: Exception (torrentleech): Error Parsing Json Response: Status=TooManyRequests Response=<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    <meta http-equiv="refresh" content="35">

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            www.torrentleech.org
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=77ce1b9a2b5e23f6')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            www.torrentleech.org needs to review the security of your connection before proceeding.
        </div>

   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1425
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 310
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 692
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 404
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Jimmy062006**
2.1 was not long enough in testing.

### CODE REVIEW

**Comment by garfield69** [comment]
did you test only with the 1 second increase, or have you tried using smaller increments, such as 2.5?

**Comment by Jimmy062006** [comment]
> did you test only with the 1 second increase, or have you tried using smaller increments, such as 2.5?

Only 1 second. Did you want me to try and back it down until it errors then go 0.1 above ?

**Comment by garfield69** [comment]
Yes, please. Thanks.

**Comment by Jimmy062006** [comment]
> Yes, please. Thanks.

Pr updated

**Review by garfield69 — APPROVED** [review]
Thanks

**Pull request merged**
