### PR TITLE
SSL Fix by default, Now use TLS (1.2, 1.1, 1) by default

### PR DESCRIPTION
**Pull request by JigSawFr**
### Optimized & Fixed Jackett SSL Mecanism

> SSL Fix is enabled by default, recoded ciphers list
> Jackett HTTP Web Client is now using TLS by default (1.2, 1.1, 1)

Fixed ISS. #311 and so many others.

*Updated with love,*
JigSaw

### CODE REVIEW

**Comment by JigSawFr** [comment]
Hm, seems actual version of Mono don't support TLS 1.2 & 1.1. Working on a workaround.

**Comment by ElYoM** [comment]
Thanks but what is PR ? Also, Jackett was just updated to v0.7.240.0 on my Windows with the integrated version check and I can't get it to work, is it normal ? Do I have to do a specific action (maybe redownload and reinstall with Windows installer ?) ?

**Comment by JigSawFr** [comment]
@ElYoM PR means Pull Request. Latest update is 0.7.240 according to https://github.com/Jackett/Jackett/releases.
Appveyor is experiencies some difficulties to upload latest version, sorry for inconveniences.
You just need to wait to see a new version as soon as our bot publish it on releases page.

**Comment by ElYoM** [comment]
Ok, thank you for the explanations. I'm not very familiar with GitHub's operation. ;)

**Comment by JigSawFr** [comment]
@ElYoM no problem ! You can now get release https://github.com/Jackett/Jackett/releases/tag/v0.7.247 to test new features of this PR.

**Comment by ElYoM** [comment]
Awesome ! It works. Thank you again. My CouchPotato install is now very happy. ^^

**Comment by maxcore** [comment]
all site in my jackett fail to logging after the update what wrong

**Comment by nucshuco** [comment]
have same issue as maxcore
Freenas 9.10
rolled back works fine

**Comment by nucshuco** [comment]
`Source value:
Jackett.Utils.Clients.WebClientByteResult ---> System.ArgumentNullException: Array cannot be null.
Parameter name: bytes
  at System.Text.Encoding.GetString (System.Byte[] bytes) <0x20fa00 + 0x0008a> in <filename unknown>:0
  at Jackett.JackettModule.<Load>m__2 (Jackett.Utils.Clients.WebClientByteResult be, Jackett.Utils.Clients.WebClientStringResult str) <0x3a13a0 + 0x00030> in <filename unknown>:0
  at AutoMapper.Internal.MappingExpression`2+<>c__DisplayClass57_0[TSource,TDestination].<AfterMap>b__0 (System.Object src, System.Object dest) <0x3a1300 + 0x00094> in <filename unknown>:0
  at AutoMapper.TypeMap.<get_AfterMap>b__40_0 (System.Object src, System.Object dest) <0x3a11c0 + 0x0006e> in <filename unknown>:0
  at AutoMapper.Mappers.TypeMapObjectMapperRegistry+PropertyMapMappingStrategy.Map (AutoMapper.ResolutionContext context, IMappingEngineRunner mapper) <0x398a30 + 0x00331> in <filename unknown>:0
  at AutoMapper.Mappers.TypeMapMapper.Map (AutoMapper.ResolutionContext context, IMappingEngineRunner mapper) <0x395df0 + 0x001e0> in <filename unknown>:0
  at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map (AutoMapper.ResolutionContext context) <0x3950a0 + 0x00673> in <filename unknown>:0
  --- End of inner exception stack trace ---
  at Jackett.Indexers.BaseIndexer+<FollowIfRedirect>c__async0.MoveNext () <0x7c58b0 + 0x0024f> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7b99b0 + 0x00038> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7b94e0 + 0x00118> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7b9410 + 0x000b3> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x2841a0 + 0x00042> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x28ffa0 + 0x0001a> in <filename unknown>:0
  at Jackett.Indexers.IPTorrents+<ApplyConfiguration>c__async0.MoveNext () <0x7c1540 + 0x00865> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7b99b0 + 0x00038> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7b94e0 + 0x00118> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7b9410 + 0x000b3> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x2841a0 + 0x00042> in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7c6f70 + 0x0001a> in <filename unknown>:0
  at Jackett.Controllers.AdminController+<Configure>c__async4.MoveNext () <0x7bf8d0 + 0x006dd> in <filename unknown>:0
05-13 23:56:56 Error Exception in Configure AutoMapper.AutoMapperMappingException:

Mapping types:
WebClientByteResult -> WebClientStringResult
Jackett.Utils.Clients.WebClientByteResult -> Jackett.Utils.Clients.WebClientStringResult

Destination path:
WebClientStringResult
`

**Comment by flightlevel** [comment]
@JigSawFr Going to revert this for now with so many on autoupdates, unfortunately, haven't got time to have a look whats happening right now.
All providers failing here on mono 3.10.0 and mono 4.2.1
```05-14 22:26:45 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()' System.Web.Http.Action: ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()'
05-14 22:26:45 Debug UnixLibCurlWebClient:GetString(Url:https://freshon.tv/browse.php) 
05-14 22:26:45 Debug UnixLibCurlWebClient:GetString Returning InternalServerError =>  
05-14 22:26:46 Info Found 0 releases from FreshOnTV ```

The joys of coding & debugging on windows and then running on mono!

**Comment by ElYoM** [comment]
@JigSawFr Jackett autoupdate this night to version 0.7.251.0 and Bluetigers doesn't work anymore (log indicates "Error - Exception in Configure")... :( 
Do you have any infos on how to revert to previous because I don't find the windows installer for previous version ? Thanks.

**Comment by JigSawFr** [comment]
As @flightlevel said, there are some problems on Mono versions, i will take a look ASAP, thanks for revert.
Please be patient for trackers that need TLS 1.1 / 1.2 for their SSL certs.
(As BlueTigers for example, they are not functional until future fix).
Stay tuned.

**Comment by ElYoM** [comment]
Ok, thank you. I will wait the necessary time.

**Comment by flightlevel** [comment]
@JigSawFr Had a quick go at bluetigers

I pasted
```System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;``` here https://github.com/Jackett/Jackett/blob/0746616b43b591c0a39914e29b63607df95b68f5/src/Jackett/Utils/Clients/HttpWebClient.cs#L48 and it seemed to work

**Comment by JigSawFr** [comment]
@flightlevel tested with mono 3.x and 4.x ? Thanks

**Comment by flightlevel** [comment]
@JigSawFr Seemed to go alright on my mono. Maybe give this release a day or two as a pre-release to see how we go.

@ElYoM Can you update to https://github.com/Jackett/Jackett/releases/tag/v0.7.271 and report back. Its a pre-release, so tick 'Update to pre-release in Jackett', then 'Apply server settings', then check for update, wait a minute and then see how you go.

**Comment by ElYoM** [comment]
@flightlevel Hello, I have updated to pre-release v0.7.271 like you asked and I confirm that the fix it's working now, I can add Bluetigers. I will made some tests and I come back to you if, eventually, I found a bug. Thank you very much.

**Comment by JigSawFr** [comment]
@flightlevel same for me i've updated my docker container and it's working with bluetigers and others. (Mono 4.x)
It's great to say that we can now support TLS 1.1 & 1.2 Certificate :)

**Pull request merged**
