### PR TITLE
Add imdb, tvdb and tvmaze to feed base release

### PR DESCRIPTION
**Pull request by Celsiusss**
#### Description

MTV uses the BaseFeedIndexer. So now imdb, tvdb and tvmaze IDs gets added to MTV releases.

### CODE REVIEW

**Review by ilike2burnthing — CHANGES_REQUESTED** [review]
Anime Tosho (the other indexer which uses BaseNewznabIndexer) returns the attribute `imdb`, rather than `imdbid` (although I'm not sure they actually use it).

The [Newznab docs](https://newznab.readthedocs.io/en/latest/misc/api.html#list-of-attributes) specify that it's `imdb`, rather than `imdbid`. As an example, Jackett returns both, `imdb` for the 'short' (numerical) ID, and `imdbid` for the full ID (not sure if others do the same). We'd need to be able to handle both.

The only other ID attribute the docs specify is for TVRage, so not TVDB or TVmaze. Either we'd need to stick to the specs here, and then add overrides to the indexers, or we'd need to add all ID attributes here. I'd be leaning towards the former. @garfield69 / @mynameisbogdan thoughts?

**Comment by garfield69** [comment]
IMO The basenewsnabindexer should stick to the newsnab specs.
if MTV has added other ids to their service then they are now in custom territory, so the MTV indexer should apply overrides to support these non-newsnab features.

**Comment by Celsiusss** [comment]
@ilike2burnthing @garfield69 
Thanks for the feedback.
I moved tvdbid and tvmazeid into the MTV sub class, and kept imdb in the base class.

**Comment by ilike2burnthing** [comment]
Should we rename `BaseNewznabIndexer` to `BaseTorznabIndexer`?

**Comment by ilike2burnthing** [comment]
Is there a reason Prowlarr only accepts `rageid` and not also `rage`?

Should `traktid`/`trakt` be included, as it's not part of the spec?

**Comment by garfield69** [comment]
Apologies to Celsiusss from me, It seems I did not read the current specifications document properly. I jumped to the external references section that pointed to an old newsnab spec https://torznab.github.io/spec-1.3-draft/external/newznab/api.html#predefined-attributes

**Comment by garfield69** [comment]
As for Traktid, doubanid and tmdbid, I added them to our torznab output along with some categories that were not in the 1.3 specs. I figured since it was unlikely anyone was ever going to go beyond the 1.3 draft specs I might as well add some new ids and cats that were becoming prevalent at some sites, and as long as they did not clash with existing specs they should be be ok.

**Comment by ilike2burnthing** [comment]
So going forward, do we build on the specs and include Trakt, TMDB, and Douban in BaseNewznabIndexer (and NewznabRssParser), as well as accommodating non-standard attribute names such as `tvdb` and `rage`?

**Comment by garfield69** [comment]
My approach up to now has been to only include a new id only when I discover that there are torznab/newsnab indexers in our stable whose web sites either allow searching for, or present ids in their results that we reprocess into torznab/newsnab output.
What I had not appreciated up to now, was that the torznab 1.3 specs also included an upgrade to the newsnab specs to 1.3 too ;-)

**Comment by garfield69** [comment]
as for whether to add ids without the id, up to now I had thought that the only variance was imdb, which also had imdbid, one being the number only and the other the ttnumber. All the other ids had the id suffix, and I did not think we should have added the same information under a different name.

**Comment by ilike2burnthing** [comment]
https://github.com/Prowlarr/Prowlarr/issues/1261 and https://github.com/Prowlarr/Prowlarr/issues/656 were both for newznab indexers, so yea, doesn't really affect us then.

So just `rageid`, `tvdbid`, `tvmazeid`, `imdb` (short), and `imdbid` (full) added to BaseNewznabIndexer then?

**Comment by garfield69** [comment]
yeah

**Comment by Celsiusss** [comment]
cool

**Comment by garfield69** [comment]
Thank you.

**Comment by garfield69** [comment]
v0.21.2387

**Pull request merged**
