### PR TITLE
nCore definition with all the available categories

### PR DESCRIPTION
**Pull request by iharosi**
Replaced nCore indexer with definition file.
Covered all the available categories.
Categories mapped with newznab predefined categories.

### CODE REVIEW

**Comment by kaso17** [comment]
Thank you for your contribution.
The C# indexer had a little more logic which can't be easily converted into the definition format. E.g. to deal with e.g. translated series titles (see issue #1450).
Is this logic no longer needed?

@morpheus133 can you have a look at this too?

**Comment by morpheus133** [comment]
Hi!
The logic is still needed. 
@iharosi  what is the reason behind this change?

**Comment by DrRabiu** [comment]
I'm new here  I need something to do

**Comment by iharosi** [comment]
@morpheus133 are you sure? I need to check the logic first because honestly I skipped to do it at the first place. The reason why I replaced the indexer for the definition file was to fix an issue which prevented to have nCore's english categories in Jackett. I've tested it for movies with Radarr and it worked correctly. I don't have too much time lately but please let me check this logic first and I'll get back to you. :S

**Comment by morpheus133** [comment]
Check this:
http://127.0.0.1:9117/torznab/ncore/api?t=tvsearch&cat=5030,5040,100041&extended=1&apikey=[APIKEY]&offset=0&limit=100&q=Shimmer%20and%20Shine&season=1&ep=1
With the current one it will find the series and episode  with your not.

How can I reproduce your problem with the "nCore's english categories in Jackett".

**Comment by kaso17** [comment]
closing this one

**Pull request closed without merging**
