### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kevinpawsey**
Added AudioBookBay in Supported Public Trackers

### CODE REVIEW

**Comment by kaso17** [comment]
now you created a master to master pull request containing only the readme change. please merge your patch-1 branch into your master branch. Then it should work.

**Comment by kevinpawsey** [comment]
OK, I have merged my patch-1 to my master... still seems to be failing... so sorry for this :P  First time I have tried to do this :)

**Comment by kaso17** [comment]
Merged, thank you.

Fixes #3160

**Comment by kevinpawsey** [comment]
Glad I could be of some help :-)

**Pull request merged**
