### PR TITLE
[Cardigann] Code Quality Enhancement

### PR DESCRIPTION
**Pull request by mikeoscar2006**
Handles #12281.
It's a WIP and I'll constantly push commits. Reviewers whenever you get time, try to test if all indexers are working with the new commits.

### CODE REVIEW

**Comment by garfield69** [comment]
It will be useful to know if there are any special testing requirements aside from the usual, for any of the PR's related to this clean up, 
My testing usually consists simply of  performing a TEST-ALL on all 359 indexers on my personal active list (a mixture of public, semi and private) and checking the log for signs of issues.
I don't normally test downloads or check closely the results fields content and try the details links etc. unless given a heads up that this may be impacted by changes in the PR. Thanks.

**Review by garfield69 — APPROVED** [review]
~~LGTM~~
tested about 80 with keywordless searches, all good.
then picked about 14 different indexers with followredirect and tested searching with those, all good.
of those, I then enabled enhanced logging and initiated a random download for each to check the download selector debug messages
when testing itorrent got a download failure, ~~turns out the selector needs adjusting~~. so error handling was tested for downloads in this example.
and testing download block infohash with hellastz shows that they have changed their requirements from a thankyou to a downloadcheck so there is another good test result. [edit] needs work after the double GET issue is resolved.
finally tested download block infohash with kinozal and got a download. so all good there.
I think that covers the scope of the changes youv'e made, did I leave anything out?

**Review by garfield69 — CHANGES_REQUESTED** [review]
Ah, may have found a bug while testing downloading with itorrent.
with Jackett 0.18.737 the flow from the debug logs looks like this:
```
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://itorrent.ws/torrent/30619/the_fountain_2006_bdrip_x264_10bit_hun_texas/)
WebClient(HttpWebClient2): Returning OK => 30496 bytes
-dump of html redacted-
CardigannIndexer (itorrent): Download selector a[href^="/torrentfiles/"] matched:
<a class="btn btn-primary seed-warning  jq-download" href="/torrentfiles/30619/the_fountain_2006_bdrip_x264_10bit_hun_texas.torrent">
	<i class="fa fa-download"></i>
	TORRENT LETÖLTÉSE</a>
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://itorrent.ws/torrentfiles/30619/the_fountain_2006_bdrip_x264_10bit_hun_texas.torrent)
WebClient(HttpWebClient2): Returning OK => 6980 bytes <BINARY>
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://itorrent.ws/torrentfiles/30619/the_fountain_2006_bdrip_x264_10bit_hun_texas.torrent)
WebClient(HttpWebClient2): Returning OK => 6980 bytes <BINARY>
Executing FileContentResult, sending file with download name 'The.Fountain.2006.BDRip.x264.10Bit.HUN-TeXaS.torrent' ...
```
which sends torrent to my torrent client. not sure why we are seeing double GETS but whatever.

with this PR 0.18.747  however I get this
```
Debug WebClient(HttpWebClient2): Returning OK => 30492 bytes
-dump of html redacted-
Debug CardigannIndexer (itorrent): Download selector a[href^="/torrentfiles/"]'s torrent file is invalid, retrying with next available selector 
Error CardigannIndexer (itorrent): Download selectors didn't match:
-dump of html redacted-
Error Error downloading. indexer: itorrent path: https://itorrent.ws/torrent/30619/the_fountain_2006_bdrip_x264_10bit_hun_texas/
System.Exception: Download selectors didn't match
   at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1888
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in D:\a\1\s\src\Jackett.Server\Controllers\DownloadController.cs:line 56 
```
current itorrent download block
```yaml
download:
  selectors:
    - selector: a[href^="/torrentfiles/"]
      attribute: href
```
if I modify the itorrent to add additional selectors
```yaml
download:
  selectors:
    - selector: a[href^="/torrentfiles/"]
      attribute: href
    - selector: a[href^="magnet:?xt="]
      attribute: href
```
the logs show
```
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://itorrent.ws/torrent/30619/the_fountain_2006_bdrip_x264_10bit_hun_texas/
-dump of html redacted-
CardigannIndexer (itorrent): Download selector Jackett.Common.Models.selectorField matched:
<a class="btn btn-primary seed-warning  jq-download" href="/torrentfiles/30619/the_fountain_2006_bdrip_x264_10bit_hun_texas.torrent">
	<i class="fa fa-download"></i>
	TORRENT LETÖLTÉSE</a>
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://itorrent.ws/torrent/30619/the_fountain_2006_bdrip_x264_10bit_hun_texas/)
-dump of html redacted-
CardigannIndexer (itorrent): Download selector a[href^="/torrentfiles/"]'s torrent file is invalid, retrying with next available selector
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://itorrent.ws/torrent/30619/the_fountain_2006_bdrip_x264_10bit_hun_texas/)
-dump of html redacted-
CardigannIndexer (itorrent): Download selector Jackett.Common.Models.selectorField matched:
<a href="magnet:?xt=urn:btih:b864021e37c37718bdf8e0e1a3b7ea4fecc8efa2&amp;dn=The.Fountain.2006.BDRip.x264.10Bit.HUN-TeXaS&amp;tr=http%3A%2F%2Ftracker.itorrent.ws%3A80%2Fannounce" class="btn btn-success seed-warning">
	<i class="fa fa-magnet"></i>
</a>
Executing RedirectResult, redirecting to magnet:?xt=urn:btih:b864021e37c37718bdf8e0e1a3b7ea4fecc8efa2&dn=The.Fountain.2006.BDRip.x264.10Bit.HUN-TeXaS&tr=http%3A%2F%2Ftracker.itorrent.ws%3A80%2Fannounce.
```
and the magnet is sent to my torrent client.

kinozal whose download block looks like
```yaml
download:
  before:
    path: get_srv_details.php
    inputs:
      action: 2
      id: "{{ .DownloadUri.Query.id }}"
  infohash:
    before: true
    hash:
      selector: li:first-child
      filters:
        - name: regexp
          args: ([A-F|0-9]{40})
    title:
      selector: div.b
      filters:
        - name: trim
```
sends the magnet no problem

acgsou with a download block 
```yaml
download:
  selectors:
    - selector: a[href^="magnet:?xt="]
      attribute: href
```
sends the magnet no problem

animefree with download block
```yaml
download:
  selectors:
    - selector: a[href*="/engine/download.php?id="]
      attribute: href
```
also fails like itorrent.

**Comment by garfield69** [comment]
as an aside, hellastz also fails with the current jackett 0.18.746
those double GETS may be the cause of the issue, and may flow on, into your PR as well causing the issue?
log
```
Debug | CardigannIndexer (hellastz): Download selector a[href^="download.php?id="] matched: <a href="download.php?id=c4a4512a4e50c3fa0f10668b520a1617c88f92c8&amp;f=%CE%99%CE%A3%CE%A4%CE%9F%CE%A1%CE%99%CE%91+%CE%A4%CE%97%CE%A3+%CE%95%CE%9B%CE%9B%CE%97%CE%9D%CE%99%CE%9A%CE%97%CE%A3+%CE%9B%CE%9F%CE%93%CE%9F%CE%A4%CE%95%CE%A7%CE%9D%CE%99%CE%91%CE%A3+%CE%94%27%CE%A4%CE%9F%CE%9C%CE%9F%CE%A3+-+%CE%91%CE%A1%CE%93%CE%A5%CE%A1%CE%99%CE%9F%CE%A5+%CE%91%CE%9B%CE%95%CE%9E%CE%91%CE%9D%CE%94%CE%A1%CE%9F%CE%A3+PDF.torrent&amp;key=65e77908" title="Κατέβασμα Torrent">
Debug | WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://hellastz.com/download.php?id=c4a4512a4e50c3fa0f10668b520a1617c88f92c8&f=ΙΣΤΟΡΙΑ+ΤΗΣ+ΕΛΛΗΝΙΚΗΣ+ΛΟΓΟΤΕΧΝΙΑΣ+Δ%27ΤΟΜΟΣ+-+ΑΡΓΥΡΙΟΥ+ΑΛΕΞΑΝΔΡΟΣ+PDF.torrent&key=65e77908)
Debug | WebClient(HttpWebClient2): Returning OK => 8451 bytes <BINARY>
Debug | WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://hellastz.com/download.php?id=c4a4512a4e50c3fa0f10668b520a1617c88f92c8&f=ΙΣΤΟΡΙΑ+ΤΗΣ+ΕΛΛΗΝΙΚΗΣ+ΛΟΓΟΤΕΧΝΙΑΣ+Δ%27ΤΟΜΟΣ+-+ΑΡΓΥΡΙΟΥ+ΑΛΕΞΑΝΔΡΟΣ+PDF.torrent&key=65e77908)
Debug | WebClient(HttpWebClient2): Returning OK => 96 bytes <BINARY>
Error  Δεν είστε εξουσιοδοτημένος να κατεβάσετε. Συγνώμη...
Error downloading. indexer: hellastz path: https://hellastz.com/index.php?page=downloadcheck&id=c4a4512a4e50c3fa0f10668b520a1617c88f92c8 System.Exception: BencodeParser failed  ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found ' ' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'    at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)    at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)    at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)    at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in D:\a\1\s\src\Jackett.Server\Controllers\DownloadController.cs:line 78    --- End of inner exception stack trace ---    at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in D:\a\1\s\src\Jackett.Server\Controllers\DownloadController.cs:line 85
```

**Comment by mikeoscar2006** [comment]
> I think that covers the scope of the changes youv'e made, did I leave anything out?

Yeah, that should be it. Thanks for all the testing.
Regarding the latest bugs, I'm gonna find out what's happening.

**Comment by mikeoscar2006** [comment]
Sorry, I made a typo which caused Jackett to request the details page link instead of torrent file link. Hence all the double requests and magnets were unaffected. Fixed it!

**Comment by garfield69** [comment]
yes that has fixed itorrent.
but the double GET of the torrent binary still exists (which was present prior to this PR and may have been introduced when we added that BEFORE block variation a little while back).
So while itorrent a public site does not mind the double GET of the torrent binary, hellastz objects to the second GET for the same torrent
```
Debug CardigannIndexer (hellastz): handleRequest() requestLinkStr= https://hellastz.com/thanks.php
Debug WebClient(HttpWebClient2).GetResultAsync(Method: POST Url: https://hellastz.com/thanks.php PostData: {infohash=db05e4dff5536bed3b89367d7c9f4e58b87c11fe, thanks=1, rndval=1487013827343} RawBody: )
Debug WebClient(HttpWebClient2): Returning OK => 157 bytes
<a href="https://hellastz.com/index.php?page=userdetails&id=nnnnnn"><img src=/gods/hermes.png border=0><span style='color:#C9BE62'>username</span></a> |1
Debug CardigannIndexer (hellastz): handleRequest() remote server returned OK
Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://hellastz.com/index.php?page=downloadcheck&id=db05e4dff5536bed3b89367d7c9f4e58b87c11fe)
-dump of html suppressed-
Debug CardigannIndexer (hellastz): Download selector Jackett.Common.Models.selectorField matched: <a href="download.php?id=db05e4dff5536bed3b89367d7c9f4e58b87c11fe&amp;f=%CE%A3%CE%A4%CE%A1%CE%91%CE%92%CE%A9%CE%9D-%CE%93%CE%95%CE%A9%CE%93%CE%A1%CE%91%CE%A6%CE%99%CE%9A%CE%91+%CE%92%27.torrent&amp;key=nnnnnnnn" title="Κατέβασμα Torrent"> 	<img src="images/download.gif" border="0" alt="Κατέβασμα Torrent" title="Κατέβασμα Torrent">&nbsp;&nbsp;Download Now</a>
Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://hellastz.com/download.php?id=db05e4dff5536bed3b89367d7c9f4e58b87c11fe&f=ΣΤΡΑΒΩΝ-ΓΕΩΓΡΑΦΙΚΑ+Β%27.torrent&key=nnnnnnnn)
Debug WebClient(HttpWebClient2): Returning OK => 6090 bytes <BINARY>
Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://hellastz.com/download.php?id=db05e4dff5536bed3b89367d7c9f4e58b87c11fe&f=ΣΤΡΑΒΩΝ-ΓΕΩΓΡΑΦΙΚΑ+Β%27.torrent&key=nnnnnnnn)
Debug WebClient(HttpWebClient2): Returning OK => 96 bytes <BINARY>
Error  Δεν είστε εξουσιοδοτημένος να κατεβάσετε. Συγνώμη...
[translation: You are not authorized to download. Sorry...]
Error Error downloading. indexer: hellastz path: https://hellastz.com/index.php?page=downloadcheck&id=db05e4dff5536bed3b89367d7c9f4e58b87c11fe
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found ' ' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Server\Controllers\DownloadController.cs:line 78
   --- End of inner exception stack trace ---
```
the hellastz download block looks like this
```yaml
download:
  before:
    path: thanks.php
    method: post
    inputs:
      infohash: "{{ .DownloadUri.Query.id }}"
      thanks: 1
      rndval: "1487013827343"
  selectors:
    - selector: a[href^="download.php?id="]
      attribute: href
```

**Comment by mikeoscar2006** [comment]
@garfield69, I don't think it is due to the before block PR. There is an excerpt of code that first tests the torrent file link and then sends it to download which is why we are getting double requests.
Here is an excerpt from a [commit](https://github.com/Jackett/Jackett/blob/2d3e079eb6a3c602864af3872aa87fe6a8c7c430/src/Jackett.Common/Indexers/CardigannIndexer.cs) before any of my commits:
```c#
var torrentLink = resolvePath(href, link);
if (torrentLink.Scheme != "magnet")
{
    // Test link
    response = await base.RequestWithCookiesAsync(
        torrentLink.ToString(), null, RequestType.GET, headers: headers);
    if (response.IsRedirect)
        await FollowIfRedirect(response);
    var content = response.ContentBytes;
    if (content.Length >= 1 && content[0] != 'd')
    {
        logger.Debug(
            $"CardigannIndexer ({Id}): Download selector {querySelector}'s torrent file is invalid, retrying with next available selector");
        continue;
    }
}

link = torrentLink;
return await base.Download(link, method, link.ToString());
```
The only changes this PR introduces is the quality changes and not affecting any functionality. Do you know why this testing is present?

**Comment by garfield69** [comment]
using the blame option on github I see that https://github.com/Jackett/Jackett/pull/11907 is responsible for this code,
as a solve for https://github.com/Jackett/Jackett/issues/11865
perhaps you can take a look and see if its evident to you why that code is there and if there is any improvement that can be made.

**Comment by mikeoscar2006** [comment]
The code is there to test if the extracted torrent link returns a valid torrent file. If not, it should process other selectors if provided. Basically, to prevent an error from being thrown when downloading the torrent.
I can only think about one or two things but need some more time to think. Maybe it's better to deal with this in a separate issue?

**Comment by garfield69** [comment]
okely dokely. I'll reopen 11865.
so are you able to merge this PR yourself or does github insist someone else do it?

**Review by garfield69 — APPROVED** [review]

**Comment by mikeoscar2006** [comment]
Yeah, I'll do it. Thanks!

**Comment by mikeoscar2006** [comment]
I've squashed and merged @garfield69 (other options "were not enabled for this repository"). Lmk if anything else has to be done next time.

**Pull request merged**
