### PR TITLE
Added Torrenting.me (Torrenting.com) 

### PR DESCRIPTION
**Pull request by twistedroutes**
based on @JigSawFr 's WiHD implementation (after a few simple translations...mon francais est mauvais!) and my bitsoup and xspeeds implementation.  This could be a useful template going forward.

I backed out of adding the RSS capability to this because the RSS feed had no seeder numbers - I assume (didn't check) that that would result in it's sources being considered inferior to another indexer.

as with this implementation, WiHD and BItSoup they all provide additional configuration information in the indexer config.  Should we have an update to the html template to have advanced options section, that most users could leave untouched, but would give the user configuration ability, but visually un-clutters the interface ?

### CODE REVIEW

**Comment by Azerelat** [comment]
The implementation looks to be ok but I can't accept it for three reasons
1. Its an open tracker
2. Its run by the folks behind IPT who are really dodgy, there is a reason they got doxed.
3. There are merge conflicts.

**Comment by twistedroutes** [comment]
resolved the merge with the last commit, but on the others...OK.

how do we know what is IPT vs not?

**Comment by twistedroutes** [comment]
Also think I'll still keep this around as a template :-)

**Comment by twistedroutes** [comment]
I will refresh my fork so I can update just the bitsoup part then.  that needs the GUID field to exist, but I missed it first time round.  If you can share some info on how you determined torrenting.me is an IPT affiliate/owned tracker that'd help.  Maybe this can be the first step in new tracker requests so I didn't spend the time on it.

**Pull request closed without merging**
