### PR TITLE
core: remove unused imports

### PR DESCRIPTION
**Pull request by ngosang**

### CODE REVIEW

**Comment by cadatoiva** [comment]
I've done this one once before this recent PR in #7159 so the files are getting out of sync with all the work we're doing. It might be useful to selectively turn on parts of the style guide enforcers that we've already taken care of so that future code must pass the checks without us having to remember all the rules.

**Comment by ngosang** [comment]
The way of forcing the style guide is adding a Job in Azure Pipelines, but I don't know if it's possible to enable it in the current state... We will have to disable all checks but "unused imports" :smile: 
@junglebus What do you think?

**Comment by cadatoiva** [comment]
Well, we can enforce the whitespace guidelines with dotnet format as well, and that one is a single command. https://pumpingco.de/blog/enforcing-a-consistent-coding-style-across-projects-and-programming-languages/amp/#installcodeformatters

There's also adding the StyleCop NuGet package for other style enforcement that creates build failures on violation of certain types. With each refactoring PR we make we could turn on the corresponding checks in the StyleCop so that we don't have to go back like this and cleanup changed code.

**Comment by cadatoiva** [comment]
Most articles I've read about adding a style guide to an existing project point out that a strategy of "fix the base then turn on enforcement" piecemeal like this is the preferred method.

**Comment by junglebus** [comment]
Can add it to the pipeline. I was think of creating of creating a second editorconfig file, `.editorconfig-passing` that the CI would use. That way as things get cleaned up, copy and paste the extra rule in and it will now be enforced. It would slowly get to the point where all the rules in `.editorconfig` make it over to `editorconfig-passing` and we'd then remove it. Thoughts?

Also, can anyone get `dotnet format` to run at the solution level, it's only working at the single project level for me e.g.
`dotnet format --check --verbosity diagnostic --workspace ./src/Jackett.sln` fails

`dotnet format --check --verbosity diagnostic --folder ./src/Jackett.Common` works nicely

**Comment by ngosang** [comment]
> Can add it to the pipeline. I was think of creating of creating a second editorconfig file, .editorconfig-passing that the CI would use. 

I agree

**Comment by cadatoiva** [comment]
It's been running for me at a solution level from day one. Also, since the editor config doesn't by itself create build errors or have Pipeline support for failing a build by itself, it's probably not a good idea to double up on the config. Instead, since `dotnet format` does very little to enforce the style guide, we can just add that check in its entirety. It's then a matter of adding other addons like StyleCop which have their own config for turning on or off certain checks.

**Comment by cadatoiva** [comment]
I don't specify a `--workspace` or `--folder` argument though, so I think the equivalent is `--folder ./src`

**Pull request merged**
