### PR TITLE
[Feature] [BeyondHDApi] Added option to extend title with available HDR for hybrid releases

### PR DESCRIPTION
**Pull request by PNWebster**
**Summary**
The intention of this PR is to allow users of Jackett to include the HDR formats in the title, if they require this information.

**Background**
Some trackers, such as BeyondHD, allow releases that contain multiple HDR format. Whether a release is hybrid, and the exact formats contained within these releases are not always obvious from a given title.

Examples:
_The Lost City 2022 UHD BluRay 2160p TrueHD Atmos 7.1 DV HEVC REMUX-FraMeSToR_ contains both Dolby Vision and HDR10 
_Collateral Beauty 2016 DV 2160p WEB DD5.1 H.265-SLOT_ only contains Dolby Vision.

As discussed in this PR #11481 BeyondHD has added this information to the API since the indexer was created.

**Screenshots**
Opt-in behaviour in settings:
image
When enabled:
image

### CODE REVIEW

**Review by garfield69 — CHANGES_REQUESTED** [review]
while its true that ConfigurationDataAPIKeyAndRSSKey.cs is currently only used by beyondhdapi, it is a generic model config which could be used by other indexer in the future.
please do not delete.

**Comment by PNWebster** [comment]
> while its true that ConfigurationDataAPIKeyAndRSSKey.cs is currently only used by beyondhdapi, it is a generic model config which could be used by other indexer in the future. please do not delete.

Thanks for the feedback. I was struggling a bit with this. When I add BHDConfiguration as an subclass, the Settings screen gets all messed up due to the order of how the settings are read. It ended up being:
1. Site Link
2. My new setting
3. API Key
4. RSS Key
5. Instruction
6. Tags

Should I keep the ConfigurationDataAPIKeyAndRSSKey which will become unused, while keeping the BHDConfiguration as a seperate copy?

**Comment by garfield69** [comment]
whatever works for you. if you are wanting to put the config in its own cs then store it in
src/Jackett.Common/Models/IndexerConfig/Bespoke/ 

Suggested name ConfigurationDataBeyondHDApi.cs

**Comment by PNWebster** [comment]
> whatever works for you. if you are wanting to put the config in its own cs then store it in src/Jackett.Common/Models/IndexerConfig/Bespoke/
> 
> Suggested name ConfigurationDataBeyondHDApi.cs

I'm not sure how I missed those bespoke configurations, thanks for pointing them out. I have re-added the ConfigurationDataAPIKeyAndRSSKey, and moved BHD configuration into a bespoke configuration

**Comment by garfield69** [comment]
So, have you tested your latest changes and are you happy for me to merge?

**Comment by PNWebster** [comment]
> So, have you tested your latest changes and are you happy for me to merge?

Yes and yes

**Review by garfield69 — APPROVED** [review]

**Comment by garfield69** [comment]
Thank you.

**Comment by garfield69** [comment]
v0.20.1463

**Pull request merged**
