### PR TITLE
fix: u2 upload/download volume factor

### PR DESCRIPTION
**Pull request by trim21**
#### Description

torrents with `img.pro_custom` have dynamic upload/download rate

#### Issues Fixed or Closed by this PR

* Fixes https://github.com/Jackett/Jackett/issues/14457

### CODE REVIEW

**Comment by trim21** [comment]
I tested this locally:

image

**Review by ilike2burnthing — COMMENTED** [review]
Are these the only custom values used? If so, then this should be fine.

If not, we should be able to modify your example from https://github.com/Jackett/Jackett/issues/14457#issuecomment-1592790089 to work here.

**Comment by trim21** [comment]
> Are these the only custom values used? If so, then this should be fine.
> 
> If not, we should be able to modify your example from [#14457 (comment)](https://github.com/Jackett/Jackett/issues/14457#issuecomment-1592790089) to work here.

these the only custom values used currently, site admin may add more values, but I didn't saw these values change for a very long time(~2 years).

That example is a better idea, but I dont' know how to impl it.

**Comment by ilike2burnthing** [comment]
Test https://github.com/Jackett/Jackett/pull/14461.

**Comment by trim21** [comment]
That example I posted doesn't work. I just updated my issue comment and you need to copy it again.

**Comment by ilike2burnthing** [comment]
Thanks, updated.

**Comment by trim21** [comment]
close this in favor of https://github.com/Jackett/Jackett/pull/14461 https://github.com/Jackett/Jackett/pull/14462

**Pull request closed without merging**
