### PR TITLE
(Add) hd4free.yml

### PR DESCRIPTION
**Pull request by HDVinnie**
- #3827

### CODE REVIEW

**Comment by garfield69** [comment]
Cheers

**Comment by durango99** [comment]
@HDVinnie It looks like your code uses regular login but when I check the login page, it includes a reCAPTCHA.  Does this work with that?  Thanks

**Comment by HDVinnie** [comment]
@durango99 UNIT3D does indeed now use reCAPTCHA on login page. 

However for HD4Free, Blutopia, Redtopia, BTXpress, Racing4Everyone and a few other indexers in Jackett that use UNIT3D. You just need cookie instead of creds for login. 

Maybe @garfield69 or @kaso17 can help figure out the new reCAPTCHA part.

**Comment by garfield69** [comment]
as I understand it, there is no current solution to the reCAPTCHA challenge.
The circumvention at the moment is to replace https://github.com/Jackett/Jackett/blob/ab6f7d52188afb83fe825b1cc3550786af7a3149/src/Jackett.Common/Definitions/hd4free.yml#L27-L35
with 
```yaml
  settings:
    - name: cookie
      type: text
      label: Cookie
          
  login:
    method: cookie
    inputs:
      cookie: "{{ .Config.cookie }}"
    test:
```
and rinse and repeat for any other UNIT3D sites that have the reCAPTCHA enabled.

**Comment by durango99** [comment]
Thanks for confirming using the cookie method as the workaround.

**Pull request merged**
