### PR TITLE
Add PublishDate to Potato feed for Radarr

### PR DESCRIPTION
**Pull request by onedr0p**
#933

### CODE REVIEW

**Comment by flightlevel** [comment]
@kaso17 Messaged radarr devs on discord regarding this one

**Comment by hotio** [comment]
I agree with keeping the focus on full Torznab compatibility accros radarr, sonarr, etc.
https://github.com/Radarr/Radarr/issues/236#issuecomment-272555529

If I recall correct, they implemented TorrentPotato because Jackett didn't work (doesn't return movies)...?

However it wouldn't hurt to merge this and extend TorrentPotato...

Just my 2 cents.

**Comment by kaso17** [comment]
I personally consider Torznab the "better" API (more attributes available, RSS compatible, not limited to Movies, ...). But Radarr probably would have to support both APIs anyway.

I would have no problem accepting this PR but I would like to ask you to try to coordinate this new attribute with the CouchPotato team so in the end it's properly documented (https://github.com/CouchPotato/CouchPotatoServer/wiki/Couchpotato-torrent-provider)

**Comment by onedr0p** [comment]
I'll get in contact with them, this shouldn't break anything moving forward with jackett.

**Comment by onedr0p** [comment]
Also I do believe we shouldn't wait for the cp team to make up their mind. They could easily say fuck off.

This also effects their code too, so maybe they will acknowledge it.

**Comment by savahu** [comment]
CP is not a team, it's just 1 guy who doesn't have time for the project anymore, unfortunately.

**Comment by hotio** [comment]
Yes, don't go waiting on RuudBurger, it feels as if he just puts duct tape on it once in a while to keep it running.

**Comment by onedr0p** [comment]
Thank you :)

**Comment by kaso17** [comment]
merged.
0846ea6a98152eae58a951eb0c4064bc50e861d9 makes sure it's UTC ISO 8601 format.df85d334a355ac6f9586586334e571d80737ac9a hides it if it hasn't been set by the indexer.

@RuudBurger: Can you please update the Couchpotato torrent provider wiki entry to reflect this new optional attribute?
publish_date: Publish date (UTC) of the release in ISO 8601 format.

**Comment by RuudBurger** [comment]
Added to https://github.com/CouchPotato/CouchPotatoServer/wiki/Couchpotato-torrent-provider

**Comment by onedr0p** [comment]
Woah, howdy RuudBurger!

**Pull request merged**
