### PR TITLE
Add Trezzor

### PR DESCRIPTION
**Pull request by gregorij89**
Adding Trezzor tracker (https://tracker.czech-server.com)

### CODE REVIEW

**Comment by kaso17** [comment]
please remove the (newline?) changes from .github/appveyor.yml

**Comment by gregorij89** [comment]
I am really sorry, but I am a newbie in GitHub things, so I know what you want from me, but I don't have absolutely any idea how to do it. The best thing to do is removing the changes in .github/appveyor.yml completely from the commit because they were made by IDE, not by me - and have no meanings. It´s my mistake, I should notice this changes and exclude this file before committing.

It took me almost a month to figure out, that I must fork the project to make changes and then request them to merge with master. I´ve been literally banging my head against the wall during all 403 errors when I was trying to add my changes to this repository after I´ve cloned it - and not forked and cloned.

Thanks for your patience.

**Comment by gregorij89** [comment]
Ok, now it looks like I´ve somehow managed it out.

**Comment by halali** [comment]
@gregorij89 can you pull CZTorrent tracker Please, i really need it

**Comment by gregorij89** [comment]
Hi @halali, not until I get approval from tracker management. They are considering it right now and as soon as I get their conclusion, I will eventually create a pull request. I am a member of this tracker and I don´t want to get banned. It is also in your interest to wait a little longer because if they will approve my piece of code, it is unlikely that they will block it in the future. As you probably know, the tracker has issues with overloading and they are concerned about that. As soon as I will have some new info I´ll post it here (or probably in #1151 thread).

**Comment by halali** [comment]
@gregorij89 Thx for this information and also big thank to your work...

**Comment by halali** [comment]
any news about CZTorrent ?

**Pull request merged**
