### PR TITLE
torrentbytes: add imdb search

### PR DESCRIPTION
**Pull request by ngosang**
Tested. Part of #4859

### CODE REVIEW

**Comment by ngosang** [comment]
@RoloSoze ping

**Comment by jyggen** [comment]
Can't say I'm a huge fan of forcing IMDb support onto TorrentBytes (and possibly other trackers) by abusing the fact that a lot of torrents have an IMDb link in their descriptions. After some quick testing it returns fewer matches than straight up searching for the movie/show name - so the end user will end up suffering due to this change since software like Radarr and Sonarr will, as far as I know, skip title search entirely if IMDb support is reported by Jackett. Just my 2¢.

**Comment by RoloSoze** [comment]
> 
> 
> Can't say I'm a huge fan of forcing IMDb support onto TorrentBytes (and possibly other trackers) by abusing the fact that a lot of torrents have an IMDb link in their descriptions. After some quick testing it returns fewer matches than straight up searching for the movie/show name - so the end user will end up suffering due to this change since software like Radarr and Sonarr will, as far as I know, skip title search entirely if IMDb support is reported by Jackett. Just my 2¢.

Hi @jyggen - I get your point. I have already covered this here https://github.com/Jackett/Jackett/issues/4859#issue-419301248 in the first two paragraphs. Unfortunately, not every tracker implements IMDb ID association correctly. Ideally, you would want every single movie and TV upload to be linked to its corresponding IMDb ID, but that's not the reality of the situation. 

I don't personally use Radarr and Sonarr, so I cannot comment on those, but when searching Jackett manually, if the IMDb ID search is possible in a given tracker, I think Jackett should support it. Many other trackers, especially the Chinese ones, require users to enter the IMDb URL, but users don't always do it, so you get fewer results despite the official IMDb ID support.

Personally I search using both the title & year, and the IMDb ID, and pick whatever release suits me best.

**Comment by cadatoiva** [comment]
@jyggen It might skip some relevant results, but it could also be that some of those results were unrelated, which means they should be skipped anyway.

Sonarr/Radarr/*arr (the Arrs) devs have stated that if IMDb Support is enabled they will first search with IMDb ID, and if no results fallback to keyword search. I need to double check with them to see if that includes searches that may return results, but 100% of them are rejected by the various user configured filters. If that is the case, then the only time a user may suffer from reduced results in an IMDb search is if a higher quality result is omitted and a lower quality one remains, as the Arrs will grab the SD release and not try to keyword search for a 720p or 1080p upgrade, as example.

Even then, this too is only a problem for users with a single tracker in Jackett or their respective Arr.

**Comment by RoloSoze** [comment]
I'll also add that in many instances, even when the IMDb ID search is not exhaustive - since it's not officially supported by the tracker - it's still a better method of searching for certain titles that may be difficult to search for otherwise. 

This is especially true for movie/series titles that have only numbers in them, are too short (have very few letters), or have many special characters that are not handled well by the tracker's processing of search keywords.

**Pull request merged**
