### PR TITLE
cardigann: respect the categories from search paths

### LINKED ISSUE #13697: [req]: searchPath category filter
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

ATM, Cardigann has the following method:
https://github.com/Jackett/Jackett/blob/4d33f93e102171b2240b06af8b429b76c865a8e7/src/Jackett.Common/Indexers/CardigannIndexer.cs#L1348-L1360

with the wiki description
```yaml
search:
  paths:
      # [OPTIONAL] list of tracker categories
      # If specified the path will be only used if at least one category from the list is included in
      # the search categories list. A "!" as first entry negates the matching logic (include the path 
      # in any other than the specified categories is in the search categories list)
      categories: ["!", 901, 902]
    - path: torrents.php
      # don't use this path if we're only searching for porn
      categories: ["!", 901, 902]
     - path: xxx.php
      # only use it if we're searching for porn
      categories: [901, 902]
```

So, given this real example from bitbazis
https://github.com/Jackett/Jackett/blob/4d33f93e102171b2240b06af8b429b76c865a8e7/src/Jackett.Common/Definitions/bitbazis.yml#L98-L109

I've added the following debug statements to a build so I could understand what actually happens
```
SearchPath=browse.php
hasInvertMatch=True
mappedCategories=[22,58,69,68,91,33,89,66]
SearchPathCategories=[!,33,66,89]
hasIntersect=True
finalIntersect=True (the searchPath will be skipped)
SearchPath=browse_xxx.php
hasInvertMatch=False
mappedCategories=[22,58,69,68,91,33,89,66]
SearchPathCategories=[33,66,89]
hasIntersect=True
finalIntersect=False (The searchPath will be actioned)
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://bitbazis.net/browse_xxx.php?c22=1&c58=1&c69=1&c68=1&c91=1&c33=1&c89=1&c66=1&search=&sort=4&type=desc&incldead=1)
```
which results in only the browse_xxx path being used, with all the categories that were selected being passed to the query.

All the above is my long winded way of saying that I don't think this is the ideal way to handle searchPath categories

### Describe the solution you'd like

I would like for the SearchPath categories to act as a filter, which is to say, that only those categories that are included in the filter are passed through to the searchPath. If none are filtered through then the searchPath is skipped.

Using the bitbazis example above, I expect to see both searchPath being used, with the following http GETs being produced:
```
https://bitbazis.net/browse.php?c22=1&c58=1&c69=1&c68=1&c91=1&search=&sort=4&type=desc&incldead=0
https://bitbazis.net/browse_xxx.php?&c33=1&c89=1&c66=1&search=&sort=4&type=desc&incldead=1
```

### Describe alternatives you've considered

_No response_

### LINKED ISSUE #14393: The content under some Categories cannot be searched
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
running in docker :yes
x86/64
synology
```

### Description

Some content under the 404 Categories of the kp.m-team.cc site cannot be searched，I'm sure I've checked 100404 in sonarr, but I've tried several episodic documentaries and they don't search

By the way I also tried prowlarr, also can't search, but can search in jackett alone to search

### Logged Error Messages

```text
05-28 21:55:33 Info Torznab search in M-Team - TP (2FA) for Story of Chuaner S01 => Found 0 releases [13941ms]
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by mynameisbogdan**
#### Issues Fixed or Closed by this PR

* Fixes #13697
* Fixes #14393
* Closes #14353

### CODE REVIEW

**Review by ilike2burnthing — APPROVED** [review]
Working well with ygg, torlock, and bitbazis (once updated https://github.com/Jackett/Jackett/commit/12da8b6131a3938b0be86a9872fe0d4a2bef636a).

**Comment by garfield69** [comment]
fantastic! 🍾 Thank you.

**Comment by PN62323424** [comment]
> Working well with ygg, torlock, and bitbazis (once updated [12da8b6](https://github.com/Jackett/Jackett/commit/12da8b6131a3938b0be86a9872fe0d4a2bef636a)).
> 
> Also closes #14353?
Is this Issues fixed in the sonarr v4 version? It seems that it still doesn't work on kp.m-team.cc, refer to https://github.com/Jackett/Jackett/issues/14393

**Comment by PN62323424** [comment]
> Actually with mteamtp I tested the changes with the links provided by your logs.
> 
> To what should I refer to in #14393? Improper use of categories not supported by Sonarr?

The problem I encountered in #14393 still exists today.

The title is: The Story Of Chuaner 2018 WEB-DL 1080p H264 AAC-HDCTV 

The category is: 404

But if I search for the season and still can't find the episode, do I need to provide a log or something

**Comment by PN62323424** [comment]
> Actually with mteamtp I tested the changes with the links provided by your logs.
> 
> To what should I refer to in #14393? Improper use of categories not supported by Sonarr?

<html>
<body>


The title is: ：Aerial China 2017 S01 2160p WEB-DL AAC 2.0 H.265-PTerWEB

The category is: 404

This one is also not searchable



</body>
</html>[Aerial China 2017 S01 2160p WEB-DL AAC 2.0 H.265-PTerWEB](https://kp.m-team.cc/details.php?id=681261&hit=1)

**Comment by PN62323424** [comment]
Even before, I could find The Story Of Chuaner season 1 by searching in jackett, but I just never found it in sonarr. I think it's sonarr's problem 。。。。

**Comment by PN62323424** [comment]
> Did you updated your Jackett to the latest version? I have to ask since you didn't provided any logs.
> 
> I tried it just now with a bunch of Torznab and Tracker categories, and it works as intended.
> 
> I can't guess your setup since you're not willing to use it properly, but my bet is on user error here. Maybe using adult categories without the adult mode enabled in the User Control Panel which results in a HTTP redirect thus in Cardigann warnings.
> 
> Proof: https://i.ibb.co/mCg4hFS/Screenshot-2023-06-03-at-21-48-59.jpg

I think I've solved the problem, it's the sonarr aspect, thanks again

**Pull request merged**
