### PR TITLE
gazelletracker: add sitelink to poster if needed

### PR DESCRIPTION
**Pull request by ilike2burnthing**
https://github.com/Jackett/Jackett/commit/e347d38fc031a4ed3bb72063d31a0c3ccc155978#r52162683

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
@garfield69 unfortunately this doesn't quite work, as local posters are formatted in the json as `"cover":"2021\/original_152222_manual_3.jpg"` but the actual URL is `https://desitorrents.tv/static//media/posters/2021/original_152222_manual_3.jpg`, so just adding the site link isn't enough.

**Comment by garfield69** [comment]
Ah. so we would have to provide an override from the desi indexer to fill in the missing path segment, and this would only work if `static/media/posters/` never changed between different posters on this site.
Do you happen to know if this is the case?
@seeyabye Assuming `static/media/posters/` was a constant, do you see a possible solve to allow the desi to override the abstract for the posters?  
Or maybe we should be get the API provider to fill it in properly?

**Comment by ilike2burnthing** [comment]
Posters on the site will apparently be fixed soon - https://github.com/Jackett/Jackett/pull/11909#issuecomment-860240941 - but yes, currently (at least as far as I've seen) that path is consistent.

**Comment by seeyabye** [comment]
I personally don't think this is a good PR.

Desitorrents is an interesting one. They allow 3rd party posters and also self-hosted posters too. So there's no one size fit all solution. I would still stick with the solution I proposed, by checking if the poster's URL is parsable by `URI()` otherwise, just skip it and leave it to downstream subclass indexers like `Desitorrents.cs` to resolve the correct URL.

@garfield69 there is a way to do it in a subclass. I might make a PR on this later, but preferably this should be solved by the tracker themselves. The API should always return an expected result, but in desitorrent's case, the result is either a JSON or a full URL which is inconsistent. As highlighted in https://github.com/Jackett/Jackett/pull/11909#issuecomment-860240941, it should be fixed soon.

**Comment by ilike2burnthing** [comment]
Would this work?
`GazelleTracker.cs`
```
    public abstract class GazelleTracker : BaseWebIndexer
    {
        protected virtual string LoginUrl => SiteLink + "login.php";
        protected virtual string APIUrl => SiteLink + "ajax.php";
        protected virtual string DownloadUrl => SiteLink + "torrents.php?action=download&usetoken=" + (useTokens ? "1" : "0") + (usePassKey ? "&torrent_pass=" + configData.PassKey.Value : "") + "&id=";
        protected virtual string DetailsUrl => SiteLink + "torrents.php?torrentid=";
        protected virtual string PosterUrl => SiteLink";
        protected virtual string AuthorizationFormat => "{0}";
        protected virtual int ApiKeyLength => 41;

[...]

                    Uri poster = null;
                    if (!string.IsNullOrEmpty(cover))
                        poster = (cover.StartsWith("http")) ? new Uri(cover) : new Uri(PosterUrl + cover);
```
`DesiTorrents.cs`
```
        protected override string PosterUrl => SiteLink + "static/media/posters/";
```

**Comment by seeyabye** [comment]
I like this approach much better.

**Pull request merged**
