### PR TITLE
Add new indexer moviesite

### PR DESCRIPTION
**Pull request by jawlkumuna**
Hungarian general private tracker with open registration at the moment.

Login doesn't work for some reason and I couldn't figure out how to parse the date, but the rest is hopefully ok.

### CODE REVIEW

**Review by ilike2burnthing — APPROVED** [review]
Switched to form login, it works, but I couldn't fix the login error trap, it just results in a redirect. Using `followredirect` didn't help. @garfield69 any clue if I'm missing something obvious there?

Site doesn't seem to have sort and order functions so removed them.

Site doesn't allow searching with fewer than 4 characters, so just using `browse.php` for keywordless search. Searching with fewer than 4 characters in Jackett returns `browse.php`.

Site can return results without a a download link (awaiting mod approval) so added `has download.php` to row selector. Can't only use that though because of the duplicate download link, so also added `has details.php`.

Using `andmatch` filter because even when searching by torrent name `search_type=t_name` it returns unrelated results.

Filtered out the 18+ icon posters and used a different location for the description (can sometimes be the full title, other times can be a much shorter title). Also added imdbid, files, and grabs selectors.

The date was fun... ;P

Once again thank you for the contribution!

**Review by garfield69 — APPROVED** [review]
\o/

**Comment by garfield69** [comment]
>Switched to form login, it works, but I couldn't fix the login error trap, it just results in a redirect. Using followredirect didn't help. @garfield69 any clue if I'm missing something obvious there?

yup, you are not looking at what was actually returned by the site when jackett makes it login attempt.
While I usually start by using the browser to see what the default login, error, success and browser pages contain, when it comes time to make it work I turn on enhanced logging and look at what Jackett sees.

>Site doesn't seem to have sort and order functions so removed them.

yes, the web site defaults to added/desc when search terms are entered, but the engine can handle sorting if you provide the complete parm sets.

>Site doesn't allow searching with fewer than 4 characters, so just using browse.php for keywordless search. Searching with fewer than 4 characters in Jackett returns browse.php.

seems to be a JS trap on the web site, but it does not prevent results and looks ok in jackett response.

>Using andmatch filter because even when searching by torrent name search_type=t_name it returns unrelated results.

site appears to have a plus prefix on keywords that correctly filters.

Well done everybody, another one in the bag.

**Comment by garfield69** [comment]
v0.19.207

**Pull request merged**
