### PR TITLE
add aro.lol a Serbian/English anime site

### PR DESCRIPTION
**Pull request by Xandaboss**
Commits may need to be squashed.

### CODE REVIEW

**Comment by Xandaboss** [comment]
Not sure why the last commit didn't pass CI as I only changed a string. This should be good to squash and merge.

**Comment by ilike2burnthing** [comment]
Thanks for the contribution.

The indexer link is just the domain.

To double-check everything is working ok before merging - https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/5937/artifacts?artifactName=drop&api-version=7.0&%24format=zip

**Comment by Xandaboss** [comment]
Confirmed working, thanks!

**Comment by garfield69** [comment]
v0.20.1144

**Pull request merged**
