### PR TITLE
Add the ability to select multiple public indexers at one time.

### PR DESCRIPTION
**Pull request by wdupree**
Add a checkbox column to the add indexers datatable which allows multiple selection of public indexers to add at one time.

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
Seems to work well, though I noticed that after adding multiple indexers I get `Selected indexers successfully added.` each time I delete an indexer. Refreshing the page stops this.

**Comment by wdupree** [comment]
> Seems to work well, though I noticed that after adding multiple indexers I get `Selected indexers successfully added.` each time I delete an indexer. Refreshing the page stops this.

hmm... I deleted indexers one at a time when I bulk added - I'll have to check and see what might be happening. Thanks for letting me know.

**Review by wdupree — COMMENTED** [review]
Added changes to force the unbind from the ajaxstop listener

**Comment by ilike2burnthing** [comment]
Can you resolve the conflict with `index.html`? It's just the change timestamp.

**Comment by garfield69** [comment]
>Can you resolve the conflict with index.html? It's just the change timestamp.

done.

**Comment by ilike2burnthing** [comment]
Yep, that fixed it. Thanks for the contribution.

**Review by ilike2burnthing — APPROVED** [review]

**Review by garfield69 — CHANGES_REQUESTED** [review]
This is cosmetic, but on my chrome, the **Add Selected** button does not behave the same way as the **Close** button right next to it.
The **Close** button starts with a _white_ background, goes _grey_ as you hover over it.
The **Add Selected** button always has  a _grey_ background.

Ideally the buttons should behave the same way. Can you update?

**Review by garfield69 — APPROVED** [review]
sorted :-)

**Comment by wdupree** [comment]
> sorted :-)

Thanks :)

**Comment by garfield69** [comment]
v0.18.88

**Pull request merged**
