### PR TITLE
MoreThanTV Rewrite & Header Support for Login

### PR DESCRIPTION
**Pull request by ryanm352**
Some sites require headers to login, otherwise they will mark you as a bot and disable your account. **RequestLoginAndFollowRedirect** has been modified to support headers for the `WebRequest`

Resolves [Issue 6783](https://github.com/Jackett/Jackett/issues/6783)

### CODE REVIEW

**Comment by dwp4ge** [comment]
Confirmed change is working properly
image

**Comment by ryanm352** [comment]
@ilike2burnthing -- we've got more than a few peeps excited for this, can you take a look at this one this week?

**Comment by ilike2burnthing** [comment]
I was hoping ngosang would have been back by now but I think he's been really busy over the last few weeks.

I don't have an account to check this either (don't worry, not invite begging, just letting you know that's why). @garfield69 / @RoloSoze can you test that the indexer works as it should?

@XYZJR could you take a look at the code please?

**Comment by ilike2burnthing** [comment]
Well I typed all that below, went back to do one last check, and I can no longer log in via Jackett. I removed the indexer, restarted Jackett, enabled enhanced logs, and tried once more, no joy.

Can still log into the site fine, but Jackett returns an `Object reference not set to an instance of an object` error, with repeated 0 byte redirects to the login page. Given it's not my account, I'm not about to try troubleshooting whether it's an issue on my end or with the indexer.

Someone else will need to test this out for a few hours to a day - searching, logging in and out of the site, removing the indexer, restarting Jackett and re-adding the indexer, etc..

-----

So I was able to test it (thank you, don't know if you want named).

Thanks @ryanm352 for the contribution, for the most part this is working, hopefully the comments below will just require small changes.

First issue is with the site: when results are grouped, it only shows the details for one of them, I'm assuming the first, so Jackett returns the same size, grabs, seeds, and leechers for a DVDRip and a 1080p WEB-DL. Nothing we can really do though.

Next issue is with the site as well, but can be resolved (kinda): the details pages for results don't work, you just get a failed search, so the details links should probably just be replaced with the sitelink.

Searching by IMDB ID doesn't work on the site, and in Jackett returns results for a keywordless search.

Sorting by time added, size, and seeders (as well as ordering by ascending or descending) is available on the site, so could be added to the indexer as well.

The search variables `tags_type` and `group_results` don't exist, so can be removed, and `searchsubmit` doesn't seem to be used.

`action=basic` is used by the indexer, whereas the site uses `action=advanced`. In saying that, I couldn't tell what the difference was.

**Comment by ryanm352** [comment]
- Thanks for getting this started! The site is a little different. I can clean up what you mentioned, but yes, the grouping is different. The site displays the same data for all items in a group (filesize, peers, etc).

- I can replace the site links, no problem.

- I can remove the tags,  group_results, etc. I wasn't sure how the new site functioning. Apparently, right now only "title" returns results, even on the page itself.

- I noticed the action basic/advanced made no difference, either

This is a customized version of luminance, so I tried to get results from what they had. I'll clean up this stuff. They mentioned that there will be some coding changes, so I don't mind maintaining in the meantime.

**Comment by ryanm352** [comment]
@ilike2burnthing 

> Next issue is with the site as well, but can be resolved (kinda): the details pages for results don't work, you just get a failed search, so the details links should probably just be replaced with the sitelink.
>
  **resolved**: was able to use the details.php to pull up details for a torrent Id.

> Searching by IMDB ID doesn't work on the site, and in Jackett returns results for a keywordless search.
>
 **resolved**: removed IMDB -- useless :)
 **Re kewordless search**: Returning results with keywordless search is default Jackett behavior. 

> Sorting by time added, size, and seeders (as well as ordering by ascending or descending) is available on the site, so could be added to the indexer as well.
> 
**?** Sorting is all done in jackett. As long as I'm pulling results, jackett seems to default to the "published date". Users can sort results locally by column the column to sort by.

> The search variables `tags_type` and `group_results` don't exist, so can be removed, and `searchsubmit` doesn't seem to be used.
>
**resolved**: removed-- useless 
> `action=basic` is used by the indexer, whereas the site uses `action=advanced`. In saying that, I couldn't tell what the difference was.
>
**resolved**: swapped to `advanced` .. but yes, this seemed to make no difference

**Comment by ilike2burnthing** [comment]
> Re kewordless search: Returning results with keywordless search is default Jackett behavior.

Sorry, that was in reference to searching by IMDB ID, so if you searched `tt4154796` in Jackett you got the same results as a keywordless search.

> Sorting is all done in jackett. As long as I'm pulling results, jackett seems to default to the "published date". Users can sort results locally by column the column to sort by.

So long as a site supports sorting, we can request those results. Given that Jackett typically only requests the first page of results, this is useful when you have more than a single page of results (e.g. 300 results, 50 per page) and you want to find the most recent, most seeded, or largest (and changing the order would allow you to get the oldest, least seeded, or smallest). See [InternetArchive.cs](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/InternetArchive.cs) as an example.

The rest looks good, thanks again.

**Comment by ryanm352** [comment]
Thanks! I've added the sorting capabilities (I didn't even know that was a thing) and cleaned up the IMDB searches.
Also fixed the issue you were having with object undefined by checking if a user is logged in already (/login redirects to / and sets a sid)

**Review by garfield69 — APPROVED** [review]
LGTM from a usage POV, tested OK.

**Pull request merged**
