### PR TITLE
Fix Date and improve seasson searching for CzTorrent

### PR DESCRIPTION
**Pull request by halali**
If you have better solution for seasson searching pls tell me

### CODE REVIEW

**Comment by kaso17** [comment]
thank you but why didn't you use the re_replace filter?

**Comment by halali** [comment]
i was trying solve stuff with seasson packs for sonarr.

with acftual re_replace filter it works fine until there where multi seasson pack, output was like 
Red Dwarf 1.​ -​S10 (CZ)

and i try filter like this 
```          - name: replace
            args: ["série", "Seasson"] 
          - name: re_replace
            args: ["(\\d{2}).", "S$1"]
          - name: re_replace
            args: ["(\\d{1}).", "S0$1"] 
```
than output was like 
Red Dwarf S01 -​SS01 Seasson (CZ)

so i decided to do it in this way :)

**Comment by kaso17** [comment]
I think you've to escape the dot:
```
          - name: replace
            args: ["série", "Seasson"] 
          - name: re_replace
            args: ["(\\d{2})\\.", "S$1"]
          - name: re_replace
            args: ["(\\d{1})\\.", "S0$1"] 
```

Is "Seasson" intentionally spelled with two s (In English it would be "Season")?

**Comment by halali** [comment]
You are right season with  one S

now is it good :D

Thank you

**Comment by kaso17** [comment]
thank you

**Comment by halali** [comment]
1 more question,

is there any command to remove diacritic from titles ?

becouse radarr is not able to read it

**Comment by kaso17** [comment]
There's a diacritics filter, it's not perfect but should cover simple cases.
`
      - name: diacritics
        args: replace
`

**Comment by halali** [comment]
yea it works, will test it for few days and will push witch new tracker SkTorrent where need solve some issues with selectors

**Pull request merged**
