### PR TITLE
Fixed search to match with Sonarr and Radarr standards.

### PR DESCRIPTION
**Pull request by a-nunes**
It fixes the search of BJ-Share to match radarr and sonarr standards. Fix issue #4365 too.

### CODE REVIEW

**Comment by garfield69** [comment]
nice one. thanks.

**Comment by a-nunes** [comment]
> nice one. thanks.

No problem. I thin that you marked the wrong contributor on the pre-release. Hehehe, could you adjust it, please?

**Comment by garfield69** [comment]
I did not manually create the description contributor, its automated using github's record of your a/c.
its because your a/c username is loaded as Artur Ligieri Nunes
I've edited the release description now, but this will keep happening any time you submit a PR.

**Comment by a-nunes** [comment]
A

> Nice one, but you forgot to close the brackets xD
> image

Actually you didn't update your version. It's The old one. 

Here is how it's returning. 

Screenshot_20191021-142343_Chrome

**Comment by christianfds** [comment]
> > Nice one, but you forgot to close the brackets xD
> > image
> 
> Actually you didn't update your version. It's The old one.
> 
> Here is how it's returning.
> 
> Screenshot_20191021-142343_Chrome

Actually i'm running on the latest version 0.12.847

**Comment by garfield69** [comment]
@christianfds 
if you are using jackett on a linux platform it's possible that you may have been bitten by the auto-updated bug in #5208.

Please shutdown your jackett service and manually upgrade your jackett with the latest version and try again.

**Comment by christianfds** [comment]
Sorry for the long time to answer.
I'm runing jackett on linux, but im using a the latests docker image, perhaps the bug happened on the docker image. 
image

I tested deploying a new container and the bracket issue persisted.
image

**Comment by christianfds** [comment]
Actually i noticed that INTERNAL releases and already downloaded movies aren't being retrieved with its quality. If i have sometime this week i shall fix it.

**Pull request merged**
