### PR TITLE
webui: fix poster flicker. resolves #12847

### LINKED ISSUE #12847: Cover art dialog flickers
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-01-17 00:30:16.7024 Info Starting Jackett v0.20.363 
2022-01-17 00:30:17.7346 Info Environment version: 6.0.1 (/app/Jackett/) 
2022-01-17 00:30:17.7356 Info OS version: Unix 4.4.180.0 (64bit OS) (64bit process) 
2022-01-17 00:30:17.7370 Info Jackett variant: CoreLinuxAmdx64 
2022-01-17 00:30:17.7373 Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l 
2022-01-17 00:30:17.7373 Info Running in Docker: Yes (image build: v0.20.363-ls55) 
2022-01-17 00:30:17.7388 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
2022-01-17 00:30:17.7388 Info App config/log directory: /config/Jackett 
2022-01-17 00:30:17.7401 Info Using proxy: Disabled 
2022-01-17 00:30:17.7401 Info Using FlareSolverr: No 
2022-01-17 00:30:17.7424 Info Using HTTP Client: HttpWebClient2
```

### Description

If you hover over a title in the search results, the cover art dialog will flicker

### Logged Error Messages

```text
n/a
```

### Screenshots

Screenflick Movie 9

### PR DESCRIPTION
**Pull request by ngosang**

### CODE REVIEW

**Comment by ngosang** [comment]
@ilike2burnthing @garfield69 this need some testing.
The image proxy feature does not introduce this issue but it makes image load slower making the issue more noticeable.

**Review by ilike2burnthing — APPROVED** [review]
Posters now display below the name, rather than above as previously, but it doesn't cause any issues. So long as that was intentional, this looks fine to me.

**Comment by ngosang** [comment]
By default the `placement: "top"` but I was having issues so I changed it to `placement: "auto"` (it's bottom...). You can test other values if you want. The documentation => https://getbootstrap.com/docs/4.0/components/tooltips/#options

**Comment by ilike2burnthing** [comment]
No, all good, just checking.

**Pull request merged**
