### PR TITLE
Add Ethor tracker

### LINKED ISSUE #182: [FR] Ethor.net
Hi, I just found your Jackett app for Windows. It's a life changer.

I would like to request support for 2 private trackers
ethor -> http://ethor.net/dp#/?
T411 -> http://www.t411.in/

Thanks

### PR DESCRIPTION
**Pull request by kaso17**
Fix #182

### CODE REVIEW

**Comment by maxcore** [comment]
Its christmas !!! Thx man for this one really! I cant wait to back home to test this!

**Comment by dardano** [comment]
Thanks ! Is there a specific syntax for the cookie input ? I tried multiple ways to get it working and it fails every time.

Thanks for adding this tracker.

**Comment by maxcore** [comment]
https://github.com/Jackett/Jackett/wiki/Finding-cookies

**Comment by garfield69** [comment]
Jackett 0.16.2256

**Pull request merged**
