### PR TITLE
RevTT: added files count

### PR DESCRIPTION
**Pull request by la55u**
Messed up the commits a bit, but the result is pretty straightforward imo.

### CODE REVIEW

**Comment by flightlevel** [comment]
@la55u I don't understand why you are modifying the `ParseUtil`. Can you please explain reason?

**Comment by la55u** [comment]
I just thought there is no reason to use a long for such a small number, and giving it a default value doesn't effect where it's being used already.

**Comment by kaso17** [comment]
@la55u the result still will be converted back to long (return type) and the final Files value is a long value too. So you code doesn't safe any memory. Please undo the ParseUtil changes.

**Comment by la55u** [comment]
oh my god, that was some next level stupidity, sorry about it... Is it ok now?

**Comment by kaso17** [comment]
merged, thank you

**Pull request merged**
