### PR TITLE
core: immutable query. resolves #8531

### LINKED ISSUE #8531: Searching in All trackers through Manual search cuts last keyword for many trackers
e.g. "harry potter azkaban" will search only for "harry potter" at bakabt, beyond-hd, bibliotik. bigfangroup, bitru ... passthepopcorn, redacted, kinozal ... lots of them

### PR DESCRIPTION
**Pull request by ngosang**
Not tested!

@cadatoiva I need your knowledge. Take a look at #8531 first. The query object is shared across all indexers. Ideally I want to make that object immutable or readonly so it can't be modified after creation. If one tracker, like BakaBT, tries to change some attribute it must fail (not compile ideally).

I don't know how to do that so in this PR I'm cloning the object before running the tasks. This should work but I'm not comfortable because maybe I forget some usage more.

Update: #8531 was fixed in #8666 but this PR is still need to avoid future problems in other indexers.

### CODE REVIEW

**Comment by cadatoiva** [comment]
Wow, sorry to leave you hanging for a month. I didn't realize how long it's been. The best way to do make it immutable is to make the field `readonly` so they can't change the underlying query after the object is created.

**Comment by ngosang** [comment]
Welcome back! we miss you.
Could you open a PR so I can close this one?

**Comment by cadatoiva** [comment]
I will after I download 4GB of Visual Studio updates at 2Mbps.

**Comment by XYZJR** [comment]
Marking a reference type variable or field as readonly, such as `int[] Categories` might not do what we want because while indexers might not be able to set a new array `query.Categories = new int[]`, they'll still be able to add or remove categories. Only a ReadOnlyCollection<T> might stop that, as far as I know, meaning that all categories have to be known when calling `TorznabQuery`'s constructor.

Cloning the query might still be our best option. I'm looking into it.

**Pull request merged**
