### PR TITLE
[Feature] Linkomanija option to search in description

### PR DESCRIPTION
**Pull request by syncck**
~~Not ready jet!~~
Edit: This can be merged now

### CODE REVIEW

**Comment by syncck** [comment]
Hi, is it possible to make "-name" line configurable via checkbox? "Search in description" will not work because of `andmatch` filter. Also, `andmatch` filter ommits search results, containing native language characters, like `ąčęėįšųūž', so this filter needs to be as option.
```
  rows:
    selector: table> tbody > tr:has(a[href^="details?"])
    filters:
      - name: "{{ if .Config.andmatch }}andmatch{{ else }}{{ end }}"
```

**Comment by garfield69** [comment]
As things are ATM, I do not think the row filters can support a `- name:` that has no functionName following.
And If I have read the C# code correctly (and I cant be 100% sure because I am not a C# dev) I don't thing the `- name:` can support an if-then-else-end clause either.
To do what your propose would need C# code enhancement to the Cardigann processor.
You could raise an Enhancement request ticket, and if we are lucky a C# dev may add this feature.

**Comment by syncck** [comment]
> As things are ATM, I do not think the row filters can support a `- name:` that has no functionName following. And If I have read the C# code correctly (and I cant be 100% sure because I am not a C# dev) I don't think the `- name:` can support an if-then-else-end clause either. To do what your propose would need C# code enhancement to the Cardigann processor. You could raise an Enhancement request ticket, and if we are lucky a C# dev may add this feature.

I see, more intrusive changes are needed here, but probably not necessary. I hope this can be merged with `andmatch` removed then, it is better to see results with non english characters for non english tracker. Here are an examples of improvements:

Original search results, as is before this PR:    


Serach result is limited (andmatched) only to single search result;

--------
Current PR results, without `andmatch` + "search in description" option unticked:   

2101S



Now native language characters are not filtered out, we get three results, which we can filter by category (still better than was):    

2309U
If filtering only movies, we get the same results as before this PR.

----------------
Now with "Search in description" checkbox ticked and filtered to show only movies:  
2625P

These are all valid, because description contains the word "drakona" (native translation from english "dragon").

--------
This can be merged.

**Review by garfield69 — APPROVED** [review]

**Comment by garfield69** [comment]
v0.20.521

**Pull request merged**
