### PR TITLE
[ExtremeTorrents] Replace dutch title keywords

### PR DESCRIPTION
**Pull request by wouter2203**
This replaces dutch keywords so radarr/sonarr understands it.

I've copied it from: https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/film-paleis.yml#L97-L105

Checked locally and it's working as intended.

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
Thanks for the contribution.

If you search on the tracker using the `SxxExx` format, are the relevant `seizoen xx afl xx` results also returned?

If not, have look at https://github.com/Jackett/Jackett/issues/11170 for my (failed) attempts to get Film Paleis to work with this.

Your PR can be published without that, but obviously if it's possible it would be a great addition.

**Comment by wouter2203** [comment]
Now that I've read that thread I think I should close this one. The tracker is using inconsistent naming schemes.

The two schemes I found thus far:
- S01E01 (yay, wish they all used this)
- Seizoen 1 (no episodes, this will be a complete season pack)
- S01 (no episodes, this will be a complete season pack)

If I correctly read the tread you referenced, this cannot be fixed. As only one of the two schemes can be used, if we replace keywords the 'official' S01 will no longer work and vice versa.

If correct, and this can indeed not be fixed as then the 'official' scheme will be broken, you can close this pr!

**Comment by ilike2burnthing** [comment]
It may still be helpful generally, e.g. someone searches for `game of thrones` (no season or episode) in Jackett and then filters their search by `S01E02`, they would then get the relevant results. But yes, unfortunately this won't help with Sonarr.

@garfield69 for this and Film Paleis, would it be worth removing `season` and `ep` from `tv-search`, due to the inconsistent naming schemes not playing well with Sonarr?

**Comment by garfield69** [comment]
>for this and Film Paleis, would it be worth removing season and ep from tv-search, due to the inconsistent naming schemes not playing well with Sonarr?

yes. in general, parms for the modes should only be included if the web site (and therefore the indexer) can support their use.

**Pull request merged**
