### PR TITLE
Add spanish tracker Newpct

### PR DESCRIPTION
**Pull request by snamds**
Support for "newpct" group of web pages (www.tvsinpagar.com, descargas2020.com, torrentrapid.com, etc.)
Movies are only returned in "rss" mode.
For TV, both "rss" and episode search are supported.

### CODE REVIEW

**Comment by snamds** [comment]
https://github.com/Jackett/Jackett/issues/1282
https://github.com/Jackett/Jackett/issues/1293

**Comment by flightlevel** [comment]
@snamds Wow, a lot of work has gone in there, thank you
I hope you can help if this tracker ever requires any changes in the future

**Comment by dtorner** [comment]
Unfortunately the indexer does not work. Using Jackett Version 0.8.975.0. The indexer is not able to find anything using manual search and a well known series/movie title

**Comment by snamds** [comment]
Just tested with manual search and with medusa, it works ok.
Movies are only returned when rss searches are made (blank text search)
For tv shows to be returned, the FULL web series name has to be specified. You can optionally add the season/episode at the end. 
Try, for example, "ray donovan", "ray donovan s03" or "ray donovan s03e02"

**Comment by dtorner** [comment]
Yes, you are totally right, my fail... Thanks you very much for your effort here. Muchas gracias.

**Comment by xbLyed** [comment]
TV shows are working perfectly but Movies don't work for me. Tested with RSS in Radarr and with manual search in Jackett. Can you confirm it is still working?

**Comment by pablitofernandez** [comment]
Has anyone got Radarr + Jackett with Newpct for movie searching?

**Pull request merged**
