### PR TITLE
Digitalcore - Cookie workaround because captcha

### PR DESCRIPTION
**Pull request by ERR1R**
dc added a captcha system.. cookie workaround!

### CODE REVIEW

**Comment by Amras-anon** [comment]
Whats the cookie workaround?

**Comment by ashtonlance** [comment]
Will this be merged soon?

**Comment by garfield69** [comment]
Thanks.

**Comment by Anon0ne** [comment]
I am on linuxserver docker container, and this issue is still there. Any idea where in the docker these files are at?

**Comment by garfield69** [comment]
@Anon0ne  Huh?
this change simply alters the digitalcore config panel to display a cookie box and hint info, instead of the usename/password boxes.
if your jackett dashboard does not display the cookie box when you edit the digitalcore profile, then upgrade your docker image to the latest version.

**Comment by Anon0ne** [comment]
I updated the image linuxserver/Jackett:latest and it didn't apply the fix.

My question is where in the docker images would the indexer config files be located? I cannot find it in the shell script under /config/Indexers.

**Comment by garfield69** [comment]
what version does your jackett dashboard have at the bottom of the page?
the location of the indexers folder for docker images is specified in the docker parameters, with the `-v` specifies where Jackett should store its config file. have a read of https://hub.docker.com/r/linuxserver/jackett/

**Comment by Anon0ne** [comment]
0.12.1398.0

Also, I have a read of the page and have looked in the local folder, as well as inside the actual docker image. Still looking around this image for the location of files, the config folder does not hold the .cs file only the actual setup of your indexers that were added to Jackett.

**Comment by garfield69** [comment]
you are not going to find the .cs file, this is the C# source,  which gets compiled into the binary files that make up the jackett program.
the issue here is that you are not running the latest version of jackett that contains the changed digitalcore indexer c# code. you are still using 0.12.1398 and you need to be on at least version  
 v0.12.1415. The current latest release of jackett is v0.12.1632 

so review how you go about pulling your docker image and once you sort that out you will be good to go.

**Comment by Anon0ne** [comment]
Alright, thanks for clearing up versions required for this. I figured it was a binary and I will figure out compiling or pulling a different docker image.

**Pull request merged**
