### PR TITLE
Add tracker HDBits

### PR DESCRIPTION
**Pull request by adamwinn**
Add tracker HDBits

### CODE REVIEW

**Comment by kaso17** [comment]
It looks incomplete (missing download/details links, etc.). It's missing from the project file/readme too.

I most likely won't have time to do any work on Jackett in the next 2-3 weeks.
@flightlevel @JigSawFr would appreciate if you could take care of pull requests, new releases, etc. 
Would also suggest giving @adamwinn full commit/release permissions. He has been very helpful.

**Comment by adamwinn** [comment]
@kaso17 I messed up that pull request.  It should be better now

**Comment by flightlevel** [comment]
@adamwinn Thanks for your all great contributions. Would you like merge rights?

**Comment by adamwinn** [comment]
@flightlevel Yes, that would be great

**Comment by flightlevel** [comment]
Great! Invite sent @adamwinn 
Happy for you to merge any new trackers or tracker fixes, but any major changes to the core can you please check with someone before merging

**Pull request merged**
