### PR TITLE
core: rewrite category code from scratch. resolves #8049

### LINKED ISSUE #8049: core: category parsing and filtering
I don't like how Jackett handles categories internally. I have found several issues in the C# indexers and each one is solving the problems in his own way or worst, it's not working at all.

In the following examples imagine a regular tracker with movies/tv. Each torrent can have only 1 category and the categories can be MoviesSD, MoviesHD, TVSD, TVHD only.

In the supported categories we have 6: Movies, MoviesSD, MoviesHD, TV, TVSD, TVHD . There aren't torrents with category Movies, but we add that category to search all movies categories.
NOTE: If I remove the Movies and TV categories, everything works fine in the following examples. **What torznabs says about this? Should we add Movies/TV categories in the trackers even if the trackers only have the children categories?**

**Example 1**
If I select category MoviesHD only, it works as expected. Sends MoviesHD id in the search, and filter the results that contains category MoviesHD. All the results are MoviesHD. Good.

**Example 2**
If I select the category "Movies" only. I expect to get all movies with all resolutions, but **I get 0 results.**
1. First issue: Some trackers will have a special category or parent category called Movies to search all resolutions. In that case the mapping is 1 to 1 and it's fine. If the tracker doesn't support that, we need to convert category Movies => categories MoviesSD & MoviesHD to search in the tracker with both. Maybe exists, but **I don't know any function in Jackett to do that conversion.**
2. Second issue: Assume the first issue is solved and the we have the expected results. The results will have the category MoviesSD or MoviesHD. Jackett has a filter that removes the results with a category not in the query.Categories(). In this case, Jackett will remove all results because none of them has the category Movies. **Jackett should be smarter and not remove the results with child categories.**

**Example 3**
If I select the categories "Movies" and "MoviesHD" (both). I expect to get all movies with all resolutions, the same as when I select the category Movies only (example 2). I'm getting only the movies MoviesHD. This case will be fixed if we solve both issues in example 2.

What do you think? @Jackett/maintainers @RoloSoze

### PR DESCRIPTION
**Pull request by ngosang**
* Core: Categories are stored in a real tree
* Sorting: First Torznab categories sorted by Id and then custom cats sorted by Name
* Filtering: Results with child category are not removed when searching by parent category. Details in #8049
* Jacket UI: Add parent category when at least one child category exists
* Torznab (caps): Remove non existent children categories. Remove duplicated categories. Details in #10006

### CODE REVIEW

**Comment by ngosang** [comment]
@garfield69 @ilike2burnthing Please, test this one. You should notice:
* Categories are sorted in different order in Jacket UI and in Torznab xml. IMHO I think this is better but I can change it back.
* In Jackett UI I added missing parent categories and they are fixed. I have been testing with `4000 PC` in IPTorrents. In previous implementation the category was not available. Now it's and you can use it to search in children categories.
* The Torznab xml is better in several ways. This should help to improve the category tree in Sonarr. Please, test it.

**Comment by ilike2burnthing** [comment]
Huh, I never realised cat 1000 was missing too.

Agreed that the tree looks better with your changes.

Searching `2019` in 1337x  for cat 2000 shows a pretty stark difference: 34 results (SD, HD, UHD, Foreign, DVD) using yours, and just 1 using the current release.

Slight aside, as I think I know the answer is no, but is 2045 a child cat of 2040 (and same for 5045 and 6045)? I'm guessing it was just a case of squeezing UHD in somewhere.

Been testing for about the last hour and yet to come across any issues. I'll keep testing and let you know if anything comes up, but all looks good!

**Comment by ngosang** [comment]
> Slight aside, as I think I know the answer is no, but is 2045 a child cat of 2040 (and same for 5045 and 6045)? I'm guessing it was just a case of squeezing UHD in somewhere.

2040 and 2045 are at the same level, both are children of movies. We can add more levels, the code is prepared but default categories in Torznab specs use only 2 levels. I think it's good. => https://github.com/Jackett/Jackett/wiki/Jackett-Categories

**Comment by ilike2burnthing** [comment]
No, it's fine as it is, I just wondered why UHD results weren't showing when I selected HD and then realised.

Can confirm that Sonarr is looking a hell of a lot better as well. It's now this:

new

instead of this:

old

**Review by garfield69 — APPROVED** [review]
For the dashboard search for an indexer's category filter, is it possible to sort the **custom** cats by their Name rather than their custom 100000+ number, in the same way this PR presents them in the **torznab caps**?
I expect most users don't really care what the custom number is, but would find it easier to filter by a custom cat if the Name was alphabetic, especially when scrolling up and down a long category list.
In any case it all LGTM and I've randomly sampled a variety of indexers that use standard, custom numbers and custom string, with dashboard and Sonarr, Radarr and Readarr and looked at the torznab caps too.
Nice job. Thanks.

**Comment by garfield69** [comment]
@ilike2burnthing  you are going to have to learn to use the PR review approval and request changes buttons, so that we know when you have completed your review and are happy for us to proceed with merging or not. Thanks.

**Review by ilike2burnthing — APPROVED** [review]

**Comment by ngosang** [comment]
> For the dashboard search for an indexer's category filter, is it possible to sort the custom cats by their Name rather than their custom 100000+ number, in the same way this PR presents them in the torznab caps?

I'm sending the categories with the same order as in Torznab (same code), but the Javascript code is wrong. I opened a new issue #10047

**Comment by ngosang** [comment]
Jackett v0.16.1996

@Taloth we did several changes in Jackett related to Torznab categories. Since you wrote the category tree in Sonarr => https://github.com/Sonarr/Sonarr/pull/3994 maybe you want to do some tests to see if everything is right.

Related=> https://github.com/Jackett/Jackett/pull/10006#issuecomment-717801929

**Comment by ilike2burnthing** [comment]
Something I hadn't tested in regards to Sonarr was updating with indexers set using the old format - the cats are still displayed using the old mess. Thankfully it's a quick fix, just restart Sonarr and it displays the new tree.

**Comment by ilike2burnthing** [comment]
Small issue, and can only find it affecting iDope and Torrent Downloads, their cat 100000 (Others) is showing at the top of the list:

**Comment by garfield69** [comment]
Oh NO, that's terrible. 
Right, that's it, reverse it out ;-b

he. he. ha. ha.

**Comment by ngosang** [comment]
> Something I hadn't tested in regards to Sonarr was updating with indexers set using the old format - the cats are still displayed using the old mess. Thankfully it's a quick fix, just restart Sonarr and it displays the new tree.

After each update Sonarr is restarted. Users will get the changes soon.

> Small issue, and can only find it affecting iDope and Torrent Downloads, their cat 100000 (Others) is showing at the top of the list:

It's ok to report small issues too. It took me 1 minute to fix it. #10078

**Comment by Taloth** [comment]
I actually don't have Jackett myself. I can do some tests, but having some of your users test would likely be more effective.

Indexer caps are cached for 7 days in memory to avoid wasting api quota on real newznab indexers, so even if there's no update they'll get the new caps eventually.

**Comment by ngosang** [comment]
@Taloth it's already tests, don't spend your time on this. :smile: 

> Indexer caps are cached for 7 days in memory to avoid wasting api quota on real newznab indexers, so even if there's no update they'll get the new caps eventually.

We reduced Torznab categories by half removing duplicates and wrong categories. That should be good for the cache size too.

**Pull request merged**
