### PR TITLE
[Improvement] Use 'Tracker[]' parameter only as secondary filter for CurrentIndexer

### PR DESCRIPTION
**Pull request by CasperVerswijvelt**
Currently, when getting results for a specific indexer, for example torrentfunk `/api/v2.0/indexers/torrentfunk/results`, it gives exactly the same results as it would if you would do this for the aggregate indexer  `/api/v2.0/indexers/all/results`.
Only the query parameters 'Tracker[]' are used to determine which trackers would be used. This results in very confusing behaviour, returning results for other indexers even when already targeting a specific indexer via the url path.

I've changed that the query parameters 'Tracker[]' are only used as a secondary filter to the main indexer found in the url path, meaning it will only be useful when using an aggregate indexer such as 'all' (or others in the future?).

This results in my opinion in a much more logical API, let me know what you think or if something needs to be changed.

### CODE REVIEW

**Comment by CasperVerswijvelt** [comment]
Unfortunately I didn't read contributing guidelines before opening this PR and worked straight of the master branch in my fork, do I open new PR or is this fine?

**Review by garfield69 — APPROVED** [review]
Tested OK, LGTM

**Comment by garfield69** [comment]
Thanks.

**Comment by ilike2burnthing** [comment]
[v0.17.710](https://github.com/Jackett/Jackett/releases/tag/v0.17.710)

**Pull request merged**
