### PR TITLE
cardigann: add `search.allowEmptyInputs`

### PR DESCRIPTION
**Pull request by mynameisbogdan**
Don't merge till #14069 is also ready.

Any thoughts?

https://github.com/Prowlarr/Prowlarr/issues/1470

### CODE REVIEW

**Review by ilike2burnthing — APPROVED** [review]
Looks useful!

**Review by garfield69 — APPROVED** [review]

**Comment by Qstick** [comment]
I think we might have discussed this before, but I can't find it. Is there ever a case where we actually want blank inputs? Should this be default behavior instead of relying on a flag?

**Comment by ilike2burnthing** [comment]
It can be useful to have a full list of inputs, even if they aren't used at the time. For example, when the use of `genre` search was expanded, searching indexers for `genre` and `tag` was easier than accessing every tracker to see if they supported it. Of course, those could just be commented out.

While many of these could probably just be removed/commented, presumably not all - https://github.com/search?q=repo%3AJackett%2FJackett+%22%3A+%5C%22%5C%22%22+language%3AYAML&type=code&l=YAML (apologies for the unrelated login results)

I can't point to a specific indexer atm, but I'm fairly certain we've had cases where an input with no value and no input at all are different, and the default is undesirable, e.g. (where it defaults to `1` if no `dead` input is present):

```yml
# 0 dead only, 1 alive only, "" both
dead: ""
```

I agree that ignoring blank inputs should probably be default behaviour, and instead add `search.allowBlankInputs`. However, that way round we'd have to ensure that blank inputs can be ignored, removed, or commented for all indexers which use them.

Before we start looking at indexers though, @mynameisbogdan would switching to `search.allowBlankInputs` be doable?

**Comment by garfield69** [comment]
>Is there ever a case where we actually want blank inputs?

lemonhd is an indexer where the presence of `&free` is all that is required to enable freeleech search #13921
Although coding `&free=1` also works so this would negate the issue of removing blank inputs by default

>Should this be default behavior instead of relying on a flag?

While I don't see a problem with API indexers, a possible problem could develop down the line with HTML scraping indexers, where the GET URL generated by Jackett/Prowlarr would not longer look like the common URL generated by the owning website (since common parms like `&search=` or `&name=` during most TEST or fetch-latest queries would be missing those parms altogether) and therefore could enable the website to flag Jackett/Prowlarr as a unwanted bot. 
But if that happens then we would delete the indexer anyway since we don't want to index a site that does not want us using it ;-) 

So perhaps making this the default behaviour is reasonable.
If necessary we could implement the reverse, to support an indexer that depends on blank inputs to trigger functions, 
say for instance search.allowBlankInputs

**Comment by ilike2burnthing** [comment]
Thought of a common case which would use empty inputs, keywordless searches for almost every Cardigann definition, e.g.:

```yml
search:
  inputs:
    query: "{{ .Keywords }}"
```

Will run a quick test on all indexers available to me, see if there are any obvious issues.

**Comment by ilike2burnthing** [comment]
Yep, there are a few which use different endpoints (usually it's all done in `paths` rather than `inputs`, a few which use `.Today.Year`, and a few (all Russian?) which use a generic keyword.

**Comment by ilike2burnthing** [comment]
Tested all public and semi-private indexers, and all private indexers I have accounts for, on this test build. Just the two which had issues when using keywordless search. Fixed when enabled `allowEmptyInputs`.

@mynameisbogdan @garfield69 if you can check private indexers I don't have accounts for. Any we collectively don't have accounts for, we'll just have to risk it.

**Comment by garfield69** [comment]
All my privates passed the test.
And no, I'm not talking about a medical check-up ;-b

**Review by ilike2burnthing — APPROVED** [review]
Tested with the indexers included in this PR, a few random ones, and the new indexers added since I last tested that I have access to (not ex-torrenty, kamept, or arabtorrents). All working well!

**Comment by ilike2burnthing** [comment]
> While I don't see a problem with API indexers, a possible problem could develop down the line with HTML scraping indexers, where the GET URL generated by Jackett/Prowlarr would not longer look like the common URL generated by the owning website (since common parms like `&search=` or `&name=` during most TEST or fetch-latest queries would be missing those parms altogether) and therefore could enable the website to flag Jackett/Prowlarr as a unwanted bot.

Just saw https://github.com/Jackett/Jackett/commit/1aff9befb44c9406f918ae7959324194ea8ace7f and was reminded of this. Should we go through non-API indexers which have [empty search inputs](https://github.com/search?q=repo%3AJackett%2FJackett+%22%3A+%5C%22%5C%22%22+language%3AYAML&type=code&l=YAML) and add `allowEmptyInputs: true` to them?

**Comment by garfield69** [comment]
Yeah, Nah. Lets leave it as is for now and only revisit if there's signs if trouble.

**Pull request merged**
