### PR TITLE
[enhancement] Handle optional field without exceptions

### PR DESCRIPTION
**Pull request by alecsg77**
In the optional fields parsing, it is no exceptional case that the selector finds nothing.
Return null value instead throwing exception increase the performance.

### CODE REVIEW

**Comment by garfield69** [comment]
Is this related to the cardigann case block?

**Comment by alecsg77** [comment]
Sorry, I don't get you.

Let me try to rephrase it with more details.

I notice that during the cardigan indexer parse result, it throws a lot of exceptions without failing.
Most of them are threw because it is not able to found fields defined as optional.
Those exceptions are caught to nullify the value of the field.

I converted this throw/catch flow to null check flow but only when the field is optional.

These changes reduce to 0 the number of exceptions raised during the search of `captain` on the torrentqq indexer and increased the response time.

**Comment by garfield69** [comment]
let me provide an example:
https://github.com/Jackett/Jackett/blob/98dad4c169a9a3dfd1fd5b344e2b8a5b8b8558b2/src/Jackett.Common/Definitions/aidoruonline.yml#L96-L110
will your change in this PR impact on the way this case block behaves?

**Review by garfield69 — APPROVED** [review]
never mind. I tested for myself and see that this PR does not change the way that case block behaves, so all is well. Thanks.

**Comment by garfield69** [comment]
v0.17.1006

**Pull request merged**
