### PR TITLE
pixelados: optimize spanish season nomenclature search

### PR DESCRIPTION
**Pull request by TuGeek**
Updated language of Indexer to es-ES
Reg replace keywordsfilters to change nomenclature of Season (Sxx) to tracker format (Txx)

### CODE REVIEW

**Review by SPlNeTe — APPROVED** [review]

**Review by ilike2burnthing — CHANGES_REQUESTED** [review]
Thanks for the contribution.

Please also add title filters to rename results from `T1` to `S1` and `2x3` to `S2E3`, to improve Sonarr detection.

**Comment by garfield69** [comment]
@TuGeek  I have added some replacements for the title. Please test and correct if required. Thanks.

**Comment by TuGeek** [comment]
> @TuGeek I have added some replacements for the title. Please test and correct if required. Thanks.

Changes are ok, thanks.

**Comment by garfield69** [comment]
Cheers.

**Comment by TuGeek** [comment]
> Thanks for the contribution.
> 
> Please also add title filters to rename results from `T1` to `S1` and `2x3` to `S2E3`, to improve Sonarr detection.

@garfield69 has done it ;)

**Comment by garfield69** [comment]
v0.20.1168

**Comment by vinanrra** [comment]
@TuGeek 

Could you add something like this, because Sonarr isn't able to know that the releases are Spanish:

```
    title_vose:
      selector: name:contains(VOSE)
      optional: true
      filters:
        # Replace Spanish season names like T1, MS (MiniSerie), TU (Temporada Unica) for normalized format S1
        - name: re_replace
          args: ["(?i)T(\\d{1,2})\\b", "S$1"]
        - name: re_replace
          args: ["(\\d{2})[×|x](\\d{2})", "S$1E$2"]
        - name: re_replace
          args: ["(\\d{1})[×|x](\\d{2})", "S0$1E$2"]
        - name: re_replace
          args: ["(?i)MS\\b", "S1"]
        - name: re_replace
          args: ["(?i)TU\\b", "S1"]
    title_notvose:
      selector: name:not(:contains(VOSE))
      optional: true
      filters:
        # Replace Spanish season names like T1, MS (MiniSerie), TU (Temporada Unica) for normalized format S1
        - name: re_replace
          args: ["(?i)T(\\d{1,2})\\b", "S$1"]
        - name: re_replace
          args: ["(\\d{2})[×|x](\\d{2})", "S$1E$2"]
        - name: re_replace
          args: ["(\\d{1})[×|x](\\d{2})", "S0$1E$2"]
        - name: re_replace
          args: ["(?i)MS\\b", "S1"]
        - name: re_replace
          args: ["(?i)TU\\b", "S1"]
        # Add Spanish, fix for Radarr language
        - name: append
          args: " SPANISH"
    title:
      # Here needs to be added {{ if or .Result.mejorada .Result.corregida .Result.audio_editado }} PROPER{{ else }}
      text: "{{ if .Result.title_vose }}{{ .Result.title_vose }}{{ else }}{{ .Result.title_notvose }}{{ end }}"
```

Thanks in advance

**Pull request merged**
