### PR TITLE
Update TorrentDay.cs

### PR DESCRIPTION
**Pull request by rog0rr**
A few class renames and some element rearranging on the browse table has broken Jackett in the last few days - this fixes them

### CODE REVIEW

**Comment by OlafvdSpek** [comment]
Has the error message (about the cookie) been fixed as well?

**Comment by kaso17** [comment]
If you're running v0.8.637 and still getting a cookie error it's most likely a legit cookie error.

**Comment by OlafvdSpek** [comment]
Most likely doesn't cut it. ;)

**Comment by kaso17** [comment]
@OlafvdSpek please post the full enhanced log.

**Comment by OlafvdSpek** [comment]
I'm not using Jackett.. just pointing out that the error message should be appropriate.

**Comment by kaso17** [comment]
7c1fbdd44b45a5ad1b42111cd7ca4127ea145c0c improved the error handling and also uses the new API

**Pull request merged**
