### PR TITLE
Update TorrentSyndikat indexer

### PR DESCRIPTION
**Pull request by hashworks**

### CODE REVIEW

**Comment by garfield69** [comment]
Thanks.

**Comment by hashworks** [comment]
[user link is broken again](https://github.com/Jackett/Jackett/releases/tag/v0.10.362)

**Comment by hashworks** [comment]
Same problem as [in this pull request](https://github.com/Jackett/Jackett/pull/3864#issuecomment-425662269).

**Comment by garfield69** [comment]
oh. ok, i've edited the credit for you.

**Comment by hashworks** [comment]
Is there a way to select the username instead of the Author?
GitCommit has a [Commiter](https://cakebuild.net/api/Cake.Git/GitCommit/) attribute, no idea if that is right.

**Comment by garfield69** [comment]
>Is there a way to use the username instead of the Author in the cake script?
>GitCommit has a Commiter attribute, no idea if that is right.

@flightlevel  @kaso17  can you investigate?

**Comment by kaso17** [comment]
Once you configured a full name the full name is used instead of the username for the commit author field.
This is what's stored in the actual git files (which can be accessed by appveyor):
`Author: Justin Kromlinger <mail@hashworks.net>`
Even the github commit API doesn't provide the username:
https://api.github.com/repos/Jackett/Jackett/git/commits/a92e0bef3766b0bb5239e38d48cf0cda895c909a
Appveyor or any other third party application doesn't see your actual username.

Using the user search based on the email isn't reliable either:
https://api.github.com/search/users?q=mail@hashworks.net works.
But this only if you set you email to public in your profile (like e.g. in your case) but it doesn't work for users with unpublished emails.

**Pull request merged**
