### PR TITLE
Update polishtracker-api.yml

### PR DESCRIPTION
**Pull request by WMP**
#### Description
API URL change. Please wait with merge for my usability test, i want to use build from you azure cloud. In linux is very hard to build this...

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

### CODE REVIEW

**Comment by garfield69** [comment]
this is a yml indexer so it is very easy for you to test.
simply find the definitions folder on your linux jackett and edit the polishtracker-api.yml source directly then restart jackett to load your change and test.

**Comment by WMP** [comment]
Unfortunatelly my commit dont fix this, i must check more...

**Comment by ilike2burnthing** [comment]
What issue are you trying to resolve? That searching works but downloads don't?

**Comment by AdamN1** [comment]
> What issue are you trying to resolve? That searching works but downloads don't?

There is a problem with downloading.

**Comment by ilike2burnthing** [comment]
Can you provide an example download URL?

**Comment by AdamN1** [comment]
> Can you provide an example download URL?

https://pte.nu/download/${id}

**Comment by ilike2burnthing** [comment]
Does `https://pte.nu/download/{{ .Result._id }}` work for the indexer?

If not, provide 2 enhanced logs of the issue, one with the current release and one using the above - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by WMP** [comment]
Now my fix is working, please merge this pull

**Comment by garfield69** [comment]
v0.21.1138

**Comment by ilike2burnthing** [comment]
@WMP can you test if `text: "/download/{{ .Result._id }}"` works? Thanks.

**Comment by AdamN1** [comment]
> @WMP can you test if `text: "/download/{{ .Result._id }}"` works? Thanks.

Works great.

**Pull request merged**
