### PR TITLE
Update tracker's URL

### PR DESCRIPTION
**Pull request by schizophrene**

### CODE REVIEW

**Comment by schizophrene** [comment]
@garfield69, except if webpage page had change in same time than the URL (I don't think so, looks the same), "no form found" on the redirected URL

**Comment by garfield69** [comment]
@schizophrene if you get an error the first time after the redirect, just repeat the test/search and it should work the second time.

**Comment by alaunay** [comment]
Does not work...

I've a strange error with it:

11-27 21:14:01 Error Jackett.Common.IndexerException: Exception (yggtorrent): Error: NameResolutionFailure ---> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: NameResolutionFailure                             
  at System.Net.WebConnection.Connect (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x00044] in <e88cec3cc7e942ec94ee2bda8fe0549b>:0                                                                                                        
  at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x000cc] in <e88cec3cc7e942ec94ee2bda8fe0549b>:0                                                                                                 
  at System.Net.WebOperation.Run () [0x0009a] in <e88cec3cc7e942ec94ee2bda8fe0549b>:0                                                                                                                                                                                                    
  at System.Net.WebCompletionSource`1[T].WaitForCompletion () [0x00094] in <e88cec3cc7e942ec94ee2bda8fe0549b>:0                                                                                                                                                                          
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <e88cec3cc7e942ec94ee2bda8fe0549b>:0    
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00020] in <e88cec3cc7e942ec94ee2bda8fe0549b>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <3984f97acb054ea2
86ef4faa4a0a5615>:0                                                                                                                                                                                                                                                                      
--- End of stack trace from previous location where exception was thrown ---

  at System.Net.Http.HttpClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x0041d] in <b9025f17e19f4778a2c8d80b5ef171d4>:0                                                                                    
   --- End of inner exception stack trace ---
  at System.Net.Http.HttpClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00478] in <b9025f17e19f4778a2c8d80b5ef171d4>:0                                                                                    
  at CloudFlareUtilities.ClearanceHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x0010c] in <d0213015414e4bf286b46bc1ee77bd72>:0                                                                                 
  at System.Net.Http.HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x000ca] in <b9025f17e19f4778a2c8d80b5ef171d4>:0                              
  at Jackett.Common.Utils.Clients.HttpWebClient.Run (Jackett.Common.Utils.Clients.WebRequest webRequest) [0x00456] in <ff531a2ddd5240d08717280628a1049d>:0                                                                                                                               
  at Jackett.Common.Utils.Clients.WebClient.GetString (Jackett.Common.Utils.Clients.WebRequest request) [0x0010b] in <ff531a2ddd5240d08717280628a1049d>:0                                                                                                                                
  at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies (System.String url, System.String cookieOverride, System.String referer, System.Collections.Generic.Dictionary`2[TKey,TValue] headers) [0x000cb] in <ff531a2ddd5240d08717280628a1049d>:0                            
  at Jackett.Common.Indexers.CardigannIndexer.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x00827] in <ff531a2ddd5240d08717280628a1049d>:0                                                                                                                                  
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x00091] in <ff531a2ddd5240d08717280628a1049d>:0                                                                                                                                    
   --- End of inner exception stack trace ---                                                                                                                                                                                                                                            
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x000ee] in <ff531a2ddd5240d08717280628a1049d>:0                                                                                                                                    
  at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x0006b] in <ff531a2ddd5240d08717280628a1049d>:0                                                                                                                                 
  at Jackett.Server.Controllers.ResultsController.Torznab (Jackett.Common.Models.DTO.TorznabRequest request) [0x00335] in <fb9fa7d247f445029d871326a8627ee0>:0  Jackett.Common.IndexerException: Exception (yggtorrent): Error: NameResolutionFailure ---> System.Net.Http.HttpRequestExce
ption: An error occurred while sending the request ---> System.Net.WebException: Error: NameResolutionFailure                                                                                                                                                                            
  at System.Net.WebConnection.Connect (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x00044] in <e88cec3cc7e942ec94ee2bda8fe0549b>:0                                                                                                        
  at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x000cc] in <e88cec3cc7e942ec94ee2bda8fe0549b>:0                                                                                                 
  at System.Net.WebOperation.Run () [0x0009a] in <e88cec3cc7e942ec94ee2bda8fe0549b>:0                                                                                                                                                                                                    
  at System.Net.WebCompletionSource`1[T].WaitForCompletion () [0x00094] in <e88cec3cc7e942ec94ee2bda8fe0549b>:0                                                                                                                                                                          
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <e88cec3cc7e942ec94ee2bda8fe0549b>:0    
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00020] in <e88cec3cc7e942ec94ee2bda8fe0549b>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <3984f97acb054ea2
86ef4faa4a0a5615>:0 
--- End of stack trace from previous location where exception was thrown ---


Only thing, the domain does resolve...

$ ping ygg.to
PING ygg.to (31.220.0.115) 56(84) bytes of data.
64 bytes from 31.220.0.115 (31.220.0.115): icmp_seq=1 ttl=60 time=11.8 ms

$ curl https://ygg.to/
    <!DOCTYPE html>
<html>

<head>
        <title>YggTorrent - 1er Tracker BitTorrent Francophone</title>
(...)

Any idea ?

**Comment by schizophrene** [comment]
@garfield69, I just tried 3 times, right now : same error.
I will test after auto-build from linuxserver, if this error will still be there or not (maybe something changed on webpage, but I'm on phone so...)

**Comment by kaso17** [comment]
seems like they had another url in between which now no longer works.
@alaunay @schizophrene What's the sitelink in your config file (~/.config/Jackett/Indexers/yggtorrent.json)?

**Comment by alaunay** [comment]
sonarr@csnag2 ~/.config/Jackett/Indexers $ grep -C 5 sitelink yggtorrent.json
[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://www.ygg.to/"
  },

Seem ok ?

(json included after modifying a few fields) (and renamed to please github...)

**Comment by alaunay** [comment]
Ok, so
stopping jackett
rm ~/.config/Jackett/Indexers/yggtorrent.json
relaunching jackett
re-adding ygg
-> works again...

**Comment by kaso17** [comment]
thank you, fixed via 798a6df5063b1efa269fa149f81a90132877bf63

**Pull request merged**
