### PR TITLE
core: unix line ending + newline at eof

### PR DESCRIPTION
**Pull request by ngosang**

### CODE REVIEW

**Comment by ngosang** [comment]
@garfield69 merge ASAP. I don't want to rebase this one :)

**Comment by garfield69** [comment]
Do I need to change my editor defaults to conform to this requirement?
image

**Comment by ngosang** [comment]
Yes, Format = Unix. Encoding is ok.

**Comment by cadatoiva** [comment]
https://editorconfig.org/2019/02/21/notepad-plugin-040-released/ should let allow your app to follow our style rules

**Comment by garfield69** [comment]
>https://editorconfig.org/2019/02/21/notepad-plugin-040-released/ should let allow your app to follow our style rules

Nice find, thanks.

**Comment by cadatoiva** [comment]
No problem. According to the website, the plugin will automatically search and find the .editorconfig file for this project without any manual setup, because it searches every parent directory until it hits the root directory (e.g. C:\ or / ) or if the .editorconfig file has a setting `root = true`

**Comment by cadatoiva** [comment]
Plugins and details for all other clients can be found at https://editorconfig.org/#download

**Pull request merged**
