### PR TITLE
Publish release to winget

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This workflow automatically generates and publishes Jackett's releases to WinGet (windows package manager).

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
Please add a github token as a repository secret with `public_repo` Scope. Also, modify the secret name in the workflow.

**Comment by garfield69** [comment]
Is this going to post a release to winget every time a commit is posted on this GitHub Repo?
Because currently the pipelines can generate as many as a couple dozen **draft** builds, and once daily we manually pick the latest draft and mark as as a **Release**.
GitHub sends a notification to those who registered as monitors.
Would not want to be pushing drafts to a 3rd party web store.

**Comment by vedantmgoyal2009** [comment]
No, when you will mark a draft release as a release, only then it will get triggered.

See https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release.

**Comment by garfield69** [comment]
cool.
@ilike2burnthing  I'm not qualified to play around with this side of things. 
Seeing as you managed the codeql additions, would you care to try your hand setting this up?

**Review by ilike2burnthing — APPROVED** [review]

**Comment by garfield69** [comment]
v0.20.1018

**Comment by ilike2burnthing** [comment]
I don't think it worked:

```text
Found Existing Version: 0.20.1010.0
Installer Entry #1:

	InstallerLocale: en-US
	Architecture: x86
	InstallerType: inno
	Scope: machine


Yaml file created: D:\a\Jackett\Jackett\winget-pkgs-automation\winget-pkgs\manifests\j\Jackett\Jackett\0.20.1018\Jackett.Jackett.locale.en-US.yaml

Yaml file created: D:\a\Jackett\Jackett\winget-pkgs-automation\winget-pkgs\manifests\j\Jackett\Jackett\0.20.1018\Jackett.Jackett.installer.yaml

Yaml file created: D:\a\Jackett\Jackett\winget-pkgs-automation\winget-pkgs\manifests\j\Jackett\Jackett\0.20.1018\Jackett.Jackett.yaml
Manifest validation succeeded.
HEAD is now at e2142dc62 Update: KDE.Dolphin version 22.04.0 (#59651)
[detached HEAD 57ea10ba3] New version: Jackett.Jackett version 0.20.1018
 Date: Fri May 6 06:03:08 2022 +0000
 3 files changed, 63 insertions(+)
 create mode 100644 manifests/j/Jackett/Jackett/0.20.1018/Jackett.Jackett.installer.yaml
 create mode 100644 manifests/j/Jackett/Jackett/0.20.1018/Jackett.Jackett.locale.en-US.yaml
 create mode 100644 manifests/j/Jackett/Jackett/0.20.1018/Jackett.Jackett.yaml
To https://github.com/Jackett/winget-pkgs.git
 ! [remote rejected]     Jackett.Jackett-0.20.1018-34BEFD1A10E968 -> Jackett.Jackett-0.20.1018-34BEFD1A10E968 (shallow update not allowed)
error: failed to push some refs to 'https://github.com/Jackett/winget-pkgs.git'
aborted: you must first push the current branch to a remote, or use the --head flag
```

**Comment by vedantmgoyal2009** [comment]
I've fixed the issue. Can you please re-run the job again?

image

Sorry for the bug. Actually, I've created a GitHub Action for the first time and it is implemented  only on 1 repository. This one is 2nd.

**Comment by garfield69** [comment]
rerun complete. how to view logs?

**Comment by vedantmgoyal2009** [comment]
PR created: https://github.com/microsoft/winget-pkgs/pull/59671

**Comment by vedantmgoyal2009** [comment]
Logs: https://github.com/Jackett/Jackett/runs/6320422753?check_suite_focus=true

**Comment by garfield69** [comment]
looks like the license/cla is pending
image

**Comment by vedantmgoyal2009** [comment]
It needs to be done by @ilike2burnthing (one-time only).

**Comment by garfield69** [comment]
in that case I'm going to bed.

**Comment by ilike2burnthing** [comment]
Done.

**Pull request merged**
