### PR TITLE
HDSpace category mappings

### PR DESCRIPTION
**Pull request by d2dyno**
Add category mappings for HDSpace. To help issue #468.

Movie functionality still needs to be introduced for this indexer. These are JUST mappings.

### CODE REVIEW

**Comment by flightlevel** [comment]
Thanks @d2dyno  !
You just need to tidy this up a little (Removed positive signs, removed commas after last values)

```
        {
            AddCategoryMapping(15, TorznabCatType.MoviesBluRay); // Movie / Blu-ray
            AddMultiCategoryMapping(TorznabCatType.MoviesHD,
            19, // Movie / 1080p
            41, // Movie / 4K UHD
            18, // Movie / 720p
            40, // Movie / Remux
            16 // Movie / HD-DVD
                        );
            
            AddMultiCategoryMapping(TorznabCatType.TVHD,
            21, // TV Show / 720p HDTV
            22  // TV Show / 1080p HDTV
                        );
            
            AddCategoryMapping(30, TorznabCatType.AudioLossless); // Music / Lossless
            AddCategoryMapping(31, TorznabCatType.AudioVideo); // Music / Videos

            AddMultiCategoryMapping(TorznabCatType.TVDocumentary,
            24, // TV Show / Documentary / 720p
            25  // TV Show / Documentary / 1080p
                        );
            
            AddMultiCategoryMapping(TorznabCatType.XXX,
            33, // XXX / 720p
            34  // XXX / 1080p
                        );
            
            AddCategoryMapping("37", TorznabCatType.PC);
            AddCategoryMapping("38", TorznabCatType.Other);
        }
```

**Comment by d2dyno** [comment]
@flightlevel Thanks for pointing that out! Cleaned up. Plus signs were a total n00b mistake (from copying from a bad commit).

**Comment by flightlevel** [comment]
Thanks! Almost there
Just an extra comma on line 57 after AudioVideo
And line 59 minor typo should be AddMultiCategoryMapping

**Comment by d2dyno** [comment]
Wow I'm bad :p Thanks for your patience and teaching, though. Fixed those two.

**Comment by flightlevel** [comment]
https://github.com/Jackett/Jackett/issues/468
Thanks, good work

**Pull request merged**
