### PR TITLE
Update torrent-heaven.yml: new download url

### PR DESCRIPTION
**Pull request by FutureCow**
Torrent Heaven changed the download url.
Before: download.php?id=
Now: downloadv1.php?id=
This wil update the Definition.

#### Description
A few sentences describing the overall goals of the pull request's commits.

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
I'm still seeing download.php here. Can you check a few torrents, old and new, to make sure this is consistent for you? If so, please provide an HTML dump of a details page for a torrent - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by FutureCow** [comment]
Tried a new (yesterday) en old torrent (august 2023) same "new" url.
[new.txt](https://github.com/Jackett/Jackett/files/14072500/new.txt)
[old.txt](https://github.com/Jackett/Jackett/files/14072501/old.txt)

**Comment by ilike2burnthing** [comment]
I see you've asked about the change here - forums.php?action=viewtopic&topicid=27&page=p431#431

I'd like to wait for a response. We can add both, but it's a bit odd that it's changed for you but not me.

**Comment by FutureCow** [comment]
I'm afried that they also don't know why this is happening. But at the moment I can use torrent-heaven without the "v1"

**Comment by ilike2burnthing** [comment]
Just to confirm that's not a typo, you CAN use the indexer without the `v1` change? So this PR can be closed?

**Comment by FutureCow** [comment]
Nope, without the v1 I get an error that it cant find the right part (download.php?id=) from the page. So for me this is not working without the v1 part. I dont know if you can change the syntax to download*.php?id=

**Comment by FutureCow** [comment]
Yes, just checked. With this change to torrents are sent to the download client.

**Comment by garfield69** [comment]
v0.21.1645

**Pull request merged**
