### PR TITLE
Implementation of TVstore Indexer #2590

### PR DESCRIPTION
**Pull request by morpheus133**
Implementation of TVstore Indexer #2590

### CODE REVIEW

**Comment by garfield69** [comment]
@morpheus133  I've made some changes https://github.com/Jackett/Jackett/pull/4738/commits/ea54d53567b7e435d01b611f03c546266694b918

would you be so kind as to test that the indexer still works please?
I don't have a login so can't be sure I haven't broken anything.

**Comment by morpheus133** [comment]
@garfield69 I tested it and works fine.
Only find one typo what I correct in https://github.com/Jackett/Jackett/pull/4738/commits/1b116ed07a2d51673e5e20d1ac91efe69d525aba

**Comment by garfield69** [comment]
Thank you.

**Comment by garfield69** [comment]
Ah. found my login. forgot I had it. :-D

**Comment by morpheus133** [comment]
https://github.com/Jackett/Jackett/pull/4745

**Pull request merged**
