### PR TITLE
Optimized & Fixed FADN Provider

### PR DESCRIPTION
**Pull request by JigSawFr**
### Optimized & Fixed FADN Provider

> Login Check (In case of invalid cookie or manual login with a browser)
> Optimized provider (Refactor, Optimized)
> New logo

Fixed ISS. https://github.com/Jackett/Jackett/issues/297 - https://github.com/Jackett/Jackett/issues/292 - https://github.com/Jackett/Jackett/issues/286

*Updated with love,*
JigSaw

### CODE REVIEW

**Comment by duramato** [comment]
@JigSawFr 
```
Apr 05, 2016 04:01:51 PM	Error	
Exception in Configure
Apr 05, 2016 04:01:51 PM	Debug	
UnixLibCurlWebClient:GetString Returning Unauthorized => <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at french-adn.com Port 443</address>
</body></html>
Apr 05, 2016 04:01:51 PM	Debug	
UnixLibCurlWebClient: Posting username=BLU&password=BLA
Apr 05, 2016 04:01:51 PM	Debug	
UnixLibCurlWebClient:GetString(Url:https://french-adn.com/takelogin.php)
Apr 05, 2016 04:01:51 PM	Debug	
Perform loggin.. with https://french-adn.com/takelogin.php
```

**Comment by fana13** [comment]
@duramato the website and the tracker is down for me, i suppose it causes errors

**Comment by duramato** [comment]
@fana13 ah that might be it :P didnt even had the idea to check it. Will wait a bit longer then.

**Comment by JigSawFr** [comment]
@fana13 & @duramato, yes, FADN seems to be down. As they ask an user/password to access tracker.

**Pull request merged**
