### PR TITLE
updater: remove Indexers/*.json &*.json.bak (yaml)

### PR DESCRIPTION
**Pull request by ilike2burnthing**
Basically the same as the Definitions, but doesn't include those which were migrated to C# (and still exist), and some comments differ where a subsequent change was more relevant.

Not sure if XtremeZone, SceneFZ, and IceTorrent should be kept or not due to being merged as SpeedApp and login details needing be migrated across - https://github.com/Jackett/Jackett/pull/10279

If there's interest in merging this, I can take an oh so short trek through removed C# indexers as well and make another PR with their relevant .json & .json.bak files.

### CODE REVIEW

**Comment by garfield69** [comment]
>Not sure if XtremeZone, SceneFZ, and IceTorrent should be kept or not

any in this table
https://github.com/Jackett/Jackett/blob/81d53d339b5e3fd1692e03f56c1cf68989360b9c/src/Jackett.Common/Services/IndexerManagerService.cs#L38-L54
will have had their corresponding config renamed by the managerservice and therefore there should not be an originally named config or backup left in the Indexers folder.

**Comment by ilike2burnthing** [comment]
Updated

**Review by garfield69 — APPROVED** [review]
fine by me.
@ngosang  Any objections to merging this, some possible palm-face we have not considered?

**Review by ngosang — APPROVED** [review]

**Comment by ngosang** [comment]
It's ok for me. You can merge

**Pull request merged**
