### PR TITLE
Append english to the language too

### PR DESCRIPTION
**Pull request by rubasace**
All releases on this tracker are both spanish and english unless "vose" is specified. So english tag should also be appended to title

### CODE REVIEW

**Comment by rubasace** [comment]
Is there an easy way of appending the spanish part only if "vose" doesn't appear on the title? I cannot think of any that isn't 2 re_replace, one for "contains vose" and another one for "does not contain vose"

**Comment by garfield69** [comment]
> Is there an easy way of appending the spanish part only if "vose" doesn't appear on the title? I cannot think of any that isn't 2 re_replace, one for "contains vose" and another one for "does not contain vose"

If I have understood you correctly, the [spanish] tag applies only to titles that do not contain vose and the default is for titles to be both spanish and english, in which case there is no need to specify a tag at all.
I can only think of this example:
```yaml
      title:
        selector: td[valign="middle"] a
      title:
        selector: td[valign="middle"] a:not(:contains("vose"))
        optional: true
        filters:
          - name: append
            args: " [spanish]"
```

**Comment by rubasace** [comment]
@garfield69 yep, had to make both optional, the one containing vose only appending [english] and the other appending both, but it works. A million thanks. 

This should now be ready to merge :)

**Comment by garfield69** [comment]
jackett 0.12.907

**Pull request merged**
