### PR TITLE
Add Azure Pipelines support

### PR DESCRIPTION
**Pull request by junglebus**
This PR allows Jackett to be built on Azure Pipelines

This will bring a number of benefits compared to the current build system:
- After the build is completed, integration tests will now run against the Windows, Linux and Mono versions of Jackett (macOS coming soon). Currently the integration tests are very simple, but they do prove that Jackett runs, the installer/systemd script works, the UI loads and the Jackett API responds
- Windows version of Jackett is now entirely .NET Core, which leaves only the Mono version not running on .NET Core
- Unit tests now run against all runtimes
- Mono version is now built on Linux and macOS version built on macOS
- Lets us have 10 VM's running at once and has macOS VM's as well

It will seem like a large file, but does the job of build.cake, build.ps1, build.sh and appveyor.yml combined

Both build systems can run happily together 

To get it going
- #7022 and #7023 and #7028 need to be merged first, then this PR
- Sign up to Azure DevOps, its free https://dev.azure.com
- Create a new Organization and Project that are public. I'd recommend calling the Organization and Project 'Jackett' e.g. like Radarr https://dev.azure.com/Radarr/Radarr
- Click Pipelines > Builds > New Pipeline
- Choose GitHub and should do the rest since azure-pipelines.yml is present in master
- Create a Github service connection https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-github (Project settings -> Service connections -> New service connection -> Github -> Grant Authorization and oAuth=AzurePipelines -> Give it a name and save )
- Edit the azure-pipelines.yml and change 'github.com_junglebus' to the name of the service connection you just created
- Github releases should now get created (they will all be drafts so only you will see them)

Once its running I'd recommend some alpha testing first before pre-release

ToDo
- Update readme to remove .NET 4.6.1 requirement for Windows and update build badge once releases are coming from Azure Pipelines
- Test the updater going from Windows full framework to Windows .NET Core version

### CODE REVIEW

**Comment by junglebus** [comment]
Just made some of the DisplayNames a bit clearer

> Once its running I'd recommend some alpha testing first before pre-release

And just realized the above is a bit ambiguous. The 4 PR's can be merged in safely and don't require a pre-release (builds will get created from Azure but users won't be downloading them, they'll still get the Appveyor ones). It's once the decision is made to the Azure builds for users i.e. Windows using .NET Core that a pre-release would be needed

**Comment by garfield69** [comment]
are you expecting me to set this up?
I'm not the owner of the Jackett GitHub repo, and you have (if I set things up correctly) as much admin access as I or ngosang has.
If I set up an account on azure, all we will be doing is swapping your azure a/c with mine, I don't see the point.
Just go ahead and implement it if you can, since you are more familiar with the who thing that I anyway ;-)

**Comment by junglebus** [comment]
Thanks @garfield69 
Ticking along nicely now!
You can see the stages it goes through here https://dev.azure.com/Jackett-project/Jackett/_build/results?buildId=9&view=results
It should provide a lot more confidence when accepting PR's. Now you'll know on every PR that:
- The Windows installer still works and Jackett runs after it
- Systemd script for Linux and Mono both work -> and Jackett runs after it
- The Web UI loads and basics are present
- Jackett's API is working

If you've got time can you have a play with the .NET Core Windows version of Jackett. I find Windows sandbox good for this if you want to keep your existing setup separate

I'll try and test the auto-updater from Windows full framework to .NET Core version later this week

**Comment by garfield69** [comment]
I already use the windows net core version when I am testing PR code through my visual studio local github repo. ;-)

**Comment by junglebus** [comment]
@garfield69 Hope you don't mind I create a new user and added it to the Jackett github project called 'jackett-bot' who is the one that 'publishes' the releases
If you have access to the 'jackettbot' user though we can change it
Also, do you want access to the Azure Pipeline project? If so, I just need an email address to send the invite to

**Comment by garfield69** [comment]
> [...]  I create a new user and added it to the Jackett github project called 'jackett-bot' who is the one that 'publishes' the releases

fine by me.

>If you have access to the 'jackettbot' user though we can change it

I don't have access to user jackettbot, it was probably set up by the owner of jackett @kaso17, before I joined the group.

>do you want access to the Azure Pipeline project?

I suppose we should have a backup access to azure pipeline project. 
garfieldsixtynine @ gmail.com

thanks.

**Pull request merged**
