### PR TITLE
Don't migrate UNIX configs if the input and output directories are the same

### PR DESCRIPTION
**Pull request by NinjaLikesCheez**
This is to address the DietPi issues where they don't use the expected default location, and instead use `$HOME/Jackett` as the config directory. This causes the migrator to copy files to themselves, then remove the config directly entirely.

This change addresses this condition by checking the AppData folder against the assumed #11313 bugged folder on UNIX systems, and if they differ the migration will occur *. In addition, it adds a guard around the deletion portion of the migration function so we don't remove folders we've just migrated to.

\* The reason this change was added only to UNIX is the original migration function was made to copy files onto themselves with an updates security policy on Windows devices only, I didn't want to affect this behaviour.

### CODE REVIEW

**Comment by NinjaLikesCheez** [comment]
Looks like DietPi isn't using the default config location - but I don't know enough about it to say that with 100% certainty: https://github.com/MichaIng/DietPi/blob/701c30575f7c59e15a72e33f15991eb5fad2bfe6/dietpi/patch_file#L1585

**Comment by NinjaLikesCheez** [comment]
Tested this with DietPi today and it's working well (thanks @Joulinar for the VM tip!)

**Comment by Joulinar** [comment]
My pleasure, basically DietPi is nothing else than a set of script on top of Debian. This enables us to have DietPi running on a larger amount of devices.

**Comment by MichaIng** [comment]
Many thanks for report and fix guys. We'll also move the config directory out of the install/executable directory for our implementation, reasonable for many reasons.

**Comment by ilike2burnthing** [comment]
Thanks again @NinjaLikesCheez 

@garfield69 given that seems to affect a fair chunk of users, it's been tested, and (I think) I can follow the logic of what is being done here, should we merge this rather than waiting in vain for a review from ngosang?

**Comment by lovegnome** [comment]
Tested 0.17.841. No change.

**Comment by Arghh** [comment]
Works on DietPi. Tested 0.17.841. Indexers, log.txt  and ServerConfig.json are NOT getting deleted after reboot/service restart. Thank you.

**Pull request merged**
