### PR TITLE
[Cardigann] Fix empty selector values

### LINKED ISSUE #12288: [bug] hardcoded size broken
Bug caused by https://github.com/Jackett/Jackett/commit/f2c760ce8c278f07d732ef9efefdf3e8c0d77473 (v0.18.686 anyway) - hardcoded size with additional optional size selector no longer works, just shows `0 B`

Example - search using OnceSearch on v0.18.686 (0 B) vs v0.18.666 (256 MB)

https://github.com/Jackett/Jackett/blob/0841f453bfa466dfa5a81ea196011301915e04f8/src/Jackett.Common/Definitions/oncesearch.yml#L129-L133

Hardcoded size on its own works, it's only when there's also an optional size selector that it fails.

### PR DESCRIPTION
**Pull request by mikeoscar2006**
Fixes #12288.

### CODE REVIEW

**Review by ilike2burnthing — APPROVED** [review]
Tested, working well with oncesearch, elitetorrent-biz, and pier720, new and old yaml files

**Comment by mikeoscar2006** [comment]
> Tested, working well with oncesearch, elitetorrent-biz, and pier720, new and old yaml files
Great!, let's wait for another review before merging.
One question I wanted to ask @ilike2burnthing and @garfield69 if you don't mind, Are there any indexer specific test modules?

**Comment by ilike2burnthing** [comment]
I think EraiRaws is the only indexer to have its own specific test - https://github.com/Jackett/Jackett/blob/master/src/Jackett.Test/Common/Indexers/EraiRawsTests.cs

**Comment by mikeoscar2006** [comment]
> I think EraiRaws is the only indexer to have its own specific test - https://github.com/Jackett/Jackett/blob/master/src/Jackett.Test/Common/Indexers/EraiRawsTests.cs

It isn't much though. I'm thinking there should be indexer specific tests where an indexer should be able to parse a specific query and download link and match with expected results. If this is enabled as a Github Action, for each pull/commit, indexers can be automatically tested to prevent some indexer breaking changes.

**Comment by ilike2burnthing** [comment]
So for each indexer we'd need to copy the site's results page's hmtl (the details page too if needed) and then have expected output to check against?

**Comment by mikeoscar2006** [comment]
Instead of copying html, we can also issue a request by Jackett itself which has a plus point of letting us know about changes in website structure.

**Comment by ilike2burnthing** [comment]
That would only work for public indexers.

**Comment by mikeoscar2006** [comment]
Actually, Github Actions allow storage of encrypted credentials which can be accessed via repository only on Github which can help in private trackers but yeah I can understand if it seems too complicated though IMHO it can help a lot.

**Review by garfield69 — APPROVED** [review]
LGTM
tested against a variety of indexer that have optional:true on fields
all works as expected.
Thank you.
I'll update the relevant indexer to remove the alternate way of checking for empty size so that there is consistency across the library

**Pull request merged**
