### PR TITLE
add Sharewood.cs for Sharewood API

### PR DESCRIPTION
**Pull request by xfouloux**
completely functionnal use of the Sharewood API via C# indexer =) !

Took me some time, but i finally got it :)

Still need some testing, can you include it as a secondary for now ? It is named "Sharewood API" so it's won't interfere with "Sharewood" YAML

for reference : #10269

### CODE REVIEW

**Review by garfield69 — APPROVED** [review]
tested OK

what the fuck is going on with this shitty compiler. I've restore the code to what was previous and it does not work anymore?

**Comment by xfouloux** [comment]
ohhh really the case mattered here, visualstudio didn't say anything -_-

**Comment by ilike2burnthing** [comment]
Nope, apparently not :/

**Comment by garfield69** [comment]
I think this might be a pipeline issue?

**Comment by xfouloux** [comment]
well the PR #11104 changed a lot of files and this one mostly

https://github.com/Jackett/Jackett/blob/eaf0513605c3f8e982c36617ca43555f2ac7a5e4/src/Jackett.Common/Models/IndexerConfig/ConfigurationData.cs

line 229 i have
```
        public class BoolItem : Item
        {
            public bool Value { get; set; }
            public BoolItem() => ItemType = ItemType.InputBool;
        }
```
but in github tree now it's not existant

i need to rewrite a bit the code to be in line with the new PR i'll do that today

**Comment by ilike2burnthing** [comment]
Was just looking at that. Try `BoolConfigurationItem` and `SingleSelectConfigurationItem`?

**Comment by garfield69** [comment]
memo to self. when testing with local vs2019, remember to fetch the latest source from GitHub! Duh ::embarrassed::

**Comment by xfouloux** [comment]
wow, something was not ok with my merge ! just delete this=

**Comment by xfouloux** [comment]
go to #11327

**Pull request closed without merging**
