### PR TITLE
[Feature] Add infohash field to blutopia-api yaml definition

### PR DESCRIPTION
**Pull request by hitboxr**
Short and sweet. See title :)

Reference: [UNIT3D API source](https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/c9ff27dbe8acf4ddcbe35d6ef62b40eea46df091/app/Http/Controllers/API/TorrentController.php#L109)

### CODE REVIEW

**Comment by garfield69** [comment]
The only caveat with this is that since the magnet is built by Jackett it will not have the site's torrent tracker.
If the site does not allow dht then you will not get any seeders to begin the download without manually adding the tracker once it's loaded on the torrent client.

**Comment by hitboxr** [comment]
I'm interested in adding this for reasons entirely unrelated to magnet links, and from what I can see Jackett does not automatically build and return a magnet link just because there's an infohash present. I'm not sure if that's intentional but that's the behavior that I see. Example output when requesting through the updated indexer:

```
{
    "FirstSeen": "0001-01-01T00:00:00",
    "Tracker": "Blutopia (API)",
    "TrackerId": "blutopia-api",
    "TrackerType": "private",
    "CategoryDesc": "Movies",
    "BlackholeLink": null,
    "Title": "RBG 2018 1080p Blu-ray AVC DTS-HD MA 5.1-CINEMATIC",
    "Guid": "https://blutopia.xyz/torrent/download/65629.2dbd6b14425293a3dc57deeaa8a66c84",
    "Link": "http://<xxx.xxx.xxx.xxx>:xxxx/dl/blutopia-api/?jackett_apikey=<XXXX>&path=Q2ZESjhFblJ0X2lTay1oSW1FSC1xcnF6bWk1MVRaY1NWRlA1M1BXUE1MVndFQ2xJU2lUbHh5NXQ2SWZDNE1iN0hVRE9TU3c3SW9UVWM5aVFHa0Vid3N3NFEtQUlUZVZNRnowX2wydmxtZmlvd2JUWjc1UGVxT3k1UVFrNEwzVXVXSHRGa3VUNW5PUmpSVmp5VExxZFphTW01LXpVSUl0WnNYUV9CMUdHa2VYWWVJWV8xYUVwTEh1cVRFRHZkVm4ybmhhcllhNEZ5cXlVcElkbTJxbGROMHA3bVQ4&file=RBG+2018+1080p+Blu-ray+AVC+DTS-HD+MA+5.1-CINEMATIC",
    "Details": "https://blutopia.xyz/torrents/65629",
    "PublishDate": "2020-10-30T17:54:00",
    "Category": [
                2000,
                100001
            ],
    "Size": 24934178816,
    "Files": 205,
    "Grabs": 1,
    "Description": null,
    "RageID": null,
    "TVDBId": 0,
    "Imdb": 7689964,
    "TMDb": 493099,
    "DoubanId": null,
    "Author": null,
    "BookTitle": null,
    "Seeders": 0,
    "Peers": 0,
    "Poster": "http://<xxx.xxx.xxx.xxx>:xxxx/img/blutopia-api/?jackett_apikey=<XXXX>&path=Q2ZESjhFblJ0X2lTay1oSW1FSC1xcnF6bWk1MkpyZW1YSFExNjJ1X3gwbVMta1pWUnltWmFZYWxGbnAwWXFGWTlLQkZ1Y1pFZy1FVFVpRkNvRlVLSEt5UE52Y25WNlkyYzJRTC1yYWFERlktb3RncXBOX3ltRFRQbmgtRUpaSEVGbVlPaWJjU1JhT20yZ2VXZlYxM0hwcjdjN01jX2ZOZ3JMYmF6aHdhZV9fSnpBNzZrMUJaSkhxbDNVbVdmMjcwQ0NZa2NB&file=poster",
    "InfoHash": "978d567619dc825990401e34af7f8f3073ac42e6",
    "MagnetUri": null,
    "MinimumRatio": null,
    "MinimumSeedTime": 604800,
    "DownloadVolumeFactor": 1.0,
    "UploadVolumeFactor": 1.0,
    "Gain": 0.0
        }
```

Note that `MagnetUri` is null.

As far as adding other trackers goes, I would hope that Jackett is smart enough not to add trackers to torrents from a `"TrackerType": "private"` indexer. I don't see a situation where you would ever want to do that.

**Comment by garfield69** [comment]
Hmm, the results you report are at odds with the wiki.
But I've checked the cardigann code, and you are correct. 

The infohash in the fields block only loads the torznab infohash output.
It's the infohash in the Download block that builds a magnet from the info hash and title, and atts 10 of the most popular public trackers to the magnets tracker list.
I'll update the wiki, and approve your PR. 
Thanks!

**Review by garfield69 — APPROVED** [review]

**Comment by garfield69** [comment]
I was curious so I just checked. 
There are currently no Private indexer with a infohash generated magnet in the download block.
Found plenty of Public indexer that use this feature, and one semi-private (kinozal).

**Comment by garfield69** [comment]
v0.20.1168

**Pull request merged**
