### PR TITLE
UI Overhaul

### PR DESCRIPTION
**Pull request by betamax2021**
Addresses Issue  #3453 Also cleans up the interface IMO, several style tweaks, code formats, and setup for some features already in the issues section. Most all existing features were checked, but some issues may arise.

### CODE REVIEW

**Comment by flightlevel** [comment]
@betamax2021 Wow, massive piece of work there! 
We've just got a large change in progress (new webserver for Jackett) at the moment. Once that's out of the way (hopefully in the next week) can look at getting this in

**Comment by garfield69** [comment]
Oops sorry @flightlevel finger problem meant I requested a review from you rather that look at a comment.

**Comment by flightlevel** [comment]
@betamax2021 
Had a chance to have a quick play
Would like others thoughts as these are just mine
@kaso17 @garfield69 
If anyone wants to try it, download from here https://ci.appveyor.com/project/Jackett/jackett/build/0.10.42/artifacts

-Like the concept, needs some tidy up though
-Couldn't see the info on how to add indexers
image
-If I click test all, wait for the responses, then go manual search, then cached releases, then configuration, then indexers and keep cycling through those buttons (not quickly, giving each page a chance to load), CPU starts going crazy and I can see a huge amount of requests getting made
image
-Prefer the look of the current indexers grid, new version font is a little small and rows a bit squished for me

**Comment by nayaj** [comment]
Amazing work!

**Comment by flightlevel** [comment]
Can reopen once changes are made
Thanks

**Pull request closed without merging**
