### PR TITLE
(Add) redtopia.yml

### PR DESCRIPTION
**Pull request by HDVinnie**
- Redtopia is a inner site of Blutopia which offers Music,Audiobooks and Podcasts
- @kaso17 @flightlevel I was not able to get this working. Maybe can help out? If have Blutopia account can use same creds to login to Redtopia.
- Error Log https://pastebin.com/9MebEr6D

### CODE REVIEW

**Comment by Metigoth** [comment]
Adds with username and password, but doesn't search correctly.

**Comment by kaso17** [comment]
so does this work or does it still need work?

**Comment by HDVinnie** [comment]
@kaso17 still needs work.....

**Comment by kaso17** [comment]
fixed it, bluetopia has an extra column (the first one), seems to be always empty.

**Comment by garfield69** [comment]
getting 502 bad gateway error from https://redtopia.xyz currently

**Comment by garfield69** [comment]
never mind, temporary error, back online.

**Comment by HDVinnie** [comment]
@garfield69 Redtopia is closing in like 4 days for good. Might as well remove this definition.

**Comment by RoloSoze** [comment]
Are we sure about Redtopia closing? It's back online & working fine now, but it's not in Jackett anymore! @HDVinnie @garfield69

**Pull request merged**
