### PR TITLE
beyond-hd (api): add freeleech filters

### PR DESCRIPTION
**Pull request by frias0**

### CODE REVIEW

**Review by ilike2burnthing — CHANGES_REQUESTED** [review]
Generally we just give a single toggle for freeleech, and not any for `50%`, etc.

Is there something specific about `limited` which would mean a user would or wouldn't want to download them over normal freeleech?

What are `refund` and `rewind`?

**Comment by frias0** [comment]
> Generally we just give a single toggle for freeleech, and not any for `50%`, etc.

Ok, personally I'd rather have an option and not need it, than, not have it and miss it. So I instinctively added all the leech discounts😋. 
However I understand that there are less use cases for the 25-75% options. Does this comment mean you want me to remove them?
> Is there something specific about `limited` which would mean a user would or wouldn't want to download them over normal freeleech?

If you're looking to build buffer, those torrents would have a limited effect (limited to x bytes upload). But if you only care about downloadvolumefactor, it's freeleech.
> What are `refund` and `rewind`?

Basically freeleech, but with caveats, and won't be free unless the user meet the requirements. I'm not sure if it's against the rules to share more detail.

I think it would be misleading to include all types of "100% freeleech" with one checkbox. 
`limited` won't mess up your ratio, but `refund` and `rewind` could/would.

At the same time, a lot of torrents would be excluded if you only filter with the `freeleech` param. 
The `freeleech` param isn't a per-user calculated filter, the params behave more like tags.

e.g If `freeleech` `limited` and `refund` torrents are defacto freeleech for you, you have to include `freeleech=1` `limited=1` and `refund=1`  to search all freeleech torrents

**Comment by frias0** [comment]
> Ta. I see there's also `rescue`, but that's just another thing that I don't understand.

`rescue` is also freeleech with a caveat, but requires manual action before download. 
I saw the "Use Freeleech Tokens when Available" in the Alpharatio indexer, but this would be a multi step action, and I don't really have experience with C#, nor the code base, nor tornzb. 

From what I saw playing around yesterday, torznab would not work with multi step downloads.

**Comment by ilike2burnthing** [comment]
Well that all sounds simple. /s

Yea, I think it would be best to remove `25`, `50`, and `75`, as no other indexer I'm aware of offers anything apart from `freeleech`. Then we can merge.

If the current indexer can't download `rescue` torrents, then can we exclude them from results? e.g. `postData.Add(BHDParams.rescue, "0")` maybe throw in a `TODO` comment as well

**Comment by frias0** [comment]
> If the current indexer can't download `rescue` torrents, then can we exclude them from results?

Oh it can, it's just that you can choose to rescue some of the torrents, so no need to filter them, they just won't be freeleech.

/s indeed

**Comment by garfield69** [comment]
Thanks.

**Comment by garfield69** [comment]
v0.20.3160

**Comment by ilike2burnthing** [comment]
@frias0 would you be able to also add tmdbid results:

https://github.com/Jackett/Jackett/blob/376c8ba13b433d17cfc42a5e112c30e6c3e7db00/src/Jackett.Common/Indexers/BeyondHDAPI.cs#L294

and search by genres:

https://github.com/Jackett/Jackett/blob/376c8ba13b433d17cfc42a5e112c30e6c3e7db00/src/Jackett.Common/Indexers/BeyondHDAPI.cs#L225

Search by year would be nice to have as well, but they are using `min_` and `max_`. I would guess `min_` is what we want, but not sure:

https://github.com/Jackett/Jackett/blob/376c8ba13b433d17cfc42a5e112c30e6c3e7db00/src/Jackett.Common/Indexers/BeyondHDAPI.cs#L255-L256

If you can figure it out, great, otherwise no worries.

**Comment by garfield69** [comment]
My guess would be that `min_year` and `max_year` set a range of values, so `min_year=2000,max_year=2010` would search for all titles in that year range. For a single year I would guess you set both parms to the same value `min_year=2023,max_year=2023`

**Comment by ilike2burnthing** [comment]
@frias0 any luck with this?

**Pull request merged**
