### PR TITLE
cardigann: fix .query.season

### PR DESCRIPTION
**Pull request by ilike2burnthing**
related https://github.com/Prowlarr/Indexers/pull/96
credit https://github.com/Prowlarr/Prowlarr/commit/d61ce3f27ca131d1c076f0570586a1246cd8e9b6

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
So close...

I'm going to guess that when using `{{ .Query.Season }}` with no season specified, `0` is not supposed to be used as the value, e.g.:

```text
https://blutopia.xyz/api/torrents/filter??sortField=created_at&sortDirection=desc&perPage=100&page=1&api_token=&name=&tmdbid=&tvdbid=&imdbid=&season=0&ep=
```

Was getting `error CS0023: Operator '?' cannot be applied to operand of type 'int'` when I tried using `query.Season?.ToString() ?? null;` so had to remove the first `?`, not sure if that's the cause of the problem. @Qstick any idea?

**Comment by Qstick** [comment]
I think we use a nullable int for season (int?) thus we are checking for null with the first ?. This allows us to pass season if it's set in the incoming request (0 or anything else), but pass null or blank if it's not. 

If you want to stick with regular int for season you might have to do something like this assuming season 0 is an issue 

```
query.Season > 0 ? query.Season.ToString() : null
```

**Comment by ilike2burnthing** [comment]
Yea, that's working, thanks again.

@garfield69 can you check this is working with Blutopia?

**Review by garfield69 — COMMENTED** [review]
test results:
- using jackett dashboard search blutopia for `craig s04e07` which generates the following query to blutopia
```
https://blutopia.xyz/api/torrents/filter?sortField=created_at&sortDirection=desc&perPage=100&page=1&api_token=myapitoken&name=craig+s04e07&tmdbid=&tvdbid=&imdbid=&season=&ep=
```
which returns the one correct result
image

- using Sonarr to make the same search generates the following torznab request to jackett
```
http://127.0.0.1:9117/api/v2.0/indexers/blutopia-api/results/torznab/api?t=tvsearch&cat=100001,100002,100003,100005&extended=1&apikey=myapikey&offset=0&limit=100&tvdbid=338736&season=4&ep=7
```
which jackett in turn generates the following query to blutopia
```
https://blutopia.xyz/api/torrents/filter?categories[]=1&categories[]=2&categories[]=3&categories[]=5&sortField=created_at&sortDirection=desc&perPage=100&page=1&api_token=myapitoken&name=S04E07&tmdbid=&tvdbid=338736&imdbid=&season=4&ep=7
```
which returns 14 results 
image

- on the website directly, name=s04e07 tvdbid=338736 returns the correct result
image

- conclusion: 
 IT would appear that this PR is generating the correct queries, but that the blutopia api server is not using the season/ep parms in combo with tvdbid to filter results

**Comment by ilike2burnthing** [comment]
If you drop `name=S04E07` from the Blutopia URL does it return the one correct result?

```text
https://blutopia.xyz/api/torrents/filter?categories[]=1&categories[]=2&categories[]=3&categories[]=5&sortField=created_at&sortDirection=desc&perPage=100&page=1&api_token=myapitoken&tmdbid=&tvdbid=338736&imdbid=&season=4&ep=7
```

**Comment by garfield69** [comment]
>If you drop name=S04E07 from the Blutopia URL does it return the one correct result?

no, that appears to make the blutopia api server return the latest 100 rows

**Comment by ilike2burnthing** [comment]
`season` and `ep` don't appear to be being used as the below returns all 'craig of the creek' results:
`name=craig%20of%20the%20creek&tvdbId=338736&season=4&ep=7`
`name=craig%20of%20the%20creek&season=4&ep=7`
`tvdbId=338736&season=4&ep=7`

See https://github.com/Prowlarr/Indexers/pull/96#pullrequestreview-857398700 for anything further.

Fixed the issue with `tvdbid` not working alone, should be `tvdbId`.

**Comment by ilike2burnthing** [comment]
@garfield69 do you want v5.3.0 indexers moved over to this formatting, just with `.Query.Season` and `.Query.Ep` removed from the start of `$raw`, or leave as is?

**Comment by garfield69** [comment]
>do you want v5.3.0 indexers moved over to this formatting, [...] or leave as is?

I'm inclined to leave as is. Once sites move to 6.0 we will be amending for the DLVF changes so we save an update cycle ;-)

**Comment by garfield69** [comment]
v0.20.413

**Pull request merged**
