### PR TITLE
Update il corsaro nero

### PR DESCRIPTION
**Pull request by Jorman**
I just realized that the rss sync was wrong, always the same page was request.
I think 5 pages are enough, so dropped to 5 page request

There's a way to make a rss sync different from a search string?
In this situation the best is to have more pages to scan after a search and less pages to scan for a rss sync

### CODE REVIEW

**Comment by garfield69** [comment]
>There's a way to make a rss sync different from a search string?

what do you mean? you are already checking if there is keywords present do search else do browse, and the rss sync is just a call without keywords, so what else are you wanting to do?

**Comment by Jorman** [comment]
See this tracker for example
During a search is better to have about 10 pages, because for the limitation of Sonarr, I need to make a "stupid" search, so I need to dig into more results. But to make a rss sync I don't need so much pages to be scanned. So actually every line is a search, then
`path: "{{if .Keywords}}advsearch.php?&category={{range .Categories}}{{.}};{{end}}&search={{ .Keywords}}&order=data&by=DESC&page=0{{else}}/browse/0{{end}}"`
Search to page 0 with and without keywords, this's the same for all pages -> 1, 2, 3 ...
So for example If I want to search 2 pages but do a rss sync to only one I need to make this?
```
path: "{{if .Keywords}}advsearch.php?&category={{range .Categories}}{{.}};{{end}}&search={{ .Keywords}}&order=data&by=DESC&page=0{{else}}/recenti{{end}}"
path: "{{if .Keywords}}advsearch.php?&category={{range .Categories}}{{.}};{{end}}&search={{ .Keywords}}&order=data&by=DESC&page=1{{else}}/recenti{{end}}"
```
This's the before situation, but what happen during a rss sync? Jackett make 2 times the same url request? Make not much sense for me.

What do you think?

**Comment by garfield69** [comment]
if the recenti page does not support multiple pages then leave it out of the *else& clause on the subsequent searches.
```
path: "{{if .Keywords}}advsearch.php?&category={{range .Categories}}{{.}};{{end}}&search={{ .Keywords}}&order=data&by=DESC&page=0{{else}}/recenti{{end}}"
path: "{{if .Keywords}}advsearch.php?&category={{range .Categories}}{{.}};{{end}}&search={{ .Keywords}}&order=data&by=DESC&page=1{{else}}{{end}}"
```

**Comment by Jorman** [comment]
Ok, got it. I'll deal with it if I need it
For now this code is correct, /recenti must be changed into the one I put, otherwise the rss sync through more pages won't works

**Pull request merged**
