### PR TITLE
Add the ability to filter the Add Indexer datatable 

### PR DESCRIPTION
**Pull request by wdupree**
Add the ability to filter the Add Indexer datatable by language based the value selected by a drop down

### CODE REVIEW

**Comment by garfield69** [comment]
bump the date so that cache does not prevent loading new version.
https://github.com/Jackett/Jackett/blob/f2a0898340d8ce338bc4ee94c6787a6f0e104e97/src/Jackett.Common/Content/index.html#L701
thanks.

**Review by garfield69 — CHANGES_REQUESTED** [review]
Now that we have the language filter, how feasible is it to add a filter for the type?

**Comment by garfield69** [comment]
I have a feeling that the `th` is only for the `thead` block, and we need to use `td` for the `tfoot`
https://www.w3schools.com/TAGS/tag_tfoot.asp

**Review by garfield69 — APPROVED** [review]
Hmm. I clearly do not understand the role of the tfoot in this, so since it is working fine in testing I'm going to merge it. 
The filtering of the type column can be done in a separate PR if there is interest for it.

**Comment by garfield69** [comment]
v0.17.938

**Comment by wdupree** [comment]
> Hmm. I clearly do not understand the role of the tfoot in this, so since it is working fine in testing I'm going to merge it.
> The filtering of the type column can be done in a separate PR if there is interest for it.

The footer is what allows the dropdown input to be injected for the column. Later in the script, you see where the TFOOT is moved under the THEAD so that the dropdown sits under the header and above the data rows. I used this technique before on another table (used for LEGO parts). Give it a try and make sure it works for you :)

**Comment by wdupree** [comment]
> Now that we have the language filter, how feasible is it to add a filter for the type?

Yes! That's what I'm working on now. I just have to figure out how to use the "hidden" string column values instead of the markup column that's displayed. Once I have a good solution - I can add that filter too. Glad you find it helpful!

**Pull request merged**
