### PR TITLE
Added TorrentWal Support and updated tracker list.

### PR DESCRIPTION
**Pull request by tide4cw**
With TorrentKim going down, I wanted to utilize Jackett with a Korean public tracker so I added a definition for TorrentWal. The format of the website is nearly identical to TorrentKim and the yml is essentially the same as https://github.com/Jackett/Jackett/pull/2620 with some modifications to make sure the data makes sense.

There is no support for seeder/leecher ratios from what I can gather on the website (every torrent seems to have 0/0 ratio and the search URL doesn't even provide those numbers). But everything else should be working! A blank search will pull up "유희열" as the search term. There's no justification for that; I used the previous user's search conditional and I happened to be watching a show called "Yoo Huiyeol's Sketchbook" ("유희열의 스케치북").

I'm not sure how the previous user was able to use TorrentKim for Sonarr because there doesn't seem to be foreign language support and show searching is locked to TVDB in English. I'm trying to see if PyMedusa will serve as an alternative but that's not looking too promising so far either. If anyone has an alternative that allows either for foreign language shows or allows for more customizable searches, it would be appreciated (regex based searches for matched shows?).

### CODE REVIEW

**Comment by garfield69** [comment]
Terrific. Thank you.

**Comment by garfield69** [comment]
included in jackett pre-release 0.11.626

**Comment by garfield69** [comment]
https://torrentwal.com/ returning 
image
would appear the site is down for maintenance?

**Comment by jlee755** [comment]
Yeah, I believe it's down for maintenance right now.

**Comment by tide4cw** [comment]
^ Wrong account... That's me.

**Pull request merged**
