### PR TITLE
Support freeleech flag on hdcity

### PR DESCRIPTION
**Pull request by rubasace**
Add support for global freeleech flag

### CODE REVIEW

**Comment by RoloSoze** [comment]
> 
> 
> Add support for global freeleech flag

Thank you. If HDCity has official recruitment somewhere, feel free to email me about it. I'd love to join.

**Comment by garfield69** [comment]
@rubasace  Thank you for the PR.

**Comment by garfield69** [comment]
Jackett 0.16.71

**Comment by rubasace** [comment]
@RoloSoze I'm afraid there are no invitations or anything

**Pull request merged**
