### PR TITLE
core: disable tv-search by default

### PR DESCRIPTION
**Pull request by ngosang**
* Disable tv-search in music trackers
* Add TVRage search in Cardigann

### CODE REVIEW

**Comment by ngosang** [comment]
@garfield69 Please:
* Document TVRage (rid) parameter in tv-search => https://github.com/Jackett/Jackett/compare/master...ngosang:feature/tests5?expand=1#diff-e7eb80ad080ca8398fe32bbf55142b5c0e4d3f6fd41211671f0a7d335332c3f8R326
* What we should do with porn trackers like empornium / erzsebet / femdomcult / focusx / kinorun? Use the movie-search, tv-search or both ?

**Comment by garfield69** [comment]
>Document TVRage (rid) parameter in tv-search

added to wiki https://github.com/Jackett/Jackett/wiki/Definition-format#caps

>What we should do with porn trackers like empornium / erzsebet / femdomcult / focusx / kinorun? Use the movie-search, tv-search or both ?

IMO, neither. I doubt that Sonarr or Radarr have porn in their search databases, so no one is going to use those torznab apps to look for them.
The default search mode in those indexers will take care of those that use the dashboard.
and if anyone complains we can always review on a case by case basis.

**Comment by garfield69** [comment]
addendum: as it happens those porn trackers you mentioned already have search, tv-search and movie-search with the basic q parm only, so we will leave them alone for now.

**Comment by ilike2burnthing** [comment]
Bonarr (yes, really...) may be used - https://github.com/klassicstudios/Bonarr

**Comment by ngosang** [comment]
> The default search mode in those indexers will take care of those that use the dashboard.

I agree

**Pull request merged**
