### PR TITLE
Added a "select" input type and "default" value for settings.

### PR DESCRIPTION
**Pull request by AeonLucid**
Title speaks for itself. 

I also modified the "nyaa.si" indexer to show what is possible with this PR. It contains the changes of https://github.com/Jackett/Jackett/pull/1419, but then easier to use.

Let me know what you think.

### CODE REVIEW

**Comment by kaso17** [comment]
Looks ok to me.

But the use case (select categories on the tracker level looks odd to me). I would suggest changing it to the usual per request mapping (torznab cat query parameter). For nyaa.si we probably would have to add a "custom category mapping" feature because the non numeric category IDs. Do they support searching in multiple categories at the same time?

**Comment by AeonLucid** [comment]
@kaso17 https://nyaa.si/ doesn't but anidex for example does https://anidex.info/?id=1,2,3&adv=1&lang_id=1&q= (notice the comma separated ids).

**Comment by kaso17** [comment]
That's why we added support or custom categories (a 1:1 mapping of torznab categories to tracker categories).
I added support for it via d95e55137ad3748c2876d5926478a6e308416dd6 for anidex.
With the patch you can do a search like this (assuming you didn't configure the cat ID):
http://127.0.0.1:9117/torznab/anidex?apikey=&cat=100001,100003
It will only return torrents from the Anime Sub and Anime Dub categories (ID 1 and 3 on the tracker).
Unfortunately this is only supported for trackers with numeric category IDs at this time.
And trackers which don't support search in multiple queries at the same time are a general problem.
I would suggest to remove the cat-id option from anidex.

**Comment by AeonLucid** [comment]
This only applies to categories right? Didn't know that was possible, I'll apply it to the other anime indexers soon. 

Select box could still be relevant other settings I guess, such as language.

**Comment by kaso17** [comment]
yes, only applies for categories.

**Pull request merged**
