### PR TITLE
Update FileList category mappings

### PR DESCRIPTION
**Pull request by mihaiblaga89**
```
<option value="0">(all)</option>
<option value="24">Anime</option>
<option value="11">Audio</option>
<option value="15">Cartoons</option>
<option value="18">Misc</option>
<option value="16">Docs</option>
<option value="25">Movies 3D</option>
<option value="20">Movies Blu-Ray</option>
<option value="2">Movies DVD</option>
<option value="3">Movies DVD-RO</option>
<option value="4">Movies HD</option>
<option value="19">Movies HD-RO</option>
<option value="1">Movies SD</option>
<option value="10">Games Console</option>
<option value="9">Games PC</option>
<option value="17">Linux</option>
<option value="22">Mobile</option>
<option value="8">Software</option>
<option value="21">Movies  HD</option>
<option value="23">Movies SD</option>
<option value="13">Sport</option>
<option value="14">TV</option>
<option value="12">Videoclip</option>
<option value="7">XXX</option>
```

Translated

### CODE REVIEW

**Comment by kaso17** [comment]
merged, thank you.

FYI: AddCategoryMapping() now supports a third argument which should be set to the tracker category name (Instead of putting it into a comment). It will be used soon for a 1:1 category mapping.

**Comment by mihaiblaga89** [comment]
@kaso17 understood. i'll make another pull request for this when I'm available. By the way, i've just started to build a system like sonarr for games and books, because the ones that exist right now are pretty buggy. I'm planning to use Jackett for searching, i'm guessing it shouldn't be an issue to search for games if I pass the correct category IDs, right?

Thanks,
Mihai

**Comment by kaso17** [comment]
Added initial support for the 1:1 category mappings.
If the Category Description (third AddCategoryMapping() argument) is specified custom categories (category ID+100000) are automatically created.
E.g. the t=caps query for IPtorrents will now return the IPTorrents specific categories in addition to the generic Newznab ones (See the example below). Unfortunately the newznab category mappings for games/books are not very detailed and often don't match the tracker categories very well. I would recommend that you query the categories and make the user select the categories he wants to use for the corresponding indexers.

Let us know once you've a release so we can add it to the list of related projects.

```xml
<?xml version="1.0"?>
<caps>
    <searching>
        <search available="yes" supportedParams="q"/>
        <tv-search available="yes" supportedParams="q,season,ep"/>
        <movie-search available="yes" supportedParams="q,imdbid"/>
    </searching>
    <categories>
        <category id="100060" name="Anime"/>
        <category id="100001" name="Appz"/>
        <category id="100086" name="Appz/Non-English"/>
        <category id="100064" name="AudioBook"/>
        <category id="100035" name="Books"/>
        <category id="100094" name="Comics"/>
        <category id="100026" name="Documentaries"/>
        <category id="100095" name="Educational"/>
        <category id="100098" name="Fonts"/>
        <category id="100074" name="Games"/>
        <category id="100002" name="Games/Mixed"/>
        <category id="100047" name="Games/Nintendo DS"/>
        <category id="100043" name="Games/PC-ISO"/>
        <category id="100045" name="Games/PC-Rip"/>
        <category id="100039" name="Games/PS2"/>
        <category id="100071" name="Games/PS3"/>
        <category id="100040" name="Games/PSP"/>
        <category id="100050" name="Games/Wii"/>
        <category id="100044" name="Games/Xbox-360"/>
        <category id="100069" name="Mac"/>
        <category id="100092" name="Magazines / Newspapers"/>
        <category id="100076" name="Miscellaneous"/>
        <category id="100058" name="Mobile"/>
        <category id="100087" name="Movie/3D"/>
        <category id="100077" name="Movie/480p"/>
        <category id="100089" name="Movie/BD-R"/>
        <category id="100090" name="Movie/BD-Rip"/>
        <category id="100096" name="Movie/Cam"/>
        <category id="100006" name="Movie/DVD-R"/>
        <category id="100048" name="Movie/HD/Bluray"/>
        <category id="100054" name="Movie/Kids"/>
        <category id="100062" name="Movie/MP4"/>
        <category id="100038" name="Movie/Non-English"/>
        <category id="100068" name="Movie/Packs"/>
        <category id="100020" name="Movie/Web-DL"/>
        <category id="100007" name="Movie/Xvid"/>
        <category id="100072" name="Movies"/>
        <category id="100075" name="Music"/>
        <category id="100003" name="Music/Audio"/>
        <category id="100080" name="Music/Flac"/>
        <category id="100093" name="Music/Packs"/>
        <category id="100037" name="Music/Video"/>
        <category id="100036" name="Pics/Wallpapers"/>
        <category id="100021" name="Podcast"/>
        <category id="100055" name="Sports"/>
        <category id="100073" name="TV"/>
        <category id="100078" name="TV/480p"/>
        <category id="100023" name="TV/BD"/>
        <category id="100024" name="TV/DVD-R"/>
        <category id="100025" name="TV/DVD-Rip"/>
        <category id="100066" name="TV/Mobile"/>
        <category id="100082" name="TV/Non-English"/>
        <category id="100065" name="TV/Packs"/>
        <category id="100083" name="TV/Packs/Non-English"/>
        <category id="100079" name="TV/SD/x264"/>
        <category id="100022" name="TV/Web-DL"/>
        <category id="100005" name="TV/x264"/>
        <category id="100099" name="TV/x265"/>
        <category id="100004" name="TV/Xvid"/>
        <category id="100088" name="XXX"/>
        <category id="100085" name="XXX/Magazines"/>
        <category id="100008" name="XXX/Movie"/>
        <category id="100081" name="XXX/Movie/0Day"/>
        <category id="100091" name="XXX/Packs"/>
        <category id="100084" name="XXX/Pics/Wallpapers"/>
        <category id="1000" name="Console">
            <subcat id="1010" name="Console/NDS"/>
            <subcat id="1020" name="Console/PSP"/>
            <subcat id="1030" name="Console/Wii"/>
            <subcat id="1040" name="Console/Xbox"/>
            <subcat id="1050" name="Console/Xbox 360"/>
            <subcat id="1060" name="Console/Wiiware/VC"/>
            <subcat id="1070" name="Console/XBOX 360 DLC"/>
            <subcat id="1080" name="Console/PS3"/>
            <subcat id="1090" name="Console/Other"/>
            <subcat id="1110" name="Console/3DS"/>
            <subcat id="1120" name="Console/PS Vita"/>
            <subcat id="1130" name="Console/WiiU"/>
            <subcat id="1140" name="Console/Xbox One"/>
            <subcat id="1180" name="Console/PS4"/>
        </category>
        <category id="1010" name="Console/NDS"/>
        <category id="1020" name="Console/PSP"/>
        <category id="1030" name="Console/Wii"/>
        <category id="1050" name="Console/Xbox 360"/>
        <category id="1080" name="Console/PS3"/>
        <category id="1090" name="Console/Other"/>
        <category id="2000" name="Movies">
            <subcat id="2010" name="Movies/Foreign"/>
            <subcat id="2020" name="Movies/Other"/>
            <subcat id="2030" name="Movies/SD"/>
            <subcat id="2040" name="Movies/HD"/>
            <subcat id="2050" name="Movies/3D"/>
            <subcat id="2060" name="Movies/BluRay"/>
            <subcat id="2070" name="Movies/DVD"/>
            <subcat id="2080" name="Movies/WEBDL"/>
        </category>
        <category id="2010" name="Movies/Foreign"/>
        <category id="2030" name="Movies/SD"/>
        <category id="2040" name="Movies/HD"/>
        <category id="2050" name="Movies/3D"/>
        <category id="2060" name="Movies/BluRay"/>
        <category id="2070" name="Movies/DVD"/>
        <category id="3000" name="Audio">
            <subcat id="3010" name="Audio/MP3"/>
            <subcat id="3020" name="Audio/Video"/>
            <subcat id="3030" name="Audio/Audiobook"/>
            <subcat id="3040" name="Audio/Lossless"/>
            <subcat id="3050" name="Audio/Other"/>
            <subcat id="3060" name="Audio/Foreign"/>
        </category>
        <category id="3010" name="Audio/MP3"/>
        <category id="3020" name="Audio/Video"/>
        <category id="3030" name="Audio/Audiobook"/>
        <category id="3040" name="Audio/Lossless"/>
        <category id="4010" name="PC/0day"/>
        <category id="4020" name="PC/ISO"/>
        <category id="4030" name="PC/Mac"/>
        <category id="4040" name="PC/Phone-Other"/>
        <category id="4050" name="PC/Games"/>
        <category id="5000" name="TV">
            <subcat id="5010" name="TV/WEB-DL"/>
            <subcat id="5020" name="TV/FOREIGN"/>
            <subcat id="5030" name="TV/SD"/>
            <subcat id="5040" name="TV/HD"/>
            <subcat id="5050" name="TV/OTHER"/>
            <subcat id="5060" name="TV/Sport"/>
            <subcat id="5070" name="TV/Anime"/>
            <subcat id="5080" name="TV/Documentary"/>
        </category>
        <category id="5010" name="TV/WEB-DL"/>
        <category id="5020" name="TV/FOREIGN"/>
        <category id="5030" name="TV/SD"/>
        <category id="5040" name="TV/HD"/>
        <category id="5060" name="TV/Sport"/>
        <category id="5070" name="TV/Anime"/>
        <category id="5080" name="TV/Documentary"/>
        <category id="6000" name="XXX">
            <subcat id="6010" name="XXX/DVD"/>
            <subcat id="6020" name="XXX/WMV"/>
            <subcat id="6030" name="XXX/XviD"/>
            <subcat id="6040" name="XXX/x264"/>
            <subcat id="6050" name="XXX/Other"/>
            <subcat id="6060" name="XXX/Imageset"/>
            <subcat id="6070" name="XXX/Packs"/>
        </category>
        <category id="6050" name="XXX/Other"/>
        <category id="6060" name="XXX/Imageset"/>
        <category id="6070" name="XXX/Packs"/>
        <category id="7000" name="Other">
            <subcat id="7010" name="Other/Misc"/>
            <subcat id="7020" name="Other/Hashed"/>
        </category>
        <category id="8000" name="Books">
            <subcat id="8010" name="Books/Ebook"/>
            <subcat id="8020" name="Books/Comics"/>
            <subcat id="8030" name="Books/Magazines"/>
            <subcat id="8040" name="Books/Technical"/>
            <subcat id="8050" name="Books/Other"/>
            <subcat id="8060" name="Books/Foreign"/>
        </category>
        <category id="8020" name="Books/Comics"/>
        <category id="8030" name="Books/Magazines"/>
        <category id="8050" name="Books/Other"/>
    </categories>
</caps>

```

**Comment by mihaiblaga89** [comment]
Sure, i'll give you guys a heads up. Thanks for the info.

**Pull request merged**
