### PR TITLE
Updated 1337X links

### PR DESCRIPTION
**Pull request by vdbhb59**
Added onion v3 (beta) link, and removed the 2 non-working proxy links. Those 2 have been giving 502, 404, and various errors for almost 5 days now.
Added: l337xdarkkaqfwzntnfk5bmoaroivtl6xsbatabvlb52umg6v3ch44yd.onion
Removed: https://1337x.unblockit.africa/ & https://1337x.unblockninja.com/

1337X Status: https://1337x-status.org/

@garfield69 how to add onion links to the files? I removed it as Jackett check was failing, but if you can add it, it will be helpful.

### CODE REVIEW

**Comment by garfield69** [comment]
>how to add onion links to the files? 

you cannot add links with the .onion suffix as Jackett does not support TOR.
However, if you can find an active tor proxy that uses http then you can.
We used to be able to use .onion.ly , .tor2web.to and .tor2web.link but these have not worked for some time now.
I have not spent any more time researching working alternatives for converting .onion links to http but there may well be something out there if you want to go looking.

Also https://1337x.unblockninja.com/ is working for me.
And according to https://www.reddit.com/r/Unblockit/comments/1b938o9/domain_update/ktt5mvi/ the unblockit team have asked to be white listed to allow 1337x to work. 
unblockit domains are renewed every month anyway so we should wait for the new domain to be published (usually around the 7th-8th of the month) and remove the link if it still not working after that.

**Comment by vdbhb59** [comment]
Ahh gotcha mate. So, let me wait till 9th for the unblockit ones at least, and meanwhile I will try and research some onion>web2 protocols, or sort of. Keeping this merge request open till then.

**Comment by garfield69** [comment]
In future, before committing to remove a link, test it with https://www.uptrends.com/tools/uptime to confirm its broken across most regions that your local.

**Comment by vdbhb59** [comment]
@garfield69 mate I have reverted the 1337X changes as they are working on cross proxy checks, but not directly on my ISP, which is fine.
I have also added one unofficial YTS proxy to the list. Request you to merge the PR now please.
Apologies for the 1337X confusion and unnecessary work caused due to that.

**Comment by vdbhb59** [comment]
Also, on a separate note, how to add a new site altogether? I have found one site called Nyaa: https://nyaa.land/ and I can see that Jackett does not have it (unless my search of Jackett did not land correctly). Kindly suggest or add it please to indexes.

**Comment by ilike2burnthing** [comment]
Thanks, but yts.nz is a clone rather than a proxy. Notice the `Blog` link at the bottom is replaced with `YTS`, which links to another less convincing clone. Search results and `Trending Movies` are different as well.

nyaa.land is an existing proxy for nyaa.si:

https://github.com/Jackett/Jackett/blob/bea94acd47af913866d6357faf29da59f538d0c4/src/Jackett.Common/Definitions/nyaasi.yml#L12

**Pull request closed without merging**
