### PR TITLE
T411v2: Fix Greys Anatomy search

### PR DESCRIPTION
**Pull request by alimnette**
Fixes Greys Anatomy V2 for T411 french keywords

### CODE REVIEW

**Comment by garfield69** [comment]
This patch is failing the jackett dashboard TEST.
The url generated by this patch is `https://t411.si/torrents/search/?search=?keywords=` which causes t411.si to look for `?keywords=`, for which there are no results.

**Comment by garfield69** [comment]
to fix the problem change code to the following:
```yaml
    path: /torrents/search/
    keywordsfilters: #1963
      - name: replace # Add Keywords
        args: ["Greys Anatomy", "Grey's Anatomy"]
    inputs:
      search: "{{ .Keywords }}"
```

**Comment by WhoKnowsWhat** [comment]
Wow, you are not going to merge that shity fix right ?
Adding 5 lines to fix only 1 specific show..

At least do something like that : 
```
    keywordsfilters:
      - name: urlencode
```
it should fix every request.

**Comment by kaso17** [comment]
@garfield69 is right, @alimnette can you fix that detail?

**Comment by kaso17** [comment]
fixed it, thank you

**Comment by Jarusz** [comment]
> I'd recommend doing something like this:
> 
> ```
>     keywordsfilters:
>       - name: urlencode
> ```
> 
> it should fix every request, it's not related to a specific show.

could you tell me please, where to add this, i have problem with grey's anatomy as well, but i have no idea how to fix it
im using jackett in docker if that matters

**Comment by ilike2burnthing** [comment]
For what indexer(s)?

**Pull request merged**
