### PR TITLE
redacted: renabled api

### PR DESCRIPTION
**Pull request by seeyabye**
Since https://github.com/Jackett/Jackett/pull/10528 has been merged, it's now possible to have accurate User-Agent which is the criteria for using Redacted's API (See https://github.com/Jackett/Jackett/issues/9751 https://github.com/Jackett/Jackett/issues/8898)

Before we consider this to be re-merged, I would like to request for testers to see if a ban still happens. Would appreciate it if some of you could test this beforehand.

@LennyPenny maybe you could lend a hand?

### CODE REVIEW

**Comment by LennyPenny** [comment]
I would love to but because _reasons_ I sadly cannot

**Comment by seeyabye** [comment]
That's fine.

If anyone else can lend a hand to test it, you can download the binaries from Jackett's azure pipeline:

[https://dev.azure.com/Jackett/Jackett/_build/results?buildId=3706&view=artifacts&pathAsName=false&type=publishedArtifacts](https://dev.azure.com/Jackett/Jackett/_build/results?buildId=3706&view=artifacts&pathAsName=false&type=publishedArtifacts)

- Click on the triple dot icon, and choose 'Download Artifacts'

**Comment by ilike2burnthing** [comment]
@flying-sausages @HamilcarH @DontWorryScro @silverberrypepperfox @Wedleey @skupjoe

**Comment by flying-sausages** [comment]
Pls don't ping me lol. I've got a banned IP rn anyway so can't help.

**Comment by ilike2burnthing** [comment]
@ThatNerdyPikachu @bool-

**Comment by ilike2burnthing** [comment]
@Winblackka @tannhauserg8 @Ayfteyd7Od @curiositycasualty @Oius @ordinarygulp @mvanbaak @BurhanDanger @Y0lan @Brando47 @awsms @danaimone @ljmerza @joydashy @jgillman @fana13

https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/3821/artifacts?artifactName=drop&api-version=6.0&%24format=zip

**Comment by Junkbite** [comment]
@ilike2burnthing is there a hotio build for this PR? I couldnt find one

**Comment by ilike2burnthing** [comment]
No, hotio base their images on our releases, not PR builds. You'd have to install this locally as a test, and if you can confirm it's working then we can merge it for a future release.

**Comment by ynavott** [comment]
I would be willing to test this, but the test build is unavailable

**Comment by ilike2burnthing** [comment]
https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/3960/artifacts?artifactName=drop&api-version=6.0&%24format=zip

**Comment by seeyabye** [comment]
@ynavott you should be able to download the artifacts from Azure Pipelines. Here's the direct link to the artifact that you can download

[https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/3960/artifacts?artifactName=drop&api-version=6.0&%24format=zip](https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/3960/artifacts?artifactName=drop&api-version=6.0&%24format=zip)

**Comment by ynavott** [comment]
Well, it's working fine and it looks like I'm not being banned when using the manual search/test functions.
Anything specific you want me to try/any other details you want me to provide?

**Comment by ilike2burnthing** [comment]
Are you using any automation software (e.g. Sonarr) that uses Redacted? If so, it'd be good to run this for 24hrs to make sure there are no issues.

**Comment by ynavott** [comment]
> Are you using any automation software (e.g. Sonarr) that uses Redacted? If so, it'd be good to run this for 24hrs to make sure there are no issues.

I will run it with lidarr for 24 hours and see if it breaks

**Comment by ilike2burnthing** [comment]
All good?

**Comment by ynavott** [comment]
I ran it for a few hours without any issues but then decided to turn it off and contact the RED dev team about running a testing build, since they specifically instructed people to not use jackett until the API support is reimplemented correctly. I will update when I receive their answer, but regardless running lidarr with a jackett torznab source for around 7 hours was successful with no issues (I made sure the sync tasks actually activated in lidarr as well).

**Comment by ynavott** [comment]
Update - after contacting the RED dev team they have kindly given me official approval to run the test build. will try to run it again now and keep you posted

**Comment by ilike2burnthing** [comment]
Thanks! I'll keep my fingers crossed.

**Comment by ilike2burnthing** [comment]
All good?

**Comment by ynavott** [comment]
> All good?

Hi, I was on vacation for a little bit so I had to stop it in the middle. I have restarted the experiment yesterday and will let it run for a few days and see if anything happens.

**Comment by ynavott** [comment]
@ilike2burnthing I have been running lidarr with the torznab feed for the jackett RED API indexer as a source for the past 5 days and have not gotten any warnings/ratelimits/bans - all the syncs completed correctly.
I think this is safe to merge

**Comment by ilike2burnthing** [comment]
Thanks. This will be out in the next release.

**Pull request merged**
