### PR TITLE
Add logos

### PR DESCRIPTION
**Pull request by khalidabuhakmeh**
Color logo for Jackett

image

Added them as SVG, so you can pick and choose colors that you like. Also included a plain one :)

#hacktoberfest

### CODE REVIEW

**Comment by ngosang** [comment]
Your design is not bad but it won't scale well to 16x16 px favicon. It has too many details.
I'm happy with current design. Could you try to modernize current icon instead of making a new one?

Related apps have different designs:
image
image
image
image
Bazarr
image
Jackett

**Comment by ilike2burnthing** [comment]
For **green-with-shadow.svg** I like the look of changing `#004c2d` for `#00bfd4`, so it includes the colours of Sonarr, Lidarr, and Radarr (and Bazarr as well I suppose) all in one logo.

blue

This can be taken a step further to also include the colour of Readarr as well.

readarr

My suggestion would be the pockets. An accurate colour would be something like `#8e2423`, but if we wanted something a little brighter, then perhaps `#ab1f1d`. Path-3 and Path-4 would have to be swapped so it doesn't look like there's a red belt buckle.

blue+red

**Comment by ngosang** [comment]
@Jackett/maintainers what do you think about the logo? It's time to change it?

**Comment by ilike2burnthing** [comment]
If we could give users a choice, I don't see there being a negative side to it (other than having to work out how to do that). Probably keep the current one as the default though.

**Comment by ilike2burnthing** [comment]
An obvious inclusion would seem to be an inverted b&w:
white black
(there's a white circle around it too)

**Comment by ngosang** [comment]
Well, I don't see enough enthusiasm. Should we close?

**Pull request closed without merging**
