### PR TITLE
Add a script to install Jackett as service on macOS

### PR DESCRIPTION
**Pull request by thebluepotato**
As mentioned in #1691, I've added instructions to the README on how to run Jackett as a service on each startup on macOS. I've tried it by calling JackettService.exe but it's suboptimal. Therefore the plist simply calls `mono JackettConsole.exe`.
I'd like your feedback on whether this is a desirable addition to the README or not and where I should put the file in the source. Should it be added to Mono Binary releases or should the instructions point to the file in the source?

Thanks for reading! Cheers

### CODE REVIEW

**Comment by kaso17** [comment]
JackettService is only for Windows.
Your approach is absolutely correct.

I would suggest to add the --debug flag to mono (mono --debug JackettConsole.exe). With it the debug symbols are loaded and the exceptions contain line numbers (very helpful).

What does the KeepAlive flag do? Will it automatically restart Jackett in case it crashes?
If it does then try adding the --NoRestart argument (mono --debug JackettConsole.exe --NoRestart).
That will improve the update experience. With the flag set the updater will extract the new files and then Jackett will just exit expecting the init system to restart it. Otherwise the updater process will restart jackett (which might confuse the init system). Can you test the update mechanism for macos?

**Comment by thebluepotato** [comment]
So this is the `KeepAlive` key:

> KeepAlive
   &lt;boolean or dictionary of stuff>
     This optional key is used to control whether your job is to be kept continuously running or to let demand and conditions control the invocation. The default is false and therefore only demand will start the job. The value may be set to true to unconditionally keep the job alive.

I've just had an issue with it because somehow another instance of Jackett was running and `launchd` kept trying to resuscitate it (only for it to exit because Jackett was already listening to port 9117. So I'll have to check how to optimize this. I've had this issue when `LaunchOnlyOnce` was set to false (the default). The description of `LaunchOnlyOnce` is more or less that it can't be respawned safely without a system reboot (definitely _not_ our case here).

Regarding the update mechanism, it failed because of the following error:
````
2017-08-23 11:46:58.5509 Error Error performing update. System.ComponentModel.Win32Exception (0x80004005): ApplicationName='mono', CommandLine='/var/folders/p6/54pvrv0j32gf4h2vvjgdbk680000gn/T/JackettUpdate-v0.8.91-636390856181164100/Jackett/JackettUpdater.exe --Path "/Applications/Jackett" --Type "mono" --Args " jackettconsole.exe --NoRestart" --KillPids "45024" --NoRestart', CurrentDirectory='', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x002dc] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/System/System.Diagnostics/Process.cs:767 
  at System.Diagnostics.Process.Start () [0x0003a] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs:2005 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x0001b] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs:2476 
  at Jackett.Services.UpdateService.StartUpdate (System.String updaterExePath, System.String installLocation, System.Boolean isWindows, System.Boolean NoRestart) [0x00132] in C:\projects\jackett\src\Jackett\Services\UpdateService.cs:299 
  at Jackett.Services.UpdateService+<CheckForUpdates>c__async1.MoveNext () [0x00365] in C:\projects\jackett\src\Jackett\Services\UpdateService.cs:134 
````
Running `mono` with the arguments given above did update successfully apart from killing the PID (I'm guessing KeepAlive is so strong it kicks in immediately?). My guess is that Jackett isn't calling correctly somehow (it doesn't find the executable I mean).

What does it do if I strip `--NoRestart` (and disable `KeepAlive`)? Would Jackett restart on crash?

**Comment by kaso17** [comment]
That error looks like it can't find the mono binary. Is it necessary to use the full path on macos? Or is this special in your setup.
Jackett won't restart on crash on it's own. That's why running it via an init system which restarts it automatically is the preferred way. In that case `--NoRestart` is needed. The problem you described (init system trying to restart jackett continuously while it's already running) is the result if you don't use the `--NoRestart` switch.

**Comment by thebluepotato** [comment]
I know that in the plist absolute paths have to be used, but maybe this also applies to programs called within a service run by `launchd`. I've tried updating with Jackett called directly from Terminal and it worked flawlessly (no issue finding `mono`).
Regarding the restart loop: it even does it with `mono --debug JackettConsole.exe --NoRestart`. As soon as the agent quits because Jackett is already running, `KeepAlive` runs it again and it quits again, etc. The workaround is to disable `KeepAlive` when the agent exits with an error. This fixes the restart loop.
I now have a better understanding of `--NoRestart`. Indeed, when running from Terminal and updating without `--NoRestart`, it restarted with output to Terminal but the process didn't exit when Terminal was quit. If you meant that running Jackett without it could create an instance of Jackett that would block the one run as service, then you're absolutely right.

**Comment by thebluepotato** [comment]
Ok so I've been able to set it up like this:
 - Restart when the program crashes (doesn't work but I'm leaving it here since it might by a bug?).
 - Dirty yet somehow elegant workaround: start when `~/.config/Jackett/updater.txt` is modified. Whenever the updater is started, that file is modified and then bam, it restarts. I've tried an update and miraculously it worked!

Other settings either wouldn't restart the service at all upon updates or would restart it upon errors (causing a loop) or worse making the service unkillable (restarted upon SIGKILL until the plist was "unloaded").

I'd like to try writing a short shell script installing that plist automatically when run from Jackett's working directory (regardless of its path).

**Comment by kaso17** [comment]
Your watched path hack/conditional keepalive seems to be to complicated for me.
With the --NoRestart flag jackett will never start itself. launchd is the only one who will start jackett.
In case of an update the updater will extract the new files and after that send a SIGKILL to the running jackett instance. Jackett will exit and launchd will start the new jackett version.
I don't see how there might be a restart loop (unless the user somehow managed to start jackett manually before launchd).
Does launchd has an option to throttle/stop after a certain amount of restart attempts?

Besides that I think you can further simplify the file because you don't have to specify the full path to JackettConsole.exe anymore in the ProgramArguments as you set the WorkingDirectory. Maybe you dont't have to specify the absolute mono path in the Arguments anymore either (since you set the PATH variable)?

**Comment by thebluepotato** [comment]
My goal was to prevent restart loops from _ever_ happening, in case the user started it manually. If we get rid of this "protection", setting `KeepAlive` to true regardless makes Jackett immortal. You can kill it, but it comes back immediately (I feel like I'm writing about zombies here).
I can get rid of `KeepAlive` completely and keep the updater "hack" for restarts or get rid of everything. In the latter case, without `--NoRestart` Jackett would start on boot (or logon I think), stay alive until killed by the updater or because of a crash, and come back thanks to the updater but outside of the scope of `launchd` (which doesn't change much from the user's perspective other that you can't stop it using `launchctl`, but you can still kill it from Activity Monitor).
Regarding the paths: Ha! if only we could. `launchd` is adamant about requiring absolute paths for the program (unless set in _PATH_STDPATH). Moreover, the `WorkingDirectory` is set after invocation using `chdir` so it isn't available at the beginning...
The install script I'm working on would locate mono using `which mono` and know Jackett's working directory since it'd be run from it. Thus, it would remove all requirement for user input.

**Comment by kaso17** [comment]
If you do a `launchctl stop org.user.Jackett` with keepalive=yes it still would be restarted?
Then your workaround makes sense. Otherwise I would expect the user to properly stop the service via launchctl if he wants jackett to stop.

The full path to JacketConsole.exe is still needed too? It's just an argument for mono and I would expect that the chdir happens just before mono is executed.

**Comment by thebluepotato** [comment]
If you run `launchctl stop org.user.Jackett` it will stop and relaunch instantly. You can only kill it with `launchctl unload ~/Library/LaunchAgents/org.user.Jackett.plist`. Quick explanation: for an agent to run, it has to be loaded and started. Agents whose plist is in `~/Library/LaunchAgents` are automatically loaded on logon. With the `RunAtLoad` parameter, the agent starts when loaded so if the plist is inside the aforementioned folder, it's both loaded and started automatically. Subsequent restarts depend on parameters like `KeepAlive`. Long story short, you can't stop it _per se_ but you can unload it. Restarting happens with `load`instead of `unload`. And to answer your previous question: it doesn't seem like you can limit the number of restarts.
So for the various restart mechanisms we have at our disposal:

- `KeepAlive` no matter what: works well, but with the risk of restart loops if for any reason Jackett crashes on startup
- (`KeepAlive` only on crashes: would restart on the updater's SIGKILL but sadly it doesn't work...)
- No `KeepAlive` but (re)start when updater.txt is modified: effective but dirty

Regarding the paths: apparently it _does_ change before running! So you are right, the full path isn't needed. However, with the little script I'm brewing up, the same path is used in both places (but I'll remove it for readability's sake). For mono's path, we can circumvent having it twice in the plist by calling `/bin/sh -c "mono --debug JackettConsole.exe --NoRestart"` instead of `/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono --debug JackettConsole.exe --NoRestart`, but it still needs to be set in the PATH environment variable. I'm not very fond of calling the shell just to shorten the invocation.

Will continue testing and will upload the script!

**Comment by thebluepotato** [comment]
So now there's an easy peasy script to handle the installation for you! It basically does what it says:
 - Checks whether Mono is installed
 - Checks if we're running from Jackett's directory
 - Writes the plist to `~/Library/LaunchAgents/`
 - Loads it and checks if it's running

I've currently set the plist to `KeepAlive` no matter what. Depending on your input, I can easily choose another restart mechanism.

However, I have no idea where in the source tree this file should be for it to be included inside the Mono binaries gzipped tarball beside JackettConsole.exe... Can you help me out for this?

The README still needs updating too.

**Comment by kaso17** [comment]
Looks fine to me. But I would choose a more macos specific name of the script (install_service_launchd.sh ?)
And you'll also have to make it part of a project (e.g. move it to src/Jackett.Console/) and add it to the csproj file:
e.g. add it to an existing ItemGroup:
```
  <ItemGroup>
    <None Include="App.config" />
    <None Include="packages.config" />
    <Content Include="install_service_launchd.sh">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

**Comment by thebluepotato** [comment]
I settled on `install_service_macos.sh`. According to Appveyor, it seems the file was correctly included!

**Comment by kaso17** [comment]
merged, thank you

**Comment by kaso17** [comment]
@thebluepotato always was wondering about the SSL instructions regarding macos:
According to the readme the following commands should be executed:
```
https://curl.haxx.se/ca/cacert.pem
cert-sync --user ~/Downloads/cacert.pem
```
Does that work on macos (Executing an URL result in a Download to ~/Download/)?
What happens if the file already exists?
You've any recommendation to improve the instruction?
E.g. on linux we recommend running `wget -O - https://curl.haxx.se/ca/cacert.pem | cert-sync /dev/stdin`

**Pull request merged**
