### PR TITLE
danishbytes: add private indexer. resolves #10758

### LINKED ISSUE #10758: [REQ] DanishBytes.org
https://danishbytes.org/

Private tracker. (has open registration undtil 10/01/21)

Looking forward. Really hope you can help us out! Peace and thank you!

### PR DESCRIPTION
**Pull request by ilike2burnthing**
Thanks to @piratkongen to doing most of the work here.

A couple of corrections to the categories, added the option for magnet downloads, and changed the minimum ratio due to the line in the FAQ, "seed at least 48 hours or 1:1 in proportion".

I couldn't see any posters or imdb/tmdb links in the results. Am I missing something, or should these be removed?

### CODE REVIEW

**Comment by piratkongen** [comment]
Thank you for making PR and making the changes.

There are actually imdb and tmdb for the 4 categories:
- Film
- Danske film
- TV
- Dansk TV

And posters are fetched from tmdb.

Can you add that?

**Comment by ilike2burnthing** [comment]
Added tmdbid for TV as well.

The poster and imdb/tvdb/tmdb ids aren't available in the search results page, only the details page for the individual torrent, and so can't be picked up by Jackett (without making 100 additional requests, 1 for each result).

Unless this is something wrong on my end, or something you want to change with the results page, we'd have to remove it from the indexer (not a massive loss).

**Comment by piratkongen** [comment]
They changed their structure, and added new categories!

Can you update the script with following:

    - {id: 7, cat: TV, desc: "Dansk / TV & Serier"}
    - {id: 6, cat: Movies, desc: "Dansk / Film"}
    - {id: 2, cat: TV, desc: "TV & Serier"}
    - {id: 1, cat: Movies, desc: "Film"}
    - {id: 10, cat: Movies, desc: "Film Boxset"}
    - {id: 13, cat: TV, desc: "Cartoon & Anime / TV & Serier"}
    - {id: 12, cat: TV, desc: "Cartoon & Anime / Film"}
    - {id: 5, cat: PC/0day, desc: "Applikationer"}
    - {id: 4, cat: PC/Games, desc: "Spil"}
    - {id: 3, cat: Audio, desc: "Musik"}
    - {id: 9, cat: Audio/Audiobook, desc: "Lydbøger"}
    - {id: 8, cat: Books, desc: "E-Books, Magasiner, osv."}
    - {id: 11, cat: XXX, desc: "XXX"}


Thank you !

**Comment by ilike2burnthing** [comment]
Any word on the poster and imdb/tvdb/tmdb ids being added to the results page (even just hidden in the html)? Or will we just remove that from the indexer and publish?

**Comment by piratkongen** [comment]
I got this error tho:
"Error while creating Cardigann instance from definition ID=danishbytes: System.Exception: Not supported tv-search param: tmdbid".


(I can send you an invite if you wanna check out yourself, just hit me up with your email)


I know these use TMDB and IMDB:
{id: 6, cat: Movies, desc: "Dansk / Film"}
{id: 1, cat: Movies, desc: "Film"}
{id: 12, cat: Movies, desc: "Cartoon & Anime / Film"}

And these uses TVDB or MAL:
{id: 7, cat: TV, desc: "Dansk / TV & Serier"}
{id: 2, cat: TV, desc: "TV & Serier"}
{id: 13, cat: TV, desc: "Cartoon & Anime / TV & Serier"}

**Comment by ilike2burnthing** [comment]
Well that's what I get for doing these on no sleep 😋  tmdb isn't supported for TV search in Jackett. @ngosang would we want to add that?

**Comment by ilike2burnthing** [comment]
Oh by the way, I have an account, but thanks for the offer.

Do you want to wait (Re: the poster and imdb/tvdb/tmdb ids being added to the results page), or publish now according to how the site is at the moment, and make any potential changes later?

**Comment by piratkongen** [comment]
There is a new category again: Music videos 😄 

This is the updated one from my end:
`   
    - {id: 7, cat: TV, desc: "Dansk / TV & Serier"}
    - {id: 6, cat: Movies, desc: "Dansk / Film"}
    - {id: 2, cat: TV, desc: "TV & Serier"}
    - {id: 1, cat: Movies, desc: "Film"}
    - {id: 10, cat: Movies, desc: "Film Boxset"}
    - {id: 13, cat: Movies, desc: "Cartoon & Anime / TV & Serier"}
    - {id: 12, cat: TV, desc: "Cartoon & Anime / Film"}
    - {id: 5, cat: PC/0day, desc: "Applikationer"}
    - {id: 4, cat: PC/Games, desc: "Spil"}
    - {id: 3, cat: Audio, desc: "Musik"}
    - {id: 3, cat: Movies, desc: "Musik / Videoer"}
    - {id: 9, cat: Audio/Audiobook, desc: "Lydbøger"}
    - {id: 8, cat: Books, desc: "E-Books, Magasiner, osv."}
    - {id: 11, cat: XXX, desc: "XXX"}
`

Can we do both? Post now and update when you have time :)

**Comment by ilike2burnthing** [comment]
Let me know if there are any changes needed.

**Comment by ilike2burnthing** [comment]
Not Jackett related, but just a heads up that torrents I'm currently seeding from DB are showing `Tracker reply has no peers field`.

**Comment by ilike2burnthing** [comment]
[v0.17.261](https://github.com/Jackett/Jackett/releases/tag/v0.17.261)

**Comment by piratkongen** [comment]
> Not Jackett related, but just a heads up that torrents I'm currently seeding from DB are showing `Tracker reply has no peers field`.

There was a huge server migration 8-12 hours ago, so should probably be good now

**Comment by ngosang** [comment]
> Well that's what I get for doing these on no sleep yum tmdb isn't supported for TV search in Jackett. @ngosang would we want to add that?

It will be easy to add torznab support for tmdb TV search, but I think Sonarr is not using it so it's a bit useless.
In the future I would like to redo the Jackett UI to add advanced search where you can use this kind of search modes. In the current UI we only support IMDB because the text match the pattern `tt<number>`. The other IDs are just numbers and we don't have enough info.

**Pull request merged**
