### PR TITLE
Update yggtorrent.yml

### PR DESCRIPTION
**Pull request by Humanzed**
ygg no work with old selector ...

#### Description
A few sentences describing the overall goals of the pull request's commits.
make ygg modules work again

#### Screenshot (if UI related)
no screenshot

#### Issues Fixed or Closed by this PR
no issue open

### CODE REVIEW

**Comment by garfield69** [comment]
there is no different is selecting a href using the class and one using the action
if you are having issues with login at ygg it is most likely a problem with flaresolverr not resolving the challenge.
see https://github.com/FlareSolverr/FlareSolverr/issues/1253

**Comment by Humanzed** [comment]
no issue with flareSolverr 
but without this uppdate ygg no work ...
i have solved issue with my linux server before pull here 

Regards

**Comment by ilike2burnthing** [comment]
Can you provide an enhanced log of the failed login for the current release? https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Humanzed** [comment]
`2024-08-15 19:32:13.0908 Error Jackett.Common.IndexerException: Exception (yggto                                    rrent): Login failed: No form found on https://www.ygg.re/auth/login using form                                     selector form[action="/auth/process_login"]

[v0.22.442.0] Jackett.Common.IndexerException: Exception (yggtorrent): Login fai                                    led: No form found on https://www.ygg.re/auth/login using form selector form[act                                    ion="/auth/process_login"]
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on htt                                    ps://www.ygg.re/auth/login using form selector form[action="/auth/process_login"                                    ]
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.DoLogin(String cookie                                    s) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 617
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQ                                    uery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 17                                    59
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Except                                    ion ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 828
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQ                                    uery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 19                                    22
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Bo                                    olean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Bo                                    olean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 389
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query,                                     Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 802
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in                                     ./Jackett.Common/Services/IndexerManagerService.cs:line 324
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server                                    /Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIAction                                    ResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapp                                    er, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeAct                                    ionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 acti                                    onResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNex                                    tActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTas                                    k, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(Ac                                    tionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State                                    & next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInn                                    erFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, St                                    ate next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipel                                    ineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Sco                                    pe scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Aw                                    aited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Aw                                    aited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpCo                                    ntext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpCo                                    ntext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

2024-08-15 19:37:31.5697 Info CardigannIndexer(yggtorrent): Relogin required
2024-08-15 19:37:31.5697 Error Error on 20240815193731 for YggTorrent.txtJackett                                    .Common.ExceptionWithConfigData: Login failed: No form found on https://www.ygg.                                    re/auth/login using form selector form[action="/auth/process_login"]
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.DoLogin(String cookie                                    s) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 617
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQ                                    uery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 17                                    59




<!DOCTYPE html>
<html>

<head>
    <title>YggTorrent - 1er Tracker BitTorrent Francophone</title>

    <meta name="description"
        content="Inscrivez-vous et rejoignez gratuitement la plus grande communa                                    uté P2P francophone pour profiter de milliers de films, séries et logiciels en l                                    ibre-service !" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="interkassa-verification" content="932c353776e6f12b0dac4f654bd3b9bf"                                     />
<link rel="icon" href="/favicon.ico" />


<link rel="stylesheet" href="/assets/css/bootstrap.min.css?cachekiller=1549578">
<link rel="stylesheet" href="/assets/css/animate.min.css">
<link rel="stylesheet" href="/assets/css/fontawesome.css">
<link rel="stylesheet" href="/assets/css/custom.css?cachekiller=15495851">
<link rel="stylesheet" href="/assets/css/master.css?cachekiller=15497190">
<link rel="stylesheet" href="/assets/css/jnotifier.css">
<link rel="stylesheet" href="/assets/css/select2.min.css">
<link rel="stylesheet" href="/assets/css/select2-bootstrap.min.css">


<link crossorigin="anonymous" media="all"
        href="https://fonts.googleapis.com/css?family=EB+Garamond|Montserrat:400                                    ,500,550,600,700|Roboto+Condensed:700|Open+Sans:600|Pangolin"
        rel="stylesheet">


<script type="text/javascript" src="/assets/js/jquery.min.js"></script></head>

<body>

    <style>
        h3 {
            color: #f7f7f7;
            text-transform: uppercase;
            font-size: 15px;
            background: #00000014;
            margin-bottom: 15px;
            padding: 14px 13px;
            border-bottom: 2px solid #ffffff0f;
        }

        .logo-brand {
            display: flex;
            justify-content: center;
            align-items: center;
            margin-bottom: 30px;
        }

        .login-page {
            width: 550px;
            max-width: 100%;
            padding-top: 50px;
            margin: auto;
        }

        .form {
            position: relative;
            z-index: 1;
            margin: 0 auto 100px;
            padding: 15px;
        }

        .form input {
            outline: 0;
            background: #f2f2f2;
            width: 100%;
            border: 0;
            margin: 0 0 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
            border-radius: 5px;
        }

        .form button {
            text-transform: uppercase;
            outline: 0;
            background: #46db8f;
            width: 100%;
            border: 0;
            padding: 15px;
            border-radius: 25px;
            color: #FFFFFF;
            font-size: 14px;
            -webkit-transition: all 0.3 ease;
            transition: all 0.3 ease;
            cursor: pointer;
        }

        a.register {
            text-transform: uppercase;
            text-align: center;
            outline: 0;
            background: #0e0e0e;
            width: 100%;
            border: 0;
            margin-top: 15px;
            font-weight: 500;
            display: block;
            padding: 15px;
            border-radius: 25px;
            color: #68debe !important;
            font-size: 14px;
            -webkit-transition: all 0.3 ease;
            transition: all 0.3 ease;
            cursor: pointer;
        }

        a.register:hover {
            background: #161c22;
        }

        .form button:hover,
        .form button:active,
        .form button:focus {
            background: #5bdb8e;
        }

        .form .message-forgot {
            text-align: center;
            margin: 15px 0 0;
            color: #ffffff;
            font-size: 16px;
            margin-top: 25px;
        }

        .form .message-forgot a {
            color: #feffff;
            text-decoration: none;
        }

        .form .register-form {
            display: none;
        }

        .login-form {
            margin: 20px;
        }

        .form img {
            width: 160px;
        }

        .error-form {
            display: none;
            color: #f2f2f2;
            font-weight: bold;
            text-align: center;
            margin-bottom: 15px;
        }

        .error-form>span {
            color: #ff4848;
        }

        .alert {
            margin-bottom: 1rem;
        }

        .error-form>a {
            color: #ffa74a;
            font-style: italic;
            font-weight: bold;
        }

        .error-form.bad-credentials,
        .error-form.unconfirmed-account {
            color: #ff4848;
        }

        .alert-notice {
            background-color: #d2ffc7;
            border-color: #6f6f6f;
            color: #0e0e0e;
            text-align: center;
        }

        .footer {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 10px 0;
            position: relative;
            bottom: 0;
            width: 100%;
        }

        .footer a {
            color: #ddd;
            text-decoration: none;
            margin: 0 10px;
        }

        .footer a:hover {
            color: white;
            text-decoration: underline;
        }

        footer p {
            color: #ffffff;
            margin-bottom: 0;
        }
    </style>
    <div class="login-page">
        <div class="form">
            <div class="logo-brand">
                <a href="/"></a>
            </div>

            <form class="login-form" form action="/auth/process_login" method="P                                    OST">
                <div class="alert alert-notice"><span class="ico_info-circle" st                                    yle="margin-right:5px;"></span> Ygg
                    devient un Tracker Bittorrent privé : <br> La connexion est
                    désormais requise pour accéder au site.</div>
                <h3>Se connecter à Ygg</h3>
                <input type="text" placeholder="Pseudo" name="id" required="" />
                <input type="password" placeholder="Mot de passe" name="pass" re                                    quired="" autocomplete="off" />
                <p class="error-form banned-account-msg">
                    <span>Votre compte a été banni ! </span> <a href="">(Voir le                                     motif)</a>
                    <br />
                    Fin du ban : <span class="duration"></span>
                </p>
                <p class="error-form unconfirmed-account">
                    Vous n'avez pas confirmer votre compte à l'aide du mail que                                     nous vous avons envoyé.
                </p>
                <p class="error-form bad-credentials">
                    Échec de connexion. Vérifiez vos identifiants.
                </p>
                <button type="submit"><span class="ico_lock" style="margin-right                                    :5px;"></span> Connexion</button>
                <a class="register" href="/auth/register"><span class="ico_plus"                                     style="margin-right:5px;"></span>
                    Créer un compte</a>
                <p class="message-forgot"><a href="/auth/reset_pass">Mot de pass                                    e oublié ?</a>
                </p>
            </form>
        </div>
    </div>

    <footer class="footer">
        <p>
            <a href="/copyright">Copyright Policy</a>
            <a href="/privacy">Privacy Policy</a>
        </p>
    </footer>
    <script type="text/javascript">

        if (!window._YGGConfig) {
            window._YGGConfig = {};
        }
        window._YGGConfig = {
            layoutType: '',
            isWide: true,
            isMobile: false,
            isHttpsEnabled: 1,
            isLogged: false,
            memberNick: '',
            memberIdHash: '',
            memberGroup: '',
            rootURL: 'https://www.ygg.re/',
            showLoginForm: false,
            bannedAccount: false,
            segment4Uri: true        };

    </script>

    
    <script type="text/javascript" src="/assets/js/jquery.min.js"></script>
    <script type="text/javascript">
        $(".login-form").on("submit", function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '/auth/process_login',
                data: new FormData(this),
                contentType: false,
                processData: false,
                success: function (data) {
                    window.location.replace('/');
                },
                error: function (e, xhr, s) {
                    let error = e.responseJSON;
                    if (e.status == 403 && typeof error !== 'undefined') {
                        let ban_msg = $('.banned-account-msg');
                        ban_msg.find('.duration').html(error.duration);
                        ban_msg.find('a').attr('href', '/user/ban_reason?h=' + e                                    rror.reason_key);
                        ban_msg.show();
                    }
                    else if (e.status == 403) {
                        $('.bad-credentials').hide();
                        $('.unconfirmed-account').show();
                    }
                    else if (e.status == 401) {
                        $('.unconfirmed-account').hide();
                        $('.bad-credentials').show();
                        $('#resetpass').show();
                    } else {
                        alert('Erreur ajax');
                    }

                }
            });
        });
    </script>
</body>

</html>
`

**Comment by ilike2burnthing** [comment]
That's what I've got as well, and like I said it's working fine. The selector is correct, so it doesn't really make sense it can't find it.

Is that a normal Jackett log and the HTML of the login page from your browser? If so, please just provide the enhanced log.

**Comment by Humanzed** [comment]
[log.txt](https://github.com/user-attachments/files/16629548/log.txt)

**Comment by garfield69** [comment]
maybe its a platform specific problem with the version of the html document processor?
switching to using the form class will not negatively impact anyone, so if it solves for this user then we might as well action it.
I'll push an update shortly.

**Comment by garfield69** [comment]
v0.22.457

**Pull request closed without merging**
