### PR TITLE
xtremezone, scenefz, icetorrent: use json api. resolves #5954 resolves #7774

### LINKED ISSUE #5954: XtremeZone (MyXYZ) API Implementation
Hello, right now, myxz.eu has a new api, the old method of page scraping will not work, if someone from the dev team can update the files for this tracker, that will be great. This is the documentation: https://myxz.eu/api/doc 
I think this is all you will need, if you need something more, please tell me in this issue.

### LINKED ISSUE #7774: [xtremezone] Login Failed, got redirected. (Config)
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
 Jackett Version 0.14.164.0 but is like this from a few versions

**Last Working Jackett Version**:
dont know

**Are you using a proxy or VPN?** [yes/no]
no
### Description

Simple to reproduce, do the fallowing: 
This tracker needs a cookie for login, this cookie have to be put in settings (press configure button)
put the cookie in, all works OK until you click settings again. As soon as you enter settings under any reason, that cookie is gone. If you open settings for this tracker (I assume this might happen to all of them, not tested) and you don't paste cookie every time you open it, then cookie is forgotten.

### Logged Error Messages

[Make sure you attach the full logs with your personal information removed in case we need more information]
Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 800
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 969
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70

### PR DESCRIPTION
**Pull request by ngosang**

### CODE REVIEW

**Comment by ngosang** [comment]
@asasinuxp @garfield69 I tested only SceneFZ. Could you test the others?
https://dev.azure.com/Jackett/Jackett/_build/results?buildId=588&view=artifacts&type=publishedArtifacts

**Comment by asasinuxp** [comment]
Confirmed, works, all 3 trackers.

**Comment by RoloSoze** [comment]
@asasinuxp All 3 were working fine for me before the update. Now I'm getting a `Wrong credentials` message despite my correct ones being saved in Jackett for all 3. Did you manage to configure all 3 with your username or email? 

I'm asking because for a while now, all 3 trackers have been displaying notifications on their websites upon logging in, saying that logging in with the username will become obsolete soon. Users will only be able to login with their emails. 

I even tried using my email in Jackett instead of my username but that did not work either. Now I have exceeded the maximum number of login attempts so I'll probably have to wait until tomorrow. I also manually deleted the old YAML files for all 3 and reinstalled Jackett, so we'll see.

@ngosang Does the API use the username or email? Although both are possible via the website right now, soon it will only be the email address, so it might be a good idea to use 'Email Address' in the configuration page instead of 'Username'?

**Comment by asasinuxp** [comment]
Now it works with email, and yes, it might be a good idea to use Email address, but for a period it will work with both.

**Comment by RoloSoze** [comment]
@asasinuxp Thank you. Did you need to delete anything manually, like the old indexer files, or did things work well after the new update?

**Comment by asasinuxp** [comment]
It will work well, I didn't delete anything, for now you can use email or username. Try and see.

**Comment by RoloSoze** [comment]
@asasinuxp OK I fixed the `Invalid credentials` error. I think my existing password did not meet the new security requirements, and so I could not use it with the new API apparently. I had to change it first from my profile, and then I reconfigured all 3 again. It works now.

But this is my first time noticing that all 3 trackers return the exact same results for every search. Has  this always been the case? Are they just different tracker names with the same torrent database? Even the torrent ID is identical for the same torrent across all 3 trackers!

**Comment by RoloSoze** [comment]
@ngosang Does the API support displaying the IMDb URL in Jackett's search results? It's shown on all 3 websites next to each release.

**Comment by asasinuxp** [comment]
No, you can't. You can search using imdb url/id, but it's not displayed. Databases of all trackers was unified in march, and in 1-2 months from now, all common users will login with the same account on every domain, right now login it's restricted by the site id of account.

**Comment by RoloSoze** [comment]
What do you guys get when you search for `The Godfather 1972`? I get an error in all 3! Enhanced log attached.

[log.txt](https://github.com/Jackett/Jackett/files/4707863/log.txt)

**Comment by ngosang** [comment]
@RoloSoze  `The Godfather 1972` fixed in #8834
@asasinuxp when you merge the sites, remember me to change username => email (and add the imdb id in the API results if you can)

**Comment by garfield69** [comment]
Jackett 0.16.598

**Pull request merged**
