### PR TITLE
core: enable genre queries

### PR DESCRIPTION
**Pull request by ilike2burnthing**

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
@garfield69 when trying to use `{{ .Query.Genre }}` with this, it gives the error:

> System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[System.String]' to type 'System.String'

Removing that and using the `genre` field (with a selector or just text) gives the error:

> System.Exception: Error while parsing field=genre, selector=, value=TEST: Value cannot be null. (Parameter 'first')
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1620

I _think_ that `genre` was supposed to have a reference list akin to `category`, and this was never developed.

I'll leave this open for you to reply, just in case I'm missing something obvious and easy, and open another PR which comments out the leftover references to `Genre` (and look into whether to comment out the results `genre` field, as it's basically pointless).

**Comment by garfield69** [comment]
I'll do some research, may take a little while.

**Comment by garfield69** [comment]
Hopefully I've transferred all my changes from my VS across.
I tested using a customised kinozal.yml whose site supports genre search and has genre in the title of results, and build a t=movie&genre=Action torznab query to see if kinozal would return just action movies. 
Seems to test ok.
Do you know of any other yml indexers whose site can do genre searches and provides genre in the results?
Before committing I recommend you perform an independent test of your own using whatever method works for you just to get a second test point.

**Comment by ilike2burnthing** [comment]
Looks good, I'll test this shortly with those indexers I have access to here - https://github.com/Jackett/Jackett/search?l=YAML&q=genre

**Comment by ilike2burnthing** [comment]
PolishSource - searching by genre works without issue, as did getting genre release info (once I commented out the filters), however when that information was copied across to the description it resulted in:

```yml
<description>System.Collections.Generic.List`1[System.String]Language: polish
&lt;br&gt;</description>
```

I resolved that by switching from:

```yml
    genre:
      optional: true
      selector: td:nth-child(2) > small
      filters:
        - name: prepend
          args: "Genre: "
        - name: append
          args: "\n<br>"
```

to:

```yml
    genre:
      optional: true
      selector: td:nth-child(2) > small
    genre_desc:
      optional: true
      selector: td:nth-child(2) > small
      filters:
        - name: prepend
          args: "Genre: "
        - name: append
          args: "\n<br>"
```

and then switching to using `{{ .Result.genre_desc }}` in the description.

If that's fine, then a note in the wiki about being careful what you add to the `genre` field, and not using its result in other fields should cover it.

Still making my way through the rest of the indexers.

**Comment by garfield69** [comment]
yes, you would not normally turn genre into a html stream, since you would normally want to keep the genre string pure for use in case blocks or conditionals or something else.
```yaml
  description:
    text: "Language: {{ .Result.language }}/n<br> Genre: {{ .Result.genre }}/n<br>"
```

**Comment by garfield69** [comment]
don't forget field genre gets parsed into release.Genres to be returned to the torznab results, and adding stuff to genre in the field section using filters will make a mess of that, causing torznab apps that might check genres to have a fit when it finds other non-genre stuff in the return.

**Comment by garfield69** [comment]
so I agree that a wiki note about leaving genre untouched may well be a sensible thing to do.

**Comment by garfield69** [comment]
mind you I still get that error just loading a description in kinozal with nothing but the .Result.genre so something is not right with line 2086 in cardigann `value = release.Genres.ToString();`
needs work.

**Comment by garfield69** [comment]
I don't think  that line in cardigann should be there. we don't want the value to be altered. 
try dropping it and see if that sorts out using .Result.genre.

**Comment by ilike2burnthing** [comment]
Have a look at those, see if you can find any issues/improvements.

theleachzone, bluesbrothers, lastfiles, and peeratiko all allow searching by genre, but either on its own and keyword search, or sharing the same field as the keywords, neither of which are great options, especially as the former 2 rely on an andmatch row filter.

wdt (which currently down) and most of those I don't have an account for appear to do the same or similar, and the only other results are `t_genre` which is for imdbid.

**Comment by garfield69** [comment]
so to be clear in my mind, the current selection process for picking which indexer to add the genre caps, is for the site to support genre in its own search parm, with  the keywords search being either empty or loaded with a term?
i.e. if the site requires that the keyword be just the genre then its not a candidate?

**Comment by ilike2burnthing** [comment]
Yea, that about sums it up, as I doubt anyone would just search by a genre.

**Comment by garfield69** [comment]
All LGTM
nice job! 👍

**Comment by garfield69** [comment]
I'll update the wiki ;-)

**Comment by ilike2burnthing** [comment]
Suggestion for the last step in all this, filling out the modes:

```yml
caps:
  modes:
    search: [q]
    tv-search: [q, season, ep, imdbid, tvdbid, rid, tvmaze, traktid, doubanid, year, genre]
    movie-search: [q, imdbid, tmdbid, traktid, doubanid, year, genre]
    music-search: [q, album, artist, label, track, year, genre]
    book-search: [q, author, publisher, title, year, genre]
```
Basically just add `year` and `genre` to everything, as it seems to make sense, and given that we have `label` for music-search, adding `publisher` to book-search would be appropriate as well (and adding a `publisher` results field).

What do you think? I haven't started anything yet, so feel free to add or remove things.

**Comment by garfield69** [comment]
Just for clarity,  you only intend to add parms for modes to indexers that are actually supported by the site's search engine, right?
And if any site returns in results any of that info we can add those files in the release returned. IS that the plan?

**Comment by ilike2burnthing** [comment]
lol yep that's right.

What a fun emotional roller coaster you went on 😋

**Pull request merged**
