### PR TITLE
[Bit-Titan] C# Implementation

### PR DESCRIPTION
**Pull request by montana123**
Ticket #10281
Added BitTitan.yml to deleted Files
Add feature BitTitan API

@T89-BT

### CODE REVIEW

**Review by garfield69 — APPROVED** [review]
Excellent. 
LGTM
I've added a few amendments, but everything from a functional point of view is working well.
I tested searching episodes and movies, accessing the details page, using a download link, selecting a few categories (there is an issue with ebooks but that is not a fault with the indexer).
I cant review from a code standards compliance point of view, I'm not a C# dev and the regular C# reviewers are all AWOL, but if they have any concerns they can amend the indexer themselves at their leisure.
Thank you for your contribution.

**Comment by mikeoscar2006** [comment]
LGTM too. Code quality is almost great and excellent contribution :)

**Comment by rakuri255** [comment]
Does this not work on all systems?
It works on Windows but not on Linux!

**Comment by rakuri255** [comment]
The bit-titan.yml is deleted after every update!

updater.txt
2021-11-17 16:22:10.4096 Info Attempting to copy bit-titan.yml from source: /tmp/JackettUpdate-v0.20.10-637727629257604836/Jackett/Definitions/bit-titan.yml to destination: /app/Jackett/Definitions/bit-titan.yml 
2021-11-17 16:22:10.4096 Info Copied bit-titan.yml 
2021-11-17 16:22:11.5997 Info Deleting file /app/Jackett/Definitions/bit-titan.yml

**Comment by garfield69** [comment]
@rakuri255  Oops. With all the going and coming, from yml to C# and back again, it looks like I forgot to stop the updater doing the clean up from the prior yml->c# migration. I'll fix this for the next update. Thanks for spotting this.

**Comment by garfield69** [comment]
v0.20.41

**Pull request merged**
