### PR TITLE
Rawsearch support

### LINKED ISSUE #8246: Extra torznab query parameter for true series titles
I was working on the newznab search code to deal with some scene naming exceptions when I remembered the ongoing issue users experience with full title searches for series with apostrophes and diacritics.

I'm thinking about adding support for a `title` query parameter. If specified in `supportedParams`, sonarr would use `title` instead of `q`, and provide the original series title (and scene naming exceptions in separate api calls) rather than the cleaned one.
`q` remains in use for certain other cases, such as specials and anime.
_(Note that you should be prepared for both `q` and `title` at the same time, although I'm not planning to use that combo right now it could be useful for searching for specials in the future)_

An alternative would be a new attribute in the caps that specifies the search engine used, which could be used to modify the behavior of `q`.
Most Newznab sites uses sphinx for text indexing, but I think some use elasticsearch or just mysql fulltextsearch.
Maybe a `searchEngine` attribute with the value `raw` would be sufficient.

Either approach is fine by me, we just need a way to convey the right capabilities.
What do you guys think?

### PR DESCRIPTION
**Pull request by bakerboy448**
- Adds RawSearch support to Core & Cardigann

Closes #11889
Reference #9719
Closes #8246

based on

https://github.com/Prowlarr/Prowlarr/commit/918071903ba0724ef47992f9c417fece3faaa498
https://github.com/Prowlarr/Prowlarr/commit/e94c8839f67aee8dcfd208493d8995d36a58094a
https://github.com/Prowlarr/Prowlarr/commit/25bb10d62b518e400710576f3a6e7267f00350c8

### CODE REVIEW

**Comment by bakerboy448** [comment]
think this works
caps compare for 1337x prowlarr vs. jackett match
https://gist.github.com/bakerboy448/2b675df50dcb8dc079dbe0140cc95533

**Review by ilike2burnthing — CHANGES_REQUESTED** [review]
Looks good.

As this is replacing #11889, can you add `SupportsRawSearch =  true` to AnimeBytes.cs caps? I see it's also available in RuTracker.cs in Prowlarr as well.

**Comment by bakerboy448** [comment]
added both

**Comment by ilike2burnthing** [comment]
The same filter exists for magico.yml and BJShare.cs, but I don't have accounts for those.

I'm assuming this isn't enabled by default for all indexers because certain special characters could potentially break searches on certain trackers?

**Review by ilike2burnthing — APPROVED** [review]

**Comment by bakerboy448** [comment]
> I'm assuming this isn't enabled by default for all indexers because certain special characters could potentially break searches on certain trackers?

correct. only some trackers need this and it all depends on how the tracker handles the query + searches itself internally

**Comment by ilike2burnthing** [comment]
Thanks. Next release will be out in a couple of hours.

**Comment by SnakeATWAR** [comment]
Can we please enable Rawsearch on BTN?

**Comment by ThomasLETELLIER** [comment]
Hi, I don't know if I should post this here or create a new issue, but I'd like to know if it is possible to add rawsearch to YggTorrent please ? Thanks a lot

**Comment by bakerboy448** [comment]
YGG was already done long ago and was one of the first ones with this added. https://github.com/Jackett/Jackett/blob/a4310e6d27b8e4bdc5e9ffe1d9fca7417230c375/src/Jackett.Common/Definitions/yggtorrent.yml#L108

Requesting updates to indexers by commenting on a very old PR is not how to request updates

**Pull request merged**
