### PR TITLE
Add a new indexer: LostFilm.tv / ru-ru / semi-private

### PR DESCRIPTION
**Pull request by krin-san**
Implementation for #1922.

Tracker Name: LostFilm.tv
Tracker Content: Huge amount of TV Series in Russian language.
Tracker URL : http://www.lostfilm.tv/
Tracker Language : Russian
Privacy: Free registration. Required to fetch torrent files. Not required for search functionality.

Noticed issue: tracker combines separate Episode releases into a single Season release so this indexer returns season releases while asking for episodes.

### CODE REVIEW

**Comment by garfield69** [comment]
Would you kindly add LostFilm to the readme.md under the *Supported Semi-Private Trackers* section, thanks.

**Comment by kaso17** [comment]
added it to the readme, thank you

**Comment by krin-san** [comment]
@garfield69, planned to perform it after the work but @kaso17 was faster. Thanks!

**Comment by Rafkat** [comment]
The tracker doesn't work with SickRage. Do you know if there is something needs to be specifically configured for the Series (i.e. name should be in Russian language etc.).
Thanks.

**Comment by krin-san** [comment]
@UniverseXXX, could you open new issue for that with the same logs attached?

**Pull request merged**
