### PR TITLE
ui: add elapsed time per indexer

### LINKED ISSUE #15095: [req]: Add Indexer Response Time Statistics
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Yes, when there are a lot of indexers are added to Jackett (like 40+), response time can be long sometimes. In fact, the reason for the long response time is usually not the high number of indexers, but the slow response of a few indexers.

### Describe the solution you'd like

It would be nice to see which indexer took how many seconds to respond to the last manual search query. A "statistics" button can be added at the bottom of the homepage (next to the check for updates button maybe?) When this button is clicked, can we sort the indexer response times for the last query from the longest to the shortest, or as a chart? Prowlarr does this and is very useful for identifying which indexer is causing problems or slowing down queries.

### Describe alternatives you've considered

_No response_

### PR DESCRIPTION
**Pull request by mynameisbogdan**
#### Issues Fixed or Closed by this PR

* Fixes #15095

### CODE REVIEW

**Comment by batuhankrmn** [comment]
@mynameisbogdan hi, thanks for your fast response to the feature request.  I wonder If this commit covers the ordering response times by longest to shortest? I mean in the log entry (example attached), will indexers be sorted according to response times?

image

**Comment by batuhankrmn** [comment]
> It's for the UI only, it doesn't cover the logs since it's spammy.

Cool, being able to see response time directly from manual search screen is better actually, thanks!

**Review by ilike2burnthing — APPROVED** [review]
Looks good.

Would it be worth adding the elapsed time to errored out indexers?

error

**Comment by garfield69** [comment]
v0.21.1888

**Comment by ilike2burnthing** [comment]
Found the world's tiniest issue that I missed before. When it returns results from cache there's no elapsed time (not really a problem, no point in reporting cache response time), however there's now an additional space between the comma or fullstop, as it's presumably expecting the elapsed time to be there:

```text
BitSearch (100) , iDope (20) [49907ms], showRSS (100) .
```

**Comment by garfield69** [comment]
do you thing we should fill that in with [cache] ?

**Comment by ilike2burnthing** [comment]
Ooooo, that would be good actually.

**Comment by garfield69** [comment]
v0.21.1897

**Pull request merged**
