### PR TITLE
updater: remove Indexers/*.json &*.json.bak (C#)

### PR DESCRIPTION
**Pull request by ilike2burnthing**
Follow up to #10392.

Went through /Jackett.Common/Indexers/ from present to Nov'17, then /Jackett/Indexers/ from Nov'17 to Apr'15 (initial commit). Checked Definitions and Indexers to remove those which had been re-added, as well as those renamed in IndexerManagerService.

Just the one thing that I'm pretty sure is wrong (but it's easier to fix than undo), those indexers which were pre-'ID being included in the .cs', were their .json file names all lower case? Pretty sure that's the case (as a stripped, lowercase ID still existed - https://github.com/Jackett/Jackett/commit/195ec0a94cb83a503d8d70fe94e4482eef32c5bf), just want to check.

### CODE REVIEW

**Comment by ngosang** [comment]
@garfield69 @ilike2burnthing After loading all definitions in memory is really easy to me to write few C# lines to remove all legacy configurations so you don't have to maintain that file.

**Comment by ilike2burnthing** [comment]
Now you tell me 😋 

Wanna close this then?

**Comment by ngosang** [comment]
I have 20 minutes before going to bed. I will try to push a solution.

**Comment by ngosang** [comment]
Closed by  #10416

**Pull request closed without merging**
