### PR TITLE
[PTTime]: increase `requestDelay`

### PR DESCRIPTION
**Pull request by trim21**
#### Description
PTTime increased its rate limie, so we need increase requestDelay.

it raised a `System.Exception: Remote server returned TooManyRequests` in logs with current config.

### CODE REVIEW

**Review by garfield69 — CHANGES_REQUESTED** [review]
if there is now a seeding requirement, then you also need to provide a minimumseedtime or/and a minimumratio, so that users know how long torrents must be kept seeding after download and/or to what ratio to avoid a hit&run penalty.
examples:
```yaml
    # [OPTIONAL] minimum ratio the torrent client must seed to avoid Hit & Run penalties
    minimumratio:
      text: 1.0
    # [OPTIONAL] minimum number of seconds the client must seed to release the MR requirement
    minimumseedtime:
      # 1 day (as seconds = 24 x 60 x 60)
      text: 86400
```

**Comment by trim21** [comment]
> if there is now a seeding requirement, then you also need to provide a minimumseedtime or/and a minimumratio, so that users know how long torrents must be kept seeding after download and/or to what ratio to avoid a hit&run penalty. examples:
> 
> ```yaml
>     # [OPTIONAL] minimum ratio the torrent client must seed to avoid Hit & Run penalties
>     minimumratio:
>       text: 1.0
>     # [OPTIONAL] minimum number of seconds the client must seed to release the MR requirement
>     minimumseedtime:
>       # 1 day (as seconds = 24 x 60 x 60)
>       text: 86400
> ```

Sorry, I misunderstand what `ratioless` means. It has a global ratio requirement but not per-torrent ratio requirement. I just revert description part.

**Comment by ilike2burnthing** [comment]
So I can see the announcement from today about crawlers and third-party programs. While it's not banning them, it is warning about their misuse and the pressures they can put on the site. I can't see anything about a specific limit, but 10s is a hell of a jump. I've run about a dozen different searches with the tracker from Jackett, all about 3-4s apart, and got no errors.

I had a look at the announcements, forum, and rules, but can't see anything specific about a required delay. However, I'm using Google Translate for all this, so I'm not sure how accurate it is.

Is there anything specific, or were you just being cautious? If the latter, I'd prefer something more reasonable, like 5s.

**Comment by trim21** [comment]
> So I can see the announcement from today about crawlers and third-party programs. While it's not banning them, it is warning about their misuse and the pressures they can put on the site. I can't see anything about a specific limit, but 10s is a hell of a jump. I've run about a dozen different searches with the tracker from Jackett, all about 3-4s apart, and got no errors.
> 
> I had a look at the announcements, forum, and rules, but can't see anything specific about a required delay. However, I'm using Google Translate for all this, so I'm not sure how accurate it is.
> 
> Is there anything specific, or were you just being cautious? If the latter, I'd prefer something more reasonable, like 5s.

can you visit pttime? it's [here](https://www.pttime.org/forums.php?action=viewtopic&topicid=16&page=0#:~:text=%C2%A060%E3%80%81%E9%99%A459%E6%9D%A1%E5%A4%96%EF%BC%8C%E5%B0%86%E5%A4%84%E7%90%86%E5%85%B6%E4%BB%96%E9%AB%98%E9%A2%91%E9%AB%98%E9%87%8F%E9%9D%9E%E6%AD%A3%E5%B8%B8%E8%AF%B7%E6%B1%82%EF%BC%88%E6%89%8B%E5%8A%A8%E5%A4%84%E7%90%86%EF%BC%89%E3%80%82%E9%AB%98%E9%A2%91%E6%83%85%E5%86%B5%E3%80%81%E9%A1%B5%E9%9D%A224%E5%B0%8F%E6%97%B6%E5%86%85%E8%AE%BF%E9%97%AE%E9%87%8F%E3%80%81%E5%A4%84%E7%90%86%E5%8F%8A%E6%96%B9%E5%BC%8F%E5%A6%82%E4%B8%8B)

It's actually updated at 2023-03-12 08:44, not tody. and code is updated 2 years ago.


And you are right, I just tested, 5s won't trigger TooManyRequests error. so 5s maybe?

**Comment by ilike2burnthing** [comment]
Yea, that's what I was looking at in the rules.

The announcement is on the homepage, and was made today.

Yea, change to 5s and I'll merge. Thanks.

**Comment by trim21** [comment]
actually I didn't see that announcement 😂

**Comment by garfield69** [comment]
v0.21.2526

**Pull request merged**
