### PR TITLE
Make movie descriptions the same as visible in web gui

### PR DESCRIPTION
**Pull request by syncck**

### CODE REVIEW

**Comment by garfield69** [comment]
None of the current team have an account on the site.
Can you check if any of the other categories need updating?
Add any new ones, and remove any obsolete ones?
Thanks.

**Review by garfield69 — APPROVED** [review]

**Comment by syncck** [comment]
> 

Ok, renamed all categories, attaching screenshot. This site was not updated for ages, just a minor changes to naming :)

1015o

Offtopic (because you asked). How should I modify this line: https://github.com/Jackett/Jackett/blob/b1c7c279cc2229c77542a8a8cd4401515162758d/src/Jackett.Common/Definitions/linkomanija.yml#L67 so that it be suffixed with additional string `&searchindesc=1` at url end (like this `https://www.bbbbb.net/browse.php?incldead=0&search=MOVIETOFIND&searchindesc=1`)? I am pretty sure this is a basic thing for you, but I cannot grasp of  how to do it correctly for two evenings :). What is interesting, this: ```    $raw: "{{ range .Categories }}c{{.}}=1&{{end}&searchindesc=1}"``` really works, but it looks like not correct syntax to be used.

**Comment by garfield69** [comment]
leave the $raw as is and add a line after the incldead with the following
```yaml
    searchindesc: 1
```

**Comment by syncck** [comment]
garfield69, Thank you!

**Comment by garfield69** [comment]
note that we normally only do title searches. adding a description search may yield spurious results to searches.

**Comment by syncck** [comment]
> note that we normally only do title searches. adding a description search may yield spurious results to searches.

I will make it switcheable via preferences (found good examples). Current definition file does not produce enough search results, need to use web gui for double checking, hope I will solve this.

**Comment by garfield69** [comment]
so this is complete and I can merge?

**Comment by syncck** [comment]
This one is complete (cosmetics), I will open another PR for `searchindesc`.

**Comment by syncck** [comment]
That was quick, thanks :D

**Comment by garfield69** [comment]
v0.20.514

**Pull request merged**
