### PR TITLE
assorted: change remaining noappend to default

### PR DESCRIPTION
**Pull request by ilike2burnthing**
Follow up to https://github.com/Jackett/Jackett/commit/d762bbd616289d0aa6b2253e0128364f83f4728e.

Do we remove `noappend` from CardigannIndexer and/or the schema?

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
Sorry, not sure what you mean.

**Comment by ilike2burnthing** [comment]
Oh, that's what I thought you meant, was just confused. Yes, Jackett supports this, that's how I test new definitions. Why do you ask?

**Comment by ilike2burnthing** [comment]
Ah, gotcha! Makes sense.

Anything we need to do, e.g. add a log warning whenever `noappend` is found? If so, that's going to be beyond my ken.

**Comment by ilike2burnthing** [comment]
Ta! Off to put some food in my face and watch Mandalorian, will add this when I get back.

**Review by garfield69 — APPROVED** [review]

**Comment by garfield69** [comment]
wiki updated https://github.com/Jackett/Jackett/wiki/Definition-format#providing-fields-with-a-default-value

**Pull request merged**
