### PR TITLE
Fixed: Bad Blutopia API Input Names

### PR DESCRIPTION
**Pull request by bakerboy448**
https://github.com/Prowlarr/Prowlarr/issues/608#issuecomment-970990330
https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/3d913291366af79016f8c7e3b21e8d4393b5b36a/app/Http/Controllers/API/TorrentController.php#L354-L360

likely needed for various other converted unit3d as well

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
Yea, looks like the change was made back in June with https://github.com/HDInnovations/UNIT3D-Community-Edition/commit/f2c9281c4ee71e7c4003e7e2287d427b481747e9, but given that the last release was 5.3.0 in May, I'm guessing this is just being gradually applied site by site on their own schedules.

Confirmed it also applies to DesiTorrents. Will check others and make the appropriate changes. Thanks!

**Comment by garfield69** [comment]
Ahh. But the problem now that we are using the correct parm names, is that the unit3d api does not accept null values for the imdbid, tvdbid and tmdbid.
And the Jackett cardigann processor does not have logic to drop the query parm if it is null,
So when Jackett generates for example:
```
https://blutopia.xyz/api/torrents/filter?api_token=tokenredacted&name=&tvdbId=&tmdbId=&imdbId=0166924&sortField=created_at&sortDirection=desc&perPage=100&page=1&categories[]=1&categories[]=3&categories[]=5
```
it returns no results
whereas 
```
https://blutopia.xyz/api/torrents/filter?api_token=tokenredacted&name=&imdbId=0166924&sortField=created_at&sortDirection=desc&perPage=100&page=1&categories[]=1&categories[]=3&categories[]=5
```
yields the expected 13 hits.

**Comment by bakerboy448** [comment]
> Ahh. But the problem now that we are using the correct parm names, is that the unit3d api does not accept null values for the imdbid, tvdbid and tmdbid.

indeed this matches what we are seeing in Prowlarr as well.
cc @Qstick

**Comment by garfield69** [comment]
I'll have to rewrite the API indexers to use the parmlist on the path statement instead of the input block, so we  can selectively add parms with values only.

**Comment by ilike2burnthing** [comment]
Using https://github.com/Jackett/Jackett/commit/aee0f2b5e3898481fcdf066f61a3abda6e678b4a as an idea, how about: `tmdbId: "{{ re_replace .TMDBID ^$  \"%\" }}"`?

**Comment by garfield69** [comment]
beat me to the rebuttal, the api specs state numeric only input for those 3 id parms.

**Comment by garfield69** [comment]
sorted. I'll update this PR shortly.

**Review by garfield69 — APPROVED** [review]
tested with Radarr and jackett dashboard imdbid searches

**Comment by garfield69** [comment]
v0.20.10

**Pull request merged**
