### PR TITLE
[Feature] Allow multiple words search in DonTorrent tracker

### PR DESCRIPTION
**Pull request by jojojox2**
#### Description
~Add pagination logic to the DonTorrent tracker.~

Now it uses the whole query for searching (not only the longest word), ~and it will iterate over all the available pages with results (while "_Next_" button is available and not disabled).~

~It will take longer for many pages due to the way it is implemented, but it will get all posible results (same as using the original web).~

### CODE REVIEW

**Review by ilike2burnthing — CHANGES_REQUESTED** [review]
I don't think we should support pagination for this tracker, especially not for unlimited pages, given that it's painfully slow already.

I'm not sure what @Lyuu17's idea was in https://github.com/Jackett/Jackett/pull/12813 for only searching by the longest word (maybe it was an issue at the time), but happy to have that removed.

**Comment by jojojox2** [comment]
Thanks for the feedback! Do you think it could make sense to add a configuration parameter to the tracker, so each user can increase the number of pages to search (with a default value of 1 page), knowing what it will take longer for the tracker?
It will need additional development of course, due to the extra complexity, but each user will have the power to decide if they want to search extra pages or not.

If it's too much, I can happily reduce the pull request only to search for the whole query string, and not just the longest word.

**Comment by ilike2burnthing** [comment]
I wouldn't want a user setting for the number of pages, as this could be abused, purposefully or not, essentially DDoSing the site (e.g. search `la` and you get almost 11,000 results).

Generally at most we request 2 pages, and only if there aren't sufficient results on a single page (while there have been some exceptions to this in the past, we've tried to cut this back as much as possible, as it often gets Jackett blocked for bot activity).

@garfield69 what do you think? This wouldn't affect the keywordless search, as there's only ever one page, so it _should_ be fine if we're just occasionally requesting a second page for keyword searches. There's already a request delay of 2.1s, so that wouldn't need to be added.

**Comment by garfield69** [comment]
Searching the whole query string will go a long way to providing better chance of getting good results.

But the web site is not suitable for indexing. it is geared for manual user clicks. 
Take a typical search for a tv episode for a series with 14 seasons. you have to search for the series name, then scroll down a list of seasons (usually needing to load more than one page to find the season you are after), then scroll through a list of episodes, fetching multiple pages to find the one you are after. It sucks. 
And while a user can make intuitive jumps to reduce the number of pages to look at, the indexer has to troll through all the possible pages to ensure a successful search.
Adding pagination to the indexer will only overload the site with traffic from Jackett and get us banned. 

I vote to search the whole query string and drop pagination.

**Comment by jojojox2** [comment]
Wow, never thought of all the consequences. Thanks a lot for the feedback!
I've updated the changes to only remove the limitation of the longest word search.

**Comment by garfield69** [comment]
Thank you.

**Comment by garfield69** [comment]
v0.21.2628

**Pull request merged**
