### PR TITLE
Fix to BJ-Share and Speed-Share

### PR DESCRIPTION
**Pull request by DarkSupremo**
Changed title layout from "Serie SxxExx YEAR" to "Serie Year SxxExx" (does not apply to anime, year is not included), sonarr was not recognizing the old title layout.
Fixed Seasons packs title on Speed-Share

### CODE REVIEW

**Comment by garfield69** [comment]
Cheers.

**Comment by loktarbr** [comment]
On speed-share the year who is showing is the episode year and not the show year. That issue is causing the show to not be identified on sonarr for example.

captura de tela 2018-01-08 as 13 01 05

**Comment by DarkSupremo** [comment]
The problem is that this field is an mess on speed-share... some releases/episodes is as show year, other is as episode year...

For example, Doctor Who, on Season 10, it's as 2005, that is the show year, but season 11 they released as 2017...

The problem is that some shows depends on that, like Doctor who for example... i can just remove it, it will fix some shows and will broken others...

**Comment by DarkSupremo** [comment]
@loktarbr partially fixed in #2391

**Comment by loktarbr** [comment]
Thanks, speed-share is working so far but bj-share not. The anime search got results but tv shows not returning any results.

**Comment by DarkSupremo** [comment]
@loktarbr tested here to few tv shows that i have here, and it's working fine... make sure that your login/pass is configured correctly, and tell me some show that is not working for you, so i can test...

Tested with: Agents of Shield, Arrow, Flash, Black Lightning

**Pull request merged**
