### PR TITLE
Add tracker hdbc

### PR DESCRIPTION
**Pull request by adamwinn**
Add support for HDBC

### CODE REVIEW

**Comment by adamwinn** [comment]
I was on www.hd-bits.com and noticed an admin/mod posted a Jackett yaml file, so I figured I'd create a pull request to get it into the main branch.  I don't know if HDBC is the correct name for this tracker or not since there's hdbits.org and hd-bits.ro

**Comment by kaso17** [comment]
Thank you for all your commits.
Also noticed this one, but asked for permission to include it first (we got it).

**Comment by RoloSoze** [comment]
May I suggest renaming this tracker to simply HD-Bits.com? I think it's better to remove the acronym HDBC just to be consistent with the other trackers in Jackett :)

**Comment by adamwinn** [comment]
Yes, I noticed that too, but I didn't know what else to call it.

I've fixed these two issues.  I made the name "HDBitscom" because it didn't look like the parser liked names with punctuation in them.

**Comment by kaso17** [comment]
renamed and more improvements were made with #1186 and 1294ea765a42d8219d0d7b01aee5c8928a6f62c5

**Pull request merged**
