### PR TITLE
[New Tracker REQ] DICMusic

### PR DESCRIPTION
**Pull request by soleil0-0**
Added support for chinese private tracker DICMusic

### CODE REVIEW

**Comment by ngosang** [comment]
@soleil0-0 nice work! I can't test the tracker, so, could you do these tests for me?
1. Empty search in Jackett
2. Text search in Jackett
3. Empty search with "Applications" category.

**Comment by soleil0-0** [comment]
> @soleil0-0 nice work! I can't test the tracker, so, could you do these tests for me?
> 
> 1. Empty search in Jackett
> 2. Text search in Jackett
> 3. Empty search with "Applications" category.

No problem. Here are some screenshots: （Sorry, I don't have permission to send invite...）

1. Empty search in Jackett
Screen Shot 2020-07-08 at 12 16 30 AM

2. Text search in Jackett
Screen Shot 2020-07-08 at 12 17 00 AM

3. Empty search with "Applications" category.
Screen Shot 2020-07-08 at 12 17 27 AM

**Comment by ngosang** [comment]
Thank you!

**Comment by garfield69** [comment]
Jackett 0.16.814

**Comment by ilike2burnthing** [comment]
https://dicmusic.club/ redirects to https://kshare.club/ can you confirm that simply changing the URL in Jackett is all which is required; nothing else has changed?

**Comment by soleil0-0** [comment]
> [dicmusic.club](https://dicmusic.club/) redirects to [kshare.club](https://kshare.club/)
> 
> @soleil0-0 can you test whether simply changing the URL in Jackett works; nothing else has changed?

Dicmusic disable the login page, and redirect to another website. It should use cookie now. A will create a PR later.

**Comment by garfield69** [comment]
https://kshare.club/ returning Error Connection timed out
Also indexer still has sitelink as https://dicmusic.club/

what's the story morning glory?

**Comment by garfield69** [comment]
both domains redirect to service provider at https://wanwang.aliyun.com/hosting/ipvisit_stop
going to remove the indexer at its been over 30 days since offline.

**Comment by garfield69** [comment]
v0.18.851

**Comment by garfield69** [comment]
I see that https://dicmusic.club/ is returning a login page, and registration is still invite only.
@soleil0-0  Do you know if it is worth reversing the removal of the indexer, or has the site changed the engine or html requiring a new indexer build?

**Pull request merged**
