### PR TITLE
Add TVDbId, TMDbId Query Support

### PR DESCRIPTION
**Pull request by Qstick**
This PR adds some capabilities to better support Sonarr/Radarr and accurate searching

- Add TvdbId query parameter for tv-search (Used by Sonarr v3)
- Add TmdbId query parameter for movie-search (Used by Radarr v3)
- Turn on support for tvdb, tmdb queries for UNIT3D 2.7.0 Indexers (Tested on Blutopia)
- Fix ImdbId parameter not showing in caps for tv-search on Cardigann Indexers 
~~- Fix ImdbId parameter not showing in caps for Rarbg~~

Related to https://github.com/Jackett/Jackett/issues/2984

### CODE REVIEW

**Comment by ngosang** [comment]
@Qstick Thank you very much! This will be really useful.
We will need some time to review and test the changes.

**Comment by Qstick** [comment]
Thanks, no hurry, just realized I didn't add the query parameters for caps for the others indexera besides blutopia, so I'll do that tonight.

**Comment by Qstick** [comment]
@ngosang Should be ready for testing now. Let me know if you guys find anything that needs changed

**Comment by garfield69** [comment]
I'm not a regular Sonarr / Radarr user, so I will need a little help checking that my app settings are correct.
for my first test, I'm trying to use Radarr to search for **captain america civil war**, using Radarr 0.2.0.1504 with Jackett 0.16.840 (the build from this PR).
the Radarr indexer is set up to use the jackett blutopia indexer, with category 2000, but I could not find any Radarr indexer settings that specifically tells it to use tmdbid.
Currently when I use Radarr to manually search for the movie, Radarr is using the imdbid 
http://127.0.0.1:9117/api/v2.0/indexers/blutopia/results/torznab/api?t=movie&cat=2000&extended=1&apikey=****redacted****&offset=0&limit=100&imdbid=3498820
which the jackett indexer turns into this request to blutopia
https://blutopia.xyz/torrents/filter?categories[]=1&categories[]=3&categories[]=7&search=&description=&uploader=&imdb=3498820&tvdb=&tmdb=&mal=&igdb=&sorting=created_at&sort=created_at&direction=desc&qty=100
As a alternative, I edited my blutopia jackett indexer and switched the order of the movie-search parms, just in case it was an issue with priority
```yaml
    movie-search: [q, tmdbid, imdbid]
```
but that did not make a difference.

So, is there a Radarr option that I have missed with tells Radarr to use the tmdbid when searching?

**Comment by garfield69** [comment]
in the mean time, I manually constructed a jakcett api request using the tmdbid, and this successfully generated a Jackett blutopia tmdbid search which yielded the expected results
http://127.0.0.1:9117/api/v2.0/indexers/blutopia/results/torznab/api?t=movie&cat=2000&extended=1&apikey=***redacted***&offset=0&limit=100&tmdbid=271110
https://blutopia.xyz/torrents/filter?categories[]=1&categories[]=3&categories[]=7&search=&description=&uploader=&imdb=&tvdb=&tmdb=271110&mal=&igdb=&sorting=created_at&sort=created_at&direction=desc&qty=100

**Comment by garfield69** [comment]
test using Sonarr 3.0.3.899 looking for **avenue 5 season 1 ep 1**
Sonarr generated 
http://127.0.0.1:9117/api/v2.0/indexers/blutopia/results/torznab/api?t=tvsearch&cat=5000&extended=1&apikey=***redacted***&offset=0&limit=100&q=Avenue%205&season=1&ep=1
which Jackett turned into
https://blutopia.xyz/torrents/filter?categories[]=2&categories[]=6&search=Avenue+5+S01E01&description=&uploader=&imdb=&tvdb=&tmdb=&mal=&igdb=&sorting=created_at&sort=created_at&direction=desc&qty=100
So am I missing a Sonarr setting here as well?

looking for **the flash season 5 ep 15** worked!!
http://127.0.0.1:9117/api/v2.0/indexers/blutopia/results/torznab/api?t=tvsearch&cat=5000&extended=1&apikey=***redacted***&offset=0&limit=100&tvdbid=279121&imdbid=tt3107288&season=5&ep=15
https://blutopia.xyz/torrents/filter?categories[]=2&categories[]=6&search=&description=&uploader=&imdb=3107288&tvdb=279121&tmdb=&mal=&igdb=&sorting=created_at&sort=created_at&direction=desc&qty=100

**Comment by garfield69** [comment]
regarding enabling imdb caps for tvsearch on cardigann, @ngosang  does  #8107 apply?

**Comment by garfield69** [comment]
regarding enabling imdb on tvsearch for rarbg:
when searching the flash season 6 episode 15 with Sonarr 3.0.3.899
the rarbg in this PR generates
http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?t=tvsearch&cat=5030,5040,5045&extended=1&apikey=***redacted***&offset=900&limit=100&imdbid=tt3107288&season=6&ep=19
Note tt3107288 is the series id not the episode id
And the rarbg indexer generated
https://torrentapi.org/pubapi_v2.php?token=**redacted**&format=json_extended&app_id=jackett_v0.16.840.0&limit=100&ranked=0&sort=last&mode=search&search_imdb=tt3107288&category=18%3B41%3B49
which returned the first 100 episodes for the series rather than the requested season 6 ep 19

**Comment by Qstick** [comment]
@garfield69 regarding Radarr, only V3 has the capability to search by tmdbid. Sonarr V3 should do it by default, but will default back to a title search if no results are yielded on the id search.

**Comment by Qstick** [comment]
> regarding enabling imdb on tvsearch for rarbg:
> when searching the flash season 6 episode 15 with Sonarr 3.0.3.899
> the rarbg in this PR generates
> http://127.0.0.1:9117/api/v2.0/indexers/rarbg/results/torznab/api?t=tvsearch&cat=5030,5040,5045&extended=1&apikey=***redacted***&offset=900&limit=100&imdbid=tt3107288&season=6&ep=19
> Note tt3107288 is the series id not the episode id
> And the rarbg indexer generated
> https://torrentapi.org/pubapi_v2.php?token=**redacted**&format=json_extended&app_id=jackett_v0.16.840.0&limit=100&ranked=0&sort=last&mode=search&search_imdb=tt3107288&category=18%3B41%3B49
> which returned the first 100 episodes for the series rather than the requested season 6 ep 19

Looks like Sonarr is passing the series IMDb with the season and episode number as well, but jackett isn't passing that on. So I can take a peak at that as part of this.

**Comment by HDVinnie** [comment]
Awesome job @Qstick

**Comment by garfield69** [comment]
I cant seem to find a link to Radarr v3 on https://github.com/Radarr/Radarr
can you point me in the right direction please? thanks.

**Comment by nicolahinssen** [comment]
@garfield69 Aphrodite branch :)

**Comment by Qstick** [comment]
Here are the Aphrodite download links...

Be sure to have a backup.

Windows:
https://radarr.servarr.com/v1/update/aphrodite/updatefile?os=windows&runtime=netcore&arch=x64
Linux:
https://radarr.servarr.com/v1/update/aphrodite/updatefile?os=linux&runtime=netcore&arch=x64
https://radarr.servarr.com/v1/update/aphrodite/updatefile?os=linux&runtime=netcore&arch=arm64
https://radarr.servarr.com/v1/update/aphrodite/updatefile?os=linux&runtime=netcore&arch=arm
macOS:
https://radarr.servarr.com/v1/update/aphrodite/updatefile?os=osx&runtime=netcore&arch=x64

**Comment by garfield69** [comment]
And are there any radarr v3 installation notes, readme, or link to a support site wiki?

**Comment by Qstick** [comment]
Not yet, jump on discord if you have issues. Should be pretty straight forward. It's a self contained net core app (similar to how Jackett is distributed now I believe)

**Comment by garfield69** [comment]
ok thanks.

**Comment by garfield69** [comment]
ok then. retesting the tmdb calls using Radarrv3
http://127.0.0.1:9117/api/v2.0/indexers/blutopia/results/torznab/api?t=movie&cat=2000&extended=1&apikey=***redacted***&offset=0&limit=100&tmdbid=299537&imdbid=4154664
generates 
https://blutopia.xyz/torrents/filter?categories[]=1&categories[]=3&categories[]=7&search=&description=&uploader=&imdb=4154664&tvdb=&tmdb=299537&mal=&igdb=&sorting=created_at&sort=created_at&direction=desc&qty=100

so recapping: 
have successfully tested using RadarrV3 and SonarrV3 with this PR to add tmdb and tvdb queries to Blutopia.
Albeit, in both instances, the imdb was also added at the same time, so it is not clear whether blutopia made use of both or just one or the other of the imdb/tmdb or imdb/tvdb combo in the respective sonarr/radarr generated queries.

In any case, I'd be happy to merge, pending resolution or deferral of the rarbg and imdb caps cardigann aspects of the PR.

**Comment by Qstick** [comment]
@garfield69 thanks, I have a test case from onlyscene that has tmdb only (as I think many of theirs do) would be a good confirmation that it still works with the aggregate ids. I do not have an account though, only screenshots from user.

**Comment by garfield69** [comment]
@HDVinnie  a question for you as the author of unit3d.
> I guess the main question is will UNIT3D return results for either [imdbid, tmdbid] when both parameters are searched for. Ex. If "imdb=4154664&tvdb=&tmdb=299537" is passed will we get results with matching tmdb even if they have blank IMDb?

**Comment by HDVinnie** [comment]
> @HDVinnie a question for you as the author of unit3d.
> 
> > I guess the main question is will UNIT3D return results for either [imdbid, tmdbid] when both parameters are searched for. Ex. If "imdb=4154664&tvdb=&tmdb=299537" is passed will we get results with matching tmdb even if they have blank IMDb?

Currently no since the query is searching for `$torrent->where('imdb', '=', 4154664);` and `$torrent->where('tmdb', '=', 299537);`

I can modify it though. This is another reason why I was suggesting in future Jackett communicates through UNIT3D's torrents API instead. The API search system is a lot more flexible.

**Comment by Qstick** [comment]
> I can modify it though. This is another reason why I was suggesting in future Jackett communicates through UNIT3D's Torrent API instead. The API search system is a lot more flexible.

That’s up to you guys on the modification, but yea using the api would be nice. Until then looks like we need to handle in Jackett not passing both that are received.

**Comment by garfield69** [comment]
>Until then looks like we need to handle in Jackett not passing both that are received.

should be achievable in the yml indexers 
example
```yaml
    tvdb: "{{ if .Query.IMDBID }}{{else}}{{ .Query.TVDBID }}{{end}}"
    tmdb: "{{ if .Query.IMDBID }}{{else}}{{ .Query.TMDBID }}{{end}}"
```
etc.

**Comment by Qstick** [comment]
> > Until then looks like we need to handle in Jackett not passing both that are received.
> 
> should be achievable in the yml indexers
> example
> 
> ```yaml
>     tvdb: "{{ if .Query.IMDBID }}{{else}}{{ .Query.TVDBID }}{{end}}"
>     tmdb: "{{ if .Query.IMDBID }}{{else}}{{ .Query.TMDBID }}{{end}}"
> ```
> 
> etc.

The only issue I see with this is it defeats the entire purpose of why I did this PR. If releases are listed on the indexer with a Tmdb Id and not a IMDb Id then we still won’t get them. We will still just use the IMDb Id passed to search.

**Comment by garfield69** [comment]
OH, I see. well in that case lets reverse the conditionals.
```yaml
  inputs:
    $raw: "{{ range .Categories }}categories[]={{.}}&{{end}}"
    search: "{{ if .Query.IMDBID }}{{ else }}{{ .Keywords }}{{ end }}{{ if or .Query.TVDBID .Query.TMDBID }}{{ .Keywords }}{{ else }}{{ end }}"
    description: ""
    uploader: ""
    imdb: "{{ if or .Query.TVDBID .Query.TMDBID }}{{ else }}{{ .Query.IMDBIDShort }}{{ end }}"
    tvdb: "{{ .Query.TVDBID }}"
    tmdb: "{{ .Query.TMDBID }}"
    mal: ""
    igdb: ""
    sorting: "{{ .Config.sort }}"
    sort: "{{ .Config.sort }}"
    direction: "{{ .Config.type }}"
    qty: 100
```
using jackett dashboard TEST (keywordless search)
https://blutopia.xyz/torrents/filter?search=&description=&uploader=&imdb=&tvdb=&tmdb=&mal=&igdb=&sorting=created_at&sort=created_at&direction=desc&qty=100
using jackett dashboard to search keyword `Perry Mason 2020 S01E05`
https://blutopia.xyz/torrents/filter?search=Perry+Mason+2020+S01E05&description=&uploader=&imdb=&tvdb=&tmdb=&mal=&igdb=&sorting=created_at&sort=created_at&direction=desc&qty=100
using jackett dashboard to search with imdbid `tt4154664`
https://blutopia.xyz/torrents/filter?search=&description=&uploader=&imdb=4154664&tvdb=&tmdb=&mal=&igdb=&sorting=created_at&sort=created_at&direction=desc&qty=100

Sonarrv3 search for the flash season 5 ep 15
Sonarrv3 sent to jackett
http://127.0.0.1:9117/api/v2.0/indexers/blutopia/results/torznab/api?t=tvsearch&cat=5000&extended=1&apikey=***redacted***&offset=0&limit=100&tvdbid=279121&imdbid=tt3107288&season=5&ep=15
and jackett sent to blutopia
https://blutopia.xyz/torrents/filter?categories[]=2&categories[]=6&search=S05E15&description=&uploader=&imdb=&tvdb=279121&tmdb=&mal=&igdb=&sorting=created_at&sort=created_at&direction=desc&qty=100

Radarrv3 search for captain marvel
Radarrv3 sent to jackett
http://127.0.0.1:9117/api/v2.0/indexers/blutopia/results/torznab/api?t=movie&cat=2000&extended=1&apikey=***redacted***&offset=0&limit=100&tmdbid=299537&imdbid=4154664
and jackett sent to blutopia
https://blutopia.xyz/torrents/filter?categories[]=1&categories[]=3&categories[]=7&search=&description=&uploader=&imdb=&tvdb=&tmdb=299537&mal=&igdb=&sorting=created_at&sort=created_at&direction=desc&qty=100

Radarr 0.2.0.1504 search for captain marvel
Radarr 0.2.0.1504 sent to jackett 
http://127.0.0.1:9117/api/v2.0/indexers/blutopia/results/torznab/api?t=movie&cat=2000&extended=1&apikey=***redacted***&offset=0&limit=100&imdbid=4154664
and jackett sent to blutopia
https://blutopia.xyz/torrents/filter?categories[]=1&categories[]=3&categories[]=7&search=&description=&uploader=&imdb=4154664&tvdb=&tmdb=&mal=&igdb=&sorting=created_at&sort=created_at&direction=desc&qty=100

success!

**Comment by Qstick** [comment]
Wouldn't this give us the reverse effect? I'm sure there are indexers that use IMDb and leave TMDb blank... We would never see those releases

**Comment by garfield69** [comment]
>Wouldn't this give us the reverse effect? I'm sure there are indexers that use IMDb and leave TMDb blank... We would never see those releases

If you look at the results from the radarrv2 you can see that only the imdb was used to make a request to jackett and jackett used just that imdb to query blutopia. 
I think the way i coded the conditionals covers that. but i welcome further testing from anyone to validate.

**Comment by Qstick** [comment]
Example, Radarr V3 sends Jackett IMDB and TMDB.... Jackett sends TMDB to indexer, Indexer returns no results because they are all attached to IMDB IDs... 

That's the case I'm getting at.. we need a way to get both sets of results. Releases that are tagged with only IMDb and those that are tagged with only TMDb, or those that are tagged with both.

**Comment by garfield69** [comment]
Well that is not going to happen. jackett is not going to send three separate requests, one for just imdb, one for tmdb, and one for both.
So you are back to being dependent on the web sites using an OR instead of a AND when both imdb and tmdb are requested by jackett.
I don't see that there is anything Jackett can do about this.

**Comment by Qstick** [comment]
>I can modify it though. This is another reason why I was suggesting in future Jackett communicates through UNIT3D's Torrent API instead. The API search system is a lot more flexible.

This comment would elude that this can be done with the UNIT3D API, so there is SOMETHING Jackett can do. If not the modification would need to be made to UNIT3D as @HDVinnie mentioned

**Comment by garfield69** [comment]
sure. 
but to use the API necessitates rewriting all the unit3d Jackett indexers in c# as the current yaml processors cannot process anything other than html.
and with all the c# taking a sabbatical or on minimal contribution mode it may be quite some time before the indexers all get converted from yaml to c#.

**Comment by Qstick** [comment]
Hehe good point. Your call on which way and I'll modify the PR. It's better than it was now just not optimal end state.

**Comment by HDVinnie** [comment]
I have not issue introducing an endpoint to UNIT3D just for Jackett. Just tell me what it should include (parameters wise) and ill get it done.

**Comment by HDVinnie** [comment]
@garfield69 I assume Jackett endpoint would only need the ability to search by title, imdb_id, tmdb_id and tvdb_id?

**Comment by garfield69** [comment]
I don't think anyone filling in this panel
image
would expect that adding two or more ids for a movie in the IMDB, TVDB, TMDB, MAL and IGDB would expect to only be presented with results that contain all of the IDs provided.
I think most users would expect that any torrent that contains at least one of the ids would be presented.
IMO the current yaml works well enough without having to rewrite  the indexers in c# or have the web sites provide a completely new api or endpoint.
I think the simplest and most direct improvement would be for the web sites search to treat the ID parms as an OR instead of an AND.

**Comment by HDVinnie** [comment]
Done. For example https://blutopia.xyz/torrents/28978 this torrent I have removed the imdb_id from to the default 0. 

If you search 
https://blutopia.xyz/torrents/filter?categories[]=1&categories[]=3&categories[]=7&search=&description=&uploader=&imdb=4154664&tvdb=&tmdb=&mal=&igdb=&sorting=created_at&sort=created_at&direction=desc&qty=100
you will get 20 results. but if add the tmdb_id like so
https://blutopia.xyz/torrents/filter?categories[]=1&categories[]=3&categories[]=7&search=&description=&uploader=&imdb=4154664&tvdb=&tmdb=299537&mal=&igdb=&sorting=created_at&sort=created_at&direction=desc&qty=100
you will get the full 21 results

Simply changed the ID search params to use `orWhere`.

**Comment by Qstick** [comment]
Nice, that should work

**Comment by garfield69** [comment]
Thank you @HDVinnie 
So which is the version of unit3d that will roll out with orWhere implemented?

**Comment by HDVinnie** [comment]
@garfield69 Ill be releasing it Saturday or Sunday to UNIT3D core tagged as `UNIT3D-Community-Edition v2.7.0`

**Comment by garfield69** [comment]
@Qstick  as it stands this PR is not suitable for merging.

what needs to be done: 

either clean up this PR or raise a separate PR that contains support for tmdb and tvdb in the cardigann processor, and activation for the blutopia indexer ONLY.

all other yaml unit3d activation should be removed, as they can only be activated if/when each website opts to upgrade their unit3d engine to 2.7.0, which we will do on a case by case basis.

the rarbg imdbtvsearch activation should be in its own PR and merging will be dependent on whether #8107 is relevant for this indexer.

I am not sure of the imdbtvsearch for the cardicann should be in its own PR too, as #8107 may be relevant here as well.

Thanks.

**Comment by Qstick** [comment]
Will do

**Comment by HDVinnie** [comment]
https://github.com/HDInnovations/UNIT3D-Community-Edition/releases/tag/v2.7.0

**Comment by Qstick** [comment]
@garfield69 sorry, time has not been on my side lately, thanks for the fixups. Anything you need me to do with this?

**Comment by garfield69** [comment]
@Qstick  wrote:
>Anything you need me to do with this?

nothing at the mo. waiting on @ngosang  to respond to:
>regarding enabling imdb caps for tvsearch on cardigann, @ngosang does #8107 still apply?

I think we may need to drop the cardigann line 116
`SupportsImdbTVSearch = Definition.Caps.Modes.Any(c => c.Key == "tv-search" && c.Value.Contains("imdbid")),`

**Comment by garfield69** [comment]
Jackett 0.16.1012

**Comment by kevindd992002** [comment]
Is tvdb id search support for TorrentDay still being worked on? I still see these in Jackett's logs:

image

**Comment by ngosang** [comment]
tvdb is not supported in Torrentday. If the site supports it and you want this feature open a new issue.
http://127.0.0.1:9117/api/v2.0/indexers/torrentday/results/torznab/api?t=caps&apikey=**redacted**

**Pull request merged**
