### PR TITLE
topnow: html fix & magnet option added. Resolves #8199

### LINKED ISSUE #8199: [TopNow] Found no results - HTML has changed again
~Will post a WIP soon~

Up. Comments/recommendations appreciated

### PR DESCRIPTION
**Pull request by ilike2burnthing**
Not all results have their own page, and instead direct you to the stream (if you click on the result's name instead of the .torrent download button). Clicking on the name of those results in Jackett also directs you to the stream. Torrents for all results, including those without their own page, are available from the search results page, but I wasn't able to work out how to get them from there instead. Any advice?

e.g. Better Call Saul S05E08 & 09 - https://topnow.se/index.php?search=better+call+saul

magnets are available for most results, but not all, so I added a note to warn users who want to the option. Although that's only from the episode/season page, not the results page, so this might have to be removed.

### CODE REVIEW

**Comment by garfield69** [comment]
>Torrents for all results, including those without their own page, are available from the search results page, but I wasn't able to work out how to get them from there instead. Any advice?

if .torrents are available from the results, then remove the download block (the one before the search block) and amend the download selector in the search block to pick up the appropriate href instead of leaving it pointing to the details page.
if this href can be missing add the optional:true statement

if the results also provide magnets, which can be missing, add a magnet selector after the download selector

if some cards only have a stream, then add an exclusion to the row selector to stop it picking those cards.

refer to https://github.com/Jackett/Jackett/wiki/Definition-format#search and feel free to pepper me with questions ;-D

**Comment by ilike2burnthing** [comment]
😒 they've just changed the site _again_...

Now, if a result has its own page then the torrent is only displayed there, not with the search results anymore, while those results without their own page have their torrent in the results page. So I'm guessing we'd have to do some kind of if/else, but I can't work that out.

So it would be something to the effect of:
IF result row contains `/please-wait.php?` then use `download:  selector: a[href*="/torrents/"]` ELSE, use `title: selector: td:nth-child(1)` and then `search:  download:  selector: td.card_content a  attribute: href` and then use `download:  selector: a[href*="{{ .Config.downloadlink }}"]` (using either `"/torrent/"` or `"magnet:?xt="`, with an `optional:true` statement for the latter)

So, ya know, simple... (if I haven't missed something that would make things waaaay easier, which is completely possible).

I can either get the search results page or the individual pages to work fine, I just can't combine them.
[topnow - search results page.txt](https://github.com/Jackett/Jackett/files/4479071/topnow.-.search.results.page.txt)
[topnow - individual pages.txt](https://github.com/Jackett/Jackett/files/4479070/topnow.-.individual.pages.txt)

Oh and I still haven't worked out how to not have the name in Jackett link to the stream, for those results without their own pages. The torrent links in Jackett are fine, just the name.

**Comment by garfield69** [comment]
If what you are saying is: if you search for a title that returns only a single result, the site now jumps straight to the details page, then this indexer will need to be re-written in C# because Cardigann cannot handle that event.
Is that correct or have I misread?

**Comment by ilike2burnthing** [comment]
No sorry, typing in frustration doesn't make things particularly clear.

If you search 2019 (or any general term), you get lots of results. Good.

Most of those, when clicked, will take you to a page with details, .torrent links, and most also having magnet links. Good.
e.g. https://topnow.se/human-capital

But some of the returned results on the search results page don't have their own individual page (if you click them you get sent to the stream).
e.g. https://topnow.se/please-wait.php?IIlIllI=IlllIIIIIllIIIIllIIlI 

Instead, they display their .torrent links in the search results page.
e.g.TopNow

So both have torrents available for us to access, and 2hrs ago they were all in the search results page so it would have been simple, given your advice. But now they're split between either the search results page, _**or**_ an individual page (which not every result has).

So I thought maybe it would be possible to if/else our way round it, but maybe not.

**Comment by garfield69** [comment]
OK. I'll take a closer look at the site when I've next got free time and see if I can make something of it with Cardigann.

**Pull request closed without merging**
