### PR TITLE
Update hdcztorrent.yml

### PR DESCRIPTION
**Pull request by mazmar**
fixes double findings, this is improved from original which was doing preprocessing and regex

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
I'm not seeing any duplicate results. Can you suggest a search term I can test which results in this?

**Comment by mazmar** [comment]
image

for me all of the results are duplicated

**Comment by garfield69** [comment]
how peculiar.
image
which theme are you using on the web site? i'm on **XBIT DT FM** the default.

**Comment by ilike2burnthing** [comment]
^ same

**Comment by garfield69** [comment]
sweet.

**Comment by ilike2burnthing** [comment]
[v0.18.155](https://github.com/Jackett/Jackett/releases/tag/v0.18.155)

**Pull request merged**
